label AO_1:
    "Haruhi bounced on her heels with a wide grin, holding Kyon's cell phone in both hands as she remained in the center of the glowing circle. \"I {i}knew{/i} it!\" she cheered. \"There was {i}something{/i} off about Asakura! What is it?\""
    "\"Um...\" the onetime class representative said, frowning."
    "\"She's alien,\" Kyon volunteered. \"From the same place as Yuki-chan and Kimidori, but she tried to kill me once.\""
    "\"Whaaaat? What did you do to make her mad?\" Haruhi asked, looking at him in bemusement."
    "\"Er,\" Asakura said, crossing her arms beneath her chest. \"Evidently my information requires an update. I was sent to dispatch Kyon-kun, because he's become an undesirable element for my superiors. Really, I'd hoped to see a new state, maybe even provoke it with his death. But, those toys seem to say that's already happened! So disappointing ... I suppose if I'd been more patient, I could see it anyway?\""
    "\"I personally like to see it as a lesson on the effects of {i}randomly stabbing people{/i},\" Kyon muttered."
    "\"Oh, it wasn't random,\" she countered. \"It was highly specific! I put a whole two hours of thought into it, you know. For us, that's quite a while!\""
    "\"I'm touched,\" he said dryly."
    "\"Blah blah blah,\" Haruhi muttered, crossing her arms over her chest and rolling her eyes. \"Skip the speeches — if I don't know the complete back story, it's all meaningless to me. I think it's about time we get down to business, right?\""
    "\"Happy to oblige!\" Asakura said brightly, as their surroundings pulsed, the window turning into a gunmetal gray steel barrier, strange patterns coalescing across the walls. The circle on the floor around Haruhi abruptly winked out. \"Now, I've converted the entire space of this stairwell into-\""
    "Kyon spun on one foot, crying out with a great, \"Ki-yah!\" and kicking the door halfway across the roof. Sparing no more time, he swept Haruhi up in one arm and dashed through the opening."
    "\"Waaah!\" she protested. \"Why are you running away!?\""
    "\"Confined spaces,\" he answered, sliding to a halt in the middle of the roof and setting her down. \"Speed dial two again.\""
    "\"Right, right,\" she mumbled, reactivating the circle of light. \"So, what's so great about this if she can just turn it off, anyway?\""
    "\"It's a barrier and emergency help function,\" he answered, reactivating the beam saber and reassuming a defensive stance. \"Unless she seals this space off — again — she can't disable it.\""
    "Asakura gave a pained sigh as she stepped through the jagged distortion between her controlled dataspace and the rooftop. \"You shouldn't be able to manipulate data like that,\" she said reprovingly. \"I suppose that means it's time to stop holding back.\" She clapped her hands together before her and drew them apart, flinging a fan of dozens of identical knives outward. Kyon maintained his guard position, his free hand already clenched into a fist, the metal ridges of his skinsuit facing outward."
    "The knives adjusted their course, most homing in on him to suddenly be halted by a semi-circular barrier of glowing blue force before shattering into nothingness, but a handful stopping suddenly in the space over the circle around Haruhi. He opened his mouth to retort, but Asakura was already within his guard, driving yet another blade into his stomach. The inner carbon-nano- weave of the greatcoat and the force field of the skinsuit beneath it converted the stabbing force into a distributed shock wave, so instead of being pierced, Kyon was merely hit with the force of a speeding minivan, flying clear across the roof with a choked grunt."
    "\"In the end,\" Asakura remarked, watching his form tumble off the edge of the school building, \"all those toys are pretty silly if you don't actually know how to use them.\""
    "\"You have to give him credit, though,\" Haruhi said, peering very closely at the knives frozen over her barrier, not even glancing back to where Kyon had vanished. \"He comes up with one hell of a distraction ploy, doesn't he?\""
    "The blue-haired interface cocked her head to one side, blinking. \"What?\""
    "* * *"
    "The sensation of being hit with a force that would crush a mid-sized car into a work of modern art was not entirely new, but was without a doubt extremely unpleasant. His skinsuit did what it could to distribute the kinetic force evenly across his body, so the crushing pain was at least perfectly uniform in infliction. The balancing gizmos gave up the ghost on keeping him upright, and struggled to guarantee he wouldn't land wherever he flew head-first. His gravity manipulation defenses all strained to bleed the inertia of his impact off without even {i}more{/i} pain, but the end result was that he didn't slow appreciably until after he passed the edge of the five story rooftop."
    "Not what he'd hoped for by a long shot. All of the 'toys' would keep him mobile, even if he was afraid he'd need to be {i}poured{/i} out of the skinsuit when it was over. He'd have to beg Nagato or Haruhi to help him out and repair things later, but there was just too damn much to keep track of with all the attack vectors, defensive capabilities...."
    "\"It started off such a nice day, too,\" he mumbled, as his forward momentum was arrested and he began the downward plummet in earnest. How had it come to this, anyway...?"
    "* * *"
    "That day had started normally enough, but then, in his experience, that was true of nearly all days. This had caused him to become naturally suspicious of every day, to the point where he was starting to suspect a slow but sure slide into absolute paranoia. Haruhi was taking her toll on him ... even if she {i}was{/i} calming down, her behavior after that horrific (in retrospect) run-in with Sasaki was doing absolutely nothing to soothe him."
    "His preferred refuge from total madness was quite simple: Drink some milk."
    "He didn't know why it had such a calming, reassuring effect on him, but it did. So he poured himself a large glass in the kitchen, one ear perking up and catching the sounds of his sister playing a video game in the living room. Damn it, he thought. He'd even left his cell in the other room specifically to lay a claim on the system!"
    "Seriously, he thought darkly, taking a large swallow of his milk, the system was a Playstation Two — about ten {i}years{/i} out of date now, and he had to haul it all the way upstairs if he wanted to play games in his room. He probably shouldn't even bother getting worked up about such an antiquated gaming system. Even if it was the only gaming system in the house. His phone rang and he sighed, rolling his eyes but staying in the kitchen."
    "\"Kyon-kun,\" his sister called, pausing the game with a loud chirp, \"phone!\""
    "He lowered his glass, already able to anticipate Haruhi demanding his participation in something. \"Answer it for me,\" he called back between gulps. \"I'm busy.\""
    "\"Okaaaaaay,\" she said, before he heard her say, \"Kyon-kun's phone! He's too lazy to answer!\""
    "\"Thanks,\" he muttered under his breath."
    "\"Oh? Okay! I'll tell him. Feel better!\" Then her voice rose from conversational, to an unnecessary bellow, \"Kyon-kun! Yuki-nee-san says she's sick and really wants you to visit her!\""
    "He didn't even bother to grab the phone on the way out."
    "\"Can I come with...\" she began, before the door slammed shut. Shrugging, she turned back to the game after flipping Kyon's phone closed."
    "* * *"
    "He calculated the ride to Nagato's place as a twenty minute trip, at one point. When he reached the lobby, barely pausing long enough to lock up his bike, he wondered if he'd beaten his best time, but didn't feel the need to check. Instead, he dashed to the console, still gasping for breath, and fumbled, mis-dialing her room number and needing to hammer the 'cancel' button to dial again. \"Nagato!\" he called, the second she picked up. \"It's me!\""
    "The door opened."
    "After taking the elevator to her floor, he slowed his mad pace, seeing her standing outside the doorway to her apartment, waiting for him. He tried to imagine that he saw some relief around her eyes when he reached her side, but wasn't confident enough to be certain that was the case. \"Nagato,\" he said, nodding. \"What's wrong?\""
    "She gestured him inside, leading him to the table. He kicked off his shoes and went to the kotatsu, watching her warily."
    "After pouring a cup of tea for each of them in silence, she finally spoke. \"The Integrated Data Sentience Entity has determined that I have become a liability,\" she said in a soft monotone, nearly devoid of inflection."
    "He stared at her for a long minute, blinking. \"What ... do you mean?\""
    "\"Factors within my makeup have become too unpredictable. It has been calculated that I will commit another error. To prevent this, deletion has been scheduled in three hours, twenty one minutes, fifteen seconds; I will be replaced with an interface more suited to defending against possible Sky Canopy Domain interference.\""
    "After taking a deep breath, he growled, \"There isn't enough milk in the world.\""
    "She blinked several times in response."
    "\"How set is this?\" he asked, his hands shaking too much to hold the teacup properly."
    "\"It is absolute.\""
    "He took another deep breath, then jumped to his feet, nearly upsetting the table, and began pacing back and forth in her living room. She watched him silently. \"Okay,\" he said, after a moment of thought. \"I'll just—\" He broke off, fumbling at his pocket when he realized his phone was still at home. Biting off a curse, he asked, \"Can I use your phone, Nagato? I need to call Haruhi and the others.\""
    "For a moment, mild disappointment flickered around her eyes. \"It is not necessary.\""
    "He stared at her, then shook his head. \"What do you mean?\""
    "\"I requested your presence for ... personal reasons,\" she said. \"It was not a request for help.\""
    "\"I don't care!\" he shouted. \"I've always relied on you — now that you need help, I am {i}not{/i} going to just stand by and watch you get taken away from— From us!\""
    "She blinked, considering, then lowered her head slightly in her infinitesimal nod. \"I see,\" she said quietly."
    "\"So, I need to make some phone calls.\""
    "\"Understood.\""
    "* * *"
    "She couldn't imagine what had possessed Kyon to call her, ranting like a lunatic about Yuki being sick. But he'd done it from {i}her{/i} phone, which meant for whatever reason that he and Yuki were alone together. She wasn't certain why that bothered her, but it did — so when he demanded her presence, instead of telling him what he could do for trying to order the Brigade leader around, she swore that she'd be there."
    "After trekking all the way there, much to her annoyance, she found that she was the last to arrive."
    "Mikuru sat at one side of the table, opposite Yuki. Koizumi sat between them, his eternal smile faded to half its normal strength. Kyon himself stood next to her — he was the one who had answered the intercom and let her in. She narrowed her eyes at him and kicked her shoes off, storming into the room to Yuki's side and immediately pressing one palm onto the smaller girl's forehead. \"You don't feel feverish,\" she finally commented. \"But if you're sick, you shouldn't be up and about anyway.\""
    "\"Not sick,\" Yuki answered. When Haruhi turned to Kyon and scowled at him, she corrected, \"Dying.\""
    "Her irritation at Kyon's practical joke momentarily blew away, like settled dust being disturbed. \"Dying!?\" she yelped, turning to stare at the smaller girl. \"What of? {i}How{/i}?\""
    "Yuki blinked twice, then answered, \"I am not able to say.\""
    "\"Mikuru?\""
    "\"Um ... classified.\""
    "She scowled at Koizumi, daring {i}him{/i} to be a defiant annoyance, too. \"I don't know,\" he said, looking embarrassed and flustered."
    "Turning around, she glared at Kyon, letting her irritation return and focus on him full-force. \"I am not in the mood for pranks!\" she snapped. \"This better not be a joke!\""
    "\"I wish it was,\" he said back crossly, and she found herself taken aback at the force in his tone. She had a mental catalogue of Kyon-like behaviors, and this fell firmly into the category of the seldom-seen but always feared {i}angry{/i} Kyon. Dour, upset, irked, sarcastic, caustic ... sure. But angry?"
    "Hell, she'd once smashed his head into her desk — entirely on accident — and he was only {i}annoyed{/i}. And it wasn't for hitting his head, it was for disrupting a class! Nevermind that he had been dozing off before that."
    "She'd seen him genuinely angry two times. Only once had it been at her. She hated that memory more than anything else she knew about him, but couldn't dare to forget it. Once it had been at — of all things — his unfinished homework over summer break, though that was the lesser of the two displays; also the first. She didn't understand it, but she knew whatever it was, she wanted to be on his side against it."
    "Even then, some small part of her really didn't like the way that when he chose to, he simply seized command of her precious hand-crafted Brigade and, no matter how cute it was—"
    "She firmly suplexed that thought into oblivion."
    "\"Alright,\" she said evenly. \"Tell me what's going on.\""
    "Kyon ran his hands through his hair and began pacing, not looking at her. Good; she wasn't the one who had made him mad."
    "\"Have a seat,\" he said. \"This may take a bit, and I need a promise from you before we start.\""
    "\"I'm not making a blind promise,\" she retorted, though she did take the seat opposite Koizumi, between Mikuru and Yuki. Yuki wordlessly poured her a cup of tea, which she threw back in a single gulp."
    "\"I need you to promise to listen to everything we have to say before leaving,\" he answered."
    "\"That's stupid,\" she grumbled. \"If Yuki's in danger, what kind of person do you take me for?\" She wasn't {i}that{/i} bad about ignoring the needs of her brigade members."
    "\"Even so.\""
    "\"Fine,\" she sighed. \"I promise. Now can you get on with it?\""
    "\"Okay,\" he said, pacing around to the window. \"Almost a year ago — last May — we ended up going on a city search where no one but you and I showed up.\""
    "\"I remember,\" she said, annoyed. A stupid practical joke on his part ... though, it had given her the idea for the movie."
    "\"I told you that aliens, espers, and time travelers really existed, right?\""
    "\"We're going back to that?\" she asked, raising an eyebrow. \"Really?\""
    "\"Yeah, okay, you remember it, so I don't need to say it again,\" he said with a shrug. \"Koizumi, you promised that if it had to happen, you'd stand next to me when Yuki needed our help. Remember?\""
    "\"Yes,\" the smiling boy said, though his smile had completely vanished. \"As much as it scares me.... Suzumiya-san, Kyon-kun is speaking the truth.\""
    "\"You're an esper?\" she asked him doubtfully. He gave a solemn nod, and she internalized a sigh. What, was Kyon just {i}acting{/i}? Was this is unsubtle way of saying he wanted to be a star in the next movie, not just a camera man? She had to admit, his emotion seemed genuine, but why couldn't he just have {i}asked{/i} her? There was an awful lot he could have just asked for, and never bothered to!"
    "That thought was drop-kicked to fly off next to the last banished thought."
    "\"And, Mikuru, you're a time traveler?\" she asked, idly spinning her teacup on the table before her."
    "\"Um ... that is ... I can't....\""
    "\"Asahina-san,\" Kyon broke in suddenly, \"please ask your supervisor to declassify this for me.\""
    "Mikuru stared at Kyon, her eyes large and confused. \"Y...yes,\" she agreed, her glance flickering nervously to Haruhi before she pressed a hand against the side of her face, and her eyes became unfocused. They abruptly snapped back into focus, though her expression had become comically bewildered. \"I ... they said yes!? I don't understand! Kyon-kun, how-\""
    "\"That's ... classified,\" he answered, looking away. \"Anyway, go ahead and explain it to Haruhi.\""
    "\"Oh! Um, Suzumiya-san ... what he says is true! I am a time traveler, though, it's more accurate to say that I'm a visitor from the future who is projected into the past, almost like a two-dimensional image projected into—\""
    "\"Right, right,\" Haruhi cut her off. \"You're a time traveler. Understood.\" Though, Mikuru's acting skills had picked up quite a bit, too.... This better not be a ploy to make Kyon the male lead opposite Mikuru in the next movie! Saving that thought for later, she turned her gaze to Yuki. \"And you're an alien?\""
    "\"The function allowing me to confirm or deny that data has been denied at this juncture in time,\" she answered. Turning to Kyon, she added, \"One hour and twenty minutes remain.\""
    "He bit off a curse, running his hands through his hair. Haruhi was taken aback again ... he obviously didn't like getting bad grades or doing poorly on exams, but he almost never got {i}this{/i} stressed about things. This was starting to become unnerving."
    "\"Okay,\" she said, before he could speak. \"Look, this has gone far enough. I get it, alright? Your practical joke ... okay. Fine. What are you really after? Producer? Co-director? You want to help write the script for the next movie? Let's just cut to the chase — this isn't really fun, especially since it's at my expense!\""
    "\"At {i}your{/i} expense—\" That had done it, she realized, flinching back. Now some of his anger was directed at her, though he quickly controlled it, smacking one palm against his face. \"Last May,\" he said, \"you came to class with your hair in a ponytail.\""
    "She suddenly couldn't meet his eyes, and a previously suplexed thought began to climb back into her awareness."
    "\"It was hot!\" she said defensively. \"What of it?\""
    "\"You had a dream — a nightmare — that night,\" he added."
    "\"So?\" She forced her heartbeat to still. She'd {i}told{/i} him that much, why wouldn't he remember? She did, after all, even now."
    "\"So, in your dream, you watched giant blue creatures smash apart the school, and you were very excited about abandoning the Brigade — your friends — and leading an exciting new life in whatever world was to come.\" Koizumi looked uncomfortable. Mikuru's face turned red, and she began studying the bottom of her teacup intently. Yuki merely stared at her, unblinking."
    "\"I never told anyone that,\" she mumbled."
    "\"In the end, I told you that I wanted to come back to {i}this{/i} world,\" Kyon said. \"That it was more interesting than you realized. Do I have to say what I did to wake you up?\""
    "She felt her face color. \"N...no,\" she managed. \"Who— No, {i}what{/i} are you?\""
    "\"I am a normal person,\" he told her, shrugging. \"I happen to have traveled to parallel worlds. I have traveled through time. I've seen some amazing things ... but through it all, I always come back {i}here{/i} to be with my friends.\""
    "It was getting very strange, and she didn't know why, but the conversation was starting to make her uncomfortable. Maybe the knowledge of her dream was just an expert analysis based on her personality? The refusal to mention the kiss specifically was because they didn't {i}know{/i}? But she wasn't certain she wanted to hear him say it {i}was{/i} a kiss, here, right now...."
    "And she'd {i}promised{/i} she would listen. \"You're claiming that you're a {i}slider{/i}?\" she asked, blinking, buying herself some time to think."
    "He was momentarily startled by the question, then exchanged a glance with Koizumi, who shrugged. \"Actually, Kyon-kun, you may be,\" the supposed esper said, smiling. \"That would explain why one never seemed to appear; it was you!\""
    "\"Nevermind that!\" he said quickly, shaking his head. \"Haruhi, there's something I have to tell you, something I think will make you believe me.\""
    "\"What's that?\" She couldn't think of anything else to say or ask."
    "\"Tanabata last year was the first time I traveled back in time,\" he began, his expression solemn. \"I went to a night three years earlier. That would be Tanabata four years ago. While I was there, I was sent to East Middle school, carrying Asahina-san on my back.\""
    "\"Y...you're...\" she gasped, her eyes widening as the world around her spun, the amazing, simultaneously horrifying and delightful realization that he was speaking the truth was making her dizzy."
    "\"And I met a younger version of yourself, and wrote the message, 'I am here' on the school grounds, following your instructions. You asked who I was, and I told you that I went by ... John Smith.\""
    "\"{i}You're{/i} John Smith!\" She wasn't aware of getting up from the table, uncertain if she had moved around or just jumped over it — she just knew that she had flung herself at him, tackling him to the floor and grabbing on tightly. \"I {i}knew{/i} it!\" she yelled. \"I {i}knew{/i} I'd find you again!\""
    "* * *"
    "\"Hmm,\" Ryouko mused, turning slowly around, to where her sealed space in the stairway had been breached. \"It was broken from the outside, somehow? I wonder—\" The shrill buzz of a brilliant energy beam licked out from the roof of the tiny structure that housed the stairwell."
    "Ryouko was struck in the chest dead-center of mass, her entire body glowing white for a second before she staggered— Instantly another beam shot out from the same location, lighting slightly to one side, near the girl's left shoulder. A third, though not as brightly glowing shot was somewhat lower, near her stomach, and Ryouko dropped to her knees, eyes widened. \"High yield neutron flare?\" she asked. \"Quantum entanglement to disrupt my connection....\""
    "De-stealthing, Kyon stood from his hiding place atop the stairwell housing, his greatcoat billowing behind him. The end of his weapon was glowing orange with discharge, the shape changed from a simple cylinder to a much thinner meter-long construction of sturdy rails and curving hand guards. He slung it over his shoulder and ignored it, pulling the second cylinder from his coat and leaping the twenty meter distance between himself and Ryouko."
    "Beneath him, a widening circle of dust marked where he leapt from, and while in midair he flipped over, a sequence of touch-points converting the unadorned cylinder into a stocky, blunt, two-handed gun. It fired with a rasping cough, launching a ring of metallic spikes to burrow into the rooftop around Ryouko, and then a grid of crackling brissant energy raked between each of the spikes, snaring the girl in a glowing, shuddering net."
    "\"Ah,\" she said, her voice disappointed as Kyon's repulsor and gravimetric systems flared his momentum and spread it evenly across the entire rooftop, landing him near Haruhi, at Ryouko's side. \"I failed again.\""
    "\"Is that going to hurt her?\" Haruhi asked, crossing her arms over her chest and raising an eyebrow at Kyon in concern."
    "\"Hurt her?\" he asked, somewhat indignantly. \"Haruhi, she's tried to kill me. Three times, now, and you just saw one of them! Your primary concern is that I not {i}hurt{/i} her?\" He muttered to himself beneath his breath, folding away his firearm into storage."
    "Haruhi tapped a toe impatiently, still staring at him."
    "Pulling a phone identical to the one Haruhi was holding from one pocket, he punched a key. \"Nagato should be here shortly,\" he added, shaking his head. \"This is all up to you. I already know you'll take care of things just fine.\""
    "\"Yes!\" she said, pumping one fist in the air. \"I get to do something! Hey, how's the future?\""
    "\"It's awesome,\" he said, annoyed. \"Try and have some pity for the me that nearly got murdered off a building, huh? Anyway, just so you know, she's programmed to try and kill me; she won't do anything to you. And you won't see me tomorrow at school, because I'm going to be ... well. You'll find out.\""
    "\"Okay,\" she agreed, frowning. \"But, hey, why aren't you going to be around?\""
    "\"Further information is not available here,\" he warned, shaking his head. \"Now, when you see that other me, tell him I said 'hi', like I always do.\" He paused before glancing at his phone again with a grimace. \"My time's up,\" he announced, re-engaging his stealth field and vanishing from sight."
    "\"What?\" Ryouko asked, still trapped in the containment field. \"He just abandoned me here with you?\""
    "\"Damn it,\" Kyon groaned, from where he was just climbing over the edge of the building, breathing hard. \"I hate when I have to rely on time-travel to take care of things.\""
    "\"Oh!\" Haruhi said cheerfully. \"Future-you says 'hi', like always!\""
    "\"Yeah? That guy always annoys me. Probably almost as much as I'm annoyed by having to save past-me.\" There was a flash of light and a warping of space, and then Nagato appeared at Haruhi's side. The circle of illumination around Haruhi's feet had vanished."
    "While Nagato knelt to examine Ryouko, Haruhi dashed to Kyon's side and helped him stand. \"How bad was it, anyway? Future-you seemed to think you weren't very tough, and that you were hurt pretty badly.\""
    "\"I think I've got some internal bleeding,\" he said, wincing, one hand pressed to his abdomen. \"And some of my gear is messed up from the impact and overload. While this is fun for you, I wouldn't mind some medical assistance.\""
    "\"Sure!\" she said cheerfully, clapping one hand on his shoulder. \"Happy, healing, all-better thoughts!\""
    "\"Medical program loaded,\" Nagato added helpfully from where she was studying the other interface. \"Permission to proceed?\""
    "\"Granted,\" Kyon said, straightening up as a sparkle of green and white lights suffused up from the rooftop beneath him, flowing through his body and undoing the damage. \"Oh, that feels so much better! Thank you; that probably saved my life. And for future reference, you can probably assume that I'm okay with that one being used.\""
    "\"Acknowledged,\" Nagato agreed."
    "\"Hmm, hey, Kyon, you know, you're going to have to really step up your game,\" Haruhi said suddenly, tossing his cell phone back to him."
    "He scowled, pocketed it, and then banished all of his equipment, the greatcoat taking the longest to phase out of view. \"What's that supposed to mean?\" he asked in irritation."
    "\"Well, this is fun and all, but you can hardly expect me to take your lectures on using power responsibly seriously when you're always relying on your future self to save you,\" she warned, raising one finger and waggling it at him."
    "He sighed and hung his head. \"You know, I really am trying my hardest,\" he muttered, crossing his arms over his chest and looking away towards the sea. \"But I can't just leave you alone, and Nagato can't handle another interface right now.\""
    "\"And you did such a great job!\" Ryouko encouraged from beneath her energy net. \"Time travel, is it? Now that's one tool you seem to know how to use well.\""
    "\"It's fine,\" Nagato said tonelessly. \"Asakura Ryouko is isolated and confined; she is limited to her organic functions at this moment. After she is dispatched, I will retrieve defenses to protect against further interference.\""
    "\"Waaaait!\" Haruhi yelled, stomping one foot and spinning to face Yuki. \"'Dispatched'? I don't think so! If you need something from her, there's got to be a way to do it without killing her! What's the point of running into another alien, just to kill them?\""
    "\"But the fighting is fine,\" Kyon observed, stretching his arms above his head, then swiveling his hips, stretching his spine out. \"After all, no one of any importance was smashed off a building.\""
    "\"Kyon!\""
    "\"Alright,\" he said, shaking his head. \"I don't really want Asakura to die either. But if her body were destroyed, she'd just go back to the place she came from. At least, as I understand it.\" He shot a questioning glance towards Nagato."
    "She didn't meet his eyes."
    "\"Good!\" Haruhi nodded decisively, grinning again. \"Yuki, let's come up with a backup plan. Something that will let you get your power-up and let us reform Ryouko. Can we do that?\""
    "Nagato stared intently at Ryouko, then gave a decisive nod. \"Awaiting program,\" she announced."
    "\"Hmm,\" Haruhi mused, narrowing her eyes and peering intently at Ryouko, who merely watched back curiously. \"Um ... some kind of second chance ... a chance to start over, prove herself, and ... let's see, realize she doesn't want to kill Kyon at all. And she gets to give Yuki what she needs to make her equal to the next interface that comes along.... But no brainwashing, that's not cool. So, maybe an 'evil' module or something like that, which Yuki can purify and use for good, letting Ryouko learn how to become a nicer person? Yeah! That sounds very good! Let's do that.\""
    "The pinned interface blinked several times, then turned her eyes to Kyon from beneath the glowing energy net. \"None of this has been reported to my superiors,\" she commented. \"It's entirely possible that this new knowledge could change their perceptions; there's no reason to be hasty!\""
    "\"Program loaded,\" Nagato replied. \"Permission to proceed?\""
    "\"We can be reasonable!\" Ryouko protested."
    "\"You're probably the most reasonable person I've ever had try to kill me,\" Kyon agreed. \"But I remember that time you {i}did{/i} stab me all too well.\""
    "\"No stabbing!\" Haruhi said in a chastising tone. \"Bad Ryouko! No class rep votes for you!\""
    "\"...you don't really think that's her prime concern, do you? Aside from which, did you even vote last time?\""
    "\"It isn't,\" Ryouko agreed. \"And no, she didn't. But, about being reasonable...?\""
    "\"Anything that I should know about this program, Nagato?\" Kyon asked, quirking one eyebrow higher."
    "\"It will be beneficial to all involved,\" Nagato assured him, while Haruhi nodded knowingly."
    "\"Okay,\" he sighed, shaking his head. \"Granted.\""
    "Then smaller girl turned her gaze back to Ryouko's bound form, the faintest hint of a smile coming to her lips. \"I will not let you harm him again.\""
    "* * *"
    "Kyon hadn't had time to think about things before. Part of that was from a certainty that if he had let himself think about things, it could easily become too late to do anything. Part of it was his desire to make sure he could find his way back to his own world. But most of it was the fact that he could deal with the {i}world{/i} going away, as long as he could keep the Brigade intact, regardless of his position in it."
    "Though, that thought in mind, when he awoke, he stared out the window after rising before his younger sister yet again. This habit was probably going to wear him out, he thought. Still, by the time he had finished washing up, just in time to watch her prance out of her room, he couldn't help but smile. Her face fell when she realized that the era of deadly wake-up elbow-slams was probably at an end."
    "He busied himself making breakfast while mulling over the likely consequences of his impulsive decision. And there would be consequences, he had no doubts of that at all."
    "Serving his curious sister a piece of toast with a fried egg on it, he set about preparing one for himself. Now Haruhi, as she understood it, believed that she could change reality...."
    "* * *"
    "\"But you're saying, I have a {i}power{/i} I don't even know about?\" Haruhi asked, now pacing anxiously back and forth. \"Why would you have {i}kept{/i} this a secret from me?! Even more than the fact that you're the people I've been looking for, the fact that {i}I{/i} can do things!\" She looked on the verge of tears and laughter at the same time."
    "\"That was the decision of my superiors,\" Koizumi offered, frowning. \"It was believed that ... there could be unfortunate consequences.\""
    "\"And you,\" she continued, peering at Mikuru, \"also followed your instructions?\""
    "\"U...um,\" Mikuru said, shrinking into herself slightly. \"I...it's not a matter of choice for me ... literally, I can't talk about classified information when it's classified. If I try to, then classified info—\" She hung her head with a weary sigh. \"Sorry.\""
    "\"And you?\" she pressed, turning her gaze to Yuki, who sat at the table, staring at the teacups."
    "\"Focus is on preventing my imminent deletion,\" the interface finally answered. \"Limited resources.\""
    "\"So, all along, the lowliest ranking member of the SOS Brigade is the only one who ever actually tried to tell me the truth,\" Haruhi grumbled."
    "\"That aside,\" Kyon said, shifting his shoulders, \"we can talk about this later. I'm sorry, but I'm really worried about Nagato. Since you believe us, or at least, I think you do—\""
    "\"I don't,\" she countered. \"I believe {i}you{/i}. Because you {i}tried{/i}. But....\" She trailed off and shrugged, gesturing to the other three. \"The people who wormed their way into my good graces were working against me! How can I trust them?\""
    "Mikuru said nothing, just sniffling as tears trickled down her cheeks. Koizumi's eternal smile had withered to a pained shadow of its normal impenetrability. Yuki continued staring at her."
    "\"Because I do,\" Kyon said, breaking the uncomfortable silence. \"I don't know if we can believe {i}everything{/i}, but I know that Nagato is a humanoid interface. I've traveled through time with Asahina-san. Koizumi's shown me the places where he and the other espers of his kind fight.... And in every case, all three of them couldn't tell you because their bosses {i}told{/i} them not to.\""
    "\"What about {i}your{/i} boss,\" she snapped, turning to eye Kyon with suspicion. \"What does {i}that{/i} person say?\""
    "\"Right now she's asking me if she has any reason to trust her closest friends,\" he answered. \"And I'm begging her to, because that may be the only way to save Nagato's life.\""
    "\"I.... I'm your boss?\" she asked, narrowing her eyes in suspicion. \"You don't work for anyone else?\""
    "\"Thankfully,\" he agreed, nodding. \"I suppose I have done things for Asahina- san and her superiors. I know my actions have benefited Koizumi's Organization. But I've only ever done things because I felt it was important for you, or for the sake of the entire world.\""
    "\"The entire world?\" she pressed, struggling to contain all the new information. \"You've saved the world?\""
    "\"Technically, {i}you{/i} did,\" he said, shaking his head. \"I just convinced you to do it ... but we already went over that.\""
    "\"So you're some kind of undercover hero without any of his own special abilities that fights to take care of me, and to save the world?\" she asked."
    "\"Yes,\" Mikuru said quickly, nodding. \"He absolutely does! I don't know if you'll believe me, but it's the truth!\""
    "\"When this reality was overwritten with a reality where you had no powers, and none of our factions existed,\" Yuki contributed suddenly, \"he found a way to restore this reality once more, actually creating a parallel universe.\""
    "\"Then I'll believe that,\" she allowed, as strange as it seemed. But he {i}must{/i} be ... it made {i}sense{/i} that John Smith was Kyon if he was a normal person who called in favors from others. But still.... \"Okay. Things are going to change, right now. Kyon, you want me to save Yuki, right?\""
    "\"You mean, you don't?\" he asked, aghast."
    "She winced. \"Of course I do! But I want your opinion!\""
    "\"Absolutely! Haven't I been clear enough!?\""
    "\"Okay, then,\" Haruhi decided. \"But no more running around behind my back! Anyone who can't do this is out of the Brigade. Everyone who really wants to help me out, and stay in the Brigade ... everyone who wants to prove to me that this is true and earn my forgiveness for the whole stupid masquerade ... has to accept {i}me{/i} as a boss, just like Kyon!\""
    "She nodded decisively, then her eyes widened slightly in realization. \"Oh, and Koizumi? You're demoted. Kyon's obviously more trustworthy as a vice commander, since you already report to him anyway. Everyone got it? We're the bosses — not your 'Organizations' or 'Thought Entities' or mysterious future 'superiors' who somehow control your minds!\""
    "\"Understood,\" Yuki replied quietly. \"Permissions change indexed. Awaiting transfer.\""
    "\"I promised this already,\" Koizumi agreed shakily. \"Very well.\""
    "\"I.... I can't,\" Mikuru whimpered. \"I'm not even allowed to try! Oh, Suzumiya- san, I {i}would{/i}, but I can't—\" Mikuru's eyes widened as she looked up, blinking away her tears. \"I ... I'm getting a message?\" she asked. \"I ... I am allowed to do whatever Kyon-kun asks? B...but not you? I don't understand! I'm sorry, those are just my instructions!\""
    "\"Well, fine,\" Haruhi grumbled, narrowing her eyes. \"I can trust {i}him{/i}.\""
    "\"Right,\" Kyon said, looking at the interface at the table. \"Nagato, how much time is left?\""
    "\"Thirty two minutes, fifteen seconds,\" she said."
    "\"So ... how do we do this?\" Haruhi asked, biting her lip. \"How do I use my power?\""
    "\"Your power is very dangerous,\" Kyon warned her. \"If it's used incorrectly, you might accidentally destroy the universe. But Nagato can use that power safely. So, my idea is that you can become her boss and replace the Integrated Data Sentience Entity for her, and hopefully we won't have to destroy them. If we have to, then they have to go — that's all there is to it. But if we can avoid that ... well. Nagato, can you do what I'm thinking of?\""
    "Yuki blinked several times, then said, \"A memetic link can be formed between myself and Suzumiya Haruhi, such that all created data is cached within an internal buffer for analysis to await approval or disapproval. This will require the permissions of Suzumiya Haruhi, and an additional password carrier.\" Her eyes fixed on Kyon. \"That carrier shall be you. Is this acceptable?\""
    "\"If that's how it has to be done,\" Haruhi agreed with a shrug. \"I don't want you to die, Yuki.... Kyon?\""
    "\"Yeah,\" he said, nodding quickly. \"Let's do it.\""
    "Rising from her seat, the smaller girl reached both hands out and placed her fingertips across the sides of Haruhi's head. \"Link established,\" she declared after a minute of silent staring into the taller girl's eyes. \"Awaiting data creation.\""
    "\"Data creation?\" Haruhi asked, frowning. \"What does that {i}mean{/i} exactly?\""
    "\"It has to do with how ... what she is views our world,\" Koizumi supplied helpfully. \"From our point of view, think of it as the ability to create new aspects of reality. I believe she is prepared for you to try and use your powers.\""
    "\"Yeah, but ... how do I do that?\""
    "\"Try and believe something,\" Kyon suggested. \"Believe that Yuki is going to be fine, and will report to you from now on.\""
    "Haruhi shifted her gaze to the smaller girl before her, then took a deep breath and closed her eyes, concentrating. \"Yuki works for me,\" she muttered. \"She's a real alien ... but she's going to break away from her bosses and work for {i}me{/i}....\""
    "\"Program loaded,\" Yuki said. Turning her eyes to Kyon, she asked, \"Permission to proceed?\""
    "\"Granted,\" he said without hesitation."
    "* * *"
    "After finishing his breakfast and heading to school, he was startled to run into Haruhi at the train station at the bottom of the hill — literally. The girl shot out from behind one of the pillars supporting the heavy structure keeping rainwater off the train platform, nearly plowing him over as she launched herself, arms wrapping around him as she swung around with her momentum, crying out, \"YES!\""
    "Struggling and only barely managing to keep his balance, he eyed all of the other Kitago students around them, watching with raised eyebrows and open smirks. \"Hey,\" he managed, remembering his new role as the vice commander, and everything they had discussed the previous night. \"What's going on?\""
    "She released him with a huge grin. \"Yesterday, after I went home, was {i}so{/i} {i}cool{/i}!\" she squealed. \"I never knew you could do all those things! I mean, I suspected, since you were the best member of the Brigade next to myself and everything, but that was {i}amazing{/i}!\""
    "Her smile not fading in the slightest, she handed him an envelope, the seal already broken. \"You said I should give this to you,\" she added. \"You said to put it in your shoe locker, but why wait? What's so great about messages in shoe lockers?\""
    "\"They pretty much never go well for me,\" he sighed, taking the envelope and eyeing the broken seal. It was just a sticker, something that looked like it might have been stolen from one of his sister's collections. \"You opened it already, I see.\""
    "\"Well, of course! Doesn't make any sense to me, though. I probably wouldn't have opened it if you hadn't {i}told{/i} me it wouldn't make any sense to me. Why did you want me to give you a letter from yourself, though?\""
    "The skies were clear of rain, if gray, so he sighed and pulled the letter out of the envelope while proceeding up the hill. \"I'm guessing,\" he said mildly, \"that since I just went home last night, I'm going to be time traveling back to yesterday relatively soon.\""
    "\"Hmm...\" she mused, considering. \"Can I go with you?\""
    "\"'No she can't',\" he quoted the first line of the note, scrawled hastily in his own handwriting. \"Well, seems that future me is a bit of a smart-ass.\""
    "\"Humph! I could have told you that.\""
    "He eyed her, then shook his head. He'd brought this upon himself. Maybe, with luck, Nagato could act as a controlling agent and keep Haruhi in line. Maybe, he told himself. If this was what it took to save Nagato...."
