label OB_3:
    "Though the car ride was only ten minutes long, Kyon judged that Sasaki had calmed down considerably in that time. He was glad, too — there had been some real concern that she might have been injured in the thick of it.... The smoke screen had allowed him to conceal what he'd done from her, at least, but it was still riskier than he would have liked. He expected she was still somewhat shaken by that, but he hadn't devised a better way to free her before it was time for the operation to actually go into effect."
    "When they reached the hospital, they climbed out of the car and she moved to walk near him — but not take his arm, this time. He gave her what he hoped was an encouraging smile, which seemed to work; she returned a weaker, but genuine smile."
    "After that, they strode into the lobby of the hospital, Kyon raising an eyebrow to see Shinobu standing inside the entrance, moving to his side as he entered. Leaning close to him when he paused, she whispered, \"Kyon-dono ... Nagato-san was just taken in for her stitches, but she should be fine.\""
    "\"That's a relief,\" Sasaki remarked, one hand going to her chest as she offered a more reassured smile."
    "Kyon nodded his agreement, surprised to realize what had happened— Damn! He'd thought the injury would be wiped away like the damage Yuki had taken in the past...."
    "\"Ah— I don't suppose I can see her yet?\" he asked hopefully."
    "\"Suzumiya-san and Asahina-san are with her at the moment,\" Shinobu said apologetically. \"It would probably be unwise to have more people in the room until the operation is finished.\""
    "He nodded at that, though given Mikuru's presence, he was confident she'd be able to stitch Yuki up just as well as she'd taken care of him, doctor or not. He wondered if the doctors would let her help, before forcing himself to focus on the situation at hand."
    "\"Well, then, are the others waiting?\" he prompted."
    "Shinobu nodded, then gestured for him to follow. He beckoned Sasaki to keep pace with him as Shinobu led the way into the depths of the hospital, stopping in another, smaller lobby, where a pair of Tsuruya's men stood guard. The heiress and the slider were sitting side-by side, not far from Mori. Kanae looked anxious, and Tsuruya thoughtful — until they caught sight of Kyon and Sasaki."
    "\"Ah,\" Tsuruya said, blinking, before nodding. \"Missions successful!\""
    "\"Sempai!\" Kanae cheered, jumping out of her seat and rushing to his side, recovered from the earlier strain of her sliding."
    "\"Hey, Kanae-chan, Tsuruya-hime,\" he returned, smiling, absently patting the slider's shoulder, while Tsuruya adopted a slightly surprised blush. \"Mori- san? Where's Koizumi?\""
    "\"He and Kasai-san arrived a bit ago with Kyouko-chan,\" Mori assured him. \"Itsuki-kun ran into some problems — but he took care of them. Right now she's being looked at.\""
    "Kyon wondered what those problems might have been, but resolved to speak it over with the esper later — he still owed him another thanks for that rescue. \"Alright,\" he said, shrugging, then picking a seat near Tsuruya. \"As long as they're okay. Man ... that was a lot of work,\" he sighed."
    "Kanae took the next nearest seat without hesitation, leaving Sasaki to pick between sitting next to the slider, or Mori."
    "\"This ... isn't quite what I expected when we planned to meet,\" Kyon's friend mused, sitting next to Kanae, eying the slider questioningly. Blinking, Kanae turned a curious look of her own to Sasaki. \"Ah, we didn't speak much when we last met — your name is Kanae, is it?\""
    "\"Ah, yes,\" Kanae allowed, nodding uncertainly. \"Um, I'm Michikyuu Kanae.\""
    "\"And I'm Sasaki,\" she answered in kind, smiling. Her smile slipping slightly, she added, \"That's ... both of my names, embarrassingly.\" She eyed Tsuruya uneasily, then turned her attention back to the slider, but before she could say anything else, the door leading to the operating room exploded open, catching on the stopper with a loud squeak."
    "Kyon was on his feet before he realized it, relaxing when he saw Haruhi standing in the doorway, grinning as her foot lowered from a triumphant kick, one hand holding Yuki's wrist as she led the smaller girl forward. Mikuru was on Yuki's other side, looking relieved, and behind them, Kuyou drifted in to join the rest."
    "He was a little surprised at how much he'd missed Haruhi, Yuki, and Kanae when he thought about it. Especially since the slider had just rescued him, from her perspective, even though he'd had days.... He resolved to find some way to thank her in the future. For the moment, as much attention as he was paying to Haruhi, he didn't miss the way her smile lessened when she saw Sasaki."
    "\"Haruhi,\" he called, rising to his feet and moving to stand before her and Yuki. \"Yuki-chan, are you alright?\""
    "The slighter girl nodded at that, raising a bandaged right hand to show off the gauze covering her palm."
    "\"This is almost perfect, though,\" Haruhi judged. \"Once Koizumi reports that Kyouko's done, everyone will be accounted for, right?\""
    "\"Right,\" Kyon agreed."
    "\"So—\""
    "She cut off, smiling brightly when the door that Kyon and Sasaki had strode through earlier opened, revealing Koizumi. Kasai and Kyouko followed the boy, the twin-tailed girl flinching away at the sight of Haruhi and Kyon. He wondered what it meant that she flinched towards Koizumi, but was quickly distracted by Haruhi's recovery:"
    "\"Okay — right— Now that we're all here, Mori-san, you can go ahead and start on Kyouko's interrogation — I want to know what her allies thought they'd get out of this!\""
    "The female esper's eyes widened in fright as she froze, Kasai closing the door behind her as her eyes scanned anxiously across Kyon, Haruhi, and Mori, in turn. Taking in her trembling, Kyon bit his tongue, glancing at Sasaki's expression, and the way she suddenly became worried. The strangest part, though, was the way that the usually unflinching Koizumi gave him an unabashed pleading expression, before covering it with his mask of patient neutrality."
    "\"Let's not go that far,\" he decided, shaking his head. \"If you missed it, Tachibana was being coerced, Haruhi.\""
    "\"Y...yes,\" the esper stuttered quickly, clasping her hands to her chest. \"I.... That is....\""
    "\"They were holding her family hostage — they're safe now.\""
    "Haruhi crossed her arms over her chest, frowning. \"Kyon,\" she said slowly, \"that girl almost got you very, very badly injured. You're just going to ignore that?\""
    "\"I'm not ignoring that,\" he countered, frowning back. \"I'm just saying we should calm down a bit. Don't you think she's shaken enough already, after what we went through?\""
    "\"Ah, I agree,\" Koizumi chimed in quickly. \"Commander, Vice Commander — if it's not too soon, might it be possible to offer protection to her in exchange for her information? There's no need for animosity between us.\""
    "\"And how's that going to keep her honest?\" Haruhi asked doubtfully, her eyes on Kyon, and not Koizumi."
    "\"Respectfully,\" Mori broke in, \"this is much more reliable than attempting to extort information out of anyone.\""
    "\"Alright,\" Haruhi grudgingly allowed, huffing a sigh, her frown deepening. \"Fine — Koizumi, she's your responsibility for now, if Mori-san won't even be interrogating her.\""
    "\"Understood,\" he acknowledged without hesitation. \"In that case, I believe if she's willing to cooperate, Tachibana-san should be allowed to rest and recover for the time being.\""
    "\"That sounds like a plan,\" Kyon agreed. \"Go ahead and ask Shinobu-san to have her assigned a room here for tonight, so she's got some place safe to stay until we get this sorted out. Ah ... Sasaki, I'm going to need to meet with some other allies for a bit. Maybe you and Suou-san would like to keep Tachibana company?\""
    "Haruhi relaxed noticeably at Sasaki's quick nod. \"Yes, of course,\" she agreed. \"I would also like to speak with her, knowing that her recent decisions were forced. Ah, but ... Kyon, we ... will be able to speak later, though?\" Sasaki pressed, offering a hopeful smile. \"As busy as I understand you must be, I would still appreciate that.\""
    "\"Of course,\" Haruhi answered, before Kyon could. \"You, Kyon, Tsu-chan, and I should speak once we finish — Mori-san, you have our conference room ready upstairs?\""
    "\"Absolutely,\" she agreed."
    "Kyon grunted, nodding Kasai over as the pair of Tsuruya-gumi guardsmen moved to unobtrusively follow Koizumi's group. Sasaki shot one last glance at him, before turning to ask Kuyou a question about something. Hmm ... that might be interesting later. He wondered what the dark-haired entity would tell Sasaki. She'd learned to bake cookies, hadn't she?"
    "Haruhi waited for the precise moment that the door separating Sasaki from the other swung shut before launching herself at Kyon, grabbing onto him tightly and prompting him to reflexively hug her back. Mori blinked, slightly taken aback at the ferocity of Haruhi's gesture. A heartbeat later, though much more sedately, Yuki moved to the side, awkwardly embracing both."
    "Kyon managed to fumble one arm free to include Yuki as well, considering her injured hand. Still.... \"Haruhi?\" he managed to ask, over the top of her head. \"Are you alright?\""
    "She made an unhappy noise, her face pressed into his chest, and he managed an awkward smile. He thought he could understand why she was upset, more than just a little."
    "\"Asahina-san's not scratched,\" he offered, weakly. \"I swear!\""
    "\"Dummy,\" Haruhi grumbled into his chest. \"I know you like Mikuru-chan and wouldn't really let her get hurt....\""
    "The time traveler allowed a nervous giggle to escape at that."
    "Haruhi heaved a sigh, breaking away from Kyon as Yuki also released the embrace. Tsuruya moved to his side, waving at Kasai as she said, \"Mori, Kasai — Haru-nyan and Kyon's affection — no one outside of us needs to know about that. Even my father.\""
    "The brigade chief's face began to suffuse red with realization of the witnesses she'd forgotten about."
    "Kasai and Mori both looked at Tsuruya in surprise, while the younger girl merely grinned in response, moving to Kyon's other side and taking his arm. \"But Kyon-kun is doing nothing wrong,\" she added pointedly. \"You can tell my father truthfully that Kyon-kun is loyal and makes me very happy!\""
    "\"Yes!\" Kanae chirped agreeably, managing a smile."
    "\"U...understood,\" Mori allowed, not meeting Kyon's eyes as Kasai offered a small shrug. \"To the conference room, then?\""
    "* * *"
    "All things considered, after her rescue, Kyouko hadn't really known what to expect. Koizumi had protected her, and then brought her to a place where a kind nurse had checked her out, finding some scrapes to treat and then giving her some painkillers to ward off the effects of the stun she'd been incapacitated with earlier."
    "Still a bit shaky, she followed Koizumi's lead into the hospital interior until he met with an elegant woman in a traditional kimono in one of the main lobbies, who answered his whispered questions with a few nods and a gesture back to the interior of the building."
    "Not long after that, the boy led the three girls following him to a private room, where he explained, \"For safety, we would appreciate it if you stay here, where we can more easily keep an eye on you tonight. I would understand if you were hesitant, though.\""
    "\"Well, you're Kyon's friend, and he does seem to have quite a grasp on this,\" Sasaki mused. \"Ah — before you answer his question, Kyouko, I apologize for interjecting here ... but it seems I had mistakenly believed you had more control over your situation recently and blamed you for things I should not have. So ... please understand that I regret my behavior towards you lately.\""
    "The esper was surprised at hearing the girl she worked so hard to try and help offer such an apology, and felt even more regretful of what she'd done. \"I.... Um....\" She felt a bit stymied and at a loss for words when the usually cheerful Sasaki offered her a more somber smile than she usually managed — but one that was filled with sincerity that Kyouko had felt had recently been lost between the two of them."
    "\"I'm sorry,\" she managed, sitting on the side of the bed that was waiting for her. \"Sasaki-san ... I ... did some very bad things ... even if I was forced.... Um.... Koizumi-kun,\" she tried to hide a wince; she should be more respectful than that to him, shouldn't she? \"K...Koizumi-san, I mean ... says that ... he wanted to help me because he said that ... you and I were friends. But ... I haven't been a very good friend for you, have I?\""
    "\"To be fair, I haven't been the best myself, especially recently,\" Sasaki returned, shaking her head. \"If we'd been better friends, as Kyon suggested ... well, perhaps this would never have needed to come to pass, right?\""
    "\"Y...you're being too nice,\" Kyouko finally decided, managing a weak smile. \"I made some real mistakes — but ... if you're willing to forgive me, I swear I want to try being a much better friend to you in the future! I.... What happened here was terrible, and....\" She bowed her head, comforted when Sasaki shifted to sit next to her on the bed, one arm going about her shoulders."
    "\"It was scary,\" Sasaki consoled her. \"Um ... both of us endured something unpleasant there. Still ... I believe that if you apologize again to Kyon and his allies, they will forgive you for whatever it was that.... Well — I believe that it was a bad choice to work against him. Kyouko-chan, if it isn't too much ... from where we stand, it seems that we've brought difficulties to Kyon and his allies and haven't done them much good."
    "\"Even if I can't fully understand everything that's going on, I believe we can be more help — and thus better friends — by trying to work with Kyon and his allies. Certainly ... it seems that the most {i}I{/i} can personally do here is try and convince you to become friends and allies.... I don't entirely know what information Suzumiya-san seems to think you would know ... but can we be friends and volunteer that without coercion?\""
    "\"I will try for you,\" Kyouko agreed without hesitation, reassured when Sasaki squeezed her slightly tighter in a reassuring hug that reminded Kyouko of when they had first met in person, and they'd truly become friends.... Before the distance came up between them, at any rate."
    "Koizumi stood by the doorway uncertainly, his gaze diverted to a window as he politely tried to pretend he couldn't hear. Kuyou's unreadable dark gaze was fixed on her. Sasaki looked up and caught the dark-haired girl's focus."
    "\"Kuyou?\" Sasaki wondered. \"Come to think of it ... how is it that you were already here? Are you allied with Kyon already?\""
    "\"Yes,\" Kuyou agreed, turning her gaze to Sasaki and offering one of her languorous blinks. She raised her right hand, lifting a small white paper bag. \"I am an ally.\""
    "\"Well, see? Isn't that a good start?\" Sasaki encouraged."
    "Thrusting the bag towards Kyouko, Kuyou explained, \"Cookies.\""
    "Slightly confused, the esper accepted the small parcel. \"Um ... thank you?\" she managed, unused to such gestures from Kuyou. Where did she get cookies, anyway?"
    "\"I baked them,\" she added, prompting Sasaki to giggle."
    "\"See?\" she prompted. \"Kuyou-chan, I think, is like me — we may not be able to offer as much to Kyon and his allies — but every little bit helps, right?\""
    "Kyouko could only smile weakly, unable to deny her amusement as even Koizumi chuckled about something. \"Well,\" he interjected, offering an amazingly warm smile to the girls, \"it's a bit late in the evening, but the cafeteria here is quite fine. If it's not too much of an interruption, would you care to accompany me for a while?\""
    "Sasaki turned to look at Kyouko questioningly, and she managed a nod, embarrassed at how much her face was reddening beneath Koizumi's gaze."
    "* * *"
    "Tsuruya was pleased that Kyon validated her father's expectations yet again. He'd performed admirably, enough so that her elder had even commented to her in passing that he was jealous of her. She didn't mind that at all, even when her father had made a more serious comment that he might need to borrow Kyon's skills in the future, given he was already evidently equal to Kasai in terms of both renown and strategy."
    "Still — she wanted to handle as much of the situation surrounding the ninkyou dantai organizations that she could, thus freeing him up to deal with ... other issues. After all, Haruhi had labeled her the director of ninkyou dantai operations within the brigade, hadn't she?"
    "So the debriefing was fairly smooth, all considered — Haruhi listened to Kyon's explanation of what had happened while he pulled Ryouko from his pocket and set the small figure on the table. She obligingly projected augmented reality images for the others, which Mori found fascinating, and prompted Kasai to rub his eyes...."
    "Well, Kasai had seen enough to realize that something serious was going on, and if he was sworn to secrecy on Haruhi and Yuki's joint display of affection anyway...."
    "After a moment to adjust, the bodyguard took it in stride, recounting an explanation of what had happened with Koizumi while they were returning. Kyon found Fujiwara's involvement {i}fascinating{/i}, and offered an amazing story of his own about running into another instance of the time traveler at almost the same time."
    "He hedged around some issue, explaining that Fujiwara had helped Kyon avoid something catastrophic that Kyouko hadn't realized she almost caused.... Tsuruya could tell he was leaving something unexplained about that, and she expected Haruhi did, too. When pressed, he finally asked Kanae for a cup of coffee, which she obligingly ran away to make for him."
    "Then he relented and explained what he'd been keeping back, while Ryouko reported some incomprehensible string of numbers to Yuki, who merely nodded in confirmation."
    "She and Haruhi could both understand why Kyon wouldn't want Kanae in the room to hear that even though she helped, it was coming so close to something so catastrophic. \"Michikyuu Kanae's training will be revised to take this issue into account,\" Yuki offered into the awkward silence that followed. \"The miscalculation was not entirely on her own. Some blame for this must also—\""
    "\"No,\" Kyon started to override her, before Haruhi moved behind the slight girl and clapped one hand on her shoulder."
    "\"Yuki-chan, you're too amazing to sell yourself so short,\" Haruhi countered. \"At the end of the day, there was a problem, so we sent Kyon to fix it. And he did!\""
    "The door clicked as Kanae reopened it, peering in cautiously, then beaming Kyon a bright smile as she set the cup of coffee down before him. \"Perfect,\" he thanked her, giving her a warm smile. \"Kanae-chan, don't let me forget to do something nice to thank you for all of your help today, alright?\""
    "\"Ah.... Okay, Sempai!\" she cheered, happily drifting to sit near Tsuruya once more."
    "After that, Kasai offered to join with Tsuruya's father to update him on everything, while Mori would remain behind and keep an eye on the assembled members at the hospital."
    "The woman rose from the table, nodding at the youths before her. \"I'll give this room over to you then, Tsuruya-san, Suzumiya-san.\" She offered a polite bow before sweeping out of the room, met at the doorway by Arakawa as the pair went off to confer over other details."
    "Tsuruya leaned back in the conference room's comfortable chair, seeing that for the moment, it was ... well, all of the girls with a claim on Kyon in one room. Probably according to Haruhi's design, though."
    "\"So!\" Tsuruya chirped, grinning at Haruhi, as Kyon finished the last of his coffee and rubbed at his eyes. \"What now?\""
    "Haruhi settled back into her own chair. \"Kyon,\" she started slowly, sounding almost timid, \"what are your plans to deal with Sasaki?\""
    "The boy heaved a heavy sigh at that, closing his eyes and crossing his arms over his chest. \"It's not like I didn't think about this ... but even with a few days to think about it, I couldn't come up with a great answer,\" he replied. \"I'd like to try and keep an eye on her, make sure she's safe, and some day when things calm down, maybe try and explain things to her."
    "\"For now ... I think we have to be careful, and that if we try and explain everything, it's just going to be too much for her. Probably ... we can explain the ninkyou dantai aspects of it, at least, as they're not going to go against any of her sensibilities,\" he suggested."
    "\"You don't think she's going to ask why she's so important in all of that, though?\" Haruhi wondered skeptically."
    "\"W...we should come up with a good reason, then,\" Mikuru suggested hesitantly. \"Um ... but ... it would be nice if we could find some way to make sure we didn't lie, or make her feel we were dishonest to her later.\""
    "Kyon nodded his agreement, glancing across Tsuruya and Kanae hopefully."
    "\"We~ll,\" Tsuruya said hesitantly, her smile fading. \"We could say it's because of Kyon-kun, and that Sasaki is valuable because she's leverage to use on him ... but I don't like saying that this is Kyon's fault.\""
    "\"We could probably tell her we don't know why they're after her,\" Kyon tried. \"Would that work?\""
    "\"Except that it's not really true,\" Mikuru sighed, shaking her head."
    "\"It's true enough to say that they intend to use her against us,\" Haruhi grumbled."
    "\"Then ... let's just leave it at that for the time being,\" Kyon said, rubbing his temples. \"It's not much, but we can tell her that we don't really understand them. Being completely honest, I don't think that Kyouko's faction is cohesive or in charge ... or, really, that's she's still aligned with them anymore. It's simple enough to say things got out of hand and now we're not really sure who all the players involved are.\""
    "\"That's also true, though,\" Tsuruya encouraged, giving him a bright smile, even as she reached across the table to pat Haruhi's shoulder. \"Okies ... Haru-nyan? Is that okay?\""
    "\"I don't know ... I guess it'll work,\" Haruhi grumped."
    "The heiress eyed the girl she considered to be her best friend critically, then steeled herself. \"Hmm ... Haru-nyan ... I have to try and encourage and support you, but this time I can't be subtle about it, so I'll say it here where he can agree with me:"
    "\"Kyon-kun isn't going to abandon you — or the rest of us — for Sasaki.\""
    "The boy blinked in surprise at that remark, while Haruhi flinched, cowering as though Tsuruya had raised a chair over her head menacingly."
    "\"Wait— Is that—\" Kyon started before shaking his head, rising from his seat to move to Haruhi's side. \"Really?\" he wondered, his hand dropping to the shoulder opposite Tsuruya's. \"That's what you're worried about? Haruhi ... you have to know that'd.... Sasaki's a friend, she wouldn't even— Even if she {i}would{/i}—\""
    "He cut himself off and shook his head again, glancing to Kanae and Mikuru, who were taken aback by the exchange. \"Come on, Haruhi ... you're working so hard for everyone to get along together ... do you really think I'd just let all of your effort go to waste for nothing? I'm part of that too, aren't I?\""
    "\"Y...yeah,\" Haruhi allowed, encouraged a little, then sighing, her head hanging. \"Ugh ... I hate this! What kind of leader keeps getting tripped up like this? I'm supposed to be leading by example!\""
    "\"Don't be like that,\" Kyon countered, before Tsuruya could speak. \"You're doing a great job, but isn't the point of this that we rely on one-another?\""
    "Tsuruya couldn't help but laugh, adding, \"Didn't I tell you that same thing in this room once, Haru-nyan?\""
    "The brigade chief blushed, and Tsuruya switched her stance — and grip — hauling her upright with a surprised yelp. Haruhi had just enough time to look cross at the handling before Tsuruya tackled her into Kyon. As she expected, he managed to stay upright after catching them both — she was pleasantly surprised when Haruhi's muffled protests found themselves buried beneath the addition of Yuki, Kanae, and Mikuru, in turn."
    "For his part, completely wrapped in the arms of the girls who planned on sharing him, Kyon managed to give Haruhi an encouraging grin."
    "* * *"
    "Though she felt a lot was unsaid, given the confusion of the day, Sasaki had to admit that finding out that Kyouko was not solely responsible for her involvement in those matters that upset Kyon and his friends so much reassured her a bit. She didn't really like the idea of discarding or ignoring her friend, but somehow, Kyon and his allies had made it possible for them to speak again."
    "She didn't really feel hungry, and she doubted Kyouko did, either, but they both politely ate at their soup along with Koizumi once he led them to the cafeteria."
    "After that, Sasaki was surprised at how relaxing the small talk was, and Kuyou's cookies were delicious when Kyouko shared them around. For the first time, Sasaki thought her usually quiet friend looked somewhat proud of something."
    "She had actually lost track of the time when, back in Kyouko's room later, the familiar figures of Mikuru and Kanae poked their heads into the doorway, the older girl offering, \"Um ... Kyon-kun's meeting is over, if you wanted a chance to speak with him. Ah ... I can walk you there, Sasaki-san.\""
    "\"Should I go as well?\" Koizumi wondered."
    "\"Ah, Suzumiya-san didn't say,\" Mikuru said apologetically."
    "\"I'll stay and look after Tachibana-san, then,\" he decided."
    "\"Y...you can call me Kyouko,\" the twin-tailed girl managed, her face reddening slightly as she was unable to meet his eyes. Sasaki bit back the pang she felt at that ... well, she supposed Kyouko had the freedom to develop romantic feelings for her rescuer...."
    "\"Ah — well, I would like to speak with Kyon,\" Sasaki agreed. She nodded at the twin-tailed girl as she rose from her seat, offering a slight wave as she stepped into the hall. The smaller girl gave her a cautious smile, while Mikuru's was still more hesitant. \"Thank you, Asahina-san.\""
    "\"I...it's no trouble, really, Sasaki-san,\" the older girl returned. She led the way a short distance down the hall before pausing hesitantly. \"Oh.... Kanae-chan, um ... Yuki-chan had something she wanted to talk to you about, actually — about how you helped Kyon-kun out today?\""
    "\"She did?\" the smaller girl asked, baffled. \"Well ... okay! Her room's right down the hall?\""
    "Mikuru beamed her a smile and directed her into one of the side rooms, then led Sasaki further down the hall, heaving a nervously relieved sigh."
    "\"Is something the matter?\" Sasaki wondered."
    "The older girl started slightly, glancing back at Sasaki as she pressed a button to summon an elevator. \"Um, well.... It's a bit of a strange question, I think, but ... do you remember one of the last times we met you mentioned meeting my, um, sister?\" she asked nervously."
    "Sasaki nodded. \"Of course ... she seemed to get along with Kyon, too—\" She paused, realization setting in as the elevator door opened. Biting her tongue until the pair stepped inside and the door closed, she asked, \"Your sister's a ... time traveler, then? Like Kyon?\""
    "\"Um!\" Mikuru practically yelped, eyes wide as one hand flew to her chest. \"Y...you know about that?!\""
    "Trying what she hoped was a reassuring smile, the younger girl said, \"Well ... I've figured out that it's a code-word for.... That is to say, I'm somewhat aware of it, but I don't really understand it, myself. I wouldn't really know anything about, um ... her rank, or anything like that.\""
    "Mikuru looked slightly perplexed. \"You.... Um ... could I ask ... what it's a code-word for?\""
    "\"W...well....\" Sasaki hesitated, glancing about, though she didn't know what she was really looking for before she lowered her voice and clarified, \"You know ... organized criminals?\""
    "\"A...ah,\" Mikuru sighed. \"Oh.\""
    "\"I want to be, er, earnest with all of you, and not hold anything back,\" Sasaki offered, when Mikuru seemed troubled and silent for a long minute."
    "\"Please don't be alarmed,\" the older girl said, shaking her head. \"I need a moment to think while we have some privacy.\""
    "Before Sasaki could ask what she was talking about, Mikuru reached to the elevator's control panel, and just before Sasaki expected the display would roll over to their floor, pressed the 'stop' button."
    "She started, a little unnerved at the older girl's actions.... But, surely Mikuru didn't want to hurt her?"
    "\"It's ... complicated ... but if I understand everything then, er, my sister has sworn Kyon-kun to secrecy about her actions to me,\" Mikuru explained slowly. \"I am allowed to know, but for certain reasons, {i}he{/i} isn't allowed to tell me.... Um, my goal is to join with my sister, so that we can be allies, but as a test to me, I have to discover what she's up to without Kyon-kun being the one to tell me.\""
    "Sasaki blinked twice, considering what she'd said. \"Your organization has very ... thorough entrance tests,\" she offered. \"If what you say is true, am I allowed to tell Kyon that I've revealed information to you? To be honest, I don't at all like the idea of holding things back from him — especially now.\""
    "Mikuru looked puzzled for a moment, mumbling to herself. \"Well,\" she muttered, \"{i}I{/i} would be mad at myself if I made Kyon-kun troubled so badly ... so ... absolutely, it's fine for him to know.\""
    "\"And it won't be an issue if he then tells your sister?\" Sasaki couldn't help but wonder."
    "\"That's ... surprisingly irrelevant in this scenario,\" Mikuru offered, shaking her head with a wince. \"I'm really sorry, but I honestly don't think it would be a good idea to try and explain that part to you right now.\""
    "Laughing uneasily, Sasaki allowed, \"Actually, I think I'm completely fine with accepting your word for that.\""
    "Sighing in relief again, Mikuru asked, \"Then ... could you say what my older sister was doing with Kyon-kun?\""
    "\"Well, at the time, Kyon was joking about—\" She broke off, blinking with sudden realization. \"Um ... I think ... he was on his way to a fight, in retrospect. Your sister seemed to have some trouble with Fujiwara, but at the same time, so did Kyon.... Still, I understand that Kyon and Fujiwara made up their differences, at least a small bit.\" She hoped they did, at any rate."
    "Having all of her friends on the same side would be wonderful — Fujiwara hadn't been around, but evidently Kuyou had offered something to Kyon's cause, as well, though Sasaki had no idea what it was."
    "\"Was there anything else?\" Mikuru pressed anxiously."
    "Sasaki struggled to remember, but it had actually been so long ago — and her attention was really on Kyon, more than the woman.... Though, she did distinctly remember her hanging on to Kyon in a way she thought was on the verge of improper, considering her probable age. She had let go when.... \"Um ... your sister seemed to think that the idea of Kuyou-chan having a crush on Kyon was very cute,\" she offered. \"Though ... now I wonder if instead of a crush, Kuyou-chan was pursuing some sort of alliance?\""
    "Mikuru shook her head abruptly, reaching towards the panel and releasing the stop, causing the elevator to lurch the last distance up to the final stop. \"Ah, thank you for helping me, then, Sasaki-san,\" she offered, giving a warm smile, though she seemed distracted. The elevator doors opened, and she squeaked in surprise to see Kyon standing in the entryway, one of Tsuruya's men just behind him."
    "\"Everything alright?\" he asked."
    "\"Ah, y...yes,\" Mikuru allowed with a blush. \"I....\" She hesitated, then seemed to steel herself, explaining, \"W...well, I asked Sasaki-san about my sister.\""
    "Kyon's expression shifted to surprise before he looked away uncomfortably. \"I.... Well, I hope she was able to help you, then.\""
    "Sasaki released a tiny sigh of relief, embarrassed to realize she was uncertain if she would need to reveal that to Kyon herself. Even better, Kyon's behavior seemed to agree exactly with what Mikuru had said."
    "\"Ah,\" Mikuru said, shaking her head, \"now that you're here, Kyon-kun, I'll leave Sasaki-san to you — I'll be with Kanae-chan and Yuki-chan.\""
    "Kyon nodded at her as Sasaki stepped out of the elevator and Mikuru waved."
    "\"Have you had something to eat?\" Kyon wondered, offering Sasaki a warm smile. \"The cafeteria here isn't too bad.\""
    "\"It isn't,\" she agreed. \"Ah, but we ate earlier, a little....\""
    "\"Alright,\" he allowed, motioning her to follow him down the mostly empty hallway. A short distance around a corner, past a pair of men she realized must be guards, he gestured her through a double-doorway, one side of which was opened. She stopped just inside, looking around and seeing only Tsuruya and Haruhi."
    "When he stepped in and closed the door behind him, Sasaki asked, \"Ah ... will anyone else be coming to this meeting?\""
    "\"Just us,\" Tsuruya assured her, shaking her head and smiling. \"Have a seat!\""
    "Somewhat uncertainly, Sasaki picked the seat opposite Haruhi, hoping that Kyon would sit at her left. Instead, he took the seat to her right — at the head of the table, so adjacent to Haruhi as well. She supposed, really, she shouldn't complain — after all, he'd picked a chair that left him apart from his fiancee."
    "\"Okay,\" Haruhi declared, her gaze flicking to Kyon before returning to Sasaki. \"So, to begin ... do you know what the people Kyon saved you from wanted with you?\""
    "\"To be honest, my value to them is unclear to me,\" she admitted. \"My best guess would be as a hostage to use against Kyon, except ... these people had an interest in me for some time, and only recently had they become so ... aggressive. Were they, perhaps, losing a conflict with you?\""
    "\"They sure weren't going to win,\" Haruhi muttered."
    "\"Mm, I think I see,\" Tsuruya mused, nodding. \"So ... Kyon-kun made the Organization stronger, and also kept Kyouko's former allies ... what do we call them, the 'Family'?\""
    "\"That's what Kasai said they were calling themselves,\" Kyon agreed."
    "\"Alrighty — the Family is envious of the strength of the reformed Organization and feels they need to act sooner ... in a way, unintentionally, this may be our fault.\""
    "Kyon looked uncomfortable at that as Haruhi looked at him in astonishment. \"That ... could be true,\" he admitted unhappily."
    "\"That still doesn't explain my importance,\" Sasaki noted. \"Or how I am of value. Unless ... is it that you're so important, anyone from your past who was close to you could be in such danger?\""
    "\"Yeah, that's it,\" Haruhi said in annoyance. \"Exactly right.\""
    "Kyon shot her a warning look and shook his head briefly."
    "\"That seems terribly unlikely, though,\" Sasaki said, shaking her head. \"I don't believe Kyon is the kind of person to intentionally bring such a difficulty to someone else ... therefore I must believe that this is an accident, or more likely, not really his fault.\""
    "\"Well, that's spoken like someone who knows Kyon,\" Tsuruya remarked. \"To be honest, we know probably more of the Family's motives than you do ... but at the same time, it's best to acknowledge that there are certain things you are better off not knowing yet.\""
    "\"I can understand that,\" Sasaki agreed. \"For the time being, I'm an outsider and a liability to your group, is that right?\""
    "\"Liability?\" Kyon asked, wincing."
    "\"That much is absolutely true,\" Haruhi chimed in, drawing a warning look from Kyon before she crossed her arms over her chest. \"It's true, unfortunately, and she said it herself.\""
    "\"Well, I'd like to become less of a liability, and if that means becoming less of an outsider, too, I'm fine with that,\" Sasaki offered. The other three turned to look at her, Tsuruya's expression the most guarded, and Kyon's most hopeful. \"And, especially for my own safety, I think I would like to be involved in ensuring I don't come to harm. Really ... it seems only sensible.\""
    "\"Alrighty,\" Tsuruya allowed, nodding. \"That does makes sense, really. To start, then ... mmm ... well, we're going to assign some of our people to watch over you and make sure you're safe. If you're cooperating with us, then I can introduce you to them, and you'll know who to look for if you thinks there's trouble!\""
    "\"That sounds fine for now,\" Sasaki agreed, hoping to speak with Kyon about possibly becoming more involved later. Maybe if she were part of his organization, he wouldn't be so reluctant to speak to her? She didn't really {i}want{/i} to become a criminal ... but she couldn't really believe that even if Kyon broke laws, he was a bad person."
    "Certainly, she felt she could see a justification for every law he'd broken rescuing her. So if she could become a subordinate to him, she could probably avoid breaking any laws he wouldn't, which should be enough.... Well, she'd need to hope he needed her mathematical or analysis skills; she had no real desire to fight. He seemed more than adequate at that for the pair of them anyway."
    "She shook her head, realizing she was trailing off into a daydream of the pair of them as one of the most cliche crime-fighting teams ever, with her providing the brains, and him the brawn. Such a foolish idea...."
    "Really, they'd be criminals, not crime-fighters."
    "\"Sorry,\" she apologized. \"Ah, today has been unexpectedly exciting.\""
    "\"Mega exciting,\" Tsuruya agreed with a nod. \"Hmm, now, though.... Sos, for tonight, you can stay here with Kyouko, if you like, or you can go home, and we'll keep a detail to watch over you.\""
    "\"I'm worried about my mother in all of this ... I'd like to go check on her,\" Sasaki admitted. \"She'll probably worry about me, too, if I stay overnight in a hospital!\""
    "\"We'll have Arakawa drive you home, then,\" Haruhi decided, just as Kyon seemed about to speak."
    "He turned to look at her and pursed his lips, then shook his head and turned back to Sasaki. \"Haruhi and I will walk you to the car, if you like, Sasaki,\" he offered."
    "Sasaki caught the way Haruhi flinched at that, and wondered why Haruhi seemed to dislike her so.... As much as she wanted to accept Kyon's offer, she didn't want to cause strife between his allies. So.... \"Actually, I imagine you must be very busy,\" she deferred, shaking her head. \"Ah, but if Suzumiya-san is arranging for transportation, then I wouldn't mind her company; really, I think we should chat!\""
    "* * *"
    "She was so tired after everything she realized her eyes were drifting closed. Well ... a side effect of the adrenaline from earlier wearing off, she supposed."
    "That simply compounded the fact that she had no idea what to say to Koizumi once they were alone together. He distracted himself with coring and peeling an apple, but she still had no appetite, so once that was done he simply set it aside."
    "She supposed she could ask him to go away, or just let herself drift away, but she couldn't deny how comforting his presence really was, especially after...."
    "How badly had she screwed up, if one of her closest allies had turned on her with lethal intent? She and Fujiwara had probably never truly been {i}friends{/i}, but as allies.... Sasaki may have forgiven her, and to Kyouko that was more important. But turning an ally into a hateful enemy ... that didn't make her feel good at all."
    "If it weren't for Koizumi, she thought she might start shaking again."
    "\"Ah, Kyouko,\" Koizumi spoke, jarring her out of her thoughts, making her blink her eyes open. \"Are you alright?\""
    "\"I....\" She trailed of, frowning, then sat up straighter, fussing with her pillows for a moment. \"Um ... Koizumi-san ... i...it may not be much ... but if you can write ... I...I'll tell you everything I know!\""
    "He gave her a surprisingly confident, reassuring smile. \"I think right now you shouldn't worry yourself about that as much,\" he assured her. \"Information is power, and Kyon-kun's ability with that power is astounding ... but all the same, I doubt he'd be pleased with the idea of you straining yourself. At the same time, speaking at least for myself ... I find that it's amazing that you have the strength to keep your head high after all you've endured.\""
    "Her head bowed at those words, her face heating up so much she thought a nurse would decide she was feverish. \"Ah...\" was all she could manage to say."
    "\"But then ... if you'd like to speak, I'll gladly listen ... simply feel no need to exert yourself too far at this point.\""
    "She blinked in surprise, some of her exhaustion perversely vanishing with the assurance that she could rest. \"Um....\" What could she speak of, then? Unbidden, the memories of her awakening to her power returned to her and she swallowed, shyly managing, \"L...let me tell you something else, then.... Um ... one day ... about four years ago....\""
    "* * *"
    "Shifting in her seat uncomfortably, Haruhi resisted the urge to outright {i}glare{/i} at Sasaki to try and cover her apprehension. She saw Kyon wince — as he should, putting that idea into Sasaki's head in the first place! Really, what was he thinking, trying to get her to spend time in Sasaki's company with him ... as a comforting presence...."
    "...somehow, he'd actually tried for a reasonable compromise, she realized belatedly, feeling her mouth twist in a grimace."
    "Kyon shook his head abruptly, and opened his mouth to dismiss the suggestion— But Haruhi couldn't leave it at that. Sasaki had already figured out that something was up — okay. Fine, she decided. As long as she was careful, it should be safe."
    "\"Why don't we?\" Haruhi agreed, causing Kyon's teeth to click together when he closed his mouth in surprise, and even Tsuruya to look alarmed. Haruhi set her hands on the table before her and pushed herself away a short distance before rising to her feet. \"If you're ready, Sasaki?\""
    "Sasaki nodded, rising from her seat and offering Kyon and Tsuruya matching respectful bows before she said, \"Thank you very much for your help and protection; I hope that in the future, I can become more of an asset than a hindrance to you.\""
    "Haruhi bit back the feelings that she felt welling up at the thought of {i}Sasaki{/i} of all people actually joining the SOS Brigade. As far as she was concerned, the biggest help Sasaki could offer was staying out of the way! But ... even if she thought that, Kyon was worried about her, because she was his friend."
    "If there was one thing she'd learned from Kyon, it was the true importance and value of friendship. Friends weren't toys you played with and abandoned as you saw fit ... and he wouldn't set Sasaki aside the same way, any more than he'd allow her to go too far with Mikuru. In a sudden burst of insight, she realized his position, trying to be the best friend possible to Sasaki, while also trying to still be there for Haruhi."
    "She wasn't really helping him, was she? Hadn't Tsuruya said Kyon had enough enemies without her causing him problems, true?"
    "\"Sasaki, we are united in wanting to cause Kyon less trouble,\" Haruhi offered, grabbing on to the only common ground she could see with the other girl."
    "Sasaki blinked at that, managing a small, nervously surprised smile. \"That's good, then,\" she agreed. \"Um ... so! Kyon, take care, and I hope we can speak again soon — hopefully in less ... grim circumstances?\""
    "\"Absolutely,\" he agreed. \"Though—\""
    "\"No, you're busy,\" Haruhi countered, before he could go further. \"Take care of the planning; I'll met you and Tsu-chan in Yuki-chan's room once I finish escorting Sasaki to the car.\""
    "Sasaki nodded slightly at that, then followed Haruhi at her gesture, walking obediently into the hallway. \"I don't ... mean to cause trouble, but Suzumiya- san, I can't help but notice that it seems ... you don't very much like me?\" she began."
    "Rather than deny it, Haruhi sighed, pressing the elevator call button at the upper lobby before turning to face her. \"Even if it was unintentional, you've done some real damage to Kyon, you know,\" she warned."
    "Sasaki flinched at that, then bowed her head, her smile completely gone. \"It troubles me greatly to think I could have done something like that without meaning to,\" she said slowly. \"I ... never saw that he was truly hurt by me until it was too late—\" She cut herself off with a sharp sigh as the elevator arrived, and both stepped in, Haruhi hitting the button for the lower floor."
    "After a quiet moment of the elevator starting up, Sasaki offered, \"I don't know if I can ever make up that damage that I seem to have somehow caused.... But I feel that because Kyon {i}is{/i} my friend that I have to make this up to him — whatever he's taught you, Kyon showed me that I was wrong, and that friendship is something worth believing in."
    "\"It may not be much, and I may only have truly seen it today ... but Kyon has been trying to show me much longer than that, I think. Suzumiya-san ... you and I don't have the same differences that Fujiwara and Kyon do — but even they can work together. Even if you resent what I have done to Kyon — as I myself must, being told how carelessly cruel I was — can you at least give me the chance to try and make that up to him?"
    "\"I can't deny that in some ways, this request is selfish, but at the same time, this is also a concern for my safety ... even if I can't be privy to all the details of that, yet. To me, you represent the greatest obstacle between me and that. From a rational perspective, my time would probably be better spent trying to work around you, or avoiding you and working with Kyon."
    "\"But I won't do that ... because I don't believe that Kyon would be happy if we didn't try to work together,\" Sasaki completed, as the elevator reached the ground floor and the doors opened."
    "Haruhi sighed, hitting the button to close the doors and then stopping the elevator. For whatever reason, Sasaki seemed slightly amused, but not very surprised. Worse, though she could try and claim otherwise, she could understand Sasaki's argument completely."
    "That still didn't mean everything sat well with her."
    "\"So ... did you know that Kyon had a crush on you in middle school?\" Haruhi asked, compelled by morbid curiosity."
    "Sasaki's calm mask crumpled into a wince as she looked away. \"I ... suspected,\" she allowed. \"Not until it was too late, though....\""
    "\"Hmm,\" Haruhi allowed, not fully convinced. \"And ... you're not going to try and cause problems with the fact that {i}you've{/i} got a crush on him now?\""
    "Sasaki flinched at that question, but managed to bring her gaze solidly up to meet Haruhi's. \"As long as you resist the impulse to damage his relationship with Tsuruya-san, then so will I, Suzumiya-san,\" she returned, her voice quavering only the slightest bit. \"If anything ... isn't that even more reason for us to be friends?\""
    "Haruhi worked her jaw for a moment before hitting the 'stop' button again, shaking her head. How could she explain that to Sasaki? In time, perhaps ... but now? Now, the girl would most likely just leap at the chance to try and get a piece of Kyon for herself ... and she'd probably try and use pragmatic arguments and guilt-trips on Kyon — even if she didn't mean to. He was such a sucker for that!"
    "No ... if Sasaki found out, she'd just want in. At least, right at the moment."
    "\"It's ... complicated,\" she said, as the doors opened and they stepped out. But, for all of her arguments and reasoning.... Being able to {i}talk{/i} to Sasaki was not nearly as scary as she had thought it was. Oh, there were whole worlds of information she couldn't speak of around her ... but hearing her talk about the same things Kyon had...."
    "\"I think ... that Kyon would be happier if we could be friends,\" she agreed. \"And me being less friendly to you wouldn't help you in that situation,\" she realized aloud, glumly. Sighing, she mumbled, \"I suppose if you're with us, you can't be caught and used against Kyon....\""
    "Offering an apologetic smile, Sasaki bowed slightly, sticking a hand out slightly as she said, \"Please take good care of me.\""
    "Haruhi found herself reflexively accepting the handshake before rolling her eyes. Sasaki was behaving as though she had accepted a job offer, and Haruhi were her new immediate superior. Shaking the other girl's hand firmly, Haruhi allowed, \"Your safety is all of our concern, you know. Alright! Let's do this, then — you can't contact any of us but Kyon if there's an emergency, right?\""
    "\"That's true,\" Sasaki allowed, nodding."
    "\"Take my phone number, and I'll give you Tsu-chan's too,\" Haruhi decided. \"Kyon's really important, and may be on a mission ... so if it's super- important, try calling one of us first.\""
    "\"And ... if it's not an emergency?\" Sasaki wondered."
    "Haruhi winced, but set her shoulders. \"I just gave you my number,\" she said, shrugging. \"Tsu-chan, maybe you should only call in emergencies, but if ... we're going to become friends, it'd be stupid for me to say you could only talk to me if it were important.\""
    "Sasaki heaved a visible sigh of relief, and Haruhi was irritated at the relief she felt herself to realize that Sasaki's confidence wasn't as boundless as it sometimes seemed ... she had moments of weakness, too, just like Haruhi."
    "\"Well, thank you very much for that, Suzumiya-san,\" Sasaki allowed, as they walked through the automatic doors to where Arakawa and Kuyou were waiting. Haruhi eyed the newly adopted member of the brigade, realizing that Kyon had probably asked her to watch over Sasaki...."
    "That did make a certain degree of sense, even though Haruhi wished she had more of a chance to speak with her."
    "\"Take care, Sasaki,\" Haruhi made herself say, nodding at the other girl. \"And you too, Suou. Um ... Sasaki, if you want, you can give me a call tomorrow night, and maybe we can chat a bit....\""
    "Sasaki's weak smile gained a tiny bit of strength. \"That might be nice, Suzumiya-san. You take care, as well!\""
    "Haruhi waved as the girls climbed into the car and Arakawa drove off. Once they were out of sight, she let an explosive sigh escape; as much of a hypocrite as she felt it made her, she needed to be with Kyon. She turned on her heel and marched swiftly back into the hospital."
    "* * *"
    "Yuki sat in her bed, watching Mikuru fuss over her injury. It was healing optimally for a human of her size and evident health, and the taller girl couldn't actually do much to accelerate that process — especially with Sasaki's influence restraining normal data alteration."
    "At the same time, she recognized that the other girl was distressed on behalf of Yuki, and was soothing herself to a degree by fussing pointlessly. Even though it accomplished nothing to accelerate the healing process, Yuki also recognized that it was an important symbol. For reasons she was having difficulty quantifying, she felt inexplicably better even though she knew she shouldn't."
    "Kanae sat in a seat to one side of the room, the smaller girl's head nodding forward as she tried to stay awake. A moment after that, the door opened, admitting Tsuruya and Kyon. The green-haired girl's eyes lit on the slider and she instantly glided across the room, sweeping her up in a hug."
    "\"It's getting late,\" she scolded mildly, smiling. \"Let's get you home before your parents worry, hmm?\""
    "\"A...ah, okay,\" Kanae allowed, pouting slightly. She brightened suddenly, shooting a significant glance at Yuki. Yuki gave a tiny nod in return, which Kyon caught, looking puzzled, but the slider did, too. Kanae blushed as she went away, undoubtedly to use the opportunity to explain that she would be sending Tsuruya to share some time in the bed of the mutual target of their affection."
    "For Yuki's part, she would explain it to Mikuru later."
    "She raised her hand waving at the boy, who managed a nervous, bleak smile. Sighing, he explained, \"Haruhi and Sasaki are having a conversation.\""
    "\"I...is that okay?\" Mikuru wondered."
    "\"I hope so,\" he said, before moving closer to Yuki's side, giving her a more genuine smile and reaching out to rest the fingers of one hand on her shoulder. \"How are you feeling, Yuki?\""
    "\"Better,\" she answered."
    "\"I'm glad to hear that,\" he said, smiling."
    "Mikuru gave a small sigh of relief. \"A...at least we're through with all of the things we needed to worry about ... right?\""
    "\"I have discovered something,\" Yuki allowed, turning to Kyon. \"I have placed subordinate data within your PDA.\""
    "He nodded. \"I understand that,\" he agreed, glancing at Ryouko, then pulling her from his pocket to place her on the bedside stand. \"Is it alright?\""
    "\"It is fine,\" she confirmed. \"However, I have subconsciously designed subroutines to periodically update your PDA. Due to your time loops, this information then updates itself to me in the past, and is received by other subconscious routines, which reveal information to my conscious self as it becomes relevant.\""
    "Kyon stared at her for a moment, surprised, then nodded slowly. \"So ... you've got a sort of cross-temporal synchronization again?\" he wondered."
    "\"A primitive implementation,\" she agreed. \"The primary benefit is that subconscious processes can review data in the background, returning the benefit of all that process time at the same moment that new data comes to light.\""
    "\"Sort of ... sending questions to the past and giving yourself more time to think about it without even knowing?\" Mikuru wondered."
    "\"Yes.\""
    "\"That seems ... good?\" Kyon offered, though he seemed unconvinced. \"As long as you're not doing that thing where you feel you're limiting your options....\""
    "\"That has not yet been an issue. However, when processed data is returned to me, I frequently find notices from future iterations of myself to alert me to critical data segments.\""
    "\"Future you is talking to you?\""
    "\"Sending notes,\" Mikuru corrected him, glancing between the two."
    "\"Yes,\" Yuki agreed. \"However, these notes are unusually terse.\""
    "\"Personally,\" Kyon sighed, \"I think future me is a {i}jerk{/i}.\""
    "\"Yes,\" Yuki agreed, understanding. \"Future me is likewise insensitive to me.\""
    "Mikuru huffed a very short sigh at that, mumbling, \"Don't I understand....\""
    "Kyon started, looking at her sharply. \"W...what was that?\" he asked."
    "\"Ah! No, um, that is ... I don't like to think of different versions of you that I wouldn't like,\" Mikuru offered, shaking her head. \"That seems strange to me.... From where I am, Kyon-kun is Kyon-kun, and Yuki-chan is Yuki-chan. I think if there were others of me ... I might think of them differently, but maybe it wouldn't be such a good thing to speak resentfully of them. Even if they are ... um ... seemingly unkind or thoughtless ... they couldn't behave in such ways if w— you didn't have the ability to overcome it after all, right?\""
    "Kyon looked at Mikuru very thoughtfully, giving a very slow nod in response. \"I think I've thought that myself, but ... from the perspective of my future self, it's hard to be sympathetic because of the ... uh ... present....\" He trailed off and shook his head. \"This is a headache right now, I don't want to think about it.\""
    "The door clicked open quietly, and they all turned to look at Haruhi stepped in. Yuki noticed the tension in her demeanor and stance, immediately remarking, \"Suzumiya Haruhi needs a hug.\""
    "She looked up at that, surprised, as the door shut behind her. \"Eh?\" she managed."
    "Kyon shrugged, deciding, \"That's something I can do,\" before he stepped forward and wrapped the girl in his arms, holding her tightly."
    "An unintelligible sound of released distress escaped the girl as Yuki saw the tension visibly fade from the parts she could see around Kyon. Mikuru giggled at that, giving Yuki another pat on the wrist before stepping around the bed and hugging the wavering Haruhi the second Kyon released her. \"Wuh?\" Haruhi managed in surprise, as Mikuru's arms wrapped around her from behind."
    "\"You grabbed me once like this,\" Mikuru reminded her. \"It was cold, and you were teasing poor Kyon-kun, though....\""
    "\"Em ... w...well, it's not teasing now,\" Haruhi mumbled, leaning back into Mikuru and not meeting Kyon's eyes. \"B...but even though I'm not cold....\""
    "Kyon chuckled and gave the girl another brief hug. \"Now,\" he mumbled, when she sighed in contentment against him, \"let's not forget Yuki-chan, hmm?\""
    "\"Right,\" Haruhi agreed, as she was released from the hugs. She moved to the bed and climbed onto it without hesitation, snuggling up to Yuki's side against her uninjured arm."
    "\"So,\" she said, one arm going across Yuki's stomach before she turned her face to muffle a yawn into the pillow. \"Mm, tell us what happened with you and Mikuru-chan — and Kuyou.\""
    "\"Sure,\" Kyon agreed. \"Asakura can help.\""
    "The smaller interface jumped excitedly. \"Okay!\" she cheered, projecting an augmented reality screen onto the far wall. \"Where to begin?\""
    "\"Well, let's just not embarrass Kuyou by going over the noodle incident,\" Kyon decided. \"But, Asahina-san is the one that actually helped Ryouko and Kuyou out the most, I think.\""
    "\"Really?\" Haruhi asked in surprise, before frowning. \"Well ... in that case.... Okay — I'll get everything from her, since you probably deserve a chance to get some sleep ... and making your mom angry won't help any of us.\""
    "\"You're sending me home?\""
    "\"You've worked hard enough for today ... you've put half a week into it,\" Haruhi clarified. \"Um ... but come here and give Yuki-chan and I a kiss goodbye, first!\""
    "Running a hand through his hair before offering a wry grin, Kyon shrugged and did as he was told — which Yuki found enjoyable, as always, though it was ... different with Haruhi holding her while Kyon kissed her, with Mikuru in the room blushing fiercely and pretending to be unaware — until it was her turn. Once he'd left, Mikuru sank woozily to a chair and heaved a sigh."
    "\"Any other surprises to spring?\" Haruhi mumbled sleepily."
    "\"Michikyuu Kanae and myself have been transporting ourselves into his bed at night after training, following her accidental discovery of this practice,\" Yuki offered."
    "\"Eh?\" Mikuru squeaked."
    "Haruhi froze. \"Y...you're getting to do that regularly?\" she managed, voice tingeing with jealousy."
    "\"Due to the day's experiences, there will be an extended error correction session tonight,\" Yuki added."
    "\"Aw, man.... I'll be stuck alone again....\""
    "\"Initially, I had intended to offer to substitute Asahina Mikuru for myself tonight,\" Yuki continued. \"But considering the current circumstances, I would like to offer that to you instead.\""
    "\"Eh!?\" Mikuru squeaked again, more loudly."
    "Haruhi wondered, \"Is that okay that I'm taking your chance, Mikuru-chan?\""
    "\"U...um, no, that's fine, Suzumiya-san,\" Mikuru said quickly."
    "\"Mmm, then ... say, does Kyon know that this is going to happen?\""
    "Yuki blinked in realization. \"...I forgot to mention it,\" she said softly."
    "Haruhi snickered. \"Perfect!\""
