label Re_6:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 061 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
    "Nonoko was having a hard time understanding why Kyon didn't take double-vacation-weekends more often. Getting to go visit all her favorite aunties and cousins for Kyon's birthday was so much fun that she only had to feel a little bad about not giving him a present! Well, technically, her mother had helped her give him something before the school year started, since that was when they pretended his birthday was."
    "She never really understood that part."
    "Whatever the reasons, everyone had a great time, and then she still got a full weekend to tell Miyoko about things! The festival was an awful lot of excitement; she was a bit jealous of Matsuri's outfit, but she wouldn't ask Mikuru for her own copy. Matsuri got to be a shrine maiden, but Nonoko was already a part time magical girl."
    "Still, after the excitement, once they all traveled back to Tsuruya's place -- except for Sasaki, who her brother explained would be coming later, they went back home."
    "Nonoko wasn't that hungry, but Kyon always seemed to have an appetite, those days, so when their mother called them down to dinner, she went with him."
    "Their mother looked at her strangely when she explained that she wasn't hungry due to time-travel. Kyon just shrugged and said that time travel made him hungry. That seemed to settle things, so she only had to eat her vegetables."
    "After that, as tired as she was, she went straight to bed. She woke up bright and early, wondering if she'd beat Kyon awake; it had been a while since she'd managed that! When she got out into the hall, she was surprised to see Haruhi coming up the stairs, looking mischievous and excited."
    "\"Haru-nee!\" she cheered, smiling. \"What brings you by?\""
    "\"After what Kyon's supposed to be learning today?\" Haruhi asked incredulously from the top of the stairway, just ahead of Nonoko's father. \"I wouldn't miss it for the world!\""
    "Yuuto looked surprised at that. \"Eh-- How do you know about that?\" he wondered, frowning. \"I mean ... I didn't even tell Kyon myself, yet!\""
    "Haruhi blinked, her face paling as she froze. \"Er, uh-- Well, you see ... you mentioned it to my father, didn't you?\" she asked, smiling nervously. \"I remembered from when he mentioned one of his subordinates and his own boss going to the hospital when Imouto was kidnapped! It was, uh, pretty big news!\""
    "Yuuto frowned and stroked his chin thoughtfully. \"Your father?\" he asked doubtfully before his eyes widened slightly. \"Ah-- I didn't realize that your father was my superior at work! I thought it must be a different Suzumiya!\""
    "\"Aha, heh, ah, yeah,\" Haruhi said anxiously. \"That's it! And, anyway, you told Kyon that if he brought his grades up, you'd teach him!\""
    "\"Well, I said 'top ten',\" Yuuto clarified. \"And it's too early for that. But.... Well, tomorrow's a special day, so why not?\""
    "\"Right!\" Haruhi exclaimed."
    "\"Is mom out?\" Nonoko wondered."
    "\"She's at the market; I suspect she'll be back very soon,\" Yuuto agreed, smiling at his daughter. \"On that note, Nono-chan, we're going to need you to distract your mother for a bit. Can you do that?\""
    "\"Sure!\" Nonoko agreed without hesitation. \"I'll ask her for help with my hair, and then tell her about how we time traveled to celebrate nii-san's birthday with the aunties!\""
    "Yuuto blinked at that, then shook his head, rapping his knuckles on Kyon's door before opening it a crack. \"Kyon-kun, are you awake?\" He doubted Akane would protest Kyon learning to drive, but she would undoubtedly protest Kyon learning to drive efficiently."
    "\"Yeah,\" he answered, pulling the door open the rest of the way, already fully dressed. So much for surprising him! \"Bit hard to miss all the discussion going on here. What's the surprise, anyway?\""
    "\"Well, Haruhi-chan here already figured it out, even though I don't particularly remember explaining it to her father ... heh, small world, isn't it?\" The bespectacled man shook his head slowly."
    "\"Yeah, something like that,\" Kyon agreed, looking off to one side. He shifted his shoulders, and Nonoko grinned as Ryouko peeked down at her and waved happily. \"I guess I shouldn't be surprised at Haruhi running down here so quickly.\""
    "\"Well, I've got some errands,\" Yuuto continued. \"Your mother wants something fetched from out of town to make a cake for tomorrow.\""
    "\"I wouldn't miss this for anything,\" Haruhi said resolutely, grinning."
    "The door downstairs opened, Nonoko's mother calling out, \"I'm back!\""
    "\"Yay!\" Nonoko cheered, already beelining down the stairs, prepared to distract her mother to help out. \"Mom! Did I tell you about my time travel adventure yet?\""
    "Akane sighed, smiling softly and shaking her head as Nonoko skidded to a halt at the bottom of the stairs, bouncing on her toes. \"No.... Not yet, Nono-chan. But first, let's put the groceries away, alright?\""
    "\"Oh, Akane-chan, dear,\" Yuuto called, climbing down the stairs. \"I'm taking Kyon and his study partner with me for that errand you asked me to take care of.\""
    "\"So early?\" Akane replied, mildly surprised. \"Oh, fine. Nono-chan's managed to muss her hair horribly, since yesterday morning. Why don't we take care of that before we make breakfast, alright, Nono-chan?\""
    "\"Sure!\" Nonoko agreed. This was going to be easy!"
    "***"
    "Yuuto really was having a tough time figuring out where he'd slipped the details of planning to teach Kyon to drive. Had he really told Suzumiya at work? He must have ... or else Haruhi was as sharp as Kyon's aunt Rena."
    "Well, that didn't particularly matter. He knew that Kyon getting into the top ten so late in the year was dreadfully unlikely, and that Kyon hardly got to celebrate his birthday because the circumstances behind it were ... awkward, to say the least. But Kyon was his son, and he deserved something for it."
    "A day early, to keep Akane from knowing exactly what was going on, but some early driver's training wouldn't hurt in the least. \"Alright!\" Yuuto called, but not too loudly, as the door was closed, and the three of them headed toward the car. \"This should be fairly simple, so, Kyon ... you'll be driving!\""
    "He pitched the keys underhand to his son, which Kyon managed to catch, looking the slightest bit surprised. \"Er, are-- Are you sure?\" he asked. \"I mean ... I don't even have a permit!\""
    "\"It's fine, it's fine,\" Yuuto insisted. \"We won't go on any major highways, there's a licensed driver giving you instruction, and ... Tsuruya-sama said he would pay for any fines if there was trouble, anyway.\" Well, he didn't want to make Kyon careless, but he was very sensitive to his ... employer/fiancee and her father professionally. He didn't expect that Kyon would intentionally cause any trouble."
    "Kyon and Haruhi both looked suitably impressed at the reminder. Yuuto did wonder what the girl knew of Kyon's part-time job, but decided it would be more sensible not to ask. She had helped Kyon study a lot, though. \"Say, Haruhi-chan,\" Yuuto prompted, opening a door so she could climb into the back seat of the car. \"You're friends with Tsuruya Haruka-san, is that right?\""
    "\"Oh, yeah!\" Haruhi agreed, hopping into the back seat and buckling herself in without hesitation. \"We're super close! Best friends -- we share everything!\""
    "Yuuto nodded at that thoughtfully as he and Kyon also got into the vehicle, buckling in. For reasons he couldn't quite figure out, Yuuto was reminded of Kyon's uncle and aunts.... No, no -- that was a stupid suspicion. Akane's brother couldn't really be like that, and there was no way Kyon would take after him, even if it were true ... right?"
    "\"A...anyway,\" he said with a cough, looking at Kyon. \"First, check the mirrors, seat position, and make sure you're comfortable with everything.\""
    "\"Right!\" Kyon agreed, rolling down the windows and nervously making the adjustments. Their heights weren't far off, though, so the changes were fairly minor. Once that was done, Yuuto talked him through starting the engine, setting the gear, and cautiously backing out of the driveway."
    "Starting with pulling out of the driveway backward was quite possibly one of the trickiest ways to go about it, but Yuuto had confidence in his son, and if he learned the harder parts of maneuvering first, he'd be that much better at the easier parts! At least ... that was the theory."
    "Haruhi was nearly bouncing in her seat in excitement as Kyon anxiously let the car slowly roll back out of the driveway, checking the mirrors constantly. Yuuto felt pride in his chest; that was his son, there, handling the car with the care it deserved."
    "It took longer for Kyon to get onto the street than Yuuto expected it would if he were a bit more confident about things, but being too confident would usually be a bad thing, at this point. Better to be more careful than not!"
    "\"Alright!\" Yuuto encouraged. \"Well done. Now, put the car in first, and we're going to pull forward to the intersection. You'll need to stop there, and then we'll make a right turn.\""
    "\"Okay,\" Kyon agreed, tongue sticking out in concentration. He was a natural, though; he scarcely glanced at the tachometer, instead going by ear. He stopped at the intersection, signaled properly, and then smoothly accelerated the car -- though still with the nervous caution of a new driver."
    "\"At this next intersection, go straight,\" Yuuto instructed. \"Don't go too fast; this is still a residential neighborhood, after all.\""
    "\"Right,\" Kyon agreed again, nodding, his eyes fixed firmly on the road. They were halfway down the street when Kyon's phone began producing some unfamiliar musical theme. Yuuto couldn't help but think that it sounded militaristic and forbidding, with unfamiliar English lyrics. Before he could admonish his son not to get distracted, the boy pulled it from his pocket and flipped it to the girl behind him without hesitation."
    "\"Kyon's phone!\" Haruhi chirped excitedly, answering it for him. \"What's up, Kasai-san?\""
    "\"Try not to get distracted,\" Yuuto warned sternly. \"This is your first time driving, and Haruhi-chan can take a message for you.\""
    "\"Right,\" Kyon agreed, rolling to a stop at the next intersection."
    "\"Sasaki's being kidnapped?\" Haruhi exclaimed. \"Oh-- Right-- Where are they now?\""
    "\"What?\" Yuuto yelped. Who was Sasaki? But ... a kidnapping? \"This sounds serious!\""
    "Kyon's grip on the steering wheel tightened as his eyebrows drew together in fierce concentration."
    "\"Okay! Four blocks ahead and then turn right!\" Haruhi exclaimed."
    "\"W-wait!\" Yuuto protested, though he knew better than to grab the wheel and fight for control."
    "\"I got it,\" Kyon replied tersely, working the clutch and shifting seamlessly. The gears didn't grind in the slightest! Yuuto had put quite a bit of work into the engine, but Kyon didn't underestimate it, and avoided over-accelerating, sending the car screaming forward. Come to think of it ... he hadn't even explained how to shift gears to his son, had he? Kyon didn't notice this seeming lack, and slowed just enough to verify the next intersection was clear, weaving around a delivery van stopped in their lane and narrowly missing an oncoming car."
    "Yuuto swallowed nervously, as Haruhi focused on the phone, giving updated directions, and Kyon continued accelerating. By the time they reached the country roads on the outskirts of town, Yuuto was beginning to appreciate his son's skill. \"Straight ahead!\" Haruhi declared. \"Kasai-san's car is just behind us!\""
    "\"Got it,\" Kyon affirmed. \"Too bad we don't have a helicopter.\""
    "Yuuto reflexively clicked the timer he habitually kept on a cord inside his shirt as they passed the turn-off to the access road, still sealed with a gate. The country roads were winding, mountain paths -- the long way to the next town over. There was almost never traffic, but it took a very skilled driver to make better time."
    "That made it Yuuto's preferred route, of course."
    "The engine purred, Kyon's shifting flawlessly, going to the optimal gear to maintain -- if not increase -- speed on the up-slopes, down-slopes, and straightaways. He managed to maintain traction the entire way. If it weren't his first time driving, Yuuto would approve without hesitation!"
    "\"We can't let them finish this route ahead of us,\" Kyon warned. \"We might lose track of them in the next town, if that happens.\""
    "\"Yeah, no more updates from here!\" Haruhi exclaimed, though she seemed more excited than alarmed. \"You're not going to let Sasaki-chan stay in trouble, though, are you?\""
    "\"Of course not!\" Kyon scoffed."
    "The midpoint between towns was a large downslope to a low bridge, followed by a great upslope. The grade was remarkably steep, and it would be an ideal point to power accelerate through, except that the curve after the bridge wasn't inclined enough to maintain a good speed without sliding off the mountain path, unless the driver was particularly skilled. \"O...okay, Son,\" Yuuto said uneasily, as Kyon continued speeding down the hill. \"You-- You need to ease off; this car might not be heavy enough for you to get the traction you'll need to stay in control on that corner!\""
    "\"We'll be okay,\" Kyon grumbled, glaring forward, to where a minivan was just cresting the top of the next steep slope. \"Haruhi -- are you ready?\""
    "\"As long as she doesn't have a line of sight on us,\" Haruhi replied unhesitatingly. \"That means that if it works out, this will all be up to you!\""
    "\"Alright -- brace for this next part; it's about to get heavy!\""
    "Yuuto didn't have time to ask what it was about, just to wish he'd actually sprung for the five-point restraining harnesses he'd frequently considered. The car rode low on its suspension as it reached the bottom of the downslope, the feeling of extra weight settling onto Yuuto and Haruhi, pressing both of them into their seats. Kyon seemed to show no sign of it, though for some reason it persisted, and the car didn't spring back up in the slightest."
    "If anything, the sensation of extra weight increased, along with the speed that Yuuto was certain was just a bit too fast. Except ... when they hit the turn, the car's tires somehow found enough traction to merely slide all the way to the shoulder, somehow making the curve and straightening out up the next hill in a flawless drift. The sensation of inexplicable heaviness abruptly vanished, leaving Yuuto feeling almost weightless before the car launched straight up the slope."
    "That ... shouldn't have been possible! Yuuto could have done it, but it wouldn't have been that straightforward; it'd take a controlled hand-brake slide, something Kyon hadn't bothered with. He didn't really have time to think about it, though. Their acceleration up the hill was so fierce that the car should have flown into the air when the road ran out, but instead somehow stuck perfectly to it."
    "Kyon cursed as the van came into sight and the strange sensation of floating abruptly cut off. The next stretch was a curve around the interior of a trio of mountainsides, giving them a perfect view of the van at the midway point. At Kyon's speed, they would catch up to it on the next straight segment around that curve -- the van's driver seemed to realize that, too, judging by the frantic-looking wobble as the (far less skilled, in Yuuto's mind) driver tried to slam on the accelerator, nearly losing control."
    "There was a window of only a few seconds where the van was out of sight, before they rounded the corner. This time Kyon shifted all the way to the top gear, shooting down the slight slope and ahead of the van. They passed it in a flash, revealing a number of thuggish looking men staring at Kyon anxiously, and a girl that Yuuto didn't recognize, squirming to escape her captors."
    "So ... it really was a kidnapping? Well, he'd known that Kyon was facing some less than savory types, but this...."
    "\"Hang on!\" Kyon exclaimed, shifting down before reaching for the hand-brake. Yuuto and Haruhi barely had enough time to brace themselves before the car screeched to a halt, turning to one side and coming to a rest as a perfectly placed roadblock on a narrow point of the road. The driver of the van had more than enough time to safely stop, but slammed on the brakes -- nearly losing control again -- and sliding to a stop a dozen meters from Yuuto's car."
    "Kyon was already in motion, though. When had he put on that coat, anyway? He'd been driving, so Yuuto wasn't certain. It scarcely felt like the car had come to a stop before Kyon leaped over the hood of the car, striding toward the van even as it ground to a halt. The driver of the larger vehicle frantically tried to put it in reverse, but before he could even get that far, Kyon was beside the larger passenger door. He unhesitatingly produced a long, curved piece of metal from inside his coat, the interior curve punctuated at regular intervals with sharp points; it fit over the tire perfectly, so that as soon as the wheel rolled back far enough, the van's own weight pierced the thick rubber treads. Well, that was one way to burst a tire without injuring yourself, Yuuto dazedly thought."
    "Another piece of metal -- a handle for a baton, it looked like -- allowed Kyon to smash out the driver's window without harming himself, though Yuuto suspected the thick coat might also have helped Kyon avoid being cut. The driver quickly stopped trying to get away. Yuuto hadn't even noticed when he got out of the car, but Haruhi tugged at his wrist before he could approach and get involved himself."
    "Well ... that was a blow to his male pride, but he had to admit that Kyon certainly seemed to have things in hand. Anyway, the familiar figure of Kasai was visible behind the wheel of the next car to scream around the corner, slowing more sedately before it blocked the van in."
    "\"Uh-- C...c...can I help you?\" the van's driver stuttered anxiously, hands tightly gripping the wheel."
    "\"Keys,\" Kyon said flatly."
    "\"Right!\" the driver yelped, pulling the keys from the ignition -- and then throwing them straight at Kyon's face. Yuuto managed a cry of outrage, in tandem with his boss's daughter -- but Kyon effortlessly batted the incoming keys away, not looking back as they flew past the edge of the road, and vanished into the foliage on the steep hillside."
    "\"Your car is now illegally parked,\" Kyon said flatly, unlocking the door and opening it-- He ducked underneath the driver's half-hearted swing and punched him in the side once before undoing the seatbelt and pulling the groaning man out. \"Find those keys before the police get here.\""
    "The other men inside seemed undecided about trying to fight, but by that point, Kasai, Mori, and three other men in dark suits had already reached the van. Despite having equal numbers and a hostage, they quickly gave up."
    "Kyon ignored them, largely, his attention going to the kidnapped girl. Well ... Yuuto was nothing more than astounded that she seemed more annoyed than scared about the entire ordeal."
    "\"I...it seems that I've caused a problem yet again!\" she apologized with false cheer."
    "\"You haven't caused a problem at all, Sasaki,\" he said earnestly, scratching the back of his head with one hand. \"I mean ... I thought these guys would do something stupid like this again, but I didn't think it'd be this early.\""
    "Haruhi, deciding that the danger was over, dashed to Kyon and Sasaki's side, hugging the other girl tightly. \"You're okay, Sasaki? Those guys didn't do anything they shouldn't have?\" she prompted."
    "\"Other than manhandling me into a car at knife-point, no,\" Sasaki agreed. \"It's ... becoming far too common, though.\""
    "\"Knife-point?\" Kyon asked, turning to the uncomfortable looking men who were sitting on the ground beside the vehicle, carefully avoiding eye-contact. The driver alone was groaning as he scrambled on hands and knees beside the road. \"This really better be the last time. I'm getting tired of this, and I think Sasaki's not a big fan of it, either. I can't even admire your persistence at this point!\""
    "\"You ever could?\" Haruhi asked doubtfully, her arms around her friend still."
    "\"...no,\" Kyon admitted, frowning. \"Well.... Alright, Kasai-san, let's see how we're going to handle these guys.... I think we should send them to the police, again.\""
    "\"Naturally,\" Kasai agreed, looming ominously over the men. \"You won't be giving us any trouble for this, will you?\""
    "\"Are you kidding?\" one of the men protested scornfully. \"We just got taken down by both of the Kowa Keigo, and the legendary 'demoness'! How many of our brothers can say that?\""
    "\"Far too many for my tastes,\" Kyon said sourly, making the sitting man wince and hunch in on himself. Mori's smile at being called a 'demoness' was especially chilling."
    "Yuuto felt his eyebrow twitch and decided it was a good time for a cigarette. Kasai and the other men quickly worked out a plan -- it seemed they'd done this sort of thing before -- as Haruhi escorted Sasaki to the car to reassure her. It only took a minute or two to work out the details, and then one of the other men with Kasai was making a phone call while Kyon and the huge man returned to Yuuto's side."
    "Eying his son critically, Yuuto stooped to stub out his cigarette. \"Kyon,\" he said sternly, frowning at the boy. \"I have to admit, I'm disappointed in you.\""
    "Haruhi allowed an indignant growl to escape, and if Sasaki weren't still loosely hanging onto her for support, Yuuto suspected the girl would have marched over to yell at him. Kasai's face was an unreadable mask, and Kyon looked stung, but resigned at the admonishment."
    "Yuuto sighed and ran a hand through his hair. \"It's my own fault -- and your mother's -- that you decided to get training on driving behind my back ... but damn it all! Despite whatever trick you used to make the corner past the bridge--\" He hesitated and yanked his timer from beneath his shirt. \"Look at this time!\" he demanded. \"What do you have to say for yourself?\""
    "All three of the younger folk shifted their expressions to confusion. Kasai's eyebrows rose from behind his dark shades."
    "\"I ... what?\" Kyon managed."
    "\"Eh-- You did fairly well,\" Yuuto conceded, shaking his head. \"But from now on, you're getting a lesson from me every week, and you will keep practicing this course until you can shave at least ten seconds off this time!\" He shook the timer for emphasis. \"And that's without using that trick that it sounds like you can't rely on all the time -- and furthermore none of this gets back to your mother-- Do you understand me, Son?\""
    "\"S...sorry,\" Kyon managed, bowing his head."
    "One of the kidnappers, watching the exchange, flatly mumbled, \"If they're all that scary, I hope none of us ever meet a Kowa-Keigo's mother.\""
    "\"I wish I were half as intimidating as her!\" Mori exclaimed cheerfully, her smile still menacing, prompting the man to swallow anxiously."
    "\"Anyway,\" Yuuto added more softly, pocketing the timer, \"maybe saying I was disappointed was too harsh. I wish I could have taught you from the beginning, myself ... but I am proud that you've shown real potential as a skilled driver. Now -- you girls can get in the back, and I'll show Kyon how to take corners better while we make up for lost time!\""
    "\"A...alright,\" Kyon managed, sounding half stunned still."
    "Haruhi's eyes widened in shock and alarm. \"B...better cornering than that!?\" she squeaked in alarm."
    "\"Family techniques!\" Yuuto said proudly. \"As passed to me by my older brother, when he was first delivering tofu on back mountain roads!\""
    "\"That ... sounds like an interesting story,\" Sasaki managed, a bit dazedly."
    "Yuuto nodded knowingly as the girls climbed into the car, still shaky from the earlier excitement. \"Y...your family sounds pretty cool,\" Haruhi said cautiously."
    "\"Well, actually, my parents passed away when I was very young, and my grandfather wasn't able to take proper care of me, so I was informally adopted by a close family friend at a young age,\" Yuuto admitted."
    "Haruhi shot Kyon a sharp look for some reason, while the boy pointedly pretended not to notice."
    "Yuuto shook his head at the memories, continuing, \"Along with my other older brother, who took to computers like I took to cars -- but that's a story for another time. Now, Kyon, I want you to focus on how the handbrake is used to drift. Proper drifting is not actually the most powerful technique, but it's a good foundation for later techniques, and awareness of it also lends better control in general, so....\""
    "***"
    "Haruhi thought her knees would be shaking far too much to walk properly once Yuuto finished Kyon's rather grueling 'instruction' on 'proper driving.' The man was an absolute demon behind the wheel!"
    "Sasaki seemed somehow less shaken, which Haruhi chalked up to her own harrowing experiences being relegated to damsel-in-distress. Hmm, Sasaki would probably love a chance to learn some martial arts once they got her to stop suppressing supernatural events, wouldn't she? Sure, she had her own super power, but even Kanae had learned how to get away from people better, and something 'normal' would probably suit her better ... her power wasn't particularly suited toward preventing relatively mundane threats, anyway."
    "Haruhi shook her head to clear it, trying to resist the urge to glare at Kyon, who'd taken the entire lesson in stride, listening to his father's lectures on driving the entire way."
    "\"Ah, that reminds me,\" Yuuto mused, frowning as he glanced at the girls. \"Will you two be visiting today?\""
    "\"I need to get Sasaki-chan home, actually,\" Haruhi apologized, shaking her head before touching a fingertip to her lower lip. Although.... She almost snapped her fingers, realizing they'd forgotten one major detail after all. \"Ah, Kyon-kun should come over to Tsu-chan's place tomorrow evening to study.\""
    "\"Alright,\" Yuuto agreed amicably, giving his son a stern look."
    "Kyon sighed and shook his head. \"Even more studying,\" he groused gently. \"Alright -- Haruhi, Sasaki, you two take care. If anything comes up, don't hesitate to call me.\""
    "\"Absolutely!\" Sasaki agreed. \"Though, I feel I should give you something in return, after all you've done for me!\""
    "\"Oh, believe me, you'll get a chance, Sasaki-chan,\" Haruhi chimed in with a smirk. \"Probably as soon as two days from now! For the moment, however, we should let Kyon have some time with his family.\""
    "\"Certainly,\" Sasaki agreed, the pair of them waving before they walked down the street, Sasaki following the other girl's lead."
    "Smacking one fist into her opposing palm, Haruhi asked, \"Sasaki-chan, have you already gotten your Kitago uniform?\""
    "\"No, not yet,\" Sasaki admitted. \"I should get sized and order one soon, if I'm transferring, shouldn't I? I was considering putting it off until after summer vacation, though, since they usually allow some leeway.\""
    "\"No need!\" Haruhi exclaimed. \"Kyon's already seen to it ... sort of. Well, him and Tsuruya, since they handle that side of things,\" she said with a vague gesture. Sasaki still didn't know all the details, but she'd already mentioned to Haruhi in the future that she and Kyon were responsible for helping the demure girl get her outfit. \"Alright -- let's grab Mikuru-chan to get you properly sized, and I'm certain we can have that uniform ready for you before class on Monday!\""
    "\"So soon?\" Sasaki asked, smiling gently. \"That sounds like quite a bit of trouble, but I have a hard time saying 'no'!\""
    "\"Nothing but the best for Kyon's girl ... cohorts,\" Haruhi insisted, catching herself, though it prompted Sasaki to giggle at the term. \"So, I'll just call Tsu-chan to set things in motion....\""
    "***"
    "After the festival, Sasaki was escorted again by Fujiwara, and found herself in Tsuruya's home. She'd only been there a few times, most recently to be measured for her uniform by Mikuru -- who was evidently quite an accomplished seamstress. It was different at night, and by the time Sasaki took off the blindfold...."
    "It really did raise a lot of questions, though."
    "Perhaps Mion's house and Tsuruya's house were the same building, and it was all clever props? The time seemed to be the same, though when Sasaki looked around, the only person nearby was the head maid. She seemed strangely subdued, gazing off to one side with a frown."
    "\"Fujiwara already vanished?\" Sasaki asked, with a frown of her own."
    "\"Somehow ... yes,\" the maid agreed, shaking her head before turning a smile to Sasaki. \"Haruka-chan and the others are waiting for you inside.\""
    "Sasaki nodded firmly, following the maid across the yard and up into the house ... though, she'd just left a similar yard anyway. The door cracked open, and she had only time to slip off her outdoor shoes before Haruhi came flying through, capturing her in a hug before Sasaki could do more than start to form a greeting."
    "\"Got her!\" Haruhi sang over her shoulder, Tsuruya and Mikuru following her more sedately to the covered porch surrounding the house."
    "\"Good, good!\" Tsuruya chuckled. \"Kyon-kun just got back from dropping your uniforms off, 'Saki-nyan.\""
    "Mikuru just waved quietly from behind the other girls as Haruhi reluctantly let Sasaki breathe."
    "\"More uniforms?\" Sasaki asked in surprise. \"But, you already gave me two! I shouldn't need that many!\""
    "\"Time travel,\" Haruhi said, grinning. \"So you think today is ... Wednesday, right? And tomorrow should be Thursday?\""
    "\"Ah ... that's right,\" Sasaki agreed, nodding. \"But you want me to think it's time travel?\""
    "\"Well, it is, and it was Kyon's job to convince you, but when you see tomorrow is Monday, it should all be sorted out.\" She nodded decisively, and Mikuru offered her own uncertain nod of encouragement."
    "Tsuruya alone looked less than convinced, staring up thoughtfully as one fingertip tapped the corner of her mouth. \"Say,\" she said abruptly, turning her attention to Sasaki. \"'Saki-nyan, if you were very unsettled and scared, because you found out time travel was real, what would make you calm and comfortable afterward?\""
    "She didn't quite meet Tsuruya's eyes as she explained, \"Um, being around my friends, of course! It ... well, it would be a disconcerting thing to happen, but with my friends, I think I'd be okay?\" Of course, that would mean that such fantastic things would be possible...."
    "Haruhi looked at Tsuruya questioningly. \"What's this about?\" she prompted."
    "\"Just making sure there's a supply of Kyon-kun on hand in the clubroom if it gets stressful tomorrows,\" Tsuruya replied with a grin. Turning back to Sasaki, she asked, \"You don't mind, do you?\""
    "\"What's this about me?\" Kyon asked, stepping in from around the corner, already dressed in a comfortable looking yukata fit to match Haruhi, Tsuruya, and Mikuru. \"Don't I get a say?\""
    "\"Yes, but like I keep saying, you already decided,\" Haruhi replied without pause. Mikuru perked up happily to see the boy in question, and Tsuruya looked satisfied, as well. \"So if Sasaki-chan needs you, you'd be there?\""
    "\"I feel like I should say something snarky here, but I wouldn't joke about that, seeing as how they keep trying to kidnap her,\" he mused, frowning as he came to a stop a step from Mikuru, one hand rubbing his chin thoughtfully. \"So, of course I would. How can that be a real question?\""
    "\"Something for tomorrow ... and us helping you take care of an assignment you let slip. Busy saving the world from slider-bots, evidently,\" Haruhi chided."
    "\"U...um, if no one is hungry, what should we do tonight?\" Mikuru asked thoughtfully, scanning across the other girls."
    "\"Are we caught up on homework?\" Sasaki asked hesitantly. Of course, if time travel were real, they might not have the actual assignments yet, so that would make sense."
    "\"Yeah, took care of that earlier, before you showed up. Since you don't have any assignments yet, we should play a game,\" Haruhi decided. \"Cards -- maybe poker! Winner gets Kyon's lap, and then we can watch some anime until it's time for him to go home!\""
    "\"G...goodness!\" Sasaki couldn't help but gasp, her blush mirroring Mikuru's. \"I...is that alright, Kyon?\""
    "\"So, what happens if I win?\" Kyon wondered."
    "\"Four way tie?\" Tsuruya suggested, grinning."
    "Sasaki bit back a giggle. If today was Kyon's birthday, she could certainly think of worse ways to spend it. Hopefully, she wouldn't get into too much trouble with the school for missing days ... really, the hard part would be explaining it to her mother!"
    "She put that thought aside to worry about it later. For whatever reason, even when she turned her phone on, she didn't see any messages waiting for her. So for the moment, Haruhi, Tsuruya, and Mikuru wanted her to spend some time with them ... and Kyon. She was certainly not going to complain!"
    "***"
    "While she knew her boyfriend was a bit of a pervert, and had a penchant for overacting -- it was kind of endearing, in a sometimes embarrassingly dramatic way -- Yanagimoto was actually a bit surprised when he wasn't first to hear about the new transfer student. She had entirely anticipated him to be just as informed (if not more) than the other boys, once it came to light that the new student was supposed to be a girl."
    "Instead, he merely raised an eyebrow and listened to the other students chatter about it. Someone made the obligatory remark about hoping that the new girl was cute, but even that didn't draw him into discussion."
    "Since homeroom hadn't started yet, she finally gave in and asked, \"You're not curious about the new student?\""
    "\"A little bit,\" he admitted, shrugging. \"But I've got you, so it's not quite as big a deal to me.\""
    "Sakanaka mused, \"I heard there were two transfer students, actually.\""
    "\"That's surprising,\" Kunikida chimed in thoughtfully. \"Two students at the same time?\""
    "\"Do we even have two free seats?\" Taniguchi wondered, looking around the classroom."
    "\"Just one,\" Kunikida confirmed."
    "\"But two students at the same time is a surprising coincidence.... Hmm, Suzumiya-san, what do you think?\" she prompted the girl who was staring out the window and toying with the tip of her ponytail. Sakanaka blinked, seeming to realize something, and quickly adding, \"Oh, um, by the way, the new hairstyle suits you!\""
    "Come to think of it ... her hair had certainly gotten much longer since the start of the school year. Yanagimoto quickly filed that thought under 'strange things that happened around her friend' and decided not to ask. Aside from Sakanaka, no one else had noticed, after all."
    "\"Oh, thanks,\" Haruhi replied cheerfully, puffing up slightly at the praise."
    "\"I like it, too,\" Kyon agreed, twisting around in his seat to nod solemnly -- which amplified Haruhi's glow of satisfaction immensely."
    "\"Yeah, but it's her girlfriend's opinion that matters most,\" Taniguchi countered. Yanagimoto bit her tongue; Taniguchi couldn't know about Haruhi and Kyon also having a relationship, but that was the level of tact she'd generally come to expect from him. He did catch her warning glare, and quickly changed the subject back: \"Uh, do you two know something about the new transfers?\""
    "\"Why would I be expected to know that?\" Kyon asked in an almost mumble, not meeting anyone's eyes."
    "\"Well, if our school is a shounen manga, you're the protagonist, probably,\" Taniguchi reasoned. \"Some rival? Enemy? New fiancee? Or maybe a friend you rescued, who is joining the team as a new ally!\""
    "Haruhi and Kyon stared at Taniguchi, and Yanagimoto tried very hard not to show her suspicion that he'd stumbled directly into the truth of the matter. \"That's stupid!\" she protested, despite a lack of reasons to make such an argument."
    "\"Well, that would only explain one of the two new students, in any case,\" Kunikida reasoned."
    "\"Right,\" Haruhi agreed. \"Though, what if it were the case that the school that recently turned from an all-boy's school to a co-ed school had some issues from rowdy boys who weren't used to dealing with girls?\""
    "\"Ah!\" Sakanaka exclaimed. \"Oh, my, that could be potentially awful!\""
    "\"Yeah, but it would explain why two students might show up simultaneously,\" Haruhi reasoned. \"Probably, other schools would also be getting transfers, if the situation were bad. Hmm, if that were the case -- hey, class rep Goto, stop pretending to sleep through this!\" Haruhi knocked sharply on the desk where the boy in question had his head resting on his crossed arms. \"Wouldn't it be a good idea to make sure the entire class was especially welcoming and thoughtful to someone who came out of a bad situation like that?\""
    "Goto sighed, his attempt at dodging the conversation by feigning sleep thwarted, and sat up. \"We should be thoughtful and welcoming to any new student,\" he remarked. \"Though, I suppose we could try and be on our best behavior.\""
    "\"Though if it was about boys being jerks to girls, we could share the story of what Kyon did to Yamane Jun,\" Taniguchi offered. \"I mean, wouldn't that comfort anyone who was worried about being teased, or something like that?\""
    "\"And just bring up that certain incident that got handled?\" Yanagimoto asked, rolling her eyes. \"That's brilliant,\" she added sarcastically."
    "\"What can I say? I'm a helper!\""
    "\"I'm pretty sure you're just the comic relief.\""
    "Taniguchi countered, \"Yeah, but someone's got to do it, and I get a fantastic girlfriend out of the deal.\""
    "\"Flattery like that will spare you comedic tsundere violence,\" Yanagimoto allowed, fighting down a blush."
    "\"I'm really getting the feeling that we've got an entire comedy troupe here, lately,\" Kyon contributed, while Taniguchi preened at his girlfriend's comment."
    "\"You and me both,\" Goto agreed, shaking his head."
    "Yanagimoto just caught the thumbs-up that Kyon gave Haruhi. Probably something she shouldn't pay too much attention to ... but that in mind, she'd try and be friendly to the new arrival, on Haruhi's subtle advice. Judging by Sakanaka's slightly raised eyebrow when their eyes met, she thought so too."
    "When Okabe entered the classroom a moment later, trailed by a meek, nervous girl that she didn't recognize, the homeroom teacher eyed his students speculatively before standing at the board and writing the characters for her name there, for everyone to read."
    "\"Class, joining us today and for the rest of the year is a new student. This is Tachibana Kyouko. Tachibana?\" he prompted."
    "\"Um!\" the girl exclaimed. \"I'm-- I'm Tachibana Kyouko, it's nice to meet you,\" she said, mildly anxious. \"Um, my hobbies are reading mystery novels, and studying philosophy. My favorite color is green, and I like period dramas. I'm hoping that things will be calmer here with my boyfriend--\""
    "This elicited some excited gasps, and Yanagimoto bit back a growl when Taniguchi shot Kyon a speculative look. For his part, Kyon seemed unsurprised, but also entirely unconcerned."
    "Okabe made a mildly surprised sound at that himself, and Kyouko quickly concluded, \"Erm-- Please take good care of me!\" before bowing deeply."
    "Goto, as the class representative, gave a half-shrug before leading the class in calling, \"Welcome!\""
    "***"
    "Kanae was more than willing to follow along when Haruhi appeared at the doorway to her class and waved before holding up a pair of bentos. \"Ah!\" she couldn't help but cheer as her classmates shook their heads, having gotten used to the dating situation."
    "Haruhi beamed a grin at her and led her to the clubroom. \"No Sempai?\" she remarked in surprise, seeing Yuki and her Mikuru-nee there, but not the boy in question."
    "\"He's keeping an eye out for Kyouko,\" Haruhi explained, spreading her hands in a shrug. \"Well, until Koizumi picks her up -- so he should be along shortly.\""
    "\"Koizumi-kun?\" she wondered, taking a seat at the table with Haruhi as Tsuruya trooped in."
    "\"Mm, he and Kyouko are dating; she told the class that one of the reasons she transfered here was to be with her boyfriend,\" Haruhi explained. \"This also makes her joining the club a little more subtle, according to Kyon.\""
    "\"Um, subtle? Why does it need to be?\" Mikuru wondered, tilting her head to one side curiously."
    "\"That's what I said....\" Haruhi crossed her arms over her chest and shook her head, sighing. \"I guess two students transferring in simultaneously and joining the same club is a bit odd ... but doesn't that happen all the time in anime?\""
    "\"That's true!\" Tsuruya said brightly. \"Anyway, if Kyouko joins our club because of her boyfriend, what about 'Saki-nyan?\""
    "\"She and Kyouko are friends!\" Haruhi said, uncrossing her arms and turning her attention to the bento before her. \"So Sasaki will follow Kyouko.\""
    "\"That means she's basically left behind and can't join us for lunch, then, doesn't it?\""
    "Haruhi winced. \"Um. We should have thought of that last night.... Okay! Yuki-chan, text Kyon and Sasaki, won't you? Sasaki can coincidentally see her middle-school friend and follow him to join us for lunch.\""
    "Yuki nodded slightly, accepting a teacup as Mikuru served them out, and not looking up from the book she held in her other hand. \"Done,\" she said quietly."
    "Kanae giggled, and Haruhi made a pout at her face before brightening. \"Aha,\" she chuckled, grinning widely. \"Say 'ah', my cute little Kanae-chan!\""
    "\"Eh?\" the slider squeaked. \"W-wha-- Um ... a~ah?\""
    "Kanae felt her cheeks burn as Haruhi delicately placed a morsel from her bento gently on her tongue. She was almost too embarrassed to taste it, or properly chew!"
    "Mikuru giggled, cheering, \"That's so cute! Ah, camera, camera--\" She cut off abruptly with a quiet gasp."
    "Yuki lowered the cell phone she had swapped for her cup of tea, eyes still on her book."
    "Swallowing, Kanae asked, \"How did you do that?\""
    "Finally looking up from the title Kanae couldn't read, Yuki's lips twitched in a tiny smile, but she said nothing. \"That goes into the collection, right?\" Haruhi asked. \"Speaking of which ... some day, we absolutely have to start putting all those pictures into scrapbooks.\""
    "\"Yes,\" Tsuruya agreed, chuckling. \"Before Mikuru-chan and I leave for college, too!\""
    "\"We should figure out which college we're going to,\" Haruhi realized belatedly, biting into a piece of onigiri. She chewed thoughtfully, and after swallowing added, \"Is Toudai or Kyoudai too cliche? Normally, I might think that getting into a top school like that would be hard, but I'm sure we can do it, can't we?\""
    "Kanae spotted her chance, and perked up; Haruhi had gotten a few grains from the onigiri on her face. \"Aha, Suzumiya-sempai, you've got some rice on your cheek!\" she said brightly, leaning forward and carefully plucking them up. She winked at Haruhi before licking them from her fingertips carefully."
    "Haruhi stared at that, eyes wide and cheeks pink. \"T...that....\" She immediately scowled and turned to Yuki, who was only just then lowering the phone. \"...well done, Kanae-chan,\" she admitted, blushing more deeply. \"Though, I think we should keep that from Kyon--\""
    "And just as she said that, Kanae's sempai opened the door, one eyebrow rising. \"Keep what from me?\" he asked doubtfully."
    "\"It was just Kanae-chan being adorable,\" Haruhi explained, countering the slider's last move by hugging the girl tightly -- and hiding her face behind Kanae's. Even if she wished her sempai, or maybe Mikuru would join in, she wasn't about to complain."
    "\"I am keeping the pictures,\" Yuki added quietly, when the silence dragged on. \"They will be uploaded to your private library.\""
    "\"Er, okay,\" her sempai said, frowning. After a blink, he asked, \"I have a private library?\""
    "Yuki's attention turned back to her book, and Kanae's sempai scratched his head in consternation. \"Oh, what is it of?\" Mikuru asked curiously."
    "Tsuruya bit back a smirk and pointedly looked out the window. Hey ... what was that about? She obviously knew!"
    "The boy shook his head quickly. \"I'll worry about that later,\" he grumbled, turning to one side, gesturing someone else into the room. Sasaki stepped in on tottering, unsteady feet, though she brightened slightly to see Haruhi and the others."
    "\"Ah, Sasaki-chan?\" Haruhi greeted. \"What's wrong?\""
    "\"T...today feels ... very strange,\" Sasaki said uneasily, as Kanae's sempai ushered the older girl to the table and took his own seat."
    "Haruhi heaved a sigh and shook her head. \"Well, you're here, now, and you'll come back again when it's time for club,\" she assured the other girl, climbing to her feet. \"Hey, Kyon ... where are Koizumi and Kyouko?\""
    "\"Having lunch down in the courtyard!\" Tsuruya answered, before he could. \"I thought 'Saki-nyan might be a bit more comfortable just now, and Koizumi can also let everyone see that he and Kyouko really are dating.\""
    "\"I guess that makes sense...\" the boy mused with a shrug, unwrapping his bento."
    "\"Yeah, it does,\" Haruhi said dryly. Moving behind Kanae's sempai's seat, Haruhi grabbed the back of it, and just before he could dig into his meal, she dragged him back a half-step. He froze, frowning at the chopsticks that he held frozen in mid-air."
    "Turning her attention to Sasaki, Haruhi gently asked, \"So ... you're starting to see that time travel is real?\""
    "The other girl started trembling. \"I.... I might be going insane, too,\" she countered shakily."
    "Haruhi sighed, shooting Kanae's sempai a look of annoyance. \"You're not going crazy!\" Tsuruya assured her. \"Though ... that was a first time time traveling for me, too -- Kyon-kun's done it several times!\""
    "\"I-- I even don't do it often!\" Mikuru added anxiously, wringing her hands. \"But don't get stressed! It's all okay, right?\""
    "Yuki said nothing, merely raising her cell phone, camera pointed at Kanae's sempai."
    "\"What's going on?\" the slider wondered."
    "\"It's going to be okay!\" Haruhi declared. \"So, take a deep breath, have a seat, and relax!\" She gently guided Sasaki a stumbling half-step forward, spun the other girl and then pushed her to stumble backward -- where she ended up landing almost perfectly in the only boy's lap, his free arm reflexively curling around her back to steady her."
    "\"Eep!\" Sasaki squeaked, eyes widening as she blushed fiercely. \"Ah, um....\""
    "Setting his chopsticks down, the boy frowned. \"I'm sorry,\" he said with a mild sigh. \"Um, I've ... kind of gotten so used to this kind of thing I hardly even think about it anymore. Though, that's a rather sad statement as to the state of my life, isn't it?\""
    "\"I-- Um, being able to ... handle something like this strikes me as quite admirable!\" Sasaki dazedly agreed."
    "\"Feeling better, then?\" Haruhi asked, hands on her hips as she smiled gently."
    "\"I'm starting to,\" Sasaki admitted, managing a weak smile of her own. \"I ... think I might have a lot of questions, though!\""
    "\"Well, originally, I gave this job to Kyon,\" Haruhi explained, retaking her own seat, then glancing at Kanae. \"Ah, jealous?\""
    "\"A little,\" the slider admitted, blushing."
    "Haruhi shrugged and plucked Kanae from her seat, setting her in Haruhi's lap, almost the exact same way. \"How about that?\" she asked."
    "Blushing even more deeply, Kanae admitted, \"...this is nice, too.\""
    "\"Right,\" Haruhi continued, nodding. \"Anyway, it was probably too much, or maybe Kyon's just better at action hero stuff. We'll all work together to explain it to you tonight! Right, Kyon?\""
    "\"We have a meetings with the Sumiyoshi-rengo, actually,\" Tsuruya remarked. \"Um, about getting them to stop kidnapping Sasaki. Remember?\""
    "\"Oh, that's right. And I really can't afford to miss that one, either,\" he apologized."
    "\"I-- Should I go?\" Sasaki asked, her face a bit red ... for all that she seemed to be enjoying her seat, she couldn't quite meet his eyes."
    "\"Aw, that sucks,\" Haruhi groused. \"Alright-- Alright. We'll meet up at Tsu-chan's place after your meeting. I guess that's Tsu-chan, Kyon, Yuki-chan, and Sasaki to handle the meeting?\""
    "\"Sure,\" the boy agreed. \"Sounds good to me.\""
    "\"We can explain a little more about time travel and other things at the club meeting, then you have work.\" Haruhi paused to make a face, giving Kanae a gentle, reassuring squeeze. \"After that, we'll all meet up for dinner at Tsu-chan's place--\""
    "\"I'll cook!\" Mikuru volunteered quickly."
    "\"Can I help?\" Kanae managed to add."
    "\"I think it's time to find a new costume for you, first,\" Haruhi decided. \"So we can work on that, instead.\""
    "\"Ah-- Okay, Suzumiya-sempai!\""
    "Mikuru beamed a smile at the slider, undoubtedly already thinking about making the new costume ... she did really seem to like sewing! Shaking her head and turning to Sasaki, the time traveler asked, \"Ah, since it's for you, Sasaki-chan, what would you like?\""
    "\"A...anything would be fine, really,\" Sasaki demurred."
    "The boy who was holding her snorted. \"Her favorite is ochazuke,\" he contributed."
    "\"Oh?\" Mikuru wondered, touching a fingertip to her lower lip, her smile turning thoughtful."
    "Sasaki's blush deepened faintly. \"That's true,\" she admitted. \"Um, there's also the ... irony that being offered that dish is also traditionally a polite way of being asked to leave, so I've really been able to enjoy it fairly rarely. I'm afraid I'm not much in the kitchen....\""
    "\"I never heard of that!\" Kanae exclaimed. Though, no one had ever offered it to her, either."
    "\"I did!\" Tsuruya chuckled. \"That's more toward Kyoto than here, though. Anyway -- we should finish our lunches before class resumes, before we get too distracted! We have the next meeting to work out these details!\""
    "\"And a meeting after that, and one after that,\" Kanae's sempai sighed. \"I wish I could still afford to be lazy!\""
    "\"Well, I like seeing you live up to your actual potential,\" Haruhi retorted, gently setting Kanae back in her seat, so they could finish their lunches."
    "\"I ... do too,\" Sasaki admitted with a giggle, as she climbed to her feet. \"Even ... if it's ... something I thought impossible, like time travel, I knew Kyon was able to handle quite a bit!\""
    "The boy in question couldn't keep his face from reddening faintly at the praise. \"I never doubted Sempai,\" Kanae asserted proudly, which made him chuckle nervously and scratch the back of his head."
    "\"He is pretty awesome, even if he's not perfect,\" Haruhi allowed. \"But we don't have much longer for lunch, so let's finish eating!\""
    "***"
    "By the time classes finished, Sasaki felt completely overwhelmed. Rather, she admitted to herself, she would have, but ... even if it was one more mad thing in an increasingly mad world, spending time ... with Kyon had certainly helped her calm down. She'd have to thank Tsuruya for her foresight on that count. That reassurance was exceptionally welcome, and even though Sasaki knew she couldn't monopolize Kyon's attention, she was thinking she could do with a bit more."
    "Public displays of affection weren't something she was especially comfortable with, but she was willing to make an exception -- aside from which, the other members of their odd arrangement weren't 'public', really."
    "Still.... The teachers and other students all being adamant about the date really did slowly start hammering things home. She could try and tell herself that the 'weekend' was an illusion or a hallucination, but that didn't really seem fair to Haruhi or Kyon, who deserved her trust."
    "It was verging on terrifying to admit that something like time travel not only existed, but was a power that Kyon of all people could use.... And she wasn't really happy to find herself arguing -- even if only to herself -- that Kyon's access to time travel would explain his unexpected skill at martial arts. Skill which had spared her substantial difficulties."
    "Well, it was possible that such supernatural powers were the only reason she ended up getting involved, but...."
    "She wondered if it was selfish of her to be willing to accept that, if it let her be with Kyon."
    "Being a damsel in distress wasn't fun, but the undeniable message of how much Kyon cared, to keep doing it...."
    "So, time travel was real."
    "She managed to smile at her classmates, who seemed already resigned to her entanglement in Haruhi's club, and smiled and waved as Kyouko met with her and Koizumi to escort her to the next meeting. She wished it were Kyon, but she wasn't sure that would be good -- she might not be able to keep herself from grabbing onto him and shaking for a while as she let the enormity of the situation settle in."
    "Kyouko seemed agitated as well, and took her hand, reassuring, \"It's all going to be alright!\""
    "\"I know,\" Sasaki replied, a bit unsteadily, though she forced a smile. \"It's just ... all so unexpected! Um ... how ... was finding out about it for you?\""
    "Kyouko blushed at that, and looked to one side. \"W...well,\" she started hesitantly. \"Um, in my case it was very different, really. You got to experience it and see someone else's ... ability, so....\" She trailed off with a shrug, glancing around at the other students."
    "Sasaki understood that well enough. So it was being kept a secret ... and she was one of the few who were allowed 'inside,' so to speak."
    "\"This is all very exciting!\" she exclaimed, prompting Kyouko to give her hand a reassuring squeeze."
    "It didn't take long to reach the clubroom, though she found Kyon standing outside, raising a hand to Koizumi in greeting. \"Not ... going in yet?\" Kyouko asked curiously."
    "\"Er, Mikuru or Kanae are changing,\" he explained, before frowning. \"Not sure which one, actually.\""
    "\"Changing?\" Sasaki wondered. \"Are we going to need our gym uniforms?\" She'd brought hers, but didn't have physical education that particular day."
    "\"No, it's--\""
    "\"Come in!\" Haruhi called from inside."
    "\"Ah, well, maybe it's better to show than explain,\" Kyon sighed, offering a somewhat lopsided smile, as Haruhi wrenched the door open proudly, her eyes tracking to Kyon, and then Sasaki before she nodded happily and gestured inside the room."
    "Sasaki blinked, mildly taken aback to see Kanae in a rather adorable stewardess uniform, and Mikuru in a charming maid costume. \"Oh, my!\" she couldn't help but exclaim. Really, that was insignificant compared to something as amazing as time travel, but she was surprised that a club could get away with such things. Well ... why not?"
    "She allowed herself to be ushered in with the others, and they all managed to fit around the table, though just barely."
    "\"Membership has swelled, hasn't it, Haruhi?\" Kyon prompted."
    "\"We've done much better than I expected,\" she agreed. \"Now, let's see ... so, you understand about the paranormal now, Sasaki-chan?\""
    "\"Er, yes,\" Sasaki allowed, unable to keep from leaning toward Kyon. He caught it and shifted his chair a bit closer, giving her a reassuring smile and a half-hearted shrug, as though to say, 'What can you do?' before he put one arm about her shoulder."
    "That prompted Kyouko to blink and cock her head slightly to one side, frowning."
    "\"It's still ... rather astounding,\" she admitted. \"Um, what are the mechanics of time travel, anyway?\""
    "\"No idea,\" Kyon answered absently. \"I mean, I know what to do, and I seem to have avoided causing a paradox so far, but how it works is a total mystery to me -- it's Mikuru who does the time traveling.\""
    "The maid blushed at that, even as she set teacups out before Sasaki and Kyon. \"Um ... since it hasn't yet been discovered in this time, I can't explain it, because it's classified,\" she said apologetically."
    "\"That does make sense,\" Sasaki allowed, nodding slowly."
    "\"Kyon's supposed to be really good at handling the logistics of time travel, though,\" Haruhi supplied. \"Last weekend was a first for both of us.\""
    "\"Most of us!\" Tsuruya corrected. \"I thinks only Kyon-kun and Mikuru-chan got to do it before!\""
    "\"Yuki-chan, too,\" Kyon offered. \"I'm sure Mikuru remembers that, though.\""
    "\"Ah, eh,\" the ... time traveler? Sasaki supposed she had to admit that much. The time traveler blushed and looked uncomfortable, grimacing. \"That wasn't a fun trip at all,\" she mumbled, shivering faintly. \"I don't like seeing Kyon-kun get injured....\""
    "\"Injured?\" Sasaki asked worriedly, turning to look at him ... which was probably silly, since he seemed fine at the moment."
    "\"That story might be better at some different time,\" he said with a grimace, shaking his head. \"I actually meant about Tanabata, but we can explain that later. Right now, I think we need to make sure you're okay with understanding all of this.\""
    "\"It's still a lot to take in,\" Sasaki agreed."
    "\"Well, you know that time travel exists. So, you understand that there are other, equally amazing things, right?\" Haruhi prompted."
    "Sasaki hesitated, then said, \"So, Fujiwara is really another time traveler? And Kyouko-chan is really an esper?\""
    "\"I-- That's right,\" Kyouko agreed, nodding uncertainly. \"Um ... where to begin....\""
    "\"Easy!\" Tsuruya exclaimed with a chuckle. Pointing at Koizumi, she said, \"Esper,\" before moving her finger to Kanae. \"Slider.\" Mikuru was indicated next. \"Time traveler.\" Haruhi was the next target. \"Part-time-magical girl.\""
    "Haruhi pouted and blushed at that, muttering, \"It's a bit more complicated than that....\""
    "Tsuruya giggled, but quickly bit it back, pointing to Yuki next. \"Um, Yuki-chan was created by some aliens -- they seem to be jerks to Kyon-kun and Yuki-chan, but she's really neat! She's not here right now, but Kuyou-chan is a sort of alien being as well, and so is Ryouko-chan -- I'm no one special, though!\""
    "\"Just the heir to the local crime syndicate,\" Kyon agreed with a drawl."
    "\"So ... that would make me very fortunate, to be the one regular person allowed into such a group!\" Sasaki exclaimed."
    "Kyouko bit her lip at that and looked to one side."
    "\"I thought I was the regular person,\" Kyon said with a frown. \"Though ... I guess I'm a part-time time traveler -- even my little sister got to be a magical girl for a while. Well ... sort of. I guess Sasaki can't see Ryouko yet?\""
    "\"Toggle has not yet been adjusted,\" Yuki said quietly."
    "\"Er, well, I can't think of anyone else your age who fights yaku-- Ah, that is ... the members of a boryokudan the way you do,\" Sasaki countered. \"But, if you're a regular person who's been helped by others, I'm more normal than you are, aren't I?\""
    "\"You don't know the half of it,\" Haruhi mumbled. \"You're so normal it could be a superpower ... and sort of even is. I never really heard Kyouko's story, though, so I think we have time for that before the meeting tonight, don't we?\""
    "\"Er, okay,\" Kyouko agreed hesitantly, glancing between Koizumi and Haruhi, biting her lip anxiously. \"Um ... it was about four years ago, that I suddenly woke up and knew that I had a power,\" she explained hesitantly. \"There, uh, was a lot of confusion at the time. I got my powers and knew how they worked, but didn't know why I was chosen.\""
    "\"This is, incidentally, also the story of how I got my powers,\" Koizumi supplied, smiling."
    "\"Taking notes from Kyon's book and letting someone else do the heavy lifting, huh?\" Haruhi chided with a smirk."
    "Shrugging, Koizumi's smile widened to a grin as he teased, \"I've learned from the master!\""
    "\"Is laziness a super power?\" Kyon wondered."
    "\"If it is, Sempai, you aren't very good at it,\" Kanae giggled, freshening his tea. \"You're too busy doing rescues to be really lazy!\""
    "\"Well, it's something to aspire to.\""
    "\"Hey, let the espers finish their story,\" Haruhi chided."
    "\"Um, well ... at that time, all of us espers tried to reach out and find others who were the same as us,\" Kyouko continued, fidgeting, until Koizumi took one of her hands. \"We, uh, used the internet and were vague about it, but eventually figured it out. So, we all came together to talk about the girl who gave us that power."
    "\"Um, but once we started meeting it and talking about it, the issue became confusing,\" Kyouko explained, blushing faintly. \"About ... half of us thought our powers were granted by one person. And the other half felt that, well, someone else gave us that power. So we ... broke apart and disagreed on how to handle things."
    "\"It didn't help that we had gotten our powers from different people, and some of us ... thought that it would be like some sort of manga where we needed to fight because we were from different factions. That ... ended up causing rather a lot of trouble, later.\""
    "\"So someone is a catalyst to allow espers to have their powers?\" Sasaki asked, intrigued."
    "Kyouko nodded tightly."
    "\"What are your esper powers?\" Sasaki prompted, smiling. \"As remarkable as this is ... can I see them?\""
    "\"Er, that's ... more difficult,\" she said with a frown."
    "\"There are two specific powers that most espers have,\" Koizumi explained. \"One of them is a mental connection to the one who provided their powers originally, and the other is the ability to enter and manipulate a specific space that the ... source person generates.\""
    "\"I see! Who are the people who make these spaces, then?\" Sasaki wondered, tapping her lower lip thoughtfully."
    "\"For myself, it's Suzumiya-san,\" Koizumi explained. \"Though ... my circumstances have actually changed, and I don't have a specific link to her any more.\""
    "Sasaki looked at Kyouko expectantly, who blushed strongly and stared at the table. \"For me, um ... the connection ... is to you, Sasaki,\" she mumbled. \"I ... tried to tell you this once before....\""
    "Sasaki blinked slowly at that, trying to absorb the concept. \"Somehow, I bestowed esper powers on people?\" she asked, mildly incredulous."
    "\"I know, right?\" Haruhi grumbled. \"How weird is that!\""
    "\"And ... another space ... a mental connection....\" Sasaki trailed off, paling. \"W...what am I thinking now?\" she pressed."
    "\"I-- I don't get specific thoughts,\" she explained, shaking her head. \"Just emotions, and only strong ones. So I know, um ... your feelings about....\" She glanced at Kyon and quickly cleared her throat."
    "\"Ah, didn't Koizumi-san explain that to you?\" Kanae wondered."
    "\"When the topic came up, so did certain other ... very distracting factors,\" the male esper replied evasively, studying the ceiling."
    "Sasaki felt her face begin to heat up. She wanted to protest that it was all nonsensical, but somehow, the idea of Kyouko experiencing a fraction of her emotions when she.... And Kyon.... And...."
    "\"...oh, my,\" she managed. \"This....\" She wasn't certain how to handle that."
    "Kyon shifted in his seat, moving his arm, and before Sasaki could fully panic he took Tsuruya's prompt (which was fairly impressive in its own right, since it was merely a pointed stare), and lifted Sasaki from her seat to rest in his lap again. She felt herself relaxing, even if it was a tiny bit embarrassing ... not enough to want to go back, at any rate."
    "\"Um ... Kyon-kun ... I think you should say the next part to her,\" Mikuru suggested anxiously."
    "Sasaki felt her head spin. There was more?"
    "\"The reason for this,\" Kyon said slowly, \"at least, as I understand it ... is that you have a special power.\""
    "Sasaki had to admit, \"Kyouko ... mentioned this once,\" a bit shakily."
    "\"But so far, you've only ever really used your power to cancel the effects of other paranormal powers,\" Kyon finished."
    "Sasaki blinked at that, looking up, even while she let herself ... well, being honest, cuddle with Kyon. He was looking to one side and blushing faintly. She wanted to protest this most of all, but...."
    "\"That ... completely explains why I would be so valuable to be kidnapped and used against you,\" she allowed faintly."
    "\"So ... you're okay?\" Haruhi interjected worriedly. \"You understand all this now?\""
    "\"I think so,\" Sasaki managed, feeling a bit distant. \"But it strikes me that it would be a very good time to faint right now, if it's not too much trouble.\""
    "She was certain that someone else said something, then, but she was safe in Kyon's arms -- she wouldn't fall and hit her head, or anything like that. And even if she was holding together, and comfortable, and surrounded by friends.... The vague certainty that things were going to be okay, somehow, even if she was overwhelmed, was her last thought before everything became comfortable, welcoming blackness."




