label OB_6:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 049 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
   
    "After completing the plan to frame Takahashi, Haruhi was obviously excited and anxious — unable to keep from talking about it."
    "\"I can't believe it worked so easily,\" Haruhi said in dismay. \"I mean— I think you probably could have done the entire thing by yourself, but after Kyon did all that, I couldn't just sit around and let you take care of things! What kind of leader would I be if I did that?"
    "\"But it's so one-sided ... Kyon's coat's disguise is perfect — looking like Takahashi to frame her was so easy I almost feel bad about it. She really deserved it, after all, but this kind of power ... I'm glad that Kyon's responsible with it. That's nothing compared to you disguising yourself like Kyon's sister, and us getting caught on some security cameras downtown, though!\" she continued, still agitated."
    "Yuki tilted her head slightly to one side, considering Haruhi's reaction."
    "\"I mean,\" Haruhi continued, \"you were able to edit the timestamps on the videos too — which I guess would be a lot harder for me, but this much ability to make people look guilty for things they didn't do.... That's kind of scary, you know? I...it ... was actually kind of hard to watch from inside this invisibility spell when we led the police to Takahashi and they hauled her away."
    "\"I can't feel too bad, but ... listening to her say she didn't do this part, even if she's guilty of worse stuff....\""
    "In Yuki's perception, she was guilty of enough other things that the idea of implicating her for a crime she did not actually commit seemed acceptable. Really, considering that it had led to Kyon being endangered, Yuki would not have protested implicating her for more or worse—"
    "Still, the framing should satisfy the requirements that Tsuruya had related to them — of ensuring that Takahashi wouldn't work with children again. That the instructions had originated from a time traveler that caused Kyon trouble was of little import, given that both Tsuruya and Kyon agreed with them."
    "Haruhi heaved an unhappy sigh and hugged her arms to her chest. Blinking, Yuki recognized what was wrong; it wasn't the first time she'd seen those cues from Haruhi, after all. Wordlessly, she stepped closer and wrapped her arms around Haruhi. The girl stiffened briefly, then relaxed, hugging Yuki back."
    "Amazing how much significance could be sent by the simple gesture of an embrace."
    "\"You're stressed about this, too,\" Haruhi recognized, once they were alone, Yuki leading the Brigade chief out the back of the building — still invisible — and to the car where Tsuruya awaited."
    "\"Yes,\" Yuki agreed, dismissing the invisibility effect as they climbed into the limousine. She was only mildly surprised to find herself captured immediately in another hug from Tsuruya, next to the equally pleased Haruhi. All in all, arranging 'witnesses' to correspond to the edited footage and staging the calls to the police had taken them until the early evening."
    "\"To the hospital!\" Haruhi ordered tiredly, slumping back into the seat, one arm still around Tsuruya's shoulders, the other around Yuki's. \"Heroic secret service isn't so bad, I guess. I never thought I'd want to take a back seat to Kyon on heroism....\" She hesitated, then shrugged, pulling the other girls closer to her."
    "\"Kyon is very good in fights — especially because he doesn't like to fight,\" Tsuruya answered, nodding. \"Knowing that Yuki-nyan has trained him, I can say honestly — Kyon-kun has always had the heart of a martial artist, even if he's only lately recently learned the skill!\""
    "\"That's for sure,\" Haruhi agreed, giving Yuki an additional reassuring squeeze. \"I bet even people who knew Kyon before we did would think that—\""
    "The brigade chief twitched slightly, then twisted her arm free of Yuki's shoulder and thrust it into her pocket, pulling out her phone and answering the vibrating device with an enthusiastic, \"Hello~!\""
    "It did not take analysis of the call's source to understand why Haruhi's pleased expression shifted to one of displeasure, but seeing her distraught so, Yuki checked anyway. Unsurprisingly, the other caller was none other than Sasaki — the one who seemed to unsettle Haruhi the most anyway."
    "Unsure of what else she could offer, Yuki adjusted her position and gave Haruhi a reassuring hug, even as Haruhi squirmed a bit, tapping a button to shift the call to speaker-phone, then dropping it in her lap to hug Yuki and Tsuruya both back."
    "\"...ondering if everything was okay,\" Sasaki was just saying. \"However, if you're able to be of such good cheer, then I suspect that Kyon must be alright!\""
    "\"Y...yeah,\" Haruhi allowed uneasily. \"Kyon's absolutely fine.\""
    "\"That's reassuring!\" Sasaki replied, almost an exclamation. \"I'm pleased to hear it — and if he's well, then, you are, too?\""
    "\"Well enough,\" Haruhi allowed, grimacing. She looked about to say something before biting her tongue and heaving a quiet sigh. \"Yeah, Kyon's absolutely fine — Nonoko-chan, too.\""
    "\"I'm glad to hear that! Well, I'm afraid I truly only have a few minutes before my cram school starts— Still, thinking we must be in very similar situations, perhaps we could meet up afterwards to speak of things?\" she suggested. \"If you're up for it, that is....\""
    "\"T...that's fine,\" Haruhi agreed, sighing softly. Then she shook her head, straightening up and reaffirming her resolve. \"I— I said you could call me, couldn't I? So, of course this is fine! Let's.... Ah, your friend is still at the hospital, right?\" she asked, giving Tsuruya a questioning glance."
    "Her expression worried, Tsuruya nodded quickly in answer."
    "\"That's true!\" Sasaki agreed. \"I was worried about Kyouko-chan, too, of course— And it wouldn't hurt at all to see Suou-san, would it?\""
    "Yuki pondered the implications of Sasaki meeting with Kuyou in her current state, unable to avoid looking at Ryouko. The smaller interface was in 'sleep' mode, helping recharge Kyon's depleted defensive mechanisms more quickly. As it was, the tiny form was almost being squished between Yuki and Haruhi — not that she would even notice, in her current state."
    "\"If she's there,\" Haruhi agreed with a shake of her head. \"Alright, so we'll meet up later tonight, at the hospital, since it's a safe place?\""
    "\"Indeed! I should go to my class now— As soon as it's over, I'll rush over to meet you as quickly as I can! Take care until I can meet with you again, Suzumiya-san!\" Sasaki then disconnected before Haruhi could answer."
    "The brigade chief sighed again, slumping further back into the seat. \"Kyon had better appreciate what I'm doing for him,\" she muttered."
    "Wordlessly hugging Haruhi tighter, Yuki nodded in agreement when Tsuruya noted, \"If he doesn't, we'll make sure he does, Haru-nyan!\""
    "* * *"
    "The strange sense of safety and comfort that she'd experienced since Takahashi's plan had fallen apart didn't fade in the slightest. Except, she realized, when Koizumi had left her side briefly."
    "She wasn't able to ignore the reason for it, and she tried to chide herself for being so silly and childish. That didn't prevent her from trying to straighten herself out in her hospital bed, bemoaning the lack of a chance to properly wash her hair when the other esper returned. He looked worn and tired in the late afternoon light, but stepped into her room with a knock on the door."
    "She supposed she really should be doing more with her time than hiding from the world and staying in a hospital bed all day. Instead of jumping out and getting to it, she found herself sinking into the pillows and tempted to pull the blanket up to her chin to hide when the handsome taller esper gave her a polite smile and nodded."
    "\"Are you feeling well?\" he prompted. \"And being treated well, too, I hope?\""
    "\"Y...yes, to both of those,\" she admitted shakily."
    "She didn't like the way her heart lurched at his tired smile. \"I'm glad to hear that, then,\" he said with a sigh, one hand going to his chest, rummaging inside his blazer for a moment before he produced a phone and checked the display. Seemingly pleased with what he saw, he put the device back and then settled down in a chair beside her bed, uninvited."
    "\"Um,\" she started, when he didn't say anything. \"D...did you want to ask me some questions?\" she offered, feeling a sudden need to provide something to him — after all, as she understood things, he was the one who prevented the worst possible outcome, thanks to her mistake. Oh, it was some small way to make things up to Kyon, and Sasaki, too...."
    "He shook his head slightly. \"No,\" he admitted, \"at least, not relevant to our cause. Rather, based on our previous discussions, I thought it might be nice to simply visit— Thinking of the things that Kyon has said, I imagine it might reassure you to see a friendly face.\""
    "She felt as though he'd somehow shoved her out of the bed and to the floor, and actually felt her mouth drop open in shock before she caught herself. \"Y...you ... don't hate me?\" she squeaked out in amazement. \"Ah— I mean, that is—\""
    "He cut her off with a quick shake of his head. \"As myself, you were a servant to greater powers. It simply seems that those you followed use that power unwisely. Being entirely honest, I cannot say I have done any better, until I chose to follow Kyon-kun's lead over those I served before.\""
    "She couldn't help but wince at that reminder."
    "\"Ah — but then, given Sasaki's relative position, I suppose this would never have been a realistic option for you. I did not mean to say something in a way that felt like a judgment!\" he apologized with a shake of his head. \"Today has been a bit busy, actually; I was hoping to share a relaxing moment of calm with you.\""
    "She felt her cheeks flame as she nodded at him, managing a weak smile. \"I would like that,\" she said quietly."
    "In fact, she so enjoyed the peaceful discussion she had with him that time seemed to slip away into a happy, fuzzy haze, ending only when she realized it was dark outside— Koizumi turned at a knock at the door, both espers looking with surprise as Sasaki poked her head in and waved."
    "\"Hello, Kyouko-chan,\" she said easily, startling Kyouko with the tiniest surge of ... was that.... The esper almost couldn't believe the tiny streak of jealousy she felt from the other girl! She'd never noticed Sasaki to be envious of ... anything! What could possibly prompt such a reaction from the girl Kyouko so admired?"
    "\"Um, hello, Sasaki-san,\" Kyouko managed, blinking in surprise."
    "\"It's late,\" Koizumi realized belatedly, shaking his head and checking his phone before Sasaki could reply. \"Ah, it seems I have a meeting shortly— I apologize. Sasaki-san, have you eaten yet?\""
    "Her face flushing slightly, Sasaki admitted, \"I haven't, yet— I would guess by that question, you and Kyouko-chan have not, either?\""
    "\"Correct!\" Koizumi returned, nodding comfortably at Sasaki as he rose from his seat. \"Your attendant must have assumed by my presence that you didn't wish to be disturbed; in such a case, would an offer to collect something from the cafeteria be unwelcome? This applies to both of you, naturally — and our allies own this building, so please don't even consider the expense to be an issue.\""
    "\"W...whatever you find, then,\" Kyouko mumbled, her face reddening further. Koizumi was offering to fetch her {i}dinner{/i}?"
    "\"If it's not inconvenient, I'm finding that I've been a bit unsettled by recent events,\" Sasaki began apologetically, one hand going to her stomach. \"Some soup would not be amiss, if it's not too much trouble.\""
    "\"Understood; I should return shortly, then,\" the other esper declared, giving each of the girls a bow before stepping outside of the room."
    "Kyouko felt another tiny surge of that strange emotion from Sasaki, then shook her head to clear it. \"U...um, Sasaki, is everything ... alright?\" she asked worriedly."
    "\"As 'alright' as things can be,\" Sasaki answered in amusement, taking the seat that Koizumi had just vacated, one hand smoothing her skirt. \"My friend is in a hospital, and I've heard that Kyon-kun was in some danger, today.\""
    "\"Eh?\" Kyouko managed, surprised at the tiny, quickly smothered spark of jealousy she felt from the other girl. \"K...Kyon was in trouble?\" Koizumi had seemed so calm, though!"
    "Sasaki shrugged, smiling softly. \"If his allies are so unconcerned, then he must be fine ... though, I expect Suzumiya-san to clarify some things for me— Perhaps if we are fortunate, we will even have a chance to see him!\""
    "Kyouko wasn't certain how to feel about that ... though, being this close to Sasaki, she was starting to feel the other girl's emotions more clearly. What an unsettling sensation — Sasaki's vague longing, making Kyouko shiver to realize it reflected ... what she felt for Koizumi? Her eyes widened and she stared into her lap in consternation."
    "\"Hmm.... Kyouko-chan, I don't mean to pry, but ... we are friends, and I do wish for the best for you. Is it ... that you have feelings for Koizumi-kun?\""
    "\"M...maybe ... a little,\" the esper managed, feeling her face redden as she looked at Sasaki shyly."
    "\"Well, then I'm happy for you!\" Sasaki lied, smiling. \"Only ... I do worry— I must ask you to search your heart and ensure your feelings are genuine, not merely a reflection of gratitude for him saving you.\""
    "\"T...that's silly,\" Kyouko protested, feeling her face burn as she hunched over, turning away from Sasaki. \"I...it's not.... I...if it were that, wouldn't it be for Kyon-san, since he's the one who saved my family?\" She wondered if that were too much of a protest...."
    "Sasaki's lips twisted in a pained smile before she settled back into her seat. \"I apologize, then,\" she sighed. \"I had an ... unfortunate encounter with a former middle school classmate. My nerves are a bit frayed, and I expect to speak with—\""
    "She cut off when there was another knock on the door, and Kyouko blinked in surprise to see Haruhi — of all people! — peeking around the frame with a weak smile of her own. Behind her was the still form of Kuyou, her eyes on some distant point."
    "Kyouko wasn't sure why, but Sasaki spent a moment seeming stunned, another flare of that alien jealousy sparking at the sight of — of all things — Haruhi's over-sized coat."
    "\"Ah, Suzumiya-san!\" Sasaki greeted, her face pinking slightly as she recovered. When Kyouko had a moment to clear her mind and think about things.... The same 'dangerous' and 'unstable' girl that she had been trying to take the power from in the room with Sasaki? The one she had wanted to give that power to?"
    "\"H...hey,\" Haruhi returned, nodding, then stepping in. Kuyou glided smoothly around her, stopping by Sasaki's side, though her gaze was still distant. \"Um,\" Haruhi started, shaking her head, turning her attention to Kyouko."
    "The esper was struck silent, suddenly nervous. Was Haruhi going to be upset with her for her involvement? She suddenly wished for Koizumi's reassuring presence again, and clung to that thought like a lifeline. If Haruhi were even a fraction as reasonable as the other esper, surely Kyouko wouldn't have anything to be afraid of?"
    "After a moment, Kyouko realized that the other girl was searching for something to say — she probably still resented Kyouko's involvement in things, after all.... The esper hunched into herself slightly, and Haruhi quickly shook her head, turning her gaze out the darkened window."
    "Breaking the awkward silence, Sasaki asked, \"Suzumiya-san, you said that Kyon is doing well?\""
    "\"Yeah,\" she allowed, shaking her head. \"Um, we should—\" She cut off with a mild start on seeing Koizumi pace through the door, bearing a tray laden with three bowls of udon."
    "\"Ah,\" he started, taking in the quartet, then looking at the tray with a slight frown. He quickly dismissed it, shrugging. \"Suzumiya-san, is it time for the debriefing, then?\""
    "\"Kyon's still ... talking with his parents,\" Haruhi said with a mild wince. \"I didn't know you hadn't eaten, Sasaki— Neither have I. Um....\""
    "\"Well,\" Sasaki quickly suggested, rising from her seat, \"why don't the pair of us go the cafeteria, then? We can leave Kyouko-chan, Kuyou-chan, and Koizumi- kun to relax for a bit?\""
    "\"Y...yeah, okay,\" Haruhi allowed, nodding."
    "\"Well—\" Koizumi began, before Haruhi cut him off with a brief shake of her head."
    "\"This is fine,\" she insisted. \"Sasaki and I ... really need to talk.\""
    "Kyouko exchanged a glance with Koizumi, surprised to see a brief reflection of the worry she felt before he smoothed it over with a mask, bowing to Haruhi while carefully balancing the tray of soup. \"Understood,\" he said, nodding."
    "Once both of the espers had watched their respective ... what was the word for that, anyway? Kyouko realized she didn't really have a good definition for it, but was distracted from the thought by Koizumi turning to Kuyou, cautiously asking, \"I hope that udon isn't a problem?\""
    "Kuyou's eyes shifted focus, dragging through that distant point and instantly locking on the tray that Koizumi set on Kyouko's bedside table. \"Noodles,\" she pronounced, the slightest hint of annoyance flicking across her expression before she shook her head."
    "* * *"
    "While she was nervous, she was not the type to shy away from things — facing them head-on was her preference, and this time should be no different. Yes, Sasaki could be dangerous to her, but all things considered ... Sasaki's presence should also prevent the worst things she needed to worry about. After all, they were surrounded by allies at the hospital."
    "\"Ah,\" Haruhi said belatedly, shaking her head, looking at Sasaki sidelong. For her part, the ... what to call her? She cut that thought off before it could continue; she wouldn't want to be labeled herself, so why do it to the girl she was supposed to be trying to befriend?"
    "\"Let's save the more important things until after we've gotten something to eat,\" Haruhi suggested."
    "\"That sounds fine by me,\" Sasaki agreed. \"Ah, then, in the meantime...?\" She trailed off, tilting her head slightly to one side, offering a hopeful smile."
    "...what {i}could{/i} they talk about, Haruhi wondered?"
    "Seeing that Haruhi couldn't find a topic, Sasaki posed, \"In light of everything, how are Kyon's study habits? Is he still as reluctant to do his homework as he used to be?\""
    "Recalling Yuki's explanation of the final two weeks of the last summer, Haruhi winced. \"You don't know the half of it,\" she said earnestly. \"That guy is so lazy about his assignments!\""
    "Sasaki giggled softly at that, looking slightly relieved. \"I suppose I'd worry if he changed too much, then,\" she allowed. \"Hmm.... Does he study with his, ah, fiancee?\""
    "\"Not so much,\" Haruhi admitted. \"Since we're in the same class together, we usually end up studying.\""
    "\"Oh,\" Sasaki answered, her smile fading. \"Is that ... difficult for you?\""
    "Haruhi nearly tripped at the question, managing to mask it with a quick turn as the pair stepped into the cafeteria. \"Why would it be hard?\" she asked, confused. \"I mean, Kyon's not dumb — just lazy. Getting him to study is usually enough ... plus, his mom said if his grade goes below ninety on any test, she'll pull him from the club. That helped motivate him quite a bit.\""
    "\"Oh,\" Sasaki said again, one hand rising to touch her lower lip thoughtfully for a second, before the pair found their way into the cafeteria line. Haruhi took a katsu sandwich, while Sasaki took a tray with another bowl of udon."
    "Once they were clear of the line, and Haruhi was leading Sasaki back through the halls, toward the elevator to the top floor conference rooms, Sasaki commented, \"Somehow, I had thought that Kyon might go to cram school. I suppose that would interfere with his.... It's a job, then?\""
    "Haruhi nodded, sighing. \"If he gets pulled from the club, it'll be to go to cram school,\" she admitted."
    "\"I see,\" Sasaki said quietly. After that, they stepped into the elevator, just the pair of them. Once the door was shut and Haruhi had pressed the button for their desired floor, she asked, somewhat hesitantly, \"In ... some ways, might that make things ... easier for you?\""
    "Haruhi blinked, turning to stare at Sasaki's earnest expression. \"Huh?\""
    "\"W...well, I mean ... since you have such feelings for him,\" she clarified. \"But then— Maybe I simply lack your strength.\""
    "Haruhi nearly dropped her plastic-wrapped sandwich in surprise at the remark."
    "\"This probably sounds foolish,\" Sasaki confessed, offering a wry smile. \"You probably wouldn't recall me ... my hair was longer then, but did you know that we attended the same elementary school?\""
    "This time, Haruhi {i}did{/i} drop her planned meal."
    "Sasaki looked down in consternation, biting her lip at the tray that took two hands to carry, while Haruhi knelt and fumbled for her dinner. As she rose, the elevator chimed, and the door opened. Haruhi wasn't certain, but she thought she saw Sasaki eying the 'stop' button before that happened."
    "She shook her head to clear it and gestured Sasaki into the hall, toward the conference room they usually used. \"You're saying we knew one-another in elementary school?\" she asked uncertainly, as Sasaki looked across the large room before choosing a seat."
    "\"You probably wouldn't recognize me,\" Sasaki allowed, folding her hands together and frowning. \"I did cut my hair since then, as I said— And we never shared a class. I ... somewhat admired you from afar, actually, and hoped that we'd be in the same class at some point. Unfortunately, across the years, that never came to pass, and when I selected my middle school, well ... you had gone elsewhere.\""
    "Haruhi blinked in astonishment — the figure that she was so scared of had known her since {i}elementary{/i} school? She thought back a moment and realized ... Sasaki had known her distantly when she was in school, but before Haruhi's perspectives had shifted."
    "What kind of impression did she have of Haruhi, anyway?"
    "\"That's amazing,\" she finally allowed."
    "\"Perhaps not statistically,\" Sasaki allowed, breaking her chopsticks apart and poking at her bowl of soup briefly."
    "Haruhi nodded thoughtfully, then unwrapped her dinner before rising from her seat to move to the tea-set sitting between two of the smaller side conference rooms. Once she'd set a cup of tea before each of them, she took her seat again. Somehow, having tea and a katsu sandwich with Sasaki just felt like the strangest thing she had ever done — which was the most bizarre thing to consider in the {i}world{/i} considering how she'd spent what should have been her lunch break!"
    "\"Though,\" Sasaki remarked thoughtfully, after Haruhi had taken a few bites of her katsu, \"I find your ability to remain near Kyon and restrain yourself quite admirable, still!\""
    "Haruhi set her food down, before she choked herself in surprise at whatever Sasaki was going to say next. \"What ... does that mean?\" she asked cautiously."
    "Sasaki blushed slightly, and ducked her head. \"I ... am not used to admitting such things.... Well, I'd still like us to be friends, though— As it is, we both seem to have certain unrequited feelings for him. With that common ground, even though I am a bit new at this, I'd like to offer what help I can for you to handle it—"
    "\"I suppose in my case, it's a sense of regret — the thought that I acted too late and lost a chance I once had. Really ... I had thought I'd lost that chance to you, not Tsuruya-san. Still, it does seem you're much better at coping with unrequited love than I....\" Trailing off, the girl offered an apologetic smile. \"I apologize; this is a bit strange for me, so I'm rambling quite a bit.\""
    "\"I...it's fine,\" Haruhi mumbled, wincing at the deception. Though, with that much being said, she had to acknowledge, \"We ... do feel the same way for Kyon, after all. So, you're right about that.\""
    "Sasaki didn't know the full details, of course, but that ... might make being a 'friend' difficult. Realistically, it was only Sasaki who needed help with such things— But as soon as Haruhi thought about why, she felt her stomach churn."
    "\"Um, and ... likewise,\" she forced herself to say. Wasn't that what she'd wanted, anyway? And being close to Sasaki, she would by in the ideal position to prevent her from getting too close to Kyon, wouldn't she? Somehow, thinking of Sasaki's earnestness ... it didn't seem the brilliant plan it had so very recently."
    "Sasaki's relief was visible as she beamed Haruhi a genuine smile. \"I'm glad to hear that!\" she allowed, settling back into her chair, one hand briefly pressed to her chest. \"Even more than being allies, being your friend ... well, I'm glad for that, then, Suzumiya-san. I only wish that I had more to offer you in exchange.\""
    "\"It's fine,\" Haruhi said again. She didn't like the feeling she had, suddenly, but it wasn't like there was much she could do about it, was there? Well ... she supposed there was {i}one{/i} thing...."
    "Sasaki nodded wordlessly, sipping at her teacup."
    "\"Um, I'm sorry I'm distracted, today was ... kind of hectic, and I can't ... talk about all the details, yet,\" she said honestly. \"Um ... but— You know, why don't you check in with Kyon after you finish eating? I'm sure you haven't seen him, and ... that would surely help settle you, wouldn't it?\""
    "\"For me, yes,\" Sasaki agreed eagerly. \"Ah, but ... I'm not as strong as you in that regard, Suzumiya-san.... Is it too much to ask for you to be there for support, as well?\""
    "\"Of course,\" Haruhi agreed miserably, forcing a smile."
    "\"Then I am in your debt! Only— Are you well? You should eat, too— If you're anywhere nearly as busy as Kyon, don't you need to keep your strength up?\""
    "\"That's true,\" she sighed, picking up the unappetizing sandwich and forcing herself to take another bite."
    "\"Wouldn't Kyon be worried to see you unwell?\""
    "\"Yeah,\" Haruhi agreed, after swallowing. That was truer than Sasaki realized...."
    "* * *"
    "Sitting in her bed Nonoko watched her brother and her parents face off. She knew adults could sometimes be difficult, but this was something {i}entirely{/i} different. Her mother had lost the usual stern confidence she had when admonishing either of them, and her father had — twice! — quietly urged her to quiet down and reconsider what she was saying."
    "But then ... Kyon was not usually so stubborn."
    "\"I just want to stay here with Imouto tonight,\" he said, shaking his head. \"I know ... that Tsuruya-sama has given you a lot to think about, but after today....\" He shrugged at that, giving her a warm, encouraging smile."
    "She giggled at him, trying her best disarming grin in return. As usual, her mother didn't buy it for a heartbeat, judging by the hard glint in her eyes. Still, when Nonoko's father gently nudged the woman's shoulder, she heaved a sigh and shook her head anyway. \"A...alright,\" she allowed. \"But ... we really {i}must{/i} speak about this, Kyon!\""
    "\"In the meantime,\" her father said quickly, before her mother could continue, or Kyon could interject, \"your mother and I have a lot to discuss ourselves. Kyon, we're, er, counting on you to keep watching out for your sister.\" He looked like he thought the words leaving his mouth had a funny taste after he finished saying it."
    "It was still enough for Nonoko's mother, as shaken as the woman was."
    "Nonoko had to wonder ... did that whole exchange ... mean Kyon was an 'adult' now, too? Or becoming one? She hoped it wouldn't interfere with his magical guardian status!"
    "When her mother came over to give her a hug, Nonoko gladly hugged her back, waving as her parents left with one last glance at her and her brother. For Kyon's part, he relaxed very slightly, bowing his head and heaving a sigh once the pair were out of earshot."
    "\"Everything's going to be okay, right?\" she blurted out a minute later. Things had gotten amazing, and strange— But hadn't the day been saved?"
    "\"I hope so,\" he agreed, raising his head and giving her a smile. \"I'm just glad you're okay....\""
    "She felt her scalp tingle where a few hairs had been pulled out by a projectile in the battle and could only giggle in embarrassment when he gently patted her head."
    "He settled back into his seat again, sighing. She was still trying to decide what to say when she heard voices in the hallway, perking up in surprise when Haruhi stepped through — followed by the girl who had stolen Kyon's smile at the end of middle school! She gasped in recognition of the other girl, her eyes widening."
    "\"You!\" she exclaimed, pointing, before the girls could introduce themselves or say hello, prompting her brother to whip his head around, rising to his feet and sliding between her and the other girls protectively."
    "He froze for a second, then looked abruptly abashed, relaxing his stance and scratching the back of his head nervously. \"S...sorry,\" he managed, stepping to one side and running a hand down his face. \"Um ... I've been a bit ... on- edge lately.\""
    "\"I can imagine,\" Sasaki replied, seemingly unable to meet Nonoko's glare, ducking her head, her expression falling."
    "Wait ... had her brother already broken the other girl free of dark general control? \"Haru-nee!\" she exclaimed in surprise. \"Has this one joined our side?\""
    "\"Absolutely!\" Sasaki affirmed, looking up and meeting Nonoko's eyes— She felt almost stunned by the nearly desperate hope in the older girl's eyes. \"That's— That's my dream, and my goal; to be an ally for your brother and his friends, and to ... to make up for what mistakes I may have made in the past!\""
    "Nonoko lowered her accusing finger and blinked in surprise, as Haruhi winced slightly, for some reason."
    "\"I wish to be a helpful presence, like Suzumiya-san, here,\" Sasaki concluded."
    "\"Uh, right,\" Kyon mumbled belatedly, scratching the back of his head with a look of confusion."
    "\"Yeah,\" Haruhi agreed in a subdued voice. \"Imouto, Sasaki-san is our ally, too, it's just, um.... It's just that she's only starting out, so doesn't know ... everything yet.\""
    "\"And I won't push on that count, either,\" Sasaki agreed. \"Ah, but— I'm glad to see you look healthy, Kyon! And you, too, Imouto — you weren't hurt, were you?\""
    "Nonoko wasn't sure about this girl calling her 'little sister' ... but if she had Haruhi had her side, it must be okay, so she smiled at the name. Having more big sisters was great! She loved the way her big sisters all got along with Kyon! \"I'm perfectly fine,\" she said proudly. \"I didn't get hurt at all!\""
    "Kyon surveyed the room, spotting the two chairs, then shook his head slightly and hopped up to sit on the edge of her bed, gesturing to the free seats. Haruhi nodded, taking off Kyon's coat and draping it over the back of the nearest chair before collapsing into it. \"Today has been exhausting,\" she groaned."
    "Sasaki giggled, blushing with the same look in her eyes that all of Nonoko's other favorite big-sisters as she glanced at Kyon, then took the other seat. \"Ah, you're named Nonoko-chan?\" Sasaki asked in a hopeful tone. \"I'd like us to be friends, if that's possible.\""
    "\"Okay!\" Nonoko agreed without hesitation. \"Friendship is magic — the most powerful force ever!\""
    "\"Kyon's taught me that, as well,\" Sasaki replied, her smile widening."
    "\"Yeah!\" Nonoko cheered, scooting closer to her brother and glomping onto him. \"He forgets sometimes, even though he reminds everyone else!\""
    "Sasaki's eyes widened, and she fished her phone from one pocket, snapping a quick picture of Nonoko hugging her brother. Giggling to herself, she asked, \"It's a bit late, but with your permission, is it alright if I keep this picture?\""
    "Kyon shrugged, looking slightly baffled, glancing between Haruhi and Sasaki as though waiting for something to suddenly go wrong. \"So, uh...\" he falteringly started, before ending at a loss for words, able only to scratch his head in confusion."
    "\"If there's anything I can do to help you, or your sister, you'll let me know, won't you?\""
    "\"Of course,\" Kyon agreed after a moment, nodding."
    "Haruhi made a face at that, out of Sasaki's line of sight, then shook her head. \"Um, Sasaki-san has set out a plan for us to be friends, so we can ... work together to help you out better,\" Haruhi managed, looking slightly uncomfortable. She shook her head abruptly. \"Ah— But, today has been busy for you, right, Kyon? Let's go ahead and let you and Imouto have a chance to rest.\""
    "\"Yes, of course,\" Sasaki agreed, nodding, giving Kyon a hopeful smile before turning her attention back to Haruhi. \"I should thank you for the kindness you've shown me today— So, I am extraordinarily grateful to you, Suzumiya- san.\""
    "\"L...let's get you a ride safely home,\" Haruhi suggested, forcing another uncomfortable smile."
    "Once the pair had left, both pausing to wave at Kyon and Nonoko, he ran his hand through his hair again. \"That ... was a little odd,\" he mumbled."
    "Nonoko hugged him, chastising, \"Even Nii-san can underestimate the power of friendship!\""
    "* * *"
    "Some time after Kyon's equipment had reached a point of reasonable charge, after the near-overloading it had taken during the battle, Ryouko was automatically booted up from her 'sleep' state. Not that she had been asleep, as much as optimizing energy gain for the equipment to bring it back online — that was done, though, and now her body was being carried in one of Yuki's hands."
    "The full-sized interface was currently sitting on one of the sofas in Tsuruya's home, and when Ryouko finished her recovery, Yuki immediately set her on the couch at her side. Ryouko checked her passive scans of what had happened while she was in a reduced activity state."
    "\"Ah!\" she protested immediately upon realization. \"Magical Radiant Nonoko isn't here!\""
    "This garnered her a snicker from the green-haired heiress as she poured drinks from a pitcher into small glasses on the side-table between sofas. \"Silly,\" she chastised, before Yuki could re-enable 'good child' mode. \"You're worried about her?\""
    "'Worry' was an emotional concern! Ryouko didn't have those— Just a crushing fear of Nonoko getting hurt if she wasn't there to try and protect the girl!"
    "Her logic check matched that behavior to the very emotion she was trying to deny— And then no 'good child' mode was needed to keep her silent, as she felt those negative emotions she had hoped would be purged with...."
    "'Hope'? How contaminated had she become? It was fine knowing about emotions in an abstract, purely logical sense. The IDSE had all the same data on human emotions that humans did — and then some! So there was no need to partake of the negative ones. She was familiar enough with the positive ones; she had judged they wouldn't be a liability when she initially assembled her physical form at the behest of her faction."
    "So, Haruhi's change was to make her feel negative emotions, too? How did humans {i}operate{/i} like that? Now that she knew what fear was — how had Kyon managed to make the comments he {i}had{/i} when she was trying to kill him? How had he kept on struggling?"
    "The second time, he had time travel and amazing equipment, but the first time? He knew he had no chance to survive until Yuki appeared to rescue him, but he tried anyway. \"Aw, the poor chibi looks confused,\" Tsuruya added a moment later, plucking Ryouko's tiny form from the couch and giving her a hug, holding her like a doll. \"So— What's this about you having so much concern for Imouto?\""
    "\"M...magical Radiant Nonoko,\" Ryouko began, before being unable to find further words."
    "\"Haha! Okies! So— You want to protect her?\""
    "\"Yes!\" Ryouko exclaimed unhesitatingly, looking around the room, finally registering the others there."
    "Yuki, of course, and on the other couch, on either side of Haruhi — who looked like she was experiencing some negative emotions of her own — were Kanae and Mikuru. The oldest and youngest girls both looked like they were deep in concentration. Haruhi just looked glum and depleted of energy, like Kyon's tools had been from using his 'last resort'."
    "\"Anyway,\" Tsuruya said, swinging around, rotating Ryouko's view as she did, \"who gets to sneak into Kyon-kun's bed tonight~?\""
    "\"Ah,\" Kanae started, before catching herself, then biting her lip. Mikuru blinked and looked thoughtful — both of them turning to look at Haruhi as a flash of hope lit in her eyes."
    "The girl with the golden ribbons in her hair shook her head quickly. \"I...it's not my turn,\" she said, though Ryouko registered that she would be much happier if she had said it was. \"And ... anyway, Kyon's decided to stay at the hospital with Nonoko, remember?\""
    "Ryouko decided not to correct her, this time. Negative emotions were awful things, and interfering with Haruhi's thoughts while she was experiencing that— What if she made it worse? She tried to ignore the thought that she had once tried to hurt — kill, actually — Kyon for specifically that reason at one point."
    "She was not able to ignore the guilt over that idea, though — stupid feelings!"
    "Yuki, seemingly unperturbed, remarked, \"There will be an extended maintenance session tonight.\""
    "\"Oh?\" Tsuruya mused. \"Then ... that means that Imouto's going to be undefended when that happens, right?\""
    "\"Unacceptable!\" Ryouko exclaimed, trying to stave off the bad feelings that thought raised."
    "\"T...then, what about ... bringing both of them ... here?\" Kanae posed shyly, her face reddening as she nervously became unable to meet anyone's eyes."
    "\"Oh, oh!\" Mikuru echoed brightly, perking up, giving Haruhi a cautious smile. \"That would be wonderful, wouldn't it? Then she'd be safe, and ... um ... all of us, somehow....\" She trailed off there, uncertain what else to say."
    "\"This is a good plan!\" Ryouko encouraged, before Haruhi could reply. \"Magical Radiant Nonoko can be here!\" Why was it that she felt so much of a sense of responsibility for the small human, anyway? Just because of the way the little girl had trusted her instructions without hesitation? Somehow, the idea of anything related to betraying that trust made all of those feelings that Ryouko was trying to ignore come back even more strongly!"
    "Haruhi nodded slowly, managing a smile. \"That ... really does sound okay to me. Um, where is Kuyou-chan, though?\""
    "\"Hyperspace manifold,\" Yuki answered."
    "The other interface chose that moment to twist space back — appearing in the center of the room at full size and blinking once before reassuming her chibi- mode. Ryouko wasn't terribly surprised when Tsuruya swept her up in the same embrace, then happily planted herself on the couch. \"Too cute!\" she enthused, beaming smiles at the tiny forms of both of the interfaces in her arms, then glancing to Yuki. \"Yuki-chan, could it be that you have a chibi modes, too?\""
    "\"It is not needed,\" she replied. Turning to Kanae, she added, \"It is safe to retrieve them, now.\""
    "\"Y...yes, okay!\" the slider chirped, vanishing into nothingness with a quiet rush of displaced air."
    "Haruhi looked at the place she had vanished expectantly, and the room was quiet and still for a long minute, until she returned, one hand on Kyon's elbow as he stood in the center of the room, carrying the slumbering form of—"
    "\"Magical Radiant Nonoko!\" Ryouko squealed, wiggling free of Tsuruya's grip and launching herself at the small girl. Though she was still asleep, Nonoko made a quiet noise and grabbed Ryouko the same way Tsuruya had — and this, Ryouko somehow minded a lot less."
    "Kyon looked down and gave her an odd look, but said nothing, just shaking his head at the way the other girls giggled, and Nonoko sleepily opened her eyes. \"Wah?\" she managed, looking around herself. \"Where is this?\""
    "\"My place~!\" Tsuruya enthused."
    "\"Right,\" Kyon said in understanding, nodding his head. \"Time for the debriefing, then?\""
    "\"Yeah,\" Haruhi agreed, rising from the couch and moving to stand near Kyon — for a moment looking like she was going to reach for him, or Nonoko, but doing neither. \"Then— Then you and Imouto can go back to the hospital.\""
    "\"Yeah; we need to get Koizumi here, too.\""
    "\"W...well, what about,\" Mikuru shyly ventured, her face reddening, \"um, before Koizumi-kun is brought by, um ... what about ... Imouto and Kyon-kun staying here tonight?\""
    "Kanae blinked, her eyes widening. \"Yeah!\" she cheered. \"Of course— A slumber party!\""
    "\"I'll let the hospital know not to mention you and Imouto being missing!\" Tsuruya agreed jubilantly, while Ryouko watched the signs of visible relief cross Haruhi's face. \"You can go back in the morning!\""
    "\"Slumber party!\" Nonoko echoed, her face lighting up as she hugged Ryouko even tighter. \"Yay!\""
    "* * *"
    "After spending some time watching over Kyouko, Koizumi had to forcibly draw his attention away when a nurse coughed quietly. That was a warning that normal visiting hours were over, he realized, but also a recognition that he in particular had some additional leeway regarding those rules."
    "He and the female esper had fallen to chatting for that long? It hadn't even really been about their current situations and the supernatural, either— Kyouko had mostly been explaining how relieved she was that her family was safe, then asked a few shy questions of her own. He didn't know how the old administration would have looked at him for volunteering personal information to an 'enemy', but he was confident his current superiors wouldn't complain."
    "Somehow, that suited him just fine."
    "\"I'm sorry,\" he apologized to the girl, giving her his best attempt at a bright smile. She seemed slightly dazed in response — possibly some lingering effects from her shock? The poor girl.... He'd have to visit her again the next day, he decided. Hopefully he could find some way to help keep her cheer up."
    "\"I should let you get some rest,\" he continued at her questioning gaze. He rose to his feet and gave her a respectful bow, before his phone chirped, the Brigade chief's custom ring tone warning him of the call's source. \"Also, I should probably check in with Kyon-kun, and make sure that everything's alright on that front.\""
    "Kyouko managed to call, \"Good luck, then! I-I hope to see you again!\" before he stepped through the door, flashing her one last smile over his shoulder before closing the entry and answering the phone."
    "\"Koizumi-kun!\" Haruhi's voice came across the line. \"Are you ready for debriefing?\""
    "That was unexpected, he thought, but just as well. \"Absolutely,\" he confirmed."
    "\"Kanae-chan will—\" She cut off suddenly, and her voice resumed, somewhat muted: \"What? You don't have his.... Okay—\" She brought the phone back up and corrected herself, explaining, \"Yuki-chan will bring you to us as soon as you're ready.\""
    "\"I'm ready, then,\" he said, glancing around the hallway cautiously. There was no one in sight at the moment."
    "\"She says to close your eyes!\""
    "He did so, and felt a disconcerting lurch, significantly odder than shifting into closed space. When he opened his eyes again, he found to his surprise he was surrounded by the entire Brigade, as well as Kyon's younger sister. He blinked upon realizing that they were all also wearing matching green pajamas, stamped all over with Tsuruya's family crest. Kyon alone was wearing a larger yukata."
    "\"Um,\" he managed, a bit surprised, and remembering to remove his shoes. Kyon was sitting on a nearby futon, his attention on his younger sister, sitting at his side and leaning against him while chatting with Ryouko and Tsuruya. The tiny figure of Ryouko was in Nonoko's lap, hugging onto one of the girl's wrists protectively, while the heiress sat directly before the smaller girl, giggling at something she had just finished saying."
    "On Kyon's other side, Haruhi leaned against him, looking simultaneously exhausted and pleased. Mikuru was standing not far away, looking down at the chest of her borrowed pajamas and worrying at how the buttons were straining. Kanae was at her side, eyeing those same buttons with barely concealed jealousy, while Yuki stood closer to him, as though waiting for him to say something else."
    "\"Hello,\" he tried a moment later. \"Apologies for the delay; is everything alright, then?\""
    "\"It's fine,\" Haruhi said, snapping her phone shut and lazily tossing it across the room. It drifted gently to land on a pile of folded clothes in one corner. \"But we need to have a debriefing, and we're all here right now; tomorrow, the school's probably going to blow up with excitement about Kyon being called out!\""
    "\"And the ground shaking,\" Koizumi agreed. \"I have been considering some cover stories for that.\""
    "\"Yeah?\" Haruhi asked, raising an eyebrow."
    "\"We have no idea what caused the shaking, naturally,\" the esper said, offering a smile and sinking to sit on the floor. \"I recall another point that was made concerning such issues; if something is inexplicable, or difficult to explain, why not appear to be as much in the dark as anyone else on the subject?\""
    "\"Well, I did say it wasn't an earthquake,\" Haruhi admitted with a wince, ducking her head."
    "\"And the meteorological service agrees,\" Koizumi replied. \"That just means you were right, not that you knew what it actually was. Is that correct?\""
    "Haruhi blinked in mild surprise, then managed a smile at that. \"That's true,\" she allowed. \"What about the student council?\""
    "\"There's no disciplinary issues to be handed to them,\" the esper answered with a shrug. \"Kyon's parents have already been informed....\""
    "\"And that could have gone smoother, but I think Tsuruya-kun's father mostly took care of that,\" Kyon commented. \"I think my mom's going to be on edge for a while, but if she hasn't delivered an ultimatum yet, she probably won't.\""
    "\"She's just grumpy because she's too old to be a magical girl,\" Nonoko asserted."
    "\"Don't say that to her,\" Kyon scolded her mildly, giving her a smile when she twisted around to look at him."
    "\"Then, that would appear to address the most mundane of concerns,\" Koizumi surmised. \"I'm afraid I have no insight into other realms. May I ask what transpired against ... our enemy?\""
    "\"Wataru-san called them 'the Combine' once,\" Kyon added, frowning."
    "Kanae cocked her head to one side. \"T...that's that ... scary person's name? Why would you call him by his first name, Sempai?\""
    "\"Ah!\" Tsuruya exclaimed, leaping to her feet as Kyon looked briefly panicked, distracting the slider. \"Kanae-chan — we need to get a yukata for Koizumi- kun~! And we should fetch some cookies, too, shouldn't we?\""
    "\"Cookies!\" Nonoko enthusiastically echoed, her eyes lighting up as she hopped to her feet. With almost no hesitation, she placed Ryouko's form on the top of her head, running between Tsuruya and Kanae and taking a hand from each. \"Let's go~!\""
    "There was a brief silence until the trio had left the room, and Kyon sighed, running one hand over his face. \"Damn,\" he muttered."
    "\"We need to figure out how to break that to her before it gets sprung on her in a bad way,\" Haruhi muttered, turning from where she was sitting to hug Kyon, holding him tightly. He looked embarrassed, unable to meet the esper's eyes, but put one arm around the girl and hugged her back anyway. \"That's not going to be fun.\""
    "\"W...what?\" Mikuru asked, blinking in worry."
    "\"We'll ... talk about that later,\" Haruhi sighed, as it was only moments later that Tsuruya and the others returned, Kanae carrying a tray of cookies, Nonoko bearing a comfortable looking robe, and the heiress herself carrying a stack of cups and a pitcher of milk."
    "\"Here, Sempai!\" Kanae chirped, offering him the plate of cookies. Haruhi released Kyon from his hug long enough for each of them to grab one. \"Um, where were we?\""
    "\"Debriefing on inter-dimensional aggressors,\" Yuki remarked."
    "Koizumi turned to her, and was briefly startled to see Kuyou just behind her. Had she been there before...? Well, that probably didn't matter."
    "\"The Combine,\" the dark-haired girl replied ominously, her eyes tracking from Ryouko to Kyon. \"The source of the Other.\""
    "All eyes turned to the pair of interfaces, while Tsuruya ushered Koizumi to a different room for privacy. He changed quickly, not terribly surprised to be met by Tsuruya's chief maid when he exited the room, and she collected the shoes he was awkwardly carrying. When he returned to Tsuruya's room, the mood had lightened somewhat, and most of the cookies were gone."
    "\"Alright,\" Haruhi declared, surveying those in attendance. \"So, what do we know about these bad guys, anyway? Can we figure out when they're going to attack now?\""
    "\"Yes,\" Kuyou answered."
    "At the same time, Yuki replied, \"Sometimes.\""
    "\"Huh?\" Mikuru and Kanae wondered together."
    "Yuki clarified, \"The mechanism that 'the Combine' use to travel between realities is inefficient. It requires a period of time to charge energy for use, and that energy is lost if their target is significantly disrupted.\""
    "Kuyou nodded in confirmation."
    "\"So ... they spend energy to send something over, like the robot on the beach— And Koizumi-kun beat it, so they lost that energy?\" Haruhi wondered."
    "\"Correct,\" Kuyou and Yuki answered in tandem."
    "Yuki blinked, and then continued alone, \"It appears that it takes approximately seven days for them to collect the energy to cause a transition sufficient to transport a sentient. Earlier today, they attempted an alternate approach that would forcibly deteriorate the boundaries that separate our reality from theirs. This allowed them to temporarily exceed this limitation."
    "\"Suou Kuyou rejected the forcible merge, incidentally destroying the agent that made such a merge possible.\""
    "Mikuru's eyes were wide with alarm while Kanae's were wide with confusion. The pair exchanged a glance, and Tsuruya surmised slowly, \"So ... they took a big hit, and should be reeling, right now?\""
    "\"Yes,\" Yuki agreed. \"Energy costs dictate that they will be unable to send significant mass into our reality for a period of seven days.\""
    "\"But they're going to be back,\" Kyon noted, frowning."
    "\"Yes,\" Kuyou answered."
    "\"But we can tell ... when, now?\" Mikuru hazarded hopefully, moving to Kanae's side and patting the slider's shoulder encouragingly."
    "\"That is correct,\" Yuki agreed. \"Suou Kuyou is sensitive to their attempts to breach the dimensional barrier, and will notify Asakura Ryouko when this information is available.\""
    "\"So, how long until they throw something at us like they tried today?\" Haruhi wondered."
    "\"At a minimum, several weeks,\" Yuki answered after a pause. \"There is a speculation that their controlled territory requires a significant amount of time in order for energy to be moved from territory within their control, and territory that has been recently acquired.\""
    "Kanae shivered, and Mikuru shifted closer the small bit of distance that separated them, giving the slider a reassuring hug and smiling at her warmly."
    "\"Most likely, the attack force that appeared today was sent directly from a location within their established control. The enemy slider himself is stationed on the border of the territory that they control. The other instance of Suou Kuyou—\""
    "\"The Other,\" Kuyou herself interjected."
    "Continuing as smoothly as if she hadn't been cut off, Yuki continued, \"—was able to bypass the energy costs associated with transfer personally as she had an assigned responsibility of maintaining internal barriers within the Combine space.\""
    "\"Meaning?\" Kyon asked, voicing the question Koizumi felt the need to ask himself."
    "\"The fundamental understructure of their reality may have been permanently damaged as a result of this loss,\" Yuki explained. \"They will have a pressing need to replace that entity.\""
    "All eyes turned to Kuyou, who looked at Kyon. \"They cannot have me,\" she said simply. \"I am yours.\""
    "Haruhi made a small noise at that, squeezing Kyon tighter and eyeing Kuyou thoughtfully."
    "Koizumi winced, and Kyon seemed to think that the floor had become intensely fascinating. Subtlety was ignored when Nonoko cheered, \"The power of love conquers all!\""
    "\"You're sure getting a lot of mileage out of that symbol I made you write,\" Haruhi allowed."
    "After looking puzzled for a moment, the boy shook his head sharply, hanging his head and sighing. \"S...sorry,\" Kyon mumbled."
    "For his part, Koizumi just heaved a small sigh of his own, glad that she wasn't angry about it. He'd taken Haruhi for the jealous type, but it seemed he was mistaken — and a good thing, too!"
    "\"Well, anyway ... even if it wasn't the most neat victory — we successfully defended the Earth, and were able to keep people from finding out and panicking,\" Haruhi decided, releasing Kyon and sitting up straight. \"I wouldn't mind telling people, but this isn't good news. And I'm not willing to share my cute alien friends with the entire world, so I guess they can't know yet. It hardly feels like we're discovering things, but I am happy we're protecting the entire world!\""
    "\"The entire world?\" Kyon answered, a little off guard."
    "\"Hahahah!\" Tsuruya finally broke in, wrapping her arms around herself as she shook. \"That's great— Haha! Haru-nyan, he wasn't doing that for the {i}worlds{/i}— He was doing it for you and Imouto-kun! And that's what makes Kyon- kun so mega awesome!\""
    "Kyon looked sheepishly taken aback by that, scratching behind the back of his head and chuckling nervously. \"I ... was just thinking about Imouto — and then Haruhi and Suou-san, since they were there...\" he offered."
    "\"That seems commendable anyway,\" Koizumi answered, giving what he hoped was an encouraging smile. Certainly, regardless of the reasons, he was glad Kyon had kept alien invaders from causing even more trouble."
    "\"Ah, but I think that covers everything, doesn't it?\" Haruhi mused. \"Is there anything else for the debriefing?\""
    "\"Just— I did have a question,\" Kyon managed, giving Haruhi an uncertain smile. \"So ... when did you learn to fly and throw energy?\""
    "\"I...it came to me,\" Haruhi said with a frown, looking down into her lap. \"I mean— The energy thing I could do for a while, but there wasn't much need for it. I figured it out after that beach episode, I think. For flying, I kind of ... realized I {i}had{/i} to in order to get to Imouto in time, so.... I think it's one of those things that Yuki-chan said I'd get if I kept practicing.\""
    "She blinked suddenly, smiling. \"Hey, that's just like an anime, isn't it?\" she realized aloud. \"I got that new power right when I needed it!\""
    "\"For Imouto's sake, I'm not going to complain,\" Kyon acquiesced. \"That's all I could think of. Being able to have advance warning for future slider attacks is good news, though.\""
    "\"Indeed,\" Koizumi agreed. \"In less pressing matters, I am still focusing on Tachibana Kyouko; she's doing well, though I suspect that she herself was never trusted with significant information by her superiors. She even seemed to be under the impression that I was in charge of our Organization until some time recently.\""
    "\"Weird,\" Haruhi remarked, shaking her head. \"I think that's it, though — alright, there's probably nothing else important. If there is, we can talk about it at the meeting tomorrow, right?\""
    "\"Right!\" everyone else but Ryouko agreed, including Kyon's sister."
    "* * *"
    "Nonoko couldn't remember the last time she'd had so much fun — once she'd been brought over to Tsuruya's place by Kanae's magical princess powers, she was having the best time possible with her big sisters! Even better, her brother seemed to calm down a lot, especially after listening to Yuki and Koizumi explain about how effective their work at stopping the Dark Generals was!"
    "Once Koizumi had been sent back home, Nonoko covered her mouth to prevent a yawn, looking around at the others and wondering what would happen next. Surprisingly enough, it was Yuki who broke the quiet and calm, announcing, \"Tsuruya Haruka may join us for tonight's training session.\""
    "\"So, Imouto and I are the odd pair out?\" Haruhi asked, putting on a smile that Nonoko could tell wasn't really genuine."
    "\"I'll have to pass tonights,\" Tsuruya deferred, rising from her seat to hug Haruhi. \"Haru-nyan and I have to talks to Imouto-kun!\""
    "\"What about?\" she asked excitedly, her tiredness vanished. She was curious about this thing that Haruhi was excluded from, but getting to spend time with two of her favorite big sisters — that was just as good as getting to do something with her brother!"
    "Haruhi looked curious, too, so Tsuruya looked thoughtful for a moment before explaining, \"Well, doctors and police will have questions for you, Imouto- kun— Haru-nyan and I will help you get ready for that!\""
    "\"Questions about what?\" Nonoko wondered, before realizing. \"Oooh! I can't give away anyone's secret identities, right?\""
    "Kyon looked puzzled for a moment, then looked between Tsuruya and Haruhi before giving a small shrug. \"Just don't give them any trouble, alright, Imouto?\""
    "She resisted the urge to pout, but once he chuckled and gave her a smile, she couldn't help but smile back — until everyone except Haruhi and Tsuruya vanishing into nothingness abruptly."
    "\"Wah! Where did they go?\" Nonoko exclaimed."
    "\"A training place — like when the Commons-tans took Trope-tan into the Tower of Knowledge,\" Tsuruya offered."
    "Nonoko felt a little bad about missing out on that! But then, she had Tsuruya and Haruhi with her. \"Why didn't you go, Tsuru-nee?\""
    "\"Because helping you gets ready is how I get to help Kyon-kun today,\" she answered brightly. \"And Haru-nyan, too~!\""
    "\"Ah, heh,\" Haruhi managed, blushing slightly. \"S...sorry about being so nervous....\""
    "\"This is new, and strange stuff,\" Tsuruya said, shrugging. \"So— Imouto-kun, the police will have questions for you, about what happened yesterday.\""
    "\"Okay,\" Nonoko said, nodding in understanding. Police were good guys, but sometimes didn't understand things right. \"What should I say?\""
    "\"Tell them the complete truth!\" she said, grinning brightly. \"Tell them all about how you became Magical Radiant Nonoko!\""
    "\"Yeah,\" Haruhi agreed belatedly. \"That— Tell them all about what you did, and that you were trying to help your brother.\""
    "\"What?\" How was that going to be a good idea?"
    "\"What's important is what you don't tells them,\" Tsuruya continued. \"And that's about everyone else!\""
    "Nonoko gasped in sudden realization. \"Just like Kyon-kun got Mom not to believe him by telling the truth!\""
    "\"{i}Exactly{/i}!\" Tsuruya agreed, chuckling. \"A truth so unbelievable you can continues being a defender of justice!\""
    "The girl couldn't help but pout. \"I wanted people to believe me when I tell them about that, though....\""
    "\"Your real friends — and your sisters, here — will all believe you,\" Haruhi countered, giving her a surprisingly warm smile. \"Even if I'm not happy that you could have been hurt ... you know ... you really did save the day, Imouto. I don't know what would have happened if you weren't there."
    "\"I think ... Kyon may be too worried for you to say it himself, but I think — at least a little bit — he's glad for that, too.\""
    "Well, that was more important than convincing some stranger that she was really a magical girl, wasn't it?"
    "\"Okay!\" she cheered, before yawning again. \"Hmm, why do all of the fairies fall in love with Nii-san?\""
    "\"All of them?\" Haruhi asked, blinking. \"Who— You mean Kuyou-chan?\""
    "\"And Ryouko-chan,\" she added in a mumble, feeling herself drift off as she leaned against Tsuruya and stifled another yawn. \"Isn't that why she wanted me to bring his things to him?\""
    "For some reason, as she drifted off, she felt Tsuruya shaking with laughter — certainly, she could hear Haruhi giggling about something."
    "* * *"
    "Puffing out a sigh, Miyuki shifted a stack of paperwork to one side, trying not to glare at her laptop. The timing was so close that her superiors had determined she didn't really have a chance to set an operation into motion. Simply put, there was no possible way to arrange a raid in the time she had, once she'd gotten the anonymous tip."
    "Alone in her office, she glanced around as though to ensure no one else was there — though she wasn't certain why she did so. Certainly, she'd had unreasonable success arranging last-minute attacks on vague tips before, suspiciously {i}common{/i} in this investigation."
    "But narrowly missing it because she was distracted by a personal phone call? That lack of professionalism didn't feel like her. Then again, neither did 'being lucky', as opposed to planning carefully."
    "Now there were two opportunities that they had missed — the first was something involving a massive cross-town car chase between the Sumiyoshi-rengo and the Yamaguchi-gumi on Monday. Reports were sketchy on that one, since they were using third-hand information at best."
    "And then, earlier that day ... something that caused a tremor felt across the hill that Kitago capped? Someone calling Kyon out by name for a fight no one had seen?"
    "It was a mark against her that she'd had no forewarning or preparation — it was following this with Kyon's sister getting {i}kidnapped{/i} that put the final piece into place for her. How much had Miyuki really uncovered, anyway?"
    "How much of it had simply been {i}given{/i} to her?"
    "So even though her superiors didn't fault her for the 'narrow misses,' she realized what they really meant. They meant that it wasn't her effort being rewarded here after all."
    "In some senses, seeing the opportunity get dropped felt more true to her performance before this case — more like herself."
    "Less like a pawn in someone else's game."
    "Pursing her lips, she leaned back in her chair, then set her fingertips on the keyboard of her laptop and took a slow, calming breath. Once she was prepared, setting all of the security options to their highest levels, she carefully drew up a file for a new investigation."
    "* * *"
