label LL_6:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 056 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear

   
    "As much fun as it was to kiss Kyon, it was a little awkward doing it in front of Shinobu-- In front of one of the other girls didn't bother her that much, and Haruhi wasn't about to just let herself miss out, but even so...."
    "This was Tsuruya's chief maid! As nice as it was that she had no complaints about the whole ... situation surrounding Kyon and the others, well...."
    "Haruhi coughed, not meeting the woman's eyes while Kyon vanished into the house."
    "\"S...so,\" she started weakly, \"what did you want to talk to me about?\" Hopefully it wasn't an embarrassing lecture along the lines of, 'Don't make out with Tsuruya's fiance where you can be caught,' or anything like that."
    "\"A small enough thing in the grand scheme of things,\" the woman replied quietly, ducking her head slightly. \"Would you care to join me on a short walk about the estate, Suzumiya-dono? And perhaps, while we do that, I could tell you a story?\""
    "\"Er, alright,\" she agreed. It had to be important, given that the maid had singled her out."
    "Shinobu nodded, offering a small, cautious smile and stepping down one of the paths crossing the estate. The pair walked through the twilight, the gardens lit with small lamps. \"This may perhaps explain some small bit regarding Haruka-chan and her behavior in some situations,\" the maid said softly, breaking the silence just as Haruhi got used to it."
    "Tsuruya's behavior? Was Shinobu trying to apologize to Haruhi for Tsuruya making out with Kyon? That couldn't possibly be it ... could it? \"Okay?\" she hazarded, no longer knowing where the conversation was going."
    "Shinobu gave Haruhi a small smile, then turned her face away, walking slowly as they rounded the side of the house, staring up at the sky. \"Many years ago, long before you or Haruka-chan were born,\" she began softly, \"there were two sisters."
    "\"These sisters belonged to an upstanding family -- they were twins, in fact. One was more excitable, a free spirit -- the other was more traditional, and followed her parents' instructions."
    "\"The more traditional, well-behaved sister was instructed by her family to accept an arranged marriage, and as a traditional woman she did so. The ... less well-behaved sister rebelled, abandoning her family to strike out on her own. She had some adventures, and faced some danger ... and eventually, she decided that as an independent woman, she would become an activist and fight for the rights and freedoms of others in distant countries.\""
    "Haruhi blinked, trying to figure out where the woman was going with this -- was Haruhi supposed to be the 'free spirit' while the 'traditional sister' was Tsuruya? Haruhi supposed that might be the comparison she was going for, but couldn't see where it was going yet...."
    "Shinobu paused briefly, collecting her thoughts and pursing her lips, face tilting the slightest bit higher. Taking a surprisingly shaky breath, considering how unflinching the maid had seemed in the past, she continued, \"In some countries where women are not ... well respected, this free-spirited girl carelessly made some dangerous enemies.\""
    "\"They were those she had thought of as privileged and unable to understand the plight of those she wished to help. Seeing as they didn't understand her, she saw no particular reason to respect them. So because of this.... She had meant to help others, and instead had been careless of how her actions might hurt those around her. That is ... as an activist, she brought attention on herself and her nearest allies carelessly, and when she realized what danger she was in....\""
    "Haruhi shifted her shoulders uncomfortably -- this didn't sound like it had anything to do with her at all. Shinobu paused at a point on the opposite side of a pond from the house's rear deck, and Haruhi stopped with her."
    "\"Selfishly, and not thinking of the consequences, this free-spirited young woman returned to her home country, pleading for shelter from her family. While it was undoubtedly deserved, her parents refused her, throwing her own disdainful remarks back at her--"
    "\"But her sister, even if traditional, was a gracious soul. E...even with her newborn daughter occupying her time, she still welcomed that free-spirit into her home."
    "\"Again, unthinking of others, that free-spirit accepted the generosity of her compassionate, considerate twin-- She cut her hair and changed her name, thinking the problem was solved.\""
    "Haruhi shivered, not from the cold. Was Shinobu saying...."
    "\"Her enemies, however, didn't care. It wasn't even a case of mistaken identity; they knew that if they hurt the free-spirited girl's family, they would still be able to strike her. And so ... it came to pass that her carelessness cost her sister her life.\""
    "The strangled noise that escaped Haruhi's throat as she realized what Shinobu was saying couldn't be held in."
    "\"From that point, that once free-spirited woman realized she had created a debt to her sister's new family that could ... never be repaid. Even if the more traditional sister's husband held no grudge against her, she realized that there must be a balance. The value of duty had been taught, even if it was at ... such great cost."
    "\"From there, she devoted her life to her sister's memory -- and her niece. She couldn't accept anything greater than the role of a servant; she had cost her family too much. Instead she sought to help those who still accepted her, no matter how careless she had been. She did her best to help raise that niece to value the strengths of her mother -- while also learning to appreciate the best things in the world about her."
    "\"A...and so,\" Shinobu continued, her voice even shakier, \"what I wish to say here, Suzumiya-dono, is that Haruka-chan tries her best-- She means well, and she tries to be considerate; when those she cares about are hurt, she is hurt, too. But despite the best intentions ... she is often alone in the world.\""
    "Haruhi worked her jaw, unable to voice a protest, then shook her head furiously before dragging her sleeve across her eyes. \"Does she even know?!\" she finally mustered the energy to snap. \"Does she-- You--\" She shook her head again."
    "\"No,\" Shinobu said softly, looking away. \"If someone must be blamed for Haruka-chan's causing hurt, it should be that same person who cost--\""
    "\"Stop,\" Haruhi groaned, closing her eyes. \"That's.... I get it....\""
    "She understood well enough. The maid -- Tsuruya's aunt! -- wasn't trying to make her feel sorry for her ... though she'd certainly done that."
    "\"Tsuruya can get really angry at people because she values her family so very much,\" Haruhi said quietly. \"Right? She's.... Of course she's not cruel or cold.\""
    "\"Yes,\" Shinobu agreed softly. \"We all have moments where we are weak, and angry -- and can hurt others carelessly. Haruka-chan meant well, when she proposed what she had. But then ... that careless, free-spirited sister meant well, too.\""
    "\"In fact,\" Haruhi said slowly, understanding dawning, \"she meant the best.\""
    "\"Just so,\" Shinobu confirmed, one hand rising to her face, wiping at her eyes. \"Just so-- And if you could learn from m-- the mistake of someone careless, then you could be a better person than her. Just like she believes Haruka-chan to be.\""
    "She couldn't bear to look at the woman any further, and turned away, staring at the stars. The 'chief maid' had a point.... There was no reason to be upset about suggestion of dealing with the Sumiyoshi-rengo. Rather, seeing as she was the daughter of a powerful member of an organized syndicate, Haruhi could easily imagine Tsuruya agreeing on the surface that Kyon's approach was right...."
    "...and then when he was distracted, taking matters into her own hands. Her intentions were good, but Haruhi was starting to realize what path was paved with those."
    "\"It could be hard,\" she said softly. Tsuruya cared about her and Kyon -- feeling powerless most of the time, and then being told to do nothing when the people she cared about were in danger.... Taking a deep breath, she shook her head. \"But then ... if it were easy ... it wouldn't be worth doing.\""
    "Shinobu said nothing in reply."
    "\"Shinobu-san ... thank you for ... sharing that with me,\" Haruhi said uncomfortably. \"I.... I'll keep a close eye on Tsu-chan, and let her know there are other ways....\" She turned around, feeling some of her strength return. \"But-- But some day, you will have to tell that story to her, I think. Maybe ... right now isn't the perfect time, but you'd better not expect me to keep that a secret from her forever!\""
    "\"I....\" Shinobu winced, looking away. \"Yes, that's fair,\" she sighed. \"I merely wish for Haruka-chan's happiness ... and the happiness of those she makes her family.\""
    "\"Yeah, well-- Wait, wait-- Does ... Tsu-chan's father know what we're doing?\" Haruhi asked cautiously."
    "\"He ... has been brought around to accepting that it is Haruka-chan's choice and it makes her happy,\" Shinobu replied, mildly evasive."
    "Haruhi pursed her lips, nodding. Given the subtext ... Shinobu was probably the one who had brought him around! \"Some day,\" she said, quietly. \"Thanks again, Shinobu-san ... I won't forget that lesson.\""
    "Not any time soon. Really -- Kyon was involved in a war against a rival organized crime syndicate, and so was Tsuruya. And then, throw in everything else.... If she was stressed, how much must Tsuruya be going through? Well -- there was still time to turn things around!"
    "Nothing had been done that Tsuruya would have a reason to regret, yet -- and if Haruhi had her way, she wouldn't!"
    "* * *"
    "Sasaki couldn't help but wonder if she should be more bothered by the way things had gone. Well, she knew some parts of it should not have worked out the way that they had -- ending up tangled in an embrace with Kyon had actually been nice. Far too nice, really."
    "She couldn't afford to let herself enjoy that sort of thing -- he was her friend, and engaged to Tsuruya! The green-haired heiress was also partially responsible for saving her and Haruhi from the situation they'd been in. Kyon's rescue was nothing to complain about, not in the slightest."
    "But wasn't Tsuruya in some senses a savior as well?"
    "...unfortunately, no amount of logical and reasonable arguments with herself could ward off the feeling of pressing into Kyon's side, his arm wrapped around her. Even with Haruhi right at her side, sharing what space there was around him for that embrace...."
    "She bit back the urge to sigh wistfully and merely bowed her head, returning to the present moment. Tsuruya's living room was quite spacious, and Sasaki could only marvel at how considerate and friendly the girl seemed, given the relative opulence she must have been raised in."
    "\"I should thank you,\" Sasaki said, shaking her head and offering the green-haired heiress a smile. \"After all, without your help....\" She trailed off and shrugged."
    "\"Ah, thinks nothing of that,\" Tsuruya said, waving a hand dismissively. \"Hmm, though-- I should apologize to you! When we met some time ago at the beach, I said some unkind things, which I shouldn't! A friend of Kyon's is a friend of mine, and so -- if you can, think of what I've done as an apology for that!\""
    "Sasaki blinked, remembering that incident suddenly. It wasn't something that haunted her constantly ... but occasionally it did trouble her thoughts. Certainly, she didn't like that it seemed almost as though she came across as a villain to Kyon and his friends."
    "\"It's nothing,\" she said, shaking her head again. \"Sometimes there are mis-communications, and that ... well....\" Being entirely honest, it did make her feel better that Tsuruya wanted to make amends for that. \"I -- I wasn't at my best that day, either. But then, perhaps it's not constructive to dwell on that -- it's better to work toward a more positive future, isn't it?\" Absolutely, there was no sense dwelling on how much she realized she was hurt by the revelation of Kyon's engagement."
    "What was done ... was done! The best course of action would be to try and be friends with Tsuruya, just like Haruhi."
    "\"I like to think like that!\" Tsuruya said brightly. \"Cheerful thoughts are the best thoughts! Don't be blind to misfortune, but don't let it rules you!\" She chuckled at that, and Sasaki found herself smiling easily at the other girl's demeanor."
    "\"How ... are things between you and Kyon?\" she asked. \"I'd feel bad if my issues were causing problems for you.\""
    "\"Cheerful thoughts,\" Tsuruya admonished with a smirk, surprising Sasaki by winking and tapping her gently on the forehead -- like an admonished child."
    "Sasaki felt her face redden. She wasn't doing the best job of what she'd promised, was she? \"Ah, you're right,\" she chuckled nervously."
    "\"But otherwise,\" Tsuruya sighed, her smile fading, \"there have been problems. Mmm, not your fault, but with, eh, enemies in generals. Kyon-kun handles it very well! But ... at least one dinner was cut short when business came up.\""
    "\"I ... wish I could help, somehow,\" Sasaki said slowly. \"If ... it's not too much to ask.... Well -- I feel I must ask, though-- Playing the role of hapless victim is quite unpleasant. While I am grateful for your protection and aid, is there ... anything I can do to help?\""
    "Sasaki wanted to pinch herself. Even if it had gone through her mind before, was she seriously asking to be taken in and given a role in a crime syndicate? It took her less than half a second to realize that yes, she was -- and it was perfectly reasonable, too. Her friends were already there, and she was going to be pursued by various enemies for some reason, anyway."
    "It was entirely logical to do everything she could to protect herself!"
    "A small voice in the back of her head noted that working in such a capacity might let her spend more time with Kyon, too, but that was fine, wasn't it? They were friends, after all!"
    "Tsuruya's eyebrows rose. \"Hmm,\" she mused thoughtfully, one hand cupping her chin, as gaze turned distant. \"Well,\" she said slowly, \"I would need to check with Kyon-kun, and see if he thinks it's a good ideas, first.\""
    "\"If what's a good idea?\" the boy in question asked, stepping through the doorway, looking curious."
    "Tsuruya explained, \"Sasaki-chan wants to join us, since she's involved anyways! What does Kyon-kun think?\""
    "\"You know,\" Kyon said, shaking his head and sighing, \"Haruhi asked if we could include Sasaki in more of our business, too?\""
    "Tsuruya's eyebrows rose, while Sasaki wondered ... what was Haruhi's role in things? \"So, then,\" she prompted, giving Kyon a smile, \"what is your thoughts?\""
    "\"Being entirely honest, it seems fair and reasonable to me, Tsuruya-hime,\" he answered slowly, one hand going behind his head as he stared at the blank television screen. \"Um, well, Sasaki, my thoughts are that ... really ... explaining things to you is something that we must inevitably do. It's ... difficult to know where to begin, though. Well -- as far as things go, I'd be happy to bring you in.\""
    "\"Is that so?\" Sasaki asked, unable to keep from perking up. This was what she'd hoped for, after all!"
    "\"It's not going to be easy,\" he warned, frowning. \"Even considering everything....\""
    "\"It is worse than you knows,\" Tsuruya said sternly, though her expression was surprisingly warm and gentle. \"You have seen the tip of the icebergs -- and you must have absolute and unwavering trust for Kyon-kun!\""
    "Sasaki couldn't help but wonder at that. \"That's.... I've had trust in Kyon for some time,\" she said quietly. \"But I thought that ... you were in charge?\" she asked cautiously."
    "\"It's complicated,\" Haruhi sighed, stepping in through the doorway from behind Kyon, making him start slightly. \"We all look out for one-another, and that means sometimes any one of us may take charge in different ways to help the others out. Like for example, when I tell Kyon he should spend some time with his fiancee, because a debriefing of any kind can wait for the time being!\""
    "\"Really?\" Kyon asked, before shaking his head. \"Yeah, you're right-- That whole thing can wait until tomorrow. Though ... where's Yuki-chan?\""
    "\"Meeting room,\" Tsuruya answered thoughtfully. \"Hmm! Okay, Kyon-kun, let's go let her know the meeting is off for tonight.\""
    "\"I feel a bit bad about leaving her like that,\" Kyon mumbled with a wince. \"With everything that's been going on--\""
    "\"Yeah, it's a pity about that,\" Haruhi said, sounding strangely evasive. \"Thinking about things ... with that missed meeting, Yuki-chan has some ... catching up to do, doesn't she?\""
    "\"That's fine, that's fine,\" the heiress assured him, grinning as she bounced to her feet. \"Well! We shall take care of that, Kyon-kun -- won't that be better than worrying about more work?\""
    "Sasaki had to giggle herself at the confused but unprotesting expression he put up. \"That's true...\" he allowed. \"Um -- if that's alright by you, Tsuruya-hime.\""
    "\"Of course!\" the heiress insisted, grabbing his hand and leading him back toward the door. She paused to call over her shoulder, \"'Saki-nyan, Haru-nyan, as friends and allies, use this room as much as you like for now!\" before vanishing, Kyon offering a semi-apologetic grin and shrug before he disappeared as well."
    "\"Ah,\" Sasaki sighed, before shaking her head. \"I can't help but be a little envious of that girl,\" she remarked to Haruhi, as the other girl lowered herself to the couch."
    "\"How ... do you mean?\" Haruhi asked cautiously."
    "\"Well ... getting to spend time with Kyon like that,\" Sasaki admitted quietly. \"Of course, he is engaged, and so as his friends, we can only admire from a distance....\""
    "Haruhi winced, undoubtedly thinking back to the hug they'd shared with Kyon. \"Tsu-chan ... is not someone who would want us to be hurt like that,\" she said slowly."
    "\"And ... likewise, we shouldn't hurt her by being careless,\" Sasaki agreed."
    "\"Well ... keep an open mind, Sasaki,\" Haruhi decided, giving a curiously lopsided smile, not quite meeting her eyes. \"Things are changing quite a bit, and if ... Kyon manages to explain everything about what we're involved in, you might be surprised at how well things can turn out!\""
    "\"Is that so?\" Sasaki asked. She wanted to dismiss it off-hand -- pretending things were anything other than they were was pointless, wasn't it? But then ... what was the hope of the rescue that she'd received? Then again, what were the odds of being mixed up in whatever it was that was going on in the first place, anyway?"
    "\"I'll try,\" she promised, chuckling. It wasn't like she could help it at this point, even if she wasn't able to get that hug out of her mind. If only there were some way that she and Haruhi.... Well-- No point fixating on that! \"For you, Tsuruya-san, and Kyon, I think I can do it!\""
    "\"Good,\" Haruhi declared. \"Now let's watch some cute, mostly mindless anime and not worry about things so much!\""
    "Sasaki balked momentarily -- as pleasant as it might be to try and relax and not worry about things at all.... How was that helping matters? Wasn't she supposed to be working with Kyon and Haruhi to try and help them out? And if she wasn't working, shouldn't she instead be working on her studies?"
    "Except...."
    "When she thought about it, she really did like the idea of just relaxing with a friend. To say nothing of the fact that she doubted that she could convince herself to pay proper attention to her studies anyway. \"Very well!\" she agreed, laughing. \"That does sound rather enjoyable!\""
    "\"Good, good! Now, what kind of anime do you like?\" Haruhi asked, looking at a shelf crammed with DVD boxed sets. My, Tsuruya must have an awful lot, hadn't she?"
    "\"Something cute should be fine,\" Sasaki said helplessly. She really didn't pay enough attention to those sorts of things, did she? What was popular these days, anyway?"
    "\"Alright, I've already seen this one, but Kyon's little sister loves it -- and Kanae-chan's a huge fan, too,\" Haruhi decided, hopping to her feet and pulling one of the cases from the shelf. \"He won't admit it, but I think Kyon enjoys it a lot, too?\""
    "\"Really?\" Sasaki asked, unable to keep the interest from her voice. Haruhi shot her a knowing smirk, and Sasaki blushed in embarrassment.... Well, at least he wasn't there to see it!"
    "\"Yep! Okay, Trope-tan, episode one!\""
    "After putting the disk in, Haruhi bounced to the couch at Sasaki's side and flopped down, smiling. \"I've seen the first episode a few times, but I really like it, and showing it to a friend is fun, anyway!\" she remarked."
    "That really was the kind of thing Sasaki didn't do quite enough. Usually she was just focusing on her studies. Well, maybe she would get something out of being Haruhi's friend as well! That seemed somehow alright, especially if she could help distract the other girl from their mutual interest in Kyon!"
    "* * *"
    "After the crazy week he'd had, and the new responsibilities he'd picked up -- important ones, though -- from Haruhi, Kyon was convinced he was finally going to have a single good day in the current week. Just one! Was that so much to ask for?"
    "The previous night had gone pretty well, though -- his 'meeting' with Tsuruya had turned into a surprisingly intense and unabashed make-out-session, and one that expanded to include Yuki. The heiress didn't kiss Yuki the way she'd kissed Haruhi -- instead it was just a friendly peck on the cheek, but hugging.... Yuki seemed to really like that."
    "There was a pleasant pause for dinner, which was an interesting experience with Yuki and Tsuruya occupying his arms and taking turns giving him bites of his food -- that kind of thing he supposed he couldn't really complain about too much. Tsuruya's giggling, and Yuki's tiny, almost invisible hints of amusement set a perfect tone."
    "Yeah, he thought he could deal with more of that."
    "And once he let his eyes open, he realized he'd woken up with the familiar, comforting warmth of two other people crammed into his tiny bed. Glancing cautiously to one side, he caught Haruhi's mop of dark hair, unbound with a ribbon at the moment, and to the other ... Kanae?"
    "The slider yawned and stretched cutely, blushing the instant her eyes opened. \"G-good morning, Sempai,\" she stuttered breathily."
    "Haruhi stirred, shifting a bit and half-flopping across Kyon. \"I stayed up too late last night,\" she groused, before pressing her face into his chest. \"Good morning, Kyon, Kanae-chan,\" she said, her voice muffled, her breath going through his shirt."
    "Oh ... boy...."
    "\"Ah...\" Kanae sighed, looking a bit wistful, before hugging Kyon's arm tightly to her chest. That ... wasn't really something he was going to complain about, either!"
    "\"Huh?\" Haruhi wondered, raising her head. \"You sound a bit down, Kanae-chan. What's going on?\""
    "\"N...nothing!\" the slider squeaked out, her eyes bouncing lower, to Haruhi's pajama top, and then quickly away. \"Um, just, good morning!\""
    "\"Uh-huh,\" Haruhi managed, unconvinced, before squirming further across Kyon and raising the smaller girl's chin, grinning deviously. \"You want to be able to ... excite Kyon, huh?\""
    "\"Y-yes!\" Kanae yelped quietly, before covering her mouth, her blush intensifying further, somehow."
    "\"I like you just the way you are, Kanae-chan,\" Kyon said, shaking his head, as he was pleasantly pinned at the moment."
    "\"Try this!\" Haruhi said eagerly, surprising him by squirming a bit more across Kyon, almost lying on top of him to kiss the slider."
    "He had the perfect view of Kanae's eyes widening, then suddenly going very distant as her expression turned almost deliriously happy, and she started kissing back enthusiastically."
    "Okay! Now that was a fine way to wake up! Haruhi being, well ... Haruhi, she wasn't content to let it rest there, and pulled Kanae gently with her as she slid back to her side of the bed until they were sharing space partially sprawled across him."
    "\"Now,\" Haruhi began--"
    "Before both of them vanished, and his door slammed open with a reverberating smash."
    "\"Hah!\" Nonoko cheered. \"I got up early to-- Aww! Nii-san is already up!\""
    "Kyon hurriedly sat up to rearrange his blankets, his own face reddening. \"Nono-chan...\" he sighed, hanging his head."
    "Well, there was a limit to how nice his day could be, he supposed. Getting too caught up first thing in the morning.... Maybe he'd have a chance to follow up on that a bit with Haruhi and Kanae later; he did have priorities, after all."
    "After turning off the alarm that he hadn't let go off in quite a while, his sister touched a fingertip to her lip and mused, \"I thought I heard Haru-nyan....\""
    "\"You did!\" Ryouko chirped from her perch on the desk, next to his phone. \"Nono-chan~! Yay!\""
    "\"Ah! Achakura~!\" Nonoko cheered, grinning. \"Can we play today?\""
    "\"Maybe later!\" the small interface replied."
    "...wait. If Haruhi and Kanae had teleported away -- Kanae's doing? Yuki's? He wasn't sure yet.... Still, if they went away before his sister could spot them, did that mean that ... Ryouko had watched that entire thing?"
    "It could just be for the best that his sister interrupted! What a thought!"
    "\"Will Chuo be there?\" his sister asked earnestly."
    "\"Who's that?\" Kyon asked, stretching as he finally climbed out of bed."
    "\"Chuo Kuyou!\" she said cheerfully. \"The fairy that helped fight the dark kingdom army when I was Magical Radiant Nonoko!\""
    "Kyon blinked at his sister in disbelief. \"Suou Kuyou,\" he corrected her gently. \"Her name is Suou Kuyou.\""
    "\"Kyon,\" his mother chided, leaning around the door-frame in the hall to give him a disapproving look. \"Don't encourage Nonoko's daydreams so much.\""
    "\"R...right,\" he agreed, forcing a smile and running a hand through his hair again. \"Well, anyway, Imouto, how about giving me a little privacy to change?\""
    "\"Okay!\" she agreed, dashing to his desk and grabbing Asakura up, the small interface waving her arms happily. \"I'm just going to go play with my 'imaginary friend' while you do that~!\""
    "His mother rolled her eyes while Kyon just wondered when his sister had become so devious."
    "* * *"
    "As much as she had enjoyed her date with 'Shutaro', Mikuru was still hoping for another chance to spend some time with Kyon. Even as she thought it, she couldn't help but perk up when she spotted Kyon marching up the hill on the way to school. \"Kyon-kun!\" she called, waving."
    "He stopped, turning to look at her and giving a subdued wave back."
    "She caught up quickly, needing to pause and catch her breath after the jog up the hill. He smiled and took her bag. \"Ah-- Thanks, Kyon-kun,\" she giggled, feeling her face redden a bit. \"Good morning!\""
    "\"Good morning to you, too,\" he returned, managing a small smile."
    "The two started the daily hike, and Mikuru resolved that one of these times, she was going to ask if Yuki couldn't help her get in better shape, too. She didn't want to get into fights, but being able to handle the hill would be a nice change."
    "\"How are you doing today?\" he asked."
    "\"I'm fine!\" she said brightly. Then, realizing how she could pose it, she added, \"I um ... really enjoyed going out with, ehe, Shutaro-kun. I'm hoping I can do it again, soon~!\" If not, she was certain she was owed some time to snuggle with him one of these nights soon! \"How about you, Kyon-kun?\""
    "\"A little stressed,\" he admitted, his smile faded. \"Haruhi's given me some pretty daunting goals.... I can probably figure out how to ... break the masquerade to Sasaki -- or at least try. I'm not quite sure how to take care of that just yet.\""
    "He sighed, shaking his head. \"Well, you shouldn't have to worry about that, though; that's my responsibility.\""
    "She bit her lip thoughtfully. She wished she could help with that.... Well, she had managed to handle the trip to Hinamizawa! Or, would once it came up. Oh, she'd forgotten to tell Haruhi that was handled, hadn't she?"
    "She placed a reminder in her augmented reality field, then asked, \"Um, Kyon-kun, do you think we could maybe have dinner tonight?\""
    "\"Uh-- As Shutaro?\" he wondered."
    "Well, that would be nice, and she didn't mind being treated, but she wanted to cook for him, and wouldn't Shutaro visiting in the middle of the week raise questions? \"A...actually, I was thinking maybe with Haruhi-chan and Kanae-chan at my place?\" she suggested. \"That would be okay, wouldn't it?\""
    "\"I ... can't think of a reason to say no,\" he said slowly. \"Well-- We do need to escort Sasaki home, just in case.\""
    "\"Would she like to join us, maybe?\" It was a pity to leave Yuki out, but Mikuru's little apartment only had so much space ... they'd have to make it up to her somehow. Maybe that night!"
    "Kyon rubbed his chin. \"I don't know,\" he admitted, before offering a rueful shrug. \"But I'll try and ask her. I think I'd enjoy that, at least.\""
    "\"Good!\" she exclaimed brightly. She might not be as capable as the others in a lot of ways, but cheering Kyon up had to count for something, didn't it? Kanae was frequently in the same situation, so letting her help ... that would be perfect!"
    "* * *"
    "While the Brigade didn't always meet for lunch, Yuki went to the clubroom to eat regardless. She didn't get a lot of attention from her classmates, so it wasn't to escape as much as she simply went because that was what she'd always done. She supposed that made it 'habit'."
    "She could have tried joining her primary and secondary observation targets for lunch, but that could cause certain social issues. She didn't care about those for her, but for others, she'd rather avoid causing trouble. Especially Tsuruya; in the public perception, she and Kyon were an 'item', which left Yuki less room to enjoy time with Kyon publicly."
    "Though, as everyone came to the clubroom anyway, that issue was largely circumvented -- though thanks to the president of the computer research society stopping her to ask for her help with an upgrade the following week, she was the last to arrive, instead of the first."
    "So much for that particular 'habit'."
    "That aside, as much as she had enjoyed spending time with both Tsuruya (unexpected, but incredibly pleasant) and Kyon the night before, she recognized an opportunity when she opened the clubroom door and found him already seated. Haruhi was to his right, and Kanae was to his left."
    "Since those two prime seats were taken, Yuki resolved to try something that she'd seen Mikuru do before. Since seats were limited, even if there were technically enough, and he'd wolfed down most of his lunch already, she set her bento on the table and then took the seat she'd planned on taking."
    "The slider gasped in response, looking envious. \"Ah, Nagato-san....\" she mumbled."
    "\"Hmm, I'll allow it,\" Haruhi decreed, nodding. \"That's insanely cute! Can you just imagine her sitting like that and reading a book?\""
    "Tsuruya merely giggled, snapping a few pictures."
    "Mikuru blushed, while Asakura gave her a curious, thoughtful look from the table between the bentos."
    "Coughing, Koizumi tugged at his collar and unfolded the remaining chair, setting it at the table. \"There is a spare seat,\" he started, before it was abruptly filled with Suou Kuyou's full-sized form. Yuki was able to trace the not-quite-data-manipulation that surrounded it moments before her arrival, but still found it interesting just how different it was."
    "The other entity's dark eyes regarded her curiously, just as Asakura had -- though the tiny interface turned to the other entity and waved her arms in greeting."
    "\"Okay,\" Haruhi declared, slapping one palm gently on the table to call everyone to attention. \"Now, let's see.... We have to finish that debriefing from yesterday, don't we? What did we find out, if anything?\""
    "\"Um, let's let Koizumi go first,\" Kyon suggested, putting one arm around Yuki as he shifted slightly in his seat, shifting his knee to provide slightly better support."
    "If his hands were occupied, it seemed only fitting that Yuki help him out, she determined. The logical solution was for her to take care of what he couldn't. Wasn't he always saying that they had to depend on one another?"
    "\"Here,\" she said softly, using her own chopsticks."
    "\"...kind of jealous I never thought of that,\" Haruhi mused, as the boy Yuki was hand-feeding blushed, accepting the bite she offered him. \"Anyway! So, Koizumi-kun, you were going to use your powers to dig for information! What did we get?\""
    "\"Based on Nagato-san's confirmation, we have determined that....\" The esper paused, turning to regard Kanae."
    "\"I...it's fine!\" she said insistently. \"I should know too, right?\""
    "\"Right,\" Haruhi agreed thoughtfully, before brightening. \"Ah, I have it!\""
    "The small slider yelped as she floated into the air, flailing for a heartbeat before curling up wide-eyed, and gently drifting down for Haruhi to pull her down and wrap her arms around her. \"We're supposed to be dating anyway, so this is fine, right?\" she said brightly, once the slider was settled into her lap. \"Now, go on, Koizumi-kun?\""
    "\"Er, yes...\" the esper managed, before shaking his head. \"Ah-- So, we were able to determine that Wataru-san is at least partially an unwitting servant of the Combine. He uses his seeming anger to fight against the controls used against him, and as he related things, he's actually doing his best to keep the Combine's actions ineffective.\""
    "\"He's on our side?\" Kanae blurted out, eyes wide. \"But--\" She cut herself off abruptly and gasped. \"T...then ... maybe that's why I was able to get away the time he caught me?\""
    "\"Oh, that could be it,\" Tsuruya agreed, suddenly solemn. \"Scary stuffs.... Can we help him, somehow?\""
    "\"Uncertain,\" Yuki answered, shifting her gaze to the dark-eyed entity."
    "Kuyou's head tilted thoughtfully. \"Uncertain,\" she agreed. \"That entity's function is synchronized, but not harmonious, with the Noise.\""
    "\"So we can't help him?\" Mikuru asked, wincing."
    "\"Or,\" Koizumi said slowly, looking thoughtful, \"is it more that he's not willing to let us help him? He warned us that if he were replaced, whoever -- or whatever -- came next would be ... more difficult to deal with. If he's trying to stand in the way of that....\""
    "\"That's possible,\" Kyon agreed between bites. \"I'm not sure what we can do.... For now, we need to figure out how to communicate with him better. All I can ... really think of is to weaken the Combine in general, to the point where he doesn't need to try and act as a stopping block.\""
    "\"What ... should I do?\" Kanae asked worriedly."
    "\"For now, rely on us,\" Haruhi answered without hesitation. \"We'll figure out a solution for that -- in the meantime, we've got other things to worry about, too. Okay, Kyon, you've got enough to worry about already, so I think the basic plan of figuring out how to strike back against the Combine to weaken them and help him out is enough of a plan-- Though I don't want to risk you doing that right now!"
    "\"So -- for the time being, just don't worry about that one.\""
    "\"It's nice to have one less thing to worry about,\" he allowed, giving her a soft smile before Yuki distracted him again. After chewing the last mouthful of his lunch, he added, \"I've got enough to try and sort out.\""
    "\"Is that the end of the official debriefing, then?\" Koizumi asked, frowning. \"I can't think of anything else....\""
    "\"There was a tangle with some Sumiyoshi-rengo last night,\" Tsuruya said, giving her head a short shake. \"Kyon-kun set them straights, but, hmm, I will ask Mori-san to see if we can't find out a longer term solutions -- this irritation has been going on too long!\""
    "\"On that note, I'll be meeting up with Sasaki after school,\" Haruhi added, grimacing. \"Hopefully that will help.\""
    "\"Um, why not bring Kyon-kun with you?\" Mikuru suggested timidly, offering a hopeful smile. \"A...after, if you like, you can meet up at my place, and I can cook?\""
    "\"Ah, that sounds fun, too bad I'll be busy,\" Tsuruya mused, clicking her tongue."
    "\"I-- I wanted Kanae-chan to come, too,\" the time traveler added quickly. \"She's a good assistant in the kitchen!\""
    "The slider perked up visibly at that. Yuki knew how to cook as well as Mikuru -- she'd helped train the time traveler after all. Even so, she didn't find the process typically enjoyable, and while she had the potential to do that ... or almost anything else the other girls who gave him attention could, she recognized the importance of worth by being able to present tangible things."
    "More importantly, Yuki had developed a firm understanding of how important it was to Mikuru specifically. It would be nice to join in on that, but Yuki was enjoying herself at the present, and could enjoy some further time with Kyon once he got back home and went to bed."
    "\"Huh ... that sounds like it could be fun,\" Haruhi agreed. \"Okay -- and afterwards, Kyon can escort Sasaki home, and Kanae-chan can give us all boosts home, right?\""
    "\"Yes!\" the slider exclaimed happily, eyes wide. \"That-- Okay!\" Yuki recognized that was yet another instance where Kanae was glad to offer something to him and the others. Normally she would just save energy, but more and more she was recognizing that giving room for others gave them a chance to spend some time with Kyon as well. And wasn't doing something for him an activity that they all enjoyed?"
    "\"It's a plan!\" the brigade chief declared."
    "* * *"
    "As wrapped up as Haruhi had been lately, Yanagimoto had found plenty of time to grill Taniguchi to spill what he knew about strange things involving Haruhi. Most of what he went on about was from their time in middle school -- most of which Yanagimoto remembered herself. Well, Haruhi had changed quite a bit from those antics, and she was more interested in the movie bit."
    "Other than some distractions involving a mumbled confession that one of Taniguchi's prime motivations for helping had been to see Asahina Mikuru in the waitress outfit she wore for the filming, which had resulted in a promise for a date to apologize, she'd gotten quite a bit of information! After that, Sakanaka had found a copy of the DVD that Haruhi had lent her, and the pair watched it curiously."
    "Between the two of them, they were assembling a surprising list of things to be curious about-- In the end, while the film was amusing, and Sakanaka couldn't quite bite back a wistful sigh at the sight of Kunikida -- the singer sure had fallen hard! Yanagimoto really found Taniguchi's expression silly and amusing, in comparison, even if the other girl had probably wanted to draw parallels between them."
    "Well, that aside, while the movie showed some things that were questionable, the only thing that stuck out as probably-not-a-special-effect was the inexplicable blooming of the cherry trees out of season. Yanagimoto had managed to forget about it until seeing it in the movie."
    "How could that be blamed on Haruhi, though? Probably it wasn't Haruhi's fault, but the two had come up with a working theory. It really did explain a lot! Haruhi had meant to find strange and spectacular things ... and somehow succeeded! They didn't know what they were, and Sakanaka agreed with Yanagimoto's sentiment that they might be happier that way."
    "In any case, her 'agency' had managed to find stuff. Most likely, the movie was a clever cover on her part to conceal the strange stuff they were dealing with. Something had happened to Sakanaka's dog, and Haruhi's club had sorted it out -- Yuki specifically had seemed instrumental, but who was to say?"
    "The small girl was more than she seemed, but was probably part of the strange crew of whatever that Haruhi had tracked down. Undoubtedly, Haruhi was too clever to give any real clues from the movie, so Yuki was almost certainly not actually a witch or an alien. After all, she'd use strange powers or magic, while from what Yanagimoto had seen she was just very, very strong for her size."
    "Well ... there was also the fact that she seemed to help Tsuruya's bleeding from when Yamane Jun tried to shove the upperclassman out the window. That thought sent chills up both girls' spines. Was that some strange ... thing, too? Not just creeps being horribly creepy?"
    "Neither particularly wanted to know too much more, but Yanagimoto had trouble sleeping after she started to think about it."
    "She was absolutely happier not knowing all the gritty details."
    "Anyway ... she could easily attribute the memory she had of seeing blood to shock. Yuki probably had some kind of training; hadn't she done insanely well at the sports meet's run? She'd matched Haruhi, after all, and that girl was a top athlete! Added to Kyon's prowess, and everyone's confidence in Koizumi's skills, Tsuruya's poise...."
    "It was far too easy to imagine them as a group of well-trained fighters, dealing with.... Well, they'd decided they didn't want to know. If it was something Haruhi was willing to pretend was 'merely a polyamorous relationship' to help cover..... Who knew what they were protecting Kanae and Mikuru from!"
    "Anyway, in the anime and manga, didn't everyone who dealt with crazy paranormal stuff appreciate their normal, everyday lives more because of it?"
    "Strange as the realization was, Yanagimoto and Sakanaka were that for Haruhi and her friends -- or at least a part of it. Kunikida was supposed to be Kyon's friend, so if he was busy sulking and being bitter over Sasaki, that was a complication that Kyon didn't need. To Yanagimoto, that made solving the Kunikida situation even more important!"
    "Of course, Sakanaka was spending half her time being lovesick, which didn't solve problems, and made Yanagimoto feel guilty about dating Taniguchi. Talk about inconvenient!"
    "\"Alright,\" Yanagimoto decided, as she and Sakanaka left the school after club. \"Sakanaka-chan, we're going to write your confession to Kunikida and practice your delivery!\""
    "\"Eh!\" the other girl started, turning to look at her in confusion. \"I-- But he's.... That's to say....\""
    "\"No excuses,\" Yanagimoto insisted. \"You've tried subtlety, but let's face it! He's a guy. Subtlety doesn't work on them.\""
    "\"That's true!\" Taniguchi agreed, stepping out of the shoe lockers and joining them, causing Yanagimoto to jump in alarm. Sakanaka startled, eyes widening as her face turned red. \"We can only pick up on girls being interested in other guys. Just like everyone could tell Haruhi was into Kyon except for him, until she hooked up with that other girl!\" He looked to one side and muttered, \"Somehow ... didn't see that one coming, even if I probably should have....\""
    "\"R...really?\" Sakanaka asked, stunned."
    "Yanagimoto wanted to slap her forehead. That was unexpected! Still...."
    "\"So, Yanagimoto-hime, who is it that Sakanaka likes?\" he wondered, shaking his head to dismiss the distraction and grinning."
    "\"Try and learn subtlety!\" Yanagimoto snapped, glaring at her boyfriend. Oh, man, that guy...."
    "\"I-- That is-- Y...you see...\" the singer stuttered, blushing so much Yanagimoto thought she would faint."
    "\"One thing at a time, Taniguchi-baka,\" she grumbled, hanging her head. \"Learn to read the mood!\""
    "\"Got it, top secret,\" he said breezily, nodding. \"Well, hmm, you know, Sakanaka, I don't think you'll have any problem. Unless the guy you like has already fallen for someone else, anyway.\""
    "Sakanaka froze, her expression falling."
    "\"Shut up!\" Yanagimoto hissed, strongly tempted to try stomping on the boy's foot."
    "For all his obliviousness, Taniguchi seemed to realize where he'd messed up and quickly backpedaled, \"Er, that means you have to confess before he confesses to her, then!\""
    "\"Not helping.\""
    "\"Ah,\" Sakanaka eked out quietly, turning away, shoulders slumping. \"I...is that ... so...?\""
    "Taniguchi winced. \"Ah ... hey, look!\" he exclaimed, pointing at a student near the gate. \"It's a convenient change of subject!\""
    "Pulling her glare from him and actually hoping the subject could be changed, Yanagimoto's gaze fell on Kunikida, leaving the school late."
    "\"You know, he's been skipping his cram school and staying late with a study group,\" he mused. \"Wonder what's up with him? Since I was waiting for Yanagimoto-hime, he tried to get me to join him, but....\""
    "The heat in Yanagimoto's gaze seemed to register, and even the legendarily dense Taniguchi was able to put two and two together."
    "\"I.... Um. I ... will see ... you two ... tomorrow,\" Sakanaka said unsteadily, sounding on the verge of breaking down."
    "Just great! Brilliant, Taniguchi! Yanagimoto was sorely tempted to hit him -- for sure she wasn't going to go on another date with him any time soon! Oh, the second she was alone with him...."
    "\"I-- I think I'm going to shut up now,\" Taniguchi babbled, laughing uneasily and avoiding her eyes. \"Um-- W...well....\" Finally at a loss, he spread his hands and allowed another forced laugh before concluding, \"Look at the time!\" and breaking into an all-out run toward the gate."
    "Sakanaka plodded away, her shoulders trembling."
    "Oh, hell. Desperate times called for desperate measures."
    "\"Okay,\" Yanagimoto declared, running to her side. \"Emergency ice cream.\""
    "\"Ah,\" Sakanaka replied, absently."
    "\"Emergency ice cream and then we go to your place to practice making a bento,\" she added desperately. \"G...guys love a girl who can cook for them! I don't think Sasaki can cook, right? It's a battle of charm -- you'll beat her no problem!\""
    "\"I...is that ... so?\" Sakanaka mumbled, faintly roused from her shock."
    "Yanagimoto forced a smile and nodded. Never mind the fact that she wasn't that great a cook ... and that Taniguchi didn't deserve a bento from her after that nonsense! All dates with him were lost to damage control on this! What a mess! Taniguchi-baka indeed...."
    "* * *"
    "As crazy as things had been lately, Sasaki found being able to attend another session of her cram school somewhat relaxing. It might have been nice to study with Haruhi and Kyon, but her life settling back into some sort of order was a positive, too. That and the fact that some day things would calm down to the point where they wouldn't need to spend that time around her...."
    "Haruhi would still be her friend, hopefully, but Kyon would want to spend time with his fiancee, undoubtedly."
    "No sooner did she think that, then Haruhi popped up again to meet her at the school exit. \"My!\" she exclaimed, unable to deny that she felt warmed by her friend's presence. \"I hope you didn't have to wait long?\""
    "\"Not long,\" Kyon agreed, from her side, startling her."
    "\"Ah! You're both here?\" Sasaki exclaimed."
    "\"It seemed a good idea, all things considered,\" Haruhi said, looking to one side."
    "Laughing uneasily, Sasaki had to agree, \"That's ... true, isn't it?\""
    "\"I remember this place,\" Kyon said with a soft smile, his gaze going back to the past. Sasaki couldn't help but remember that time as well, riding on the back of his bicycle."
    "\"You went here?\" Haruhi wondered."
    "\"We-- We attended together,\" Sasaki agreed. \"That seems so long ago, didn't it?\" No sense dwelling, even if she couldn't get that hug out of her head, shared with Haruhi or not. \"But -- are you going to walk me home, then?\""
    "\"Actually, we were kind of hoping you'd feel like hanging out,\" Haruhi said, smiling. \"Can you join us for dinner with Mikuru-chan?\""
    "\"She's a really good cook,\" Kyon chimed in, nodding. \"I have to admit, I'm looking forward to it, myself!\""
    "That was unexpected! \"What about your fiancee?\" she wondered. As tolerant as that girl was, she didn't want Kyon to accidentally strain his relationship!"
    "\"She's dealing with some work stuff ... if it's an emergency, she'll call,\" Haruhi said resolutely. \"Come on, it'll be fun! Do you need to call your parents first?\""
    "\"My mother,\" Sasaki agreed. Well ... why not? \"Ah, I'll do that now, then.\" Kyon nodded, and Haruhi crossed her arms over her chest in satisfaction, both of them waiting while Sasaki stepped slightly to one side, ducking her head and calling her mother."
    "\"Sasaki-chan?\" her mother answered, after only two rings."
    "\"Ah, mother, I've been invited to dinner with a friend, so wanted to let you know what was going on,\" she answered quickly, hoping she wouldn't need to explain too much."
    "\"Someone I know?\" Always probing, that woman...."
    "\"Kyon,\" she said, before she could stop herself. Oh, well. There'd be questioning after the fact, of course, but her mother would probably agree quickly -- she had the entirely wrong idea, but had liked the boy, after all."
    "\"Oh, good!\" her mother said with enthusiasm. \"Such a well-behaved young man! You know, not that long ago, his mother was suggesting you should be a study partner with him?\""
    "\"Is that so?\" she answered, keeping the sigh from being audible."
    "\"That's right! That's right!\" her mother said absently. \"Well, that's fine then. You'll have to tell me all about it afterward! Hopefully he'll come to his senses quickly enough.... Anyway, you have fun, Sasaki-chan!\""
    "\"I will!\" she agreed. \"Well -- he's waiting, so we'll chat later.\""
    "\"Looking forward to it.\""
    "That made one of them, Sasaki thought, hanging up."
    "\"What's wrong?\" Haruhi asked curiously, letting Sasaki realize she had let her resignation show on her face."
    "\"Ah, that's.... My mother can be a bit overbearing,\" Sasaki answered, shrugging and offering a weak smile. \"But-- No matter! For now we should have fun visiting, shouldn't we?\""
    "\"Right!\" Haruhi agreed, looking contemplative. Kyon seemed distracted by some other thought, but given his own mother, Sasaki suspected he'd largely tuned hers out every time they met and just nodded absently...."
    "\"Well.... Kanae-chan is helping Mikuru-chan cook, so it should be a lot of fun,\" Haruhi said, a warning gleam in her eye warning Sasaki that the issue wasn't closed yet. Oh, well, she could worry about that later."
    "\"You know,\" Sasaki mused softly after checking that no one else was in earshot, looking for a change of subject, \"if I'm working with you, I can't help wonder what Tsuruya-san is up to?\""
    "\"I'm certain it's a meeting,\" Kyon chuckled. \"Formal, a bit intimidating, but usually actually pretty boring, all things considered.\""
    "\"Really? They're boring?\" Haruhi asked, sounding a bit crestfallen."
    "\"You haven't been to any?\" Sasaki added in surprise."
    "\"Er, no,\" she answered, shrugging with a wry grin. \"I've kind of wanted to, but I've managed to almost always be busy with other things, so it's just never worked out that way.... I guess if it turns out to be boring I can't complain too much that I get to miss them. Tsu-chan's super-patient and good-tempered, though! It makes sense that's what she's doing!\""
    "\"That really does follow,\" Kyon agreed."
    "* * *"
    "Even if the people she cared about were handling things well, and she hadn't done anything she regretted, Tsuruya still felt enough was enough. She didn't particularly want to go against her father's superior ... and she absolutely didn't want to go against Kyon or Haruhi. But if there was one thing she knew it was that she could trust in the people she'd chosen to share her life with."
    "That thought in mind, when Haruhi mentioned her self-appointed task to keep an eye on Sasaki, and that Kyon would be there, things had started to come together. Yuki was likewise not going to be involved, and that meant she was alone while everyone else was enjoying time with Kyon."
    "As much as Tsuruya enjoyed spending time with him, she was glad he was busy -- and distracted. That gave her time to take care of other matters. Mori had helped, though undoubtedly didn't know what Tsuruya really intended with the information the heiress had asked for. That thought in mind, shortly before it was time for dinner, she called Yuki, unsurprised at the other girl's swift answer."
    "Having become familiar with how quiet she could be, even when answering the phone, Tsuruya asked, \"Yuki-nyan? Are you free tonight to help me with something?\""
    "\"...yes,\" Yuki answered after a pause. \"Last night was ... pleasant.\""
    "She felt her face heat up a tiny bit, unable to keep from grinning. That was fun, wasn't it? And for that night, and (she hoped!) a great deal more like it.... \"I also need to ask you a favor -- I'll need helps with something ... but it can wait until I'm at your place. Ah, how about this! When we're done, I'll buy you dinner anywhere in town you'd like!\""
    "\"See you soon,\" the smaller girl replied before disconnecting."
    "Tsuruya nodded to herself, her resolve firmed. Yuki was every bit as reliable as Kyon; she'd helped Tsuruya and Kyon both out before, hadn't she? So, together...."
    "Kasai was gone when she went to find a driver, but she decided that was for the best. Mori had seemed faintly distracted -- maybe they were having another date. That idea made Tsuruya smile the entire ride to Yuki's place. She worked hard! So did Kasai! The two of them seemed like a cute couple, even if Mori did appear tiny next to Kasai's bulk."
    "Actually, that just made it cuter! She dialed Yuki's apartment number and was swiftly buzzed in, unable to stop chuckling all the way to the elevator. Would Haruhi think it was cute, too? Still grinning, she traipsed to Yuki's door and rapped her knuckles loudly."
    "The quiet girl answered, and Tsuruya didn't hesitate to grab her in a hug. \"Yuki-nyan~!\" she chirped. \"How are you doing tonight?\" She nudged the door shut with one ankle and set the girl back down, still grinning."
    "Blinking quietly, the girl answered, \"I am fine.\""
    "\"That's great!\" Tsuruya started. \"Now, hmm, if it's not too much, could I ask you that favor?\""
    "Yuki's head tilted the slightest bit in curiosity, but she said nothing."
    "\"There's some people who have been making troubles for Kyon-kun, and his friend Sasaki, too-- I want them to leave us alone, but I'm not supposed to, officially. And Kyon-kun is well-behaved, so I don't want to get him in trouble with my father's or his boss....\" She trailed off, unable to smile at that thought. This was serious stuff, after all."
    "Yuki's expression didn't change, except that the light in her eyes seemed to slightly harden."
    "\"So! Yuki-nyan, I'm coming to you because I trust you, and we've worked together in the past.... But really, I guess I'm asking for you to lend me your strengths. I know how strong you really are, but I can't handles this one alone. I know you could, though, and so ... not really for me, but for Kyon-kun, and Haru-nyan, and Sasaki, too, I have to asks!\""
    "The smaller, quiet girl only blinked a single time before answering, \"Okay.\""
    "\"So easy!\" Tsuruya exclaimed, smiling uneasily. Well ... then again, Yuki hadn't hesitated to dress up to infiltrate the Sumiyoshi-Rengo involved with the photography ring, either, had she? She shook her head. \"Okay, then we'll needs to get over there. I'll call a cab, alrighty?\""
    "Yuki nodded quietly while Tsuruya made the call; no need to let her driver or anyone else know what they were doing, after all. If it got back to her father.... Or worse, Kyon! All the more reason to be careful and cautious, then. \"Yuki-nyan,\" she said thoughtfully, tapping her chin, \"it's not much, but have you thought about what you'd like to eat?\""
    "\"Do not worry,\" Yuki replied, as Tsuruya led the way out the door, the pair of them walking to the apartment building's rear and climbing down the stairs there. While they were primarily intended for emergencies, there was no connected alarm, after all. As they stepped into the parking lot, Tsuruya waved down the approaching cab."
    "One way or another ... she would deal with one particular problem, at least! Kyon had a vacation coming up -- they all did! And they could all deal with one less looming threat to worry about."
    "* * *"
    "It wasn't precisely what she'd wanted, and Mikuru's apartment was crowded with all of them there, but it was a cozy environment, thanks to the atmosphere. The only real issue was that with Sasaki there, she couldn't give Kyon a kiss. Or Kanae, for that matter!"
    "The slider was absorbed in watching Mikuru's work with wide-eyed amazement, eagerly bustling next to her 'Mikuru-onee' whenever the time traveler needed an ingredient, or wanted to let her help out. Well, it was a foregone conclusion that whatever Mikuru made would taste amazing; Haruhi was certain that the older girl was a six star chef or better!"
    "And if such rankings didn't exist, well, that didn't change the truth of that assessment!"
    "In the meantime, Haruhi and Sasaki found themselves seated at the kotatsu on either side of Kyon. That wasn't actually so bad.... It was a bit of a pity that Tsuruya and Yuki couldn't be there, but it was still nice. Those two were probably taking care of themselves."
    "So ... what to do while Kanae and Mikuru -- as adorable as they were -- were occupied with cooking?"
    "Sasaki seemed to be thinking something similar, so broke the silence by asking, \"So ... Kyon, what are your plans for this weekend?\""
    "\"Ah, well ... if everything works out, somehow, I'll be visiting my family in the country,\" he said with a wince."
    "Haruhi couldn't imagine why he'd be evasive about that. Mikuru had already let her know Kyon had taken care of travel arrangements to Hinamizawa. She didn't know what they were, yet, but had no reason not to trust the time traveler! Well, maybe he was trying to be evasive about how they were going rather than cause interference with Sasaki's powers? That made complete sense."
    "\"It's also a special day!\" Haruhi added. And she was excited about it, all things considered."
    "\"Kyon's birthday?\" Sasaki asked, smiling brightly."
    "While momentarily taken aback, Haruhi ruefully nodded. Of course she'd know.... \"You still remember?\" Kyon asked, just as surprised as Haruhi felt."
    "\"Naturally,\" Sasaki agreed, laughing softly. \"Well, if you're going to be visiting your family, I will have to hope I can wish you well at some point!\""
    "\"Maybe if things go really well, you could come along!\" Haruhi said hopefully. Kyon was supposed to be figuring out a way to break things to the other girl, after all. Judging by his wince, he hadn't made any progress on that ... well, he hadn't had any time to do so, had he?"
    "\"I doubt my mother would agree to that,\" she countered with a small sigh."
    "Haruhi still wondered what animosity there was between Sasaki and her mother, but knew better than to probe right there. Kyon had probably met her anyway, so that would be a much better place to start. Time for a subject change!"
    "\"Well, in that case, since I thought we might want to relax a bit,\" Haruhi said, smiling, \"I borrowed the Trope-tan DVD collection from Tsu-chan!\""
    "\"Ah, right,\" Kyon said belatedly. \"Kanae-chan and my sister love that show.\""
    "Haruhi ignored him and got up to put it into the player connected to Mikuru's small television."
    "\"I-- I like it, too,\" the time traveler volunteered from the cooktop, while Kanae studiously stirred a pot, her attention focused on the task before her."
    "\"I also found it amusing,\" Sasaki agreed. \"Ah-- Well, this should be fun! I will need to thank Tsuruya-san most sincerely for the loan!\""
    "Haruhi wondered if Sasaki meant of the disks, or of Kyon, though she wouldn't be surprised if it was actually both."
    "\"Yeah, Tsuruya's really thoughtful that way,\" Kyon mused, relaxing a small bit. \"I hope she's having a relaxing evening, too.\""
    "* * *"
    "After Tsuruya and Yuki had set out from Yuki's apartment, the taller girl slowly became more and more tense. Yuki said nothing, because she didn't typically act first unless she felt she had to. Moreover, she wasn't certain what Tsuruya was thinking."
    "During the last kilometer of the drive to Osaka, she was able to determine what was going on with Tsuruya."
    "The girl was nervous. And what had Mikuru taught Yuki about that, anyway? Also factoring in what she had learned from the time traveler, Yuki wordlessly leaned toward the taller girl. As both of them were sitting in the back seat, it was trivial to put one arm around her and give a reassuring hug."
    "That turned out to be the very thing the heiress needed, because most of her tension vanished, replaced with indicators Yuki understood to be confidence."
    "\"Okay,\" the heiress declared, leaning forward and breaking the hug. She pointed at a nearby building and added, \"You can drop us off there.\""
    "Yuki studied the building as the car stopped and she stepped out. Tsuruya spent a moment longer, paying the driver."
    "It didn't seem that different from most of the other buildings in the area. It appeared to be a slightly run-down pachinko parlor. The men standing at the door were familiar -- obviously members of a rival syndicate."
    "\"You're a bit young to be in here,\" the one on the left said, as Tsuruya stepped out of the car and approached the door. Yuki remained at her side, ready to act, but keeping her physical form relaxed."
    "\"We gots a lot of money,\" Tsuruya answered with a shrug, her teeth glinting as she grinned. \"But I was looking to get into the back room.\""
    "\"What back room?\" the man on the right asked, crossing his arms over his chest and frowning."
    "\"Hmm, subtlety is overrated,\" Tsuruya sighed. \"Today, I'll just tell you: I'm the daughter of Tsuruya Kenshiro. Except for my friend Yuki-nyan, here, I'm alone. I want to talk to your boss about things in Nishinomiya -- specifically, I'm annoyed at you attacking my fiance so much!\""
    "\"W...what?\" the figure on the left managed, eyes widening as he stared in confusion. The other figure blinked, his mouth dropping open a short distance. \"You--\" He paused, looking around. Probably because of the parlor's reputation, no one was within easy earshot. \"You're claiming to be the fiancee of the legendary Kowa-Keigo Kyon?\" he scoffed, looking doubtful."
    "\"H-hey, I think she's serious,\" the other door guard said before Tsuruya could reply. \"And ... she could be telling the truth, you know? If she wants to come into our territory alone in any case ... I say we show her and her friend what ... hospitality we can in the back room, huh?\""
    "Yuki saw the signs of tension return to Tsuruya's frame, but they were subtle; she doubted the men noticed, even if they did grin."
    "\"Yeah, alright,\" the first man said, shaking his head and gesturing the pair inside. \"Come on, little girls.... We'll show you a good time.\""
    "Somehow, Yuki doubted the accuracy of his assessment."
