label Re_4:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 060 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
    
    "Kanae wasn't sure what to make of things after finishing up with her sempai's aunt Rika -- or as she had insisted, 'Auntie Rika'. That part had gone just fine, even if it was bewildering. The woman had her sempai's trust, so Kanae decided that she could trust her as well."
    "It was staggering to realize that she could meet someone who had gone through something so like what she had.... But Rika had found a happy ending after getting through her trials, and seemed convinced that Kanae could, as well!"
    "She had wanted to believe it anyway, but hearing that.... And of course, when Kanae related her own story, the older woman had given her a comforting hug. Okay, so parts of that made Kanae a little jealous, but Rika assured her that if she didn't run (and she drank her milk) that problem would solve itself as she got older."
    "So, in high spirits, she hadn't really thought about things, and when she was visiting with Rena, had carelessly let something spill.... Though, thinking about it, didn't that boy that her sempai had protected her from share a family name with Rena?"
    "Even though it wasn't far off from the light in her sempai's eyes -- both of them, really -- when they were angry and protective, it was still scary to see that! So she just followed at her Mikuru-onee's side when they were ushered from the building by Keiichi and Mion -- which made a bit more sense once Kanae understood their relationship."
    "In that light, it wasn't really that hard to imagine some future where she had a home like Rena's, and her sempai...."
    "But the mood was still a bit too tense to let herself be drawn into that particular daydream. She shivered, smiling when Mikuru gave her a comforting squeeze. They were all together, right? And Rena.... Well, she was together with her special people, too, wasn't she?"
    "She shook her head and tried to clear it. Really, the only problem was that Sasaki was alone. Though ... the way that Haruhi was approaching things...."
    "As though to confirm that thought, Haruhi sighed and rose from her seat. \"Alright,\" she said briskly. \"Tsu-chan, let's make some tea. Ah ... Sasaki-chan, why not move to the couch? That'll make serving tea easier.\""
    "As much as Kanae would have liked to sit next to her sempai, she thought she understood what Haruhi was getting at. Sasaki nodded in distraction and rose, taking a half-step toward the recently vacated seat at the side of Kanae's sempai before confusion showed in her eyes."
    "\"I...it will?\" Sasaki wondered aloud. Seated around the room in other chairs, the other girls just gave small shrugs or smiles; they knew what was happening, after all."
    "Kuyou alone merely looked to one side before standing up and announcing, \"Cookies.\" From there she treaded toward the kitchen after Tsuruya and Haruhi on silent feet, while Yuki gave a tiny nod."
    "Kanae's sempai looked deep in thought, seeming not to have noticed. Smoothing her skirt down, Sasaki gave an uncertain shrug and gingerly took the seat that Haruhi herself had vacated. \"I ... I suppose so,\" she finally allowed, offering a faint attempt at a smile toward the boy at her side."
    "He shook his head to dispel some lingering thought and flopped backward on the couch, his arms up across the back of it. Kanae had to wonder ... would he end up accidentally hugging Sasaki? There was that time she was watching anime with him and...."
    "\"I don't know what we should do about this ... or if we should really do anything,\" he finally sighed."
    "\"W...well, regardless of if we should or shouldn't,\" Sasaki began, \"what could be done?\""
    "Yuki silently raised her eyebrows, while Kanae had to wonder herself."
    "\"He pulled a knife on Kanae-chan,\" her sempai said flatly. \"He also tried to assault Tsuruya-hime. I'm not really feeling that charitable after that ... but I guess I could try and get him to reform. Then again ... I don't even know why Aunt Rena is upset -- is she mad that I beat up her nephew? Or is she upset about her nephew doing something like that?\""
    "\"I don't think she's upset with you at all, Kyon,\" Sasaki volunteered. \"I only got a chance to meet her a little bit ago, but even so.... Based on the evidence and behavior, I would think she wanted him to behave better?\""
    "\"Hum,\" Tsuruya mused, stepping back into the room, bearing a tea tray. \"Well! If she wants him to be disciplined, if she wants him to be taken care of -- both of those things can be easily handled! But -- isn't it cute that Kyon-kun is more concerned about Kanae-chan being threatened with a knife?\""
    "\"Eh?\" he wondered, turning to look at her. \"I have to look out for my kohai!\" he protested."
    "\"Yeah, but you think that is more severe than him ... what was that little thing ... oh, yeah, shooting you,\" Haruhi noted, rolling her eyes as she followed Tsuruya into the room with another tray. Passing out cups, she added, \"But ... it is nice that you worry so much about the Brigade.\""
    "\"Kyon is best saiko-komon,\" Tsuruya agreed, nodding."
    "Sasaki's eyebrows rose at that."
    "\"Anyway, what was this idea you had, Tsu-chan?\" Haruhi asked. \"The jerk who did all that....\""
    "\"Right!\" Tsuruya agreed, pouring tea carefully in one cup after another. \"So, we can offers him a position -- he will have work! And be taken care of! I still don't like him at all, but it would let us keep a very, very close eye on him!\""
    "\"And that is one organization that would ensure he behaved,\" the boy allowed, sitting forward slightly and accepting a cup. \"I'm still not sure we want him in the Tsuruya-tachi, though. Well, how does that saying go ... keep your friends close, and your enemies closer? I'm not sure I buy that, but keeping tabs on him doesn't seem like a bad idea at all. Jun at least had that....\" He paused, then shifted his shoulders in a minimal shrug. \"There were extenuating circumstances for him -- Ryuugu didn't really have that.\""
    "\"So we give him to Masao,\" Tsuruya said with a grin. \"Didn't he want to work for that group anyway? Masao certainly won't let Ryo-chan jeopardize his new position!\""
    "\"Well, we know they should be on best behavior...\" he mused, nodding thoughtfully. \"I guess that can work -- good thinking, Tsuruya-hime!\""
    "The heiress blushed, setting her tray on a side-table and sitting next to her fiance once more. \"Thankie!\" she chuckled."
    "\"Well, in any case, that'll let us have someone keep a close eye on him, at the very least -- maybe make him apologize to Kanae-chan, too,\" Haruhi allowed, sitting next to Sasaki, nudging the girl closer to the boy between her and Tsuruya."
    "Sasaki nervously shifted to give Haruhi more room, edging closer to Kanae's sempai and glancing at him and then away quickly. Before he could move to give her more room, Tsuruya edged closer to him, sidling right up to him. Ah! Kanae wished she could have joined in!"
    "He didn't seem to notice, other than glancing at her briefly, returning her smile before nodding. \"Alright,\" he agreed. \"Still.... I do wonder what happened. It's probably a good thing that Aunt Rena has such good friends to calm her down.\""
    "Just walking back into the room, Kanae's Mikuru-onee blinked at hearing that, cocking her head to one side. Kuyou was just behind her, and both were carrying plates of cookies."
    "\"That ... actually brings us to another topic of discussion,\" Haruhi said thoughtfully. \"You know, Kyon, how I promised I was going to give you proof of something?\""
    "\"What's this?\" Sasaki wondered."
    "\"I-- Oh, y...yeah, is this the time for that?\" he asked uncertainly, his face slightly reddening."
    "Glancing at Sasaki briefly, and then back to him, Haruhi gave a confident nod. \"It absolutely is,\" she insisted. \"Mikuru-chan, Kuyou-chan, pass those cookies out and make yourselves comfortable; we need to make the most of the time we have!\""
    "* * *"
    "Prompted by Haruhi's instruction, Mikuru nodded, handing out cookies before setting the tray aside and taking her seat next to Kanae. The slider was so cute when she accepted a cookie, holding it in both hands and blushing. Mikuru wanted to give her a hug! Well ... why not? She was supposed to be the slider's big sister anyway!"
    "She giggled cutely when Mikuru gave her a gentle squeeze, as Kuyou drifted to sit next to Yuki."
    "\"Okay!\" Haruhi said, nodding. \"Kyon, let's talk about your aunts and uncle!\""
    "\"What does that have to do with anything?\" he wondered, putting an arm around Tsuruya when the heiress leaned against him."
    "Sasaki's eyebrows rose as she glanced at Haruhi, then back to Kyon."
    "\"Um ... where to begin,\" Haruhi sighed. \"So -- have you ever wondered about the fathers of your cousins?\""
    "\"Huh?\" he asked, furrowing his brow. \"Not especially, no -- I mean, they were never around that I remember, except for Uncle Keiichi. Why?\""
    "\"You had an older cousins,\" Tsuruya offered. \"Auntie Mion's first daughter?\""
    "\"Er, I remember ... Nee-chan,\" Kyon agreed, blushing faintly and avoiding meeting her eyes. \"What about her?\""
    "\"Just--\" Haruhi started, before shaking her head and prompting, \"So, she had to have a father, obviously.\""
    "\"And he was out of the picture before I was born,\" Kyon returned."
    "\"Think about it,\" Tsuruya said, nodding."
    "\"So, then,\" Haruhi said cautiously, \"where is the father of Makoto and Naota?\""
    "\"Well--\" Kyon started before blinking. \"I....\" He raised the arm nearest to Sasaki and scratched his head. \"They probably got back together at some point. There were a few years where we didn't visit here, much.\""
    "\"I've never seen a picture of that cousin, but did she had a strong familial resemblance?\" Sasaki wondered."
    "\"Uh, yeah, I think she looked mostly like Makoto at the same age,\" Kyon said, nodding. Mikuru managed to stifle a gasp when Sasaki shrugged, incidentally nudging Kyon, who absently dropped his arm across her shoulder in response. Sasaki's eyes widened, and she managed to bite back a squeak of alarm -- though she didn't try and push Kyon away or break free. Haruhi grinned triumphantly at the other girl's expression."
    "Sasaki appeared completely bewildered by the response, and looked across the others for support. Mikuru managed a smile for her, but was starting to suspect something on her own.... \"Well,\" Tsuruya pressed, \"what does that make you think?\""
    "\"That things have been tough for Aunt Mion?\" Kyon asked, frowning. \"I mean -- think about it -- I guess whoever her husband was, he was a jerk, especially if he ditched her twice.\""
    "\"Ha--\" Sasaki started, before coughing. \"Um, has your aunt ever actually been married?\" she managed."
    "Kyon started to turn toward her, but was distracted by Tsuruya squirming around a bit, managing somehow to look completely innocent while she did it."
    "\"She must have,\" he answered, shaking his head slightly. \"I mean, she's got her reputation to think of, doesn't she?\""
    "\"Yeah, the local head of the ninkyo dantai family that pretty much controls the entire valley must be super concerned about her image,\" Haruhi jibed, rolling her eyes."
    "Kyon turned to look at her despite Tsuruya's distraction, somehow missing that he was holding Sasaki in one arm, and gave Haruhi a level stare. \"What's that supposed to mean?\" he asked."
    "Sasaki blushed silently, giving Tsuruya a helpless, beseeching stare. The heiress just winked at her, grinning widely, which only served to make Sasaki's eyes widen in surprise."
    "\"I mean, she only has the support of the village's most prominent shrine maiden and your uncle to help her out, right?\" Haruhi asked dryly."
    "\"You're saying my aunt never married?\" Kyon asked, looking somehow uncomfortable about it."
    "\"D...did any of them?\" Sasaki managed."
    "Kyon opened his mouth to reply, then cocked his head to one side, falling silent. Mikuru stared, wondering if he'd noticed Sasaki's position yet -- Haruhi and Tsuruya were certainly very good at what they were doing, she had to admit! \"W...well, I ... don't remember any weddings, come to think of it,\" Kyon allowed quietly. \"But what are you getting at? You think that Aunt Mion's children have different fathers, or something? And why are we discussing this, anyway?\""
    "\"I'm actually positive Auntie Mion's children have the same fathers,\" Tsuruya chuckled, drawing Kyon's attention."
    "He settled slightly, despite still looking confused."
    "\"The point of this relates to that proof I promised you,\" Haruhi clarified."
    "\"How?\" Kyon asked doubtfully. \"Er ... I mean.... And is this something we should be discussing....\" He trailed off and blinked, looking at Sasaki in surprise. Before he could yank his arm away, Haruhi glomped onto it -- and Sasaki -- pinning him down. Tsuruya likewise grabbed onto him, cementing the lock. \"Gah,\" he managed, flushing red. \"Um-- Uh--\" he fumbled, looking nervously away."
    "Yuki raised an eyebrow and sipped at her tea wordlessly, while Kuyou blinked attentively, holding a single cookie in both hands and nibbling at one edge of it."
    "\"H...Haruhi, maybe we should let Sasaki go?\" he finally managed anxiously."
    "\"It was just an accident, I'm sure,\" Sasaki offered quickly, looking just as nervous."
    "\"Perils of Kyon's role,\" Tsuruya said, still smirking."
    "\"Don't spit out that 'sister' line and hurt her feelings like you did with Kanae that time we were watching anime,\" Haruhi added, mirroring Tsuruya's smirk, minus the exposed fang. \"That's not really how you are with your sister, anyway!\""
    "\"This ... is probably-- It's just friendly, though,\" Sasaki said, almost desperately. \"S...so it's fine! That's, um, why Tsuruya-san doesn't mind ... probably....\""
    "\"No, it relates to Kyon's aunts and uncle,\" Haruhi returned authoritatively."
    "\"Eh?\" Sasaki squeaked, looking stunned again. \"B...but that would mean....\" She looked across the other girls -- Mikuru and Kanae gave their own shrugs and weak smiles. Yuki watched wordlessly, merely accepting a cookie from Kuyou when she offered it. The dark-haired girl blinked incredibly slowly, not looking away in the slightest."
    "\"I'm a little jealous,\" Kanae admitted. \"Um, but.... What is this about? Other than Sasaki-san, I mean....\""
    "\"I am so confused,\" Kyon sighed, giving up on wrestling free. \"Um, sorry, Sasaki....\""
    "\"I ... don't mind,\" she mumbled in answer, giving up and leaning against him."
    "\"That's better,\" Haruhi judged. \"Anyway -- think about it, Kyon. What kind of comparison are we trying to make, here?\""
    "Rolling his eyes, Kyon complained, \"I don't know!\""
    "\"R...really?\" Sasaki asked meekly. \"W...wait, Suzumiya-san, are you suggesting that I--\""
    "\"Yes,\" Haruhi answered unhesitatingly. \"Except I'm 'Haruhi' to you, remember?\""
    "\"But--\""
    "\"It's fine!\" Tsuruya insisted. \"We discussed this last night after Kyon-kun went to sleep, and we all agreed!\""
    "Mikuru nodded at that, along with Kanae, sitting in her lap."
    "\"...um....\" Instead of protesting further, Sasaki gave a small sigh and settled against Kyon, unable to hide a little smile for the situation despite her blush."
    "\"Will someone explain things to me?\" Kyon protested."
    "Kanae nodded, looking between the older girls curiously."
    "\"Blind spot the size of Hokkaido,\" Haruhi sighed."
    "Giggling, Tsuruya added, \"It's cute, though!\""
    "\"Hey!\" he protested, frowning."
    "\"Kyon-kun, I'm not sure how to tell you this,\" Mikuru managed tremulously. \"But, um, I think ... all of your cousins have the same father!\""
    "He blinked at that. The only response he could manage wasn't quite a question as he eked out a, \"What.\""
    "\"There ... is a very clear familial resemblance,\" Sasaki agreed."
    "\"I'm going to find and kill the bastard that abandoned my aunts!\" Kyon declared, suddenly scowled. \"What a jerk! How could he--\""
    "\"Uh, hold up a moment before swearing vengeance,\" Haruhi interrupted, snickering. \"Think, Kyon!\""
    "\"I just thought they were all cute!\" Kanae allowed. \"Sempai ... do you mean ... you didn't know that your uncle Keiichi was the father of all your cousins?\""
    "Mikuru nodded, patting Kanae gently on the head with an encouraging smile for making the observation."
    "Kyon blinked, his anger -- rare as it was to see -- vanishing behind a wall of confusion. His mouth dropped open a short distance as he stared blankly for a long minute. \"I ... am having the craziest dream,\" he finally deduced, shaking his head."
    "Tsuruya blinked, staring at him. \"Really?\" she chuckled, grinning even more widely after a moment."
    "Rolling her eyes, Haruhi ordered, \"Right -- dream -- so kiss Sasaki-chan already. You can get away with that in a dream without getting in trouble.\""
    "\"Eh?!\" Sasaki squeaked, face reddening. \"B-but--\""
    "\"Why not?\" Kyon muttered. \"I'm already going to be heading to the special hell anyway, so--\""
    "\"I-- But--\" Sasaki started to protest, despite tilting her face up and offering no resistance at all when Kyon moved to kiss her. He froze, his lips a hairs-breadth away from hers. Just as he started to second-guess himself and pull away, Sasaki muttered, \"Oh, why not? I must have fainted -- so I might as well....\""
    "And before Kyon could pull away, she pressed her lips firmly against his. Kyon gave a half-shrug before reciprocating, the kiss turning deep and searching. Sasaki gave a pleased, almost purring sigh of appreciation as she succumbed, and Mikuru had to fan her face ... he really was quite good at it, after all!"
    "Unable to stare at him and Sasaki while they were...."
    "Mikuru couldn't help herself, and despite how silly it was, she covered Kanae's eyes with one hand and looked away. Her gaze fell on Yuki, who was watching Kyon quite avidly, her expression betraying the faintest smile. Was she ... proud of her part in teaching Kyon that skill?"
    "Kuyou watched with almost as much interest, still nibbling her cookie as an eyebrow rose."
    "Finally, he released Sasaki, who looked about ready to burst into flame, but also unmistakably pleased about the situation. \"Ahm,\" she managed, collapsing almost bonelessly against Kyon's side. \"Good ... dream,\" she sighed, nearly purring."
    "Rolling her eyes, Haruhi pinched Sasaki's upper arm, prompting the girl to flinch."
    "\"Ow!\" Sasaki protested. \"What was ... that....\" Her expression shifted to stunned amazement. \"Um....\""
    "\"What does that--\" Kyon let off with a yelp when Tsuruya affectionately nuzzled him and then nipped his ear. \"...Haruhi,\" he protested, sighing. \"I can't believe-- I'm so overwhelmed with-- I can't properly keep track of.... Oh, man -- there's no way I can properly apologize to Sasaki for this!\""
    "Haruhi snorted. \"Yeah, well, now you've ruined her for marriage,\" she warned."
    "\"What!?\""
    "\"Ah, n-no, I--\" Sasaki began, before Haruhi covered her mouth."
    "\"Utterly ruined!\" Tsuruya agreed. \"You'd better promise to take care of her!\""
    "\"But-- But--\" Kyon started to protest."
    "Mikuru giggled as understanding dawned, and Kanae finally pulled the older girl's hand from her eyes. \"Aww,\" she protested. \"I missed the entire thing! Mikuru-onee....\""
    "\"Ah, um,\" Mikuru realized belatedly. It probably was a bit silly, considering Kanae had kissed Kyon on her own...."
    "\"Well?\" Haruhi prompted."
    "\"This is it,\" Kyon swore, shaking his head. \"Seriously -- doesn't this just seem like way too many girls for one guy? Anyway -- you still haven't proven that this.... Uh this ... whole idea....\" He trailed off in stupefied amazement."
    "\"S...so, am I to understand that ... the idea is that we ... enter an arrangement much like Kyon's uncle has with his aunts?\" Sasaki posed tremulously."
    "\"...huh,\" Kyon completed, looking stunned. \"But-- No, I can't imagine that Sasaki would want--\""
    "\"I...I really don't mind,\" Sasaki offered shyly. \"I might ... be a bit selfish at certain times, but.... Well, to be completely honest, I lost a chance I very much wanted in middle school ... so if I can reclaim just a bit of that, and share it with ... people who are looking out for and care for me as they do ... that would make me extraordinarily happy!\""
    "\"...I have no idea what to say,\" Kyon confessed, slumping. \"I.... I guess ... you win that argument, Haruhi. I ... have no idea how this whole thing is supposed to work, but if you've got some crazy plan....\" He trailed off when she scowled at him. \"Well, your crazy plans usually do work somehow -- alright, I'm putting my full trust in you, then!\""
    "The Brigade chief nodded decisively at that. \"Good!\" she declared. \"Like the rest of us agreed last night!\""
    "\"I can't help but notice that I wasn't brought into these discussions,\" Kyon remarked, frowning."
    "\"Are you really complaining?\" Tsuruya asked, grinning. \"Really?\""
    "\"...I guess not,\" he admitted very softly, not meeting anyone's gaze."
    "\"Great!\" Haruhi declared. \"Now you just have to figure out how to explain that ... other thing to Sasaki.\""
    "\"Yeah, okay,\" Kyon agreed, nodding. \"Seems reasonable in comparison!\""
    "\"What other thing?\" Sasaki wondered, before gasping. \"Oh, goodness -- Kyon, did you already.... So, um, when is Tsuruya-san due?\""
    "Kyon blinked and started to form a response before his jaw went slack and he stared numbly."
    "Mikuru gasped and covered Kanae's ears. \"Goodness!\" she yelped, eyes widening as her face warmed up. \"I-- I had no idea! Um -- congratulations?\""
    "Haruhi twitched, then shook her head vigorously. \"Uh, a bit too soon!\" she declared. Eyes narrowing, she regarded Tsuruya. \"Unless....\""
    "\"No, no!\" Tsuruya choked, before she started howling with laughter, and nearly fell out of her seat. \"Hahaha-- No, not that -- yet!\""
    "\"Gah,\" Kyon eked out."
    "Sasaki blinked. \"Then ... what is it?\" she wondered in confusion, as Haruhi caught the infectious laughter."
    "\"...oh, boy,\" Kyon sighed."
    "\"Unique,\" Yuki commented, finishing her tea as Kanae broke free of Mikuru's weak hold and started giggling on her own."
    "* * *"
    "Since their purpose in Hinamizawa was to have a vacation, Koizumi made the most of it -- and generally, that meant enjoying his time with Kyouko without anything more serious to worry about. Though, that was serious enough, really."
    "There were worse ways to spend time than enjoying picnics with a very pretty and intelligent girl, however."
    "Even better, the vacation seemed to be doing some real good for the other esper. Hopefully things would continue on that trend once she started attending Kitago."
    "Though, that would be quite a change."
    "So the pair of them had gone for another walk to one of the area's innumerable picnic spots -- the views were pleasant, but tended to become very similar to one-another after the second or third one. Well, it was about the company more than the view, so that didn't seem to be a real issue in any case."
    "It was a novel change, though not one he minded, to think of the other esper as his girlfriend -- in point of fact, he'd never actually had one of those before. He could certainly do worse than her, in his mind!"
    "He was still mulling that thought over as they slowly walked back from their picnic spot -- they hadn't brought enough to have a dinner after their lunch. He held the basket in one hand, while his other hand grasped hers. Her other arm was holding a blanket to her chest as she looked thoughtful, but even as he glanced at her, her gaze dimmed, seeming to turn distant."
    "Her step faltered, and she stood still, tilting her head faintly to one side. \"Something on your mind?\" he prompted gently, giving her hand a soft, reassuring squeeze."
    "\"Um, it's Sasaki,\" she explained, giving a shake of her head. \"Remember what I said about her feelings for Kyon? Well ... she's ... not able to be as fortunate as me, so....\" She trailed off, blushing darkly, though she smiled and couldn't meet his gaze. \"Ah-- Um, anyway....\""
    "\"That must be difficult,\" he sympathized. He could recall well enough the ... oddity of his own connection to Haruhi. Of course, it was worst when Haruhi was actually ... enjoying Kyon's presence. Thankfully, that was something he was free from, but it would take a bit of work before Kyon got to that level."
    "\"I'm not.... I-- I think Sasaki's asleep,\" Kyouko said slowly, her cheeks still inflamed, her breathing speeding up faintly."
    "\"Oh?\" Koizumi wondered, frowning. \"At this hour? That's surprising.\""
    "She nodded faintly, her hand tightening on his as her lips parted with a quiet gasp."
    "\"Ah,\" he realized, starting. \"Has something happened? She's been kidnapped, perhaps?\""
    "Kyon could probably handle that, but Koizumi would want to do his part to take care of things -- well, if he had to, he could turn into energy and fly the pair of them to the house quickly. Shaking his head before Kyouko could respond, he asked, \"Kyouko-chan, would it be alright for me to link with you?\""
    "\"Ah, heh,\" she chuckled, before dropping the blanket and practically pouncing at him, her lips pressing against his with unexpected ferocity."
    "Oh, he realized with faint surprise, recognizing that sensation from her thoughts and feelings."
    "Yes, he would have to explain a bit about Kyon's ... arrangement."
    "He made a mental note to talk to Kyon most sternly about the importance of helping Kyouko get disentangled from Sasaki's state before she released his hand and wrapped both arms around him."
    "He kissed her back anyway, and when she finally broke for breath, he managed, \"I-- I'll see what I can do to put an end to that for you.\""
    "\"Why?\" she asked, bewildered. \"I don't-- Sasaki's just having a nice dream, and ... as long as you're there....\""
    "Blinking in surprise, Koizumi couldn't find anything to say before she started kissing him again."
    "...why not, he decided, dropping the picnic basket as he returned the kiss again, his own arms wrapping around her."
    "Some time later, when they had smoothed their clothes back into place and picked up the items they had dropped, Kyouko gasped in belated realization. \"Oh-- I-- Um, d-don't mention anything about that to Sasaki!\" she exclaimed. \"It-- It would be so embarrassing for her if we were to discuss....\""
    "She trailed off, staring at her feet, cheeks red."
    "He scratched the back of his head, frowning. Based on his guess, Sasaki wasn't actually dreaming. Really, that would make the entire thing the Brigade Chief's doing, in any case."
    "Still...."
    "\"I will be most discreet, Kyouko-chan,\" he promised her, nodding."
    "* * *"
    "As much as she would have liked to press the issue, the sound of the front door being opened, and the excited chatter of Kyon's cousins quickly prompted Sasaki to sit up straight, instead of ... well, being entirely honest ... cuddling up to Kyon. She was still unsure what she'd just gotten herself involved with, but ... if she could enjoy occasional moments like that with Kyon ... she didn't mind that much."
    "She had to admit a small bit of annoyance at Haruhi for hiding that from her, given how hard Sasaki was trying to be her friend ... but she could actually understand Haruhi's reasons. If it weren't for the example that Kyon's uncle was providing, it would be rather hard to believe such a thing could work! But seeing how happy Kyon's aunts seemed -- Rena's ... episode notwithstanding -- she wanted to believe it could work!"
    "Kyon was willing to work toward it, and Tsuruya, who she had thought was the only girl 'in Kyon's life', so to speak approved as well, so...."
    "She wasn't sure how, yet, and she was especially uncertain about ... being kissed in front of so many others. She would really like some time with Kyon alone -- or at least only Haruhi present. His aunts seemed to have an arrangement that afforded a bit more privacy, so some day...."
    "In the meantime, while she felt she had to at least gently chide Haruhi for not telling her about the plan before, being a close friend with her seemed like an even better idea than it had been."
    "She shook her head, realizing she'd been distracted, and Kyon's adorable little cousins (his uncle's children, she reminded herself) had crowded into the room. Matsuri was staring at her with hooded eyes for some reason, looking suspicious. \"What's wrong with this nee-chan?\" she prompted, putting her hands on her hips."
    "\"The mountain air,\" Tsuruya said quickly. \"Short on breath after the hike up the hill!\""
    "Stepping in after the children and looking a bit weary, Mion looked up. \"You only just got back?\" she wondered. \"Well -- it's a steep hill, especially if you're not used to it.\""
    "\"Um, yes,\" Sasaki agreed, when Yurie stared at the empty teacup she had managed not to drop, tapping her lower lip thoughtfully."
    "\"Where's uncle Keiichi?\" Kyon wondered, unable to stop staring between his collected cousins."
    "\"Oh, he's ... going over some paperwork with Rena-chan, Satoko-chan, and Rika-chan,\" she offered."
    "Kyon bit his tongue, rather than question anything further in front of the cousins, nodding doubtfully."
    "\"Ah -- since we're all here, again, should we play a game?\" Mikuru prompted, before he could dwell."
    "The children unanimously cheered, even Matsuri brightening a bit."
    "\"Yes -- that's a good idea!\" Mion approved, nodding. \"Ah ... let's see. I might need to kidnap one of these charming girls to help in the kitchen later, though.\""
    "\"I-- I'd be glad to help!\" Mikuru volunteered quickly."
    "\"Help?\" Mion asked, smirking. \"You'll end up running that kitchen, I've got no doubt!\""
    "The older girl blushed at that, ducking her head at the praise."
    "\"Before that, though -- Kyon-kun, there's something that Kei-chan and I have to take care of tomorrow, before the festival starts. Would you be willing to join us?\" she prompted."
    "\"Er, I don't think that would be a problem,\" he agreed, glancing at the others before shrugging."
    "\"Can I help?\" Matsuri wondered, perking up."
    "\"Ah, you need to get ready for the ceremony,\" Mion countered, shaking her head. \"But Makoto, Naota, you two will be coming along as well -- it's a family tradition. My grandmother started it, and then my mother took responsibility, and until 100 years of Sonozaki have fulfilled the debt, it shall continue!\""
    "\"That's an impressive tradition!\" Tsuruya exclaimed. \"Should I join as well?\""
    "\"I don't see a problem with that!\""
    "Matsuri pouted. \"I wanted to spend time with Kyon-kun,\" she muttered."
    "\"I heard about that,\" Kanae mused. \"You're a shrine maiden in training, aren't you?\" she asked the younger girl."
    "The younger girl puffed up faintly with pride. \"That's right!\" she declared. Looking at him expectantly, she pressed, \"Kyon-nii is going to watch me, right?\""
    "\"I should be able to,\" he agreed, scratching his head. \"Er ... won't I, Aunt Mion?\""
    "\"You certainly should!\" Mion agreed, smiling. \"Alright ... hmm, come to think of it, I should probably pass on playing a game and get started on making dinner for this big a group!\""
    "\"Ah, let me!\" Mikuru protested, hopping to her feet. \"Um, I have to repay your hospitality!\""
    "\"What, you think you can do it alone?\" the woman wondered, smiling gently."
    "\"W...well, maybe,\" Mikuru allowed. \"Um, but if I can have help from Haruhi-chan and Yuki-chan, it won't be very hard at all!\""
    "\"Yeah, I should do something to help out, and not just have fun,\" Haruhi agreed, nodding. \"Alright, come on, Yuki-chan.\""
    "Giving a tiny nod of her own, Yuki drifted to her feet, silently following the other girls into the kitchen, while Kuyou stared after them wordlessly."
    "\"...I'm not even included in my own kitchen?\" Mion asked."
    "\"Well, you can hardly cook, Mom,\" Naota noted, shrugging as he produced a deck of cards, while his sister rifled through a stack of boxed games."
    "\"Aww, that's so sweet!\" the woman gushed, tousling her son's hair."
    "\"Is that so?\" the Houjou twins asked in tandem, eyebrows rising."
    "\"I was going to see if I could trick some of Kyon's friends into doing the dishes, but since you volunteered, I guess I don't have to!\" Mion confirmed warmly."
    "\"What did I say?\" Naota whined plaintively, wilting."
    "Sasaki had to chuckle along with the others."
    "* * *"
    "\"Miyuki-chan, you're on vacation,\" the officer's father gently scolded her."
    "She started, looking up from the report that had been e-mailed to her on her cell phone. \"S...sorry,\" she muttered, feeling her cheeks heat up. \"You know how it is to be really focused on a case, though.\""
    "\"I certainly know how both of you can get about it,\" her mother remarked, glancing back over her shoulder to the rear seat of the car. \"It's just as well we dragged you out of your stuffy office for some fresh air!\""
    "Miyuki nodded and put her phone away; this particular lecture was much better than the line of questioning about her settling down and providing grandchildren. A glint in her mother's warning gaze told her not to reach for her phone again, or that lecture probably would end up being the topic of the day."
    "As much as she loved her parents, and they were the only other family she had...."
    "She stretched a bit -- as much as she could in the car, and stared at the surroundings instead. Of course, her mind still turned to the last update she had gotten. More and more, there were hints that the boy she was watching so closely was involved in something illegal, but hard evidence was much harder to come by."
    "There were things she had as evidence in theory, but was extraordinarily reluctant to try actually using before a judge -- or even her superiors. Footage of him vanishing into thin air? Appearing out of it? In the one instance, it had seemed he was about to get into a fight and draw a weapon, and in the other, he was in a secured area, evidently missed by all of the guards."
    "But how believable would those end up being if she tried to bring them to bear? The inexplicable parts would make everything else suspicious by circumstance. If she could find concrete evidence, instead of trying to use questionable circumstantial evidence...."
    "Of course, she wasn't helping her cause by taking a vacation, but what were the chances of missing something important? That was the reason she had aides and lower ranking members to assign to the task."
    "And thanks to that, even though she wasn't there to see it for it herself, they had one bit of evidence."
    "Miyuki didn't see much reason to bring him in for speeding, however. And wherever he was driving, he'd gotten away from the people watching him, so that wasn't going to help at all; better to let him do something else they could arrest him for."
    "Which was the reason she was checking her updates on his location. At least as of twenty minutes ago, he still hadn't done anything that would help her cause ... but she knew where he was."
    "\"Miyuki-chan, could you grab the flowers?\" he mother asked, as her father pulled into a parking spot."
    "She shook her head scowling internally at how she'd let herself become distracted. \"Of course,\" she agreed, picking up the small vase sitting on the floor between her feet so it wouldn't spill before opening the door and stepping out. The chill mountain air was refreshing as she surveyed the green hillsides ... and the entrance to the nearby graveyard."
    "The parking lot had a very small number of other cars in it, and Miyuki glanced across them, holding a vase in each hand, until her mother took one from her. Mamoru nodded, giving both his wife and daughter a warm smile before turning more solemn as he regarded the graveyard, linking one arm with his wife's."
    "The Akasaka family walked forward together, with Miyuki trailing behind. She'd met the man who the grave marker they were visiting belonged to -- but it was very long ago. She had distant memories of him giving her candy before playing mah-jong with her parents, leaving her to babysit."
    "\"Ah,\" her father called, nodding to another group standing at the same pair of nearby markers. \"It's very good to see you, old friend!\""
    "Miyuki had to smile at the man, though her expression froze when her gaze went past him ... to the people standing with him. Nishinomiya was more than twenty minutes away by any form of travel, she reminded herself. There was.... There was no way that the sharply dressed young man at Keiichi's side could be—"
    "\"You remember Kyon, right?\" Keiichi said warmly, nodding at Miyuki. Turning to Kyon, he explained, \"You might have been too small to really remember, but Miyuki-chan babysat you a few times, long ago!\""
    "The boy looked just as surprised as Miyuki felt. \"What-- Really?\" he wondered."
    "\"I...it's coming back to me now,\" Miyuki managed, recognizing the Tsuruya heiress in a formal kimono at his side. \"It was ... a long time ago now.\""
    "The similarly dressed older woman -- Mion -- nodded. \"You'd better be nice to her, Kyon,\" she scolded gently. \"She's an NPA officer, and she's changed your diapers!\""
    "\"And here I was worried about the occasion being solemn,\" Kyon deadpanned in reply, blushing faintly."
    "The Tsuruya heiress giggled, reminding him, \"It's your family's duty to embarrass you, Kyon-kun.\""
    "\"Yes, but the skill ranks involved are unparalleled,\" he noted, before bowing to Miyuki. \"That aside -- um, thank you for keeping an eye on me when I was younger, and it's nice to meet you again.\""
    "Miyuki bowed in return. \"Though,\" she realized, \"when you were younger, you were named....\" She trailed off as her eyes fell to one of the grave markers they were visiting. He'd been named after that same doctor, though, hadn't he? That must be why he went by the nickname instead."
    "\"Well, there's no reason to be bashful,\" Keiichi said brightly. \"If I know them at all, Irie-sensei and Ooishi-san would both have wanted us to be able to laugh and smile -- and still be friends!\""
    "\"Absolutely,\" Mamoru agreed with a rueful chuckle. \"Well -- let us remember our fallen friends, then.\""
    "\"R...right,\" Kyon and Miyuki both said, somewhat awkwardly."
    "He scratched the back of his head nervously, while the girl he was engaged to hugged his arm, grinning brightly."
    "Miyuki shook her head, trying to keep a straight face and avoid staring at Kyon too obviously."
    "She didn't even know where to begin, anymore. The target of her investigation was evidently a long-time family friend? She didn't really think back to her vacations with her family often, but she wasn't able to avoid remembering when she'd watched over a younger Kyon while her parents visited their friends."
    "That would be problematic; as soon as her superiors found out, it would be declared a conflict of interests, and she'd be taken off the case. Of course, that was still ignoring several issues, such as Kyon's evident ability to be in two places at the same time -- or any of the other inexplicable things he'd done that she knew of."
    "Well ... now what?"
    "* * *"
    "Since Kyon was tied up in 'family business', Haruhi had decided to explore the festival grounds. At the moment, it was mostly bustling vendors and workers setting up stalls and moving boxes around the area at the base of the stairs leading up to the shrine. Kanae, Mikuru, and Sasaki had joined her, and the group wandered around."
    "She'd like to run around and see everything, but there really wasn't anything to see yet. That was the problem with setting up ... it was like that same phase of the school festival, and she had nothing to do but pensively wait until it was complete." 
    "Of course, the scenery made for a nice change of pace, which didn't hurt. Kanae was wide-eyed and appreciative, even though the festival grounds themselves weren't anything to speak of yet. Sasaki seemed to slowly be adjusting to her borrowed clothing ... Haruhi was actually a bit jealous of that. Admittedly, from what Haruhi could tell, the chest was slightly loose on her, but it looked good -- her own skirt and blouse combo felt bland in comparison."
    "The group was approaching the stage at the base of the stairs -- it wasn't particularly large, but then ... this was a small village."
    "\"This is ... pleasant,\" Sasaki finally tremulously broke into the silence."
    "\"It's not bad,\" Haruhi agreed. \"Somehow, it's really not hard to imagine Kyon here as a kid. Raised by those aunts....\""
    "Sasaki looked curious, but Haruhi shook her head, turning her attention to Mikuru and Kanae."
    "\"Are you having fun?\" she asked."
    "Mikuru's expression was actually distracted, seemingly deep in thought. Kanae, on the other hand, was practically glowing in excitement, calling out, \"Auntie Rika!\""
    "Haruhi and Sasaki turned to regard the woman curiously -- she was dressed in a miko's attire, walking down the stairs with her identically dressed daughter at her side. \"Oh?\" Rika mused, smiling at the girls, while Matsuri was torn between puffing up with pride at her outfit, or jealously glaring at the older girls."
    "Shrugging, Haruhi stepped around the low stage to approach the pair, calling out, \"Good morning, Matsu-chan -- you look cute as a button in that costume!\""
    "She scowled, but before she could snap out a response, Sasaki smoothly added, \"I imagine Kyon-kun will have to agree!\""
    "Matsuri brightened instantly at that, nodding quickly. \"I'm going to practice for tonight!\" she declared, turning around and dashing up the stairs."
    "Rika shook her head fondly, watching her daughter fly up the steps. Turning back to Haruhi, she moved down a few more steps, stopping just beneath the torii. \"Are you girls having fun?\" she asked warmly."
    "\"Ah-- Um, yes!\" Mikuru said quickly, nodding."
    "Haruhi and Sasaki nodded their agreement as Kanae exclaimed, \"Yes! Thank you, um, for yesterday, Auntie Rika!\""
    "The woman smiled warmly. \"I'm especially glad for you, Kanae-chan, given ... your past,\" she said."
    "Blushing, Kanae shied away, ducking her head and bumping into Haruhi. Without really thinking about it, Haruhi dropped a hand on the smaller girl's shoulder and gave her an absent, comforting squeeze. She was so cute!"
    "Rika's eyebrows rose slightly, but her gaze went to Sasaki. \"But the festival won't start properly until sundown. What brings you by so early?\" she wondered."
    "\"Uh ... we're going to try and explain something to Kyon, once he gets back from his errand,\" Haruhi explained hesitantly."
    "The shrine maiden nodded slowly. \"I wish you the best of luck with that, Haruhi-chan,\" she said solemnly. \"I truly do. I don't know if I could be of any help ... but if I can, let me know.\""
    "\"So you know Kyon very well, then?\" Sasaki posed. She blushed faintly, shaking her head with a laugh as she seemed to consider what she was saying. \"Sorry -- that is ... Kyon spoke very little of his family, outside of his parents and his sister.\""
    "Rika laughed at that, grinning, before she stood up to her full height. She also had the advantage of standing on the steps, but managed somehow to not quite loom overhead. \"I am standing,\" she declared, \"on the very spot where Kyon-kun was born!\""
    "Haruhi couldn't help herself; her gaze fell to the stone steps as though to look for some visible clue of it. Sasaki gasped, and Mikuru squeaked in surprise. Even Kanae jolted slightly."
    "Remembering Mion's story that it had happened right here, on a Watanagashi long ago.... \"I remember hearing about that,\" Haruhi allowed, still a bit surprised. \"Though ... Kyon was named after the doctor who delivered him, right?\""
    "\"Ah, goodness!\" Sasaki exclaimed. \"I had no idea there was that much excitement around Kyon's birth!\""
    "\"Haruhi-chan can explain it in more detail later,\" Rika assured her. \"But it's quite a tale.\""
    "\"Um, Auntie Rika?\" Kanae wondered. \"Can I ask a question about Sempai?\""
    "\"I can't see why not,\" Rika returned, shrugging easily. \"What did you want to know, Kanae-chan?\""
    "\"Um ... do you know why he has that nickname?\""
    "\"Because I gave it to him!\" Rika exclaimed, clapping her hands together with a laugh. \"But you want to know the story of why?\""
    "\"Er.... Yes,\" the slider said, stepping away from Haruhi and nodding resolutely."
    "Sasaki and Mikuru looked on, the pair of them exchanging a curious glance with Haruhi. Well ... it was a good question, come to think of it. \"I haven't heard this story,\" she assured them. \"What is it?\""
    "\"I should check on Matsu-chan, so come with me,\" Rika declared, gesturing for the girls to follow her up the stairs to the shrine. \"I'll give you some hot tea afterward, shuu~!\" She mimicked a pouring motion to join the sound-effect."
    "Haruhi had thought the shrine maiden was quite an amazing character after her last visit to Hinamizawa. Certainly, her favorite among Kyon's aunts."
    "Once the girls were following her up the stairs, Rika gestured ahead and explained, \"When Kyon-kun was small, he was very rambunctious, and full of energy!\""
    "\"That, I have a hard time imagining,\" Haruhi said, squinting. \"In fact, I imagine him even as a child not getting worked up about much of anything at all!\""
    "\"Oh, I can imagine it,\" Sasaki countered. \"He was much more energetic in middle school ... and I suspect you've helped him recover a lot of that energy!\""
    "Haruhi bit her tongue, feeling her face warm up. Somehow, when Sasaki put it that way, it felt entirely plausible."
    "Rika's over-the-shoulder-smirk suggested she could see Haruhi rethinking it. Mikuru and Kanae merely looked curious."
    "\"Ah, but Kyon was full of energy and loved to run around and climb on everything, even when he was small,\" Rika continued. \"And one day, when it was my turn to watch him, I brought him to the temple with me. He ran right up these stairs, and then back, and up again -- three times before I reached the top!\" she exclaimed."
    "Haruhi studied the stairs. They were fairly gentle, compared to many shrine steps -- it was plausible. She could imagine a weary Rika trudging up while a chibi Kyon rushed up and down."
    "It wasn't very far to the top, either -- he would have been in sight the entire time. In fact, as Haruhi thought that, they reached the top -- the level area with the shrine building straight ahead, and side-buildings lining the plaza. While some shrines had ornate gardens, this one maintained a clear space, lined with flagstones."
    "She had to wonder if the festival used to take place right on that stone courtyard, before the village grew a bit larger, but that would have been a very, very long time ago. Then again ... the shrine was very old. Directly ahead of them was the offering box, and above it the bell hanging from a heavy rope."
    "\"Of course, once I reached the top he wanted to run aaaaall around the courtyard,\" Rika continued somewhat wistfully. \"And then ... he climbed up onto the offering box.\""
    "Sasaki giggled, and Mikuru gasped, \"Oh, no! Did he fall in?\""
    "\"If only~!\" Rika giggled. \"He loved to climb, so he grabbed onto the cord for the bell and hung on, as tight as he could!\""
    "\"He tried to climb the bell cable?\" Kanae asked, looking at the thing askance."
    "\"And then ... he pulled it out from the trestle, and ka-pun~! He crashed down onto the top of the offering box and the bell came with him!\" Rika continued, gesturing animatedly. \"I was so worried; it crashed into his head and bounced to the ground with a graaaand noise!\""
    "Sasaki gasped, this time, while Mikuru looked agitated, shifting from foot to foot. \"Oh, oh, dear!\" she fretted. \"Was he alright?\" she asked anxiously, before realizing how silly the question was. \"Um ... that is....\""
    "\"I was worried, too!\" Rika assured the time traveler, finally stopping just before the offering box. \"So I rushed to his side -- there was no blood, though.\""
    "Mikuru and Kanae both sighed in relief, though continued staring at Rika intently."
    "\"Naturally, I had to scold him for being so reckless, though I was just glad he was okay,\" she continued. \"So to tease him and remind him to be more careful in the future, I called him after the bell sound!\""
    "\"What?\" Sasaki exclaimed."
    "Tugging the rope, Rika sang a single soft note along with it: \"Kyo~n!\""
    "\"It's not a 'suzu' bell,\" Rika added after a moment, winking at Haruhi. \"It's a 'kane' bell.\""
    "Looking up, Haruhi and the other girls saw why; the bell shaped like a large bronze dish, and the rope had a ringer around it, so that when pulled or swung, it would resonate against the flat surface on the back. From what Haruhi recalled, hitting the back produced a sound usually named 'kon', and the sound from hitting the rim was named 'chin'. If the rope were swung properly, she saw it would bounce off the sides and the back, making a rudimentary chime."
    "More importantly than where the bell was anchored to the trestle overhead, Haruhi could see the damages from long, long ago, where it had been mounted slightly to one side and evidently been ripped out. At a glance, the new moorings were more carefully set in the overhead wooden bar ... and someone had scrawled a message of, 'No climbing!' on the underside of the offering box's awning."
    "\"...and that's where Kyon-kun got his nickname~!\" Rika finished proudly."
    "\"I ... had no idea,\" Mikuru said, looking torn. \"Um ... I want to feel a bit sorry for Kyon-kun, but somehow ... it's a cute story anyway, isn't it?\""
    "\"It makes me want to give Sempai a hug!\" Kanae declared. \"I'm glad he wasn't hurt!\""
    "\"I'm starting to realize that no penalty I could really assign him would match up to his nickname,\" Haruhi said after a moment, shaking her head."
    "\"Somehow, he's really ... grown out of that nickname, though,\" Sasaki countered. \"Um ... I said at one point to Kyon that his own name felt too noble for him....\" She winced at Kanae's sharp gasp, and Rika's raised eyebrows. \"That-- I mean ... his name is so formal and.... I have to think it means something that Kyon lets us call him that and doesn't get upset, even if it's not his favorite thing to be called?\""
    "\"Pin-pon~!\" Rika chimed, making the 'correct' sound-effect from game shows as far back as Haruhi could remember. \"Though, I think that Kyon-kun doesn't remember this story, just the name?\""
    "\"W...well, I wouldn't spread this story around!\" Mikuru exclaimed. \"E...even if it is ... kind of cute that he was so energetic....\""
    "\"Sempai is Sempai,\" Kanae declared resolutely, crossing her arms over her chest."
    "\"I wonder if I should try using his name properly?\" Sasaki admitted with a wince, voicing the thought Haruhi didn't want to have to admit. \"I did ... say to him that I liked calling him by that nickname, but....\""
    "Rika shook her head, smiling softly. \"Kyon-kun will let you call him anything,\" she assured softly. \"And as long as you mean it kindly....\""
    "Haruhi blinked at the realization.... Of course, if she and Sasaki were being tsundere and not calling Kyon by his real name, was Rika suggesting that Kyon knew -- and was okay -- with that? Admittedly ... neither of them were as tsundere as those characters from anime, but real people behaved rationally."
    "Well, more rationally."
    "...somewhat more rationally."
    "Anyway, if that was Rika's point...."
    "\"I.... If we start calling him differently right now it'll raise the question of why,\" Haruhi said aloud. \"But ... maybe for certain special ... occas....\" She trailed off without even finishing the word, eyes widening."
    "\"Hmm?\" Sasaki wondered, tilting her head to one side."
    "\"I-- I think I just realized something,\" Haruhi said slowly. \"Mikuru-chan, we're going to experiment at some point in the future and see what happens if you call Kyon by his name properly.\""
    "\"Eh? I-- Okay, I don't mind, but ... why?\" Mikuru wondered."
    "\"If I'm right,\" Haruhi said slowly, \"it will work just like him calling you 'Mikuru-chan'!\" she declared."
    "...of course, there was a very good chance she'd try it herself first -- it was only right to try something potentially dangerous before Mikuru did, wasn't it?"
    "Rika smirked knowingly and shook her head. \"You should go back to Mion-chan's place if you want to talk to Kyon,\" she reminded gently. \"You'll still have time to dress for the festival, if you want to do that, too~!\""
    "\"Right!\" Haruhi exclaimed. \"We can't forget that -- we have to talk to Kyon before today is over! I made a promise!\""
    "* * *"
    "As Mion had explained it to Kyon and Tsuruya, the traditional observance of the Sonozaki family was to leave flowers for Ooishi and his father. The reasons for Ooishi's father receiving flowers went back to some incident before even Kyon's parents were born, but Mion's mother, and her mother before her, had left flowers for him, and so the tradition continued. Ooishi was left flowers on account of his assistance to the family -- among the bouquets was one picked out by Rika."
    "While Mion assured Kyon and Tsuruya that she would explain the story some other day, she said it wasn't fitting for the pleasant atmosphere -- but that Ooishi had done a lot to help them. Kyon himself was given a wreath specifically to lay on the stone commemorating a doctor who shared his own first name -- the same doctor that had evidently delivered him."
    "If it weren't for just how pleasant Tsuruya's laughter really was, the jibes and teasing directed toward him might wear thin. Of course, he respected the doctor, especially since he could very well owe his life to the man."
    "Encountering the same NPA agent he had thought was investigating events that he was involved with was alarming, to say the least."
    "Having his aunt offhandedly remind him that she had changed his diapers when he was very, very small...."
    "And he'd thought it was awkward before?"
    "Unless he guessed wrong, she was just as surprised as he was, though. Not really sure what to make of it, once their observances at the graves were complete and they were on the road back to her house, Mion explained, \"I have some other errands to run with Kei-chan, but you should have a chance to spend some time with your friends!\""
    "Kyon really wasn't certain how that would work out, considering he'd given up on thinking that Haruhi's arrangement was unworkable. Hard work, almost certainly ... but impossible?"
    "...then again, it was a strange feeling, realizing that his uncle had a similar situation with his aunts."
    "He was still a bit torn on that. On the one hand, he wanted to yell at his uncle for not being there for Mion -- or Rena, or Satoko. On the other hand, there were legal reasons why it was set up the way that it was, and the reason why the cousins were raised as close as siblings became abundantly clear. Because outside of the Houjou twins, they were!"
    "On the gripping hand, Mion certainly didn't seem unhappy. Rena and Satoko didn't, either. In fact, Keiichi traveling with Rena should have been more suspicious, but then, what Haruhi had said...."
    "As he and Tsuruya strode to the door, he sighed and muttered, \"...it really is the size of Hokkaido.\""
    "Her eyebrows rose before she blinked in understanding and stopped him from opening the door, taking his hand in both of her own. \"It's okay,\" she reassured him, eyes shining, grinning like she always did. \"You know, it was driving back from this village that Haru-nyan made me the offer to have part of you for myself, too?\""
    "Kyon couldn't help but raise his eyebrows at that. \"She was planning it from then, huh?\" he wondered, shaking his head. \"I guess ... hmm, she probably figured out what was going on, didn't she?\""
    "Tsuruya looked mildly evasive. \"You probably have a blind spot because you grew up with it,\" she explained. \"But that's okay. It will not be easy, always ... but as long as we work together, it will be alright!\""
    "He nodded thoughtfully. \"You're probably right,\" he agreed. \"I should ... try not to worry about it so much, shouldn't I?\""
    "Tsuruya's smile faded as her expression turned thoughtful. \"I think it's good that you worries,\" she countered. \"You shouldn't worries so much that you can't do anything else -- but you worry because you're thoughtful. And that ... is something I am happy for, Kyon-kun ... that's one of the reasons....\" Her cheeks took on a blush, as she grinned again. \"Well--\" And then she leaned forward and kissed him, evidently deciding that words weren't needed."
    "He didn't let himself kiss her back reflexively; he didn't want to do things like that without thinking. If Haruhi and the others were going to be going so far, he had to pay it back. No absently putting his arms around someone, or kissing them just because they were close. From that day forward, he promised himself, everything -- all of it -- would be intentional. Not just any girls -- but the girls he was going to try and be with -- and no one else."
    "So focusing on it, releasing Tsuruya's hands to gently encircle her with his arms, he kissed her back with all of the purpose he could muster. He had only so much time to spend with each of them ... but was he really doing Tsuruya any favors worrying about everyone when she was with him just then? That was probably what she meant by not worrying too much. He couldn't forget, obviously, but that...."
    "It was some time before they finally broke for breath, Tsuruya grinning even more hugely than usual, leaning against him for support as she breathed heavily, still recovering."
    "\"Haha,\" she chuckled softly, turning her head to rest it against his chest. \"Kyon-kun, tonight I will give you a massage to repay that!\""
    "He felt his face heat up, and was still a bit dizzy himself from the kiss. Somehow, for once, Haruhi hadn't managed to pop in mid-kiss and record him.... \"I ... can't complain about that,\" he agreed dazedly, grinning back."
    "\"But -- happy birthday, Kyon-kun!\" she added, straightening up from their embrace and opening the door, where he was startled to see all of the other girls staring expectantly."
    "\"Er,\" he managed."
    "Before he could go any further, Kanae cried out, \"Surprise!\" and was quickly joined by the others."
    "And somehow, he had to admit -- he hadn't seen that coming. \"Say,\" he realized belatedly. \"Where are Koizumi and Tachibana, anyway?\" Asakura was accounted for thanks to being with his sister, but the espers hadn't stayed near the house very much." 
    "Grinning triumphantly and wearing a pointed, conical hat atop her head, Haruhi shrugged and said, \"He said something about needing to explain something to her and wanting to be somewhere private with her while we were having our celebration. I'm not sure why, but she seemed really excited, for some reason....\""
    "Kyon wondered what they might have been talking about, anyway...."
