label Re_3:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 059 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
    "Haruhi was mildly annoyed that even when they cheated and used teleportation, the traditional post-journey tiredness seemed to set in on the entire group. Either that or else Kyon's excitable cousins were more draining than she'd expected."
    "Certainly, it seemed that by teleporting to Hinamizawa, they should have been perfectly fresh and ready for a long evening of adventure and fun-- Instead, they'd spent a few short hours playing games with Kyon's cousins. All of them were cheerful, with the occasional exception of Matsuri, who eyed all the girls suspiciously from time to time."
    "Well, she'd liked Kyouko, but Haruhi was pretty sure it was just her crush on Kyon coming into play -- not that she could fault the little girl that much."
    "All-too-soon, it was time for dinner, though with the cousins at the main room's large kotatsu, the Brigade settled for trays. It wasn't like the adults fared any better, and considering that they'd just dropped in on Kyon's relatives completely unnanounced...."
    "Mikuru managed to escape into the kitchen as soon as there was the merest sign of cooking, and Kyon's aunt Rena approved of the help. Haruhi was fairly certain that she was the best cook among the lot, and with Mikuru backing her up, the pair had assembled quite the feast -- though Mion did admit with a chuckle after the fact that it wiped out their reserves, and they'd need to shop before breakfast in the morning."
    "Sasaki insisted that she do something to help as well, after the meal was over -- so Kyon and Koizumi were assigned the roles of dish collection, while Haruhi and Sasaki did the actual washing. Kyouko was still following Koizumi -- or possibly Sasaki -- so dried the dishes rather than just lurk about."
    "With everyone working together, despite the impressive volume of dishes there were to go through, it was very quick work. It probably would have gone faster if Mikuru weren't so distracted by the semi 'domestic-mode' Kyon ... not that Haruhi could entirely blame her!"
    "Haruhi wiped her hands on a dish towel and then handed it to Sasaki, who nodded her thanks as Kyouko dried the last plate."
    "Though he wasn't complaining, Kyon also got stuck with the job of putting them away, since he was the only one who actually knew where everything went."
    "\"And that's that!\" Haruhi declared proudly. \"Hmm, I do feel bad about going through your aunt's pantry so completely, though.\""
    "\"Oh, don't worry,\" Mion said from the archway to the living room, smirking. \"It needs to be cleared once in a while anyway -- Kyon can help Kei-kun do some shopping tomorrow morning and we'll stock up for the rest of the weekend. I must say, I'm really excited about Kyon being here for Watanagashi! This should be fun!\""
    "\"What's Watanagashi about, anyway?\" Sasaki asked curiously, handing the dishrag to Kyouko when she finished, though half directing her question to Kyon."
    "\"You know, it's been so long I can barely remember?\" Kyon answered, when Mion smirked at him."
    "The older woman's smile faded slightly as she shrugged. \"I guess it has been a while for you, huh?\" she allowed. \"Well ... long story short, it's an annual local festival. We do some dances, have some song, and after Matsuri-chan does the traditional dance and hacks apart a bale of cotton, everyone grabs a piece to symbolize their sins, and releases it into the river to symbolize that sin being washed away!\""
    "\"That's interesting,\" Kyouko offered, setting the towel on the counter. \"But why a bale of cotton?\""
    "\"Well, supposedly the original tradition was to hack apart a sacrificial person and then tear out bits of their flesh to throw in the river, symbolizing that one person each year was given to Oyashiro to apologize for the sins of the village,\" Mion explained, waggling her eyebrows with exaggerated menace. \"If you ask Rika-chan really nicely ... maybe she'll show you the ancient ritual shed full of spooky ritual torture equipment!\""
    "Haruhi shivered uncomfortably at that reminder, a little surprised when Kyon said in time with her, \"No, thanks.\""
    "\"Really?\" Sasaki wondered, smiling softly and glancing between them. \"Surely that was a very long time ago.... It sounds interesting from a historical standpoint!\""
    "\"T...torture?\" Kyouko asked nervously, trembling."
    "\"Oh, I'm sure most of it is too old to work properly anymore,\" Mion assured the girl, chuckling when Koizumi offered the other esper a pat on the shoulder. \"But seriously -- there will be no sneaking across the hall at night, youngsters!\""
    "Sasaki giggled at that. Haruhi wondered how serious Mion was and decided that she'd probably rely on Yuki or Kanae's help to avoid using the hallway if they decided to go that route. Best let Tsuruya in on that, too, when she thought about it."
    "* * *"
    "While her brother was busy in the kitchen, Nonoko eagerly dragged her cousins to the table to rope Tsuruya, Yuki, and Kuyou into their next card game. For some reason, they couldn't see Ryouko -- but that was probably okay, since they had a lot of players already. While her cousins were receptive to her explanation that Kyon was a hero (Matsuri especially), they didn't seem to believe that she was a magical girl."
    "That was too bad, but maybe if she was lucky, she'd get a chance to show them! Ryouko had insisted that Magical Radiant Nonoko's power was only needed for emergencies, and she should enjoy not needing to use that power."
    "That wasn't nearly as fun!"
    "Still, she got to play games with her cousins, and she was pretty sure the whole trip to Hinamizawa was part of her brother's plan to turn Sasaki completely away from the Dark Generals. That made sense; she just needed to have fun, relax, and probably spend some more time with Kyon."
    "She was willing to bet a hug would probably work. Sasaki seemed to be coming around slowly anyway, though, and a fast fix would probably come undone just as quickly; taking their time would mean if Dark Generals appeared again and tried to turn Sasaki, she would be more resistant."
    "Just as she thought that, the dish-washing team came back from the kitchen, as Makoto played the winning hand."
    "Alright, even more players! But ... what games did they have that everyone could play? Haruhi seemed to have the same thought, and suggested, \"Why don't we split into teams for the next game? Every Brigade member just needs to pick one of Kyon's cousins!\""
    "\"The count is off,\" Yurie said, shaking her head. \"Even if we take Nono-chan on our side, there are ten of you and only nine of us.\""
    "Actually eleven, by Nonoko's count. \"Pairing,\" the quiet dark-haired girl said softly. \"One each of us with one smaller entity?\""
    "\"Yeah,\" Aiko agreed, nodding."
    "Kuyou instantly leaned forward and picked up Ryouko. \"Team,\" she announced."
    "\"You'll be a team by yourself?\" Sasaki wondered."
    "\"She's with Ryouko-chan,\" Nonoko said, shaking her head. She was going to offer to be Ryouko's partner, though!"
    "\"Oh, is that an imaginary friend?\" the older girl asked, smiling."
    "\"That's what mom calls her!\""
    "\"That ... works,\" Kyon agreed with a shrug, nodding."
    "\"Then, I pick--\" Matsuri began, before Shutaro stood up and stared at her solemnly. \"What?\""
    "\"I will protect Kyon-kun from cooties,\" he declared, moving to stand in front of Kyon and crossing his arms over his chest."
    "\"That is so cute!\" Mikuru gushed, clapping her hands together."
    "Shutaro turned his gaze to her and blinked slowly before offering his trademark utterance: \"Icky.\""
    "\"Be nice or she won't make you cookies later,\" Haruhi chided gently. \"Matsuri-chan, why don't you play with me?\""
    "\"Okay,\" the girl grumbled, pouting."
    "\"I have to pick one of the two 'mini-me's!\" Tsuruya declared, pointing at Yoko. \"Does that sound fun?\""
    "\"Okay!\" Yoko agreed, nodding. \"I'm Azusa!\""
    "\"Oh, really?\" Tsuruya asked, her fang showing as she grinned. \"Somehow, you looked like a Yoko-chan to me!\""
    "Both of the Houjou twins were startled at that. The actual Azusa turned to her sister and admitted, \"She's good. You'll make a strong team!\""
    "Naota piped up and asked, \"Can I be on a team with that nee-chan?\" while pointing at Mikuru."
    "\"No, you big perv,\" his sister scoffed. \"Aiko-chan, you're innocent -- protect that nee-chan from Naota's wandering eyes!\""
    "\"Eh?\" Mikuru asked, eyes widening. Aiko nodded without hesitation, popping to her feet and sitting down at Mikuru's side. \"Ah ... okay....\""
    "\"Nee-chan, can I sit in your lap?\" the small girl asked."
    "\"Aw, sure you can!\" Mikuru agreed, throwing her arms wide for the smaller girl and hugging her tightly."
    "Naota scowled. \"I wanted to ask that...\" he grumbled. \"Okay, fine -- I'll be on a team with that guy, then,\" he declared, pointing at Koizumi."
    "\"Thanks ... I think,\" Koizumi chuckled weakly."
    "\"I'd be on your team, if I could, Koizumi-kun,\" Kyouko offered, giggling."
    "\"Well, let's team up,\" Azusa declared, smiling at the twin-tailed girl."
    "\"Sure!\""
    "Yurie and Makoto eyed the other older girls, then turned to Nonoko curiously. \"I'll be with Kanae-chan,\" Nonoko announced, nodding. \"We're both fans of Trope-tan!\""
    "\"I am, too!\" Tsuruya announced, along with all of the other cousins."
    "\"Well, in that case, I like the look of this nee-chan,\" Makoto decided, moving to Sasaki's side. \"Is that okay?\""
    "\"Certainly!\" Sasaki agreed, smiling gently. \"I'm glad to be able to be friends with Kyon's cousins!\""
    "\"Well, that leaves us!\" Yurie concluded, nodding at Yuki. \"Are you okay with being on my team, I wonder, I wonder?\""
    "Yuki nodded faintly in return, agreeing, \"It is fine,\" in her soft voice."
    "\"That rules out logic puzzle or mystery solving games,\" Kyon mused. \"No other combination of people on this planet will beat that team.\""
    "\"Really?\" Haruhi wondered, studying Yurie thoughtfully. \"Well -- in any case, let's start with another round of Old Maid.\""
    "\"Old Man,\" Matsuri corrected. \"We play Old Man instead of Old Maid.\""
    "\"Is that so?\" Haruhi asked, smiling. \"Well, that's just to get started-- But that's enough planning! Alright, everyone, grab your chibis and lets play!\""
    "* * *"
    "After a few hours of various board and card games, the cousins finally began to tire. Makoto and Naota had the shortest trip to their beds, since they were already at home, and as excitable as she was, Nonoko wasn't far behind her cousins in starting to doze."
    "Kyon couldn't help but notice how the aunts had monopolized the surplus of playmates for the cousins. Once the children were distracted, his aunts retreated to another room to play games of their own with his uncles. It seemed to be a rule of opportunity, judging by his past."
    "Around the same time Aiko released a huge yawn and curled up to fall asleep in Mikuru's lap, the aunts finally broke from whatever game they were playing and came around to collect their children."
    "\"Alright!\" Shion declared, though she paused to blink at the sight of Tsuruya and Yoko sitting together in the same position. \"That.... That's adorable....\""
    "\"Ah!\" Rena gasped, looking at Satoko's daughter. \"I want to take her home!\""
    "\"What about me?\" Yurie mumbled sleepily, straightening up from where she had been leaning against Yuki."
    "\"Well, you I will take home,\" the woman explained without hesitation, picking her up without any visible sign of effort. \"I think Satoko-chan would probably be upset with me if I abducted her daughter!\""
    "\"I'd let it pass for a day or two,\" Satoko allowed with a wry grin. \"Her color-blind mother isn't as good at baking, is she?\""
    "Rika smiled softly and shook her head. \"Shutaro, Matsuri -- come along, now,\" she ordered."
    "\"I want to hug Kyon-nii goodbye!\" Matsuri said with a pout."
    "Even sleepily leaning against Kyon, Shutaro stirred enough to grumble a protesting, \"Icky.\""
    "\"Are you a skipping CD or something?\" the girl grumbled, scowling."
    "\"There's plenty of time to visit your cousin later,\" Rika said sternly. \"Don't you want to be at your best for the Watanagashi ceremony?\""
    "\"Yes!\" Matsuri declared, perking up. \"Kyon-nii, you'll watch me, right?\""
    "\"I should be able to,\" he agreed. \"I don't really remember the ceremony well.\""
    "\"Remind me to tell your fiancee the story about how you came to join us during your first Watanagashi!\" Mion giggled."
    "Tsuruya chuckled at that as she helped Yoko to her feet, and the girl tottered to her mother's side. Azusa joined her, both girls yawning in tandem. \"Good night!\" they chorused as Yoko took Shion's hand, and Azusa took Satoshi's."
    "The Houjou family retreated out the door, followed quickly by Rena and Satoko, both aunts inviting anyone who wanted to visit over the next day."
    "\"Oh,\" Rika mused, \"Mion-chan, you'll be borrowing Kei-chan tomorrow?\""
    "\"I'm not a tool to be leant out,\" Keiichi said with an exaggerated pout, picking up his slumbering son."
    "\"Yeah, I'd kind of planned on borrowing him,\" Mion agreed, nodding as she ignored his protest. \"We've got a lot more people to shop for -- Kyon-kun, would you be willing to help him out and gather some supplies tomorrow?\""
    "\"That's not a problem,\" Kyon agreed. \"We're unexpected guests here, after all.\""
    "\"Nii-san can fight any Dark General minions for you, too,\" Kyon's sister contributed sleepily, before muffling a yawn."
    "\"He already did that, Nono-chan,\" Rika assured the girl, smiling as she accepted Shutaro from Keiichi's arms."
    "\"They're not likely to be a problem for the rest of your trip here,\" Mion agreed with a chuckle."
    "\"I did?\" Kyon asked, a bit surprised. \"Wait, those guys? Really?\""
    "\"My nephew's got a powerful reputation!\" Mion said with a wink. \"Now, let's see about putting some children to bed!\""
    "\"Not sleepy,\" Naota mumbled."
    "Makoto just snored softly from where she was leaning against Sasaki. \"Ah, dear,\" Sasaki chuckled. \"Could I be of help, then?\""
    "\"If you can carry her,\" Mion agreed. \"If not, then Kyon-kun can help.\""
    "\"I need to be carried!\" Matsuri declared unhesitatingly."
    "\"Not a problem!\" Keiichi assured, scooping his daughter up in his arms. \"Ready to go home and get in bed, then?\""
    "The girl pouted, but waved. \"Goodbye, Kyon-nii!\" she called, as he carried her through the door, followed by Rika and Shutaro, who sleepily stumbled after his mother, holding her hand."
    "Shortly after that, Nonoko, Makoto, and Naota were all tucked in, letting the Brigade reconvene in the living room."
    "\"Well, I'll let you set your own bedtimes,\" Mion said with a wink. \"You're old enough for that -- but I meant what I said about no sneaking across the hall at night!\""
    "\"I'd better obey,\" Tsuruya chuckled. \"I hear the Sonozaki-gumi has some scary stuff to enforce good behavior on outsiders!\""
    "\"Not half as bad as what we use for distinction,\" Mion answered, shivering faintly, one hand brushing across the other before she abruptly shook her head. \"Still -- don't stay up too late, Kyon-kun; you're helping Kei-chan out tomorrow, after all.\""
    "\"Alright,\" he agreed. \"I'm probably going to be ready to get some sleep soon, anyway.\""
    "\"Also, we're wiped out, so I'm probably going to send your friends to visit the other aunts for breakfast,\" Mion added. \"Unless they want to wait for you to come back.\""
    "\"I don't have a problem with waiting,\" Haruhi said without hesitation, to a general murmur of agreement."
    "Kyon felt his face redden slightly. \"Y-you don't have to wait on me,\" he chuckled, shaking his head."
    "\"But we want to,\" Tsuruya countered, grinning."
    "\"Well, I may ask you to drag some children around, then,\" Mion said with a shrug. \"Hmm, three other aunts, three children on hand ... that should work, come to think of it. Could give you some time to yourselves, too.\""
    "\"I'm also glad to contribute my fair share,\" Sasaki agreed. \"Though, hmm....\" Turning to Haruhi she hesitantly explained, \"I ... didn't get a chance to bring a change of clothes, I'm afraid. I might need to borrow some of yours?\""
    "Before Haruhi could answer, Mion mused, \"Actually, Rena-chan's still got her old clothes from when she was your age. You look about her size. Why don't you visit her tomorrow morning and see about borrowing something?\""
    "\"I...is that alright?\" Sasaki asked, taken aback."
    "\"It'll be fine! Anyone else need clothes?\""
    "\"Actually, I didn't pack for myself or Imouto, either,\" Kyon admitted with a wince."
    "\"Heh -- you'll have to ask Kei-chan for help when you see him tomorrow, then,\" she chuckled. \"But Makoto's about Nono-chan's size, so that should be fine!\""
    "\"Ah, Rena-san is a very good cook,\" Mikuru said quietly. \"Um, I wouldn't mind meeting with her to trade some tips, as well?\""
    "\"Well, we can sort that out in the morning,\" Mion said, shrugging. \"I should try and get some sleep, myself! Don't stay up too late, now!\" With that, she waved before heading down the hall to her own room."
    "\"Hmm, she's right,\" Haruhi mused. \"Kyon's aunts are all so cool it's really hard to decide!\""
    "\"That's true!\" Tsuruya laughed. \"But -- we should all get some sleep, too, shouldn't we?\""
    "\"We can still come up with a plan of attack for tomorrow's activities,\" Haruhi insisted, nodding."
    "\"Kyouko-chan, what do you think about tomorrow?\" Koizumi asked, turning to the other esper."
    "\"Ah-- Um ... Kyon-kun's family seems very nice,\" she said shyly. \"Er ... but I don't ... want to get in the way....\""
    "\"If you just want to explore the village, there's quite a few scenic areas where you can get away from the cousins,\" Kyon offered. \"It could get a bit dull, but it's an option if you want peace and quiet.\""
    "\"That sounds pleasant!\" Koizumi remarked. \"Hmm, perhaps we could discuss this in our room before we sleep?\""
    "Kyon shrugged. Why not? \"Alright, Haruhi, Tsuruya-hime -- don't stay up too late planning. Be sure to let Kanae-chan and Mikuru get some rest, too,\" Kyon warned."
    "\"On that note, I'm ready to get some sleep,\" Sasaki agreed, nodding."
    "Haruhi pouted, then brightened. \"We can plan in our room, then,\" she decided. \"Come on, Tsu-chan!\""
    "After saying good night to the other girls, Kyon moved down the hall with Koizumi to their shared room. Once they were past the girls' earshot, Kyon asked, \"Are you trying to take Tachibana on a date?\""
    "Koizumi nodded without hesitation, giving a weak smile. \"It could be nice,\" he explained. \"I think it would be good to take her somewhere like a theater, or another place where there are more people to acclimate and overcome her recent trauma ... but that's not really an option here, is it?\""
    "\"Not really,\" Kyon agreed, shrugging as he set out his futon and got blankets from the closet. \"The nearest town is Okinomiya, and it's pretty small, too. One movie theater, a small shopping district.... It does have a water park -- if you packed something to swim in, you could take her there, I guess.\""
    "\"That might be worthwhile, then,\" Koizumi mused. \"But if that's too much for her, perhaps a simple picnic in calmer environments would work, too. I would very much like to chat with Rena-sensei, but I suspect that Kyouko-chan might get the wrong idea about that, so will avoid pestering her for now.\""
    "Kyon regarded the esper for a moment, while Koizumi fussed with his futon and bedding. He really was being pretty considerate, given how much a fan he was of Rena's books. Thinking about it ... Sasaki had Haruhi and the other girls to rely on. Kyouko seemed a bit distant, and hadn't completely mended the damage between her and Sasaki after the kidnapping."
    "\"I'll double-check with Uncle Keiichi tomorrow and find out if any of the places I know of have been made more dangerous with pit traps or anything,\" he decided, nodding. After that, he knuckled back a yawn. \"On that note, I should get some rest if I can; I've evidently got to learn how to drive tonight.\""
    "\"Ah,\" Koizumi chuckled, shaking his head. \"Then I will know where you vanish to if you disappear abruptly.\""
    "\"Yep,\" Kyon agreed, nodding. The esper then excused himself to the bathroom to change into his pajamas, which ... Kyon had none of. Sighing, he absently stripped down to his boxer shorts and undershirt before crawling into bed."
    "* * *"
    "The moment Kyon stepped into his room with Koizumi and Sasaki was out of sight, Haruhi practically tackled Yuki. \"You know the plan for tonight, right?\" she asked mischievously, grinning."
    "The quiet girl looked mildly interested and tilted her head slightly—"
    "What, she couldn't figure it out? Well ... fine, then! \"Aunt Mion said no sneaking through the hall,\" Haruhi explained, \"and we're going to follow that rule. We can just gather in the room Tsu-chan and I are sharing!\""
    "\"Understood,\" Yuki replied, nodding unhesitatingly, while Kuyou looked interested at her side, but said nothing."
    "\"Ah -- when it's time for Kyon-kun's training, I'll keep you company, Haru-nyan!\" Tsuruya added, grinning."
    "Haruhi tried to keep her expression from slipping. It sucked that she didn't get to join in on that!"
    "Yuki hesitated, then shook her head a short distance. \"The creation of junk data has been steadily decreasing,\" she explained softly. \"As a consequence, the relative duration of 'training sessions' has been declining as well. In order to facilitate a training session of sufficient length, it would be advisable to create a feedback loop by bringing you into the session.\""
    "Haruhi blinked in astonishment. \"What am I, a decaying breeder reactor?\" she asked, trying to pretend she was more upset than she felt. She could finally go on one of those training sessions?! That was great!"
    "The quiet girl only stared at her quietly and blinked."
    "\"Haru-nyan!\" Tsuruya cheered -- though quietly, with a glance at Kyon's room. \"This is going to be so much fun -- what do you want to learn?\""
    "\"I-- I didn't think about it,\" Haruhi admitted, grinning. \"Well -- everyone else is learning to use their powers, right? Except Mikuru-chan, I suppose, who has become the domestic ur-goddess, ruling the domain of the kitchen and sewing needle.\" She also was studying medicine, which Haruhi was glad for, but even happier when the time traveler had no reason to use that skill."
    "\"Cookies,\" Kuyou contributed helpfully with a sage nod."
    "\"Oh, will you be joining us?\" Haruhi wondered. What would Kuyou learn?"
    "\"Incompatible time frame,\" the dark-haired girl answered."
    "Oh.... \"So ... you'll be left alone?\" Haruhi worried."
    "Shaking her head, the girl looked slightly off to one side and answered, \"New friend.\""
    "Haruhi looked but saw nothing. For some reason, Yuki looked the faintest bit amused and evasive. What was that about? Well ... she could let it slide until after her training session, anyway. \"Okay -- in that case, I'll work on using my powers in fights better, if I have to. The last time I had to help Kyon....\" She shivered at that memory. She'd rather not have to, but if it came up again, she wanted to at least be equal to Kyon's sister, instead of barely able to hold her own!"
    "\"Good plan!\" Tsuruya cheered, nodding."
    "\"What are you going to learn, Tsu-chan?\" Haruhi wondered."
    "Grinning mischievously on her own, Tsuruya explained, \"Somethings for Kyon-kun!\""
    "Haruhi's eyebrows shot up as Tsuruya's waggled, and she whispered, \"Massage!\""
    "...that was a good call. \"You'll have to teach me the old fashioned way later,\" Haruhi decided, nodding. \"Even if I can come along this time, I get the impression it's kind of a rare thing, isn't it?\""
    "Yuki nodded as well."
    "\"Okay! I'm too excited to wait! Let's get started!\" she enthused."
    "This was going to be awesome!"
    "* * *"
    "After following Nagato Yuki to the room they had been assigned to share, Kuyou followed the space-folding transfer effect she used to bring almost everyone else to Haruhi and Tsuruya's room. Technically, it created a small amount of Noise ... but it wasn't hard to harmonize against it. Well within tolerances, anyway."
    "There was some fuss and interesting facial reactions (extreme reddening) over the fact that Kyon's physical form was wrapped in a smaller number of atoms than usual, but it didn't last long. Nagato Yuki very quickly assembled a small bubble that was very like a shadow song of almost isolated space-time and then transfered everyone else there."
    "Left alone with her new friend, Kuyou turned to regard the other. She was almost perfectly in harmony with the Chorus; if she were to harmonize anymore, she would be another voice singing with the others. Her ability to manipulate spin and string were far less than what Kuyou could manage, but it took the merest nudge to provide enough spin to let her shape it as she needed."
    "Still, just introducing that into her system uninvited would be impolite, from what Kuyou understood of things now. Instead, she imbued some spin into string she had kept idle in a shadow-song, giving it physical form."
    "Before she could determine how to present it, the other entity fretted anxiously, explaining, \"I must tell Rika that this happened, it is so!\""
    "\"Why?\" Kuyou asked, tilting her head to one side slightly."
    "\"It's-- Kyon-kun shouldn't be doing naughty things like that! Rika and Kei-chan could be blamed for it if anything happens, it is so! I'm sorry, I'm sorry, I'm sorry-- But-- But I have to explain that Kyon-kun was alone with all those girls, it is so!\""
    "Kuyou didn't really understand that argument, so changed the subject, offering out the modified packet of spin and string to the smaller entity."
    "The other figure's eyes widened, seeming to spark the light of a distant member of the Chorus within their depths as she gasped."
    "Explaining what the current form of the construct in her hand was, Kuyou declared: \"Cookie.\""
    "\"I-- I--\" A trembling hand reached out and daintily plucked the cookie from Kuyou's palm, before she slowly raised it and cautiously nibbled. The blaze in her eyes suddenly intensified. \"I ... suppose Rika doesn't need to be told right away,\" she said."
    "Kuyou reached into her shadow song and produced a small bag of the baked goods Mikuru had taught her to make. \"Cookies?\""
    "\"Teenagers will be teenagers,\" the other entity agreed quickly, this time snatching the bag from Kuyou's hand in only the span of three rotations. \"There's no sense in spoiling their fun, is there? Especially since Mion, Rika, Rena, and Satoko did the same thing all the time at that age! And still do, it is so.\""
    "That seemed more like it! \"Friend?\""
    "\"Yes!\" the other entity agreed, nodding quickly. \"We can be friends! I'm Hanyuu, it is so~!\""
    "\"I am called Suou Kuyou,\" Kuyou answered, smiling happily. \"Hanyuu is my friend.\""
    "\"That's right, Kuyou-chan!\" Hanyuu agreed happily. \"You can call me Hanyuu-chan, it is so!\""
    "\"Like Nagato Yuki,\" Kuyou added."
    "\"Kyon-kun knows amazing and interesting people, it is so!\" Hanyuu mused, nibbling another cookie happily. \"Kuyou-chan and Yuki-chan are fun to spend time with, it is so!\""
    "Kuyou couldn't disagree."
    "* * *"
    "Sasaki was surprised at how tired she was once she'd gone to bed, but the day had been exciting, and Kyon's energetic cousins could wipe anyone out. It was a small miracle someone as historically lethargic as Kyon could survive them! But maybe she was looking at it the wrong way, and it was thanks to them that Kyon had learned to savor relaxation and idleness?"
    "She supposed there was some logic to that."
    "When she woke up, Kyouko was also yawning and stretching in her futon, rubbing at her eyes before blearily regarding Sasaki and mumbling, \"Good morning.\""
    "\"Good morning to you, too, Kyouko-chan,\" Sasaki returned, offering a gentle smile. \"Did you rest well?\""
    "\"Yes -- did you?\" Kyouko returned."
    "Sasaki nodded, sitting up and smoothing down the school uniform she had slept in -- a shame, really, that it was the first thing she'd really done in the new outfit. Before she could speak, there was a knock at the door. Seeing as both she and her friend were awake, she shrugged and climbed to her feet. \"Yes?\" she called. \"Come in?\""
    "The door slid open, revealing their host, her long green ponytail swaying behind her as she peeked in. \"Good morning! If you're up, you can head down to Rena-chan's to borrow some clothes for your weekend here before taking a bath,\" she offered. \"Kyon-kun and Kei-chan might be a bit doing the shopping, so it would be a chance to get something to eat, too.\""
    "\"Oh-- Absolutely,\" Sasaki agreed, nodding. \"Is there anything I can do to repay the favor?\""
    "\"No-- Well, actually, there is one thing,\" Mion allowed. \"If you're willing to walk Makoto-chan down to Rena-chan's, I would be most grateful!\""
    "\"I'd be glad to,\" Sasaki accepted, nodding quickly. \"Does she know the way?\""
    "\"Yep-- And that Mikuru-chan will be headed down there, too.\""
    "\"Um,\" Kyouko started, before biting her lip."
    "Mion winked at the girl and explained, \"Your boyfriend is setting something up for you! If you've got something to wear for a date....\""
    "\"Ah! I, um.... I ... think so?\" Kyouko squeaked."
    "Sasaki bit back a wince; she wouldn't mind giving the other girl space for that. Come to think of it.... \"Where is Haruhi?\" she wondered."
    "\"Hmm, she took that tiny little Kanae-chan to Rika-chan's house,\" Mion offered. \"Kyon-kun seemed to think they might have a lot in common, for some reason. Yuki-chan and Naota-chan went with with her. And, let's see.... Tsuruya-chan stayed here to discuss some business between our families, and Kuyou-chan went with Nono-chan and her new invisible friend to make sure Kyon's sister got properly fed.\""
    "\"I-- I see!\" Sasaki realized belatedly. \"Well ... I suppose I'd best hurry, shouldn't I? I'm keeping your daughter from her breakfast!\""
    "\"And yourself from clean clothes!\" Mion added, winking."
    "Blushing, Sasaki nodded and bustled to catch up with Mikuru and Makoto. The tomboyish girl was peering at Mikuru with interest, while the older girl fidgeted hesitantly and offered a nervous smile -- both of them looked up when Sasaki reached the living room. \"I'm sorry,\" she apologized. \"I didn't mean to keep you waiting!\""
    "\"It-- It's no problem!\" Mikuru said quickly."
    "\"I'm hungry,\" Makoto said with a mild pout. \"It's okay so far, but let's get moving!\""
    "\"Absolutely,\" Sasaki agreed."
    "\"Be polite,\" Mion scolded her daughter gently. \"Sasaki-chan, Mikuru-chan, Makoto-chan can lead the way.\""
    "\"Yeah, let's go!\" the little girl cheered, slipping on her shoes and zipping out the door. Sasaki and Mikuru followed quickly, the energetic little girl leading them down the hill while skipping. As much space as there was between homes, it was only a walk of about ten minutes to the cozy little house that Rena appeared to own."
    "Before they got to the door, Rena's daughter Yurie zipped out from behind a retaining wall, meeting up with Makoto as the two chatted excitedly. Sasaki giggled to recognize the smaller girl's musing verbal tic of, \"I wonder, I wonder.\""
    "Rena herself awaited at the door, eyebrows raised. After examining Mikuru's sun dress, the older woman turned to Sasaki and said, \"You need something to wear?\""
    "\"I...if it's not too much trouble,\" Sasaki agreed, bowing her head."
    "\"Not at all!\" Rena countered, chuckling. \"Hmm, breakfast will need to wait a few minutes, girls,\" she advised the children."
    "\"Oh, that's not--\" Sasaki started, before Mikuru interrupted."
    "\"I-- If you don't mind, I could help cook while you're helping Sasaki-san,\" the older girl offered with a gentle smile."
    "Rena's eyes seemed to spark, but she smiled anyway. \"Well, I suppose you could, couldn't you?\" she answered with a laugh. \"Alright -- I've been impressed with your skill in the kitchen; I can't wait to see if I can learn a few new tricks from you!\""
    "Mikuru blushed at the praise, but managed a firm nod anyway. The next thing Sasaki knew, Rena had taken her hand in an astonishingly strong grip, and would probably have hauled her down the hall to the woman's bedroom if Sasaki weren't willing to go along. A heartbeat after that, she was released as Rena went to a box she'd already set on her bed."
    "\"Go ahead and use the shower in the master bath,\" Rena instructed absently. \"Pass your outfit through the door and I'll check your size against what I used to wear.\""
    "\"Ah, okay,\" Sasaki agreed, spotting the door she had previously missed and ducking into the shower. She didn't feel particularly clean after sleeping in her uniform, somehow, so that much was welcome. When she stepped out and toweled herself dry, she was surprised to see that Rena must have slipped an outfit in for her."
    "Clean clothes were a nice change, as well! The outfit was a long white dress with short sleeves -- that much seemed fine, though she had to feel that the cut in the skirt running nearly to her waist for mobility was a bit revealing. A set of clean stockings helped offset that for the most-part, and the only part that gave her pause was remembering how to knot the long ribbon into a bow -- but the way it had been draped across the collar of the dress suggested that was where it went."
    "Once that was in place, she stepped into the living room. Makoto and Yurie only glanced at her from their television show -- but Rena broke off from her conversation with Mikuru in the kitchen and gasped, grinning brightly. \"Oh, that is too cute!\" she gushed. \"Oh-- Wait! Wait! I know!\""
    "She zipped past Sasaki and returned from her bedroom a moment later with a hat that matched Sasaki's current outfit. \"There!\" she said proudly, setting it atop the girl's head. \"Adorable!\""
    "Mikuru peeked in from the kitchen, asking, \"What-- Oh, that's lovely! We must get a picture for Kyo-- Um, Haruhi-chan!\""
    "\"W...what?\" Sasaki asked, blushing. She thought she normally dressed fairly well, but wasn't much to look at. She didn't feel she could compete with Okamoto, anyway -- and certainly not with ... well ... someone like Mikuru! \"I...it must be the outfit itself,\" she said, shaking her head."
    "And why did Mikuru think that Kyon would want a picture of Sasaki in that outfit anyway? Not that she would mind some praise from him -- ah, no, she couldn't afford to think that! Kyon was engaged, and that wouldn't be proper! She must have meant Kyouko. She probably thought that Kyouko would be entertained by the costume -- yes, that made much more sense."
    "\"And so humble!\" Rena gushed. \"If you weren't already here, I'd have to take you home!\""
    "\"A picture!\" Mikuru insisted, snapping one with her cell phone. As an afterthought, she added, \"Breakfast is ready, too.\""
    "\"Okay!\" Yurie cheered, rushing to Mikuru's side with Makoto."
    "\"Well, most of my outfits are identical to that one,\" Rena explained, shaking her head, \"so she'll be dressed up like that all weekend -- unless she wants to wear my old school uniform!\""
    "Sasaki couldn't help but laugh at that."
    "\"Well, we do need to eat,\" Rena said pragmatically, shaking her head, following her daughter and niece toward where Mikuru waited."
    "Nodding, Sasaki glanced at a row of pictures lining the shelf. \"Um, thank you very much for loaning me clothes, Rena-san.\" Hmm ... no picture of a husband? Come to think of it, there weren't any signs of anyone other than Rena occupying her own bedroom, either. The only older male in the picture frames was Kyon's uncle Keiichi, and unless she was mistaken, he was married to Rika, so wouldn't be Yurie's father."
    "\"For someone as adorable as you, it's no problem!\" Rena declared. \"Your boyfriend must love it when you dress up!\""
    "Sasaki's heart skipped at the combination of compliment and unintentional reminder. Trying to change the subject as her face reddened, she asked, \"May I ask what you do for a living?\""
    "\"Eh?\" Rena asked, surprised. \"Oh, well....\""
    "* * *"
    "Haruhi wasn't really sure why Kyon seemed to think it would be good for Kanae to talk to Rika, but he seemed to trust her especially among all his aunts. Well, considering what Rika had told Haruhi, she suspected the woman was pretty wise. And she trusted Kyon's judgement in general anyway, so told Kanae that Rika could be trusted with anything that Kyon could, probably."
    "Kanae's judgement wasn't awful, either, but Kyon had left the house earlier to get a change of clothes from his uncle's older outfits, and he'd evidently told Rika something then. Rika had almost immediately led Kanae off to that creepy shed, leaving Yuki and Kuyou to watch over her children."
    "As cute as that was, it was kind of strange, too...."
    "There was something else Haruhi wanted to know, though. Once she had delivered Kanae to the same house she'd once walked all the way to from Okinomiya, she immediately spun on her heel and sprinted back to Mion's place. When she got there, the woman was chatting amiably with Tsuruya, evidently just finishing some business."
    "It didn't seem to be formal, at least."
    "\"Back so soon, Haruhi-chan?\" Mion asked, looking over from where she and Tsuruya had been surveying the grounds."
    "\"What's the rush, Haru-nyan?\" Tsuruya chuckled."
    "Huffing once to catch her breath, Haruhi explained, \"There's something only you can answer, Aunt Mion!\""
    "The older woman looked surprised at the name, but only smiled at it. \"Is there? Well, you see, Haruhi-chan, when a man and a woman love each other very much....\" She trailed off when Haruhi didn't interrupt her, pouting faintly. \"Not funny?\""
    "\"It's about Kyon's mother,\" Haruhi clarified."
    "\"Ah,\" Tsuruya realized, perking up, her smile fading. \"I am curious, too-- This is about why Kyon's mother behaves the way she does?\""
    "\"Right!\" Haruhi agreed."
    "Mion grimaced. \"Well, now that joke was horribly inappropriate. Or worse, terribly appropriate.... Well -- okay. I can understand why you want to know, but this is something we should discuss inside.\""
    "\"Okay!\" Haruhi and Tsuruya agreed in tandem, sharing a significant glance before nodding at the older woman."
    "In short order, they were assembled in a meeting room -- a hall on one side of the impressive house, Tsuruya and Haruhi sharing a side and facing their host. Mion distracted herself for a few minutes fussing with a tea set and then serving it, finally settling back on her heels where she knelt on her cushion."
    "\"How old is Kyon-kun?\" Mion asked, looking between the two girls after handing them their teacups."
    "\"Seventeen tomorrow,\" Haruhi returned, as Tsuruya nodded confidently."
    "\"That's right,\" Mion agreed, offering a wan smile. \"Do you know how old his mother is?\""
    "\"I ... late thirties?\" Haruhi guessed, shrugging. \"Maybe early forties?\""
    "\"Thirty eight or nines,\" Tsuruya agreed."
    "Mion nodded slowly and set her teacup down. \"Well, then. Let me explain a little bit of her history. Her name is Akane -- did you know that?\""
    "\"Yes!\" Tsuruya chirped, nodding."
    "\"My mother's name was also Akane,\" Mion added wryly, shaking her head. \"And in a village this size, names really tend to be unique -- even a relatively common one like Kei-kun's! So to the rest of the villagers, she was given nicknames she didn't like and protested against. So she became standoffish and eventually rebellious.\""
    "Haruhi frowned, objecting, \"Isn't she a little old to be rebelling against her parents still?\""
    "\"This is about then, not now. In any case, when a young man with a freshly earned driver's license came up to our town just because he could, he didn't earn much respect from the villagers, either. Imouto-- That is, Kyon's mother decided to befriend him to upset her parents.\""
    "The girls waited patiently for Mion to continue."
    "\"What started as something to spite her parents developed into a friendship, and from there, well ... teenage romance. Nobody thought much of it, and slowly people came to largely ignore the outsider who visited often, and the local girl who seemed to have a crush on him."
    "\"None of us really knew what was going on, and thanks to Akane being a ... late bloomer in some ways, she didn't realize what was even going on herself.\""
    "\"Huh?\" Haruhi noised, looking at Tsuruya and catching a matching look of confusion. Both girls started simultaneously. \"Wait! You don't.... You don't mean....\""
    "Mion nodded. \"Kyon's mother was standoffish enough that no one saw it. Yuuto got caught up in something toward the end, when it would have been more obvious, so ended up not visiting for a good ... three months. So only she was able to see it, and she wasn't willing to ask anyone else for help."
    "\"So -- that Watanagashi, she waited at the festival for Yuuto to arrive, and no one really remarked that she was dressed differently. She'd taken to wearing bulkier clothing, but in a late spring, that's not that uncommon. Perhaps I'm trying to justify it to myself a little, that we all missed it, but we were ... caught up in other issues.\""
    "By that point, both girls could only stare, speechless."
    "Clearing her throat and pausing to sip her tea, Mion continued, \"So -- these things happened at once. Rika-chan finished the ritual shredding of the cotton for the Watanagashi ceremony, Yuuto arrived at the festival and saw Kyon's mother waiting for him on the steps to the temple ... and her water broke.\""
    "Haruhi worked her jaw once, but couldn't find any words, so just settled back to keep staring."
    "\"The theme of Watanagashi is that the cotton balls allow us to remove sin from the body. So Kyon's mother collapsed on the steps leading to the shrine, the villagers were carrying their cotton bundles down to the river past her.... Irie-sensei realized what was happening, at least. So -- thanks to him acting quickly, Kyon-kun was delivered right there, in the middle of the Watanagashi ceremony.\""
    "\"How old?\" Tsuruya asked, startling Haruhi slightly. That was right -- Mion had mentioned that, hadn't she? It had to be relevant!"
    "\"Today, Kyon's mother is thirty two.\""
    "\"Damn,\" Haruhi muttered, unable to think of anything else to say. \"I mean....\""
    "Heaving a sigh, Mion shook her head slightly. \"Things got ... even more difficult for her after that. Some of the villagers felt that Kyon-kun represented his mother's sin, which was difficult. Yuuto was ... persuaded to marry her immediately and take responsibility. But if things weren't difficult enough, Kyon's mother wasn't even ... physically able to care for the poor boy!\""
    "\"Because of her 'late bloomer' status?\" Haruhi asked, blinking. \"She would have been ... fifteen? Sixteen when that happened?\""
    "\"Fifteen,\" Mion agreed. \"For that and other reasons, even though Kyon-kun was her child, since she wasn't ... quite ready to handle it, well, Kyon's 'aunts' all came together to care for him.\""
    "\"Wow,\" Haruhi managed. \"That.... I had no idea!\""
    "\"So ... once she was old enough, and could take control of her own life...\" Tsuruya mused slowly."
    "\"Exactly right-- As soon as Yuuto was able to get a reasonable job, she moved as far from what she saw as unwelcome control over her life as she could,\" Mion agreed sadly. \"It ... still grates on her. Thanks to myself and Rika, we've explained to the villagers that she shouldn't be judged for her past, but....\" She shrugged wordlessly."
    "\"But that probably means that for the first two or three years of his life, it was you who raised him,\" Haruhi determined. \"Isn't that right?\""
    "\"Not just me,\" Mion countered, shaking her head and smiling wistfully. \"We all did our part. I'd had a daughter before -- so it wasn't too much trouble for me to induce and.... Well, anyway, I was glad to help.\""
    "\"That ... really helps put her behavior into perspective,\" Haruhi said quietly. \"So ... she thinks she made mistakes growing up, and tries to clamp down on Kyon's behavior so he can't repeat her mistakes?\""
    "\"Something like that,\" Mion agreed. \"It's nothing short of a miracle that she even agrees to visit us! If it weren't for Kei-chan's father having a heart-attack some years ago.... So we accept what we can get!\""
    "\"That's.... Thanks for sharing that with us,\" Haruhi managed."
    "\"It's quite a story,\" Tsuruya agreed solemnly. \"But -- I can see your influence in Kyon's behavior! You helped make him a good and gentle soul as a child, I think!\""
    "Thinking back to what Tsuruya's aunt had revealed to her, Haruhi mused, \"There really are a lot of amazing stories about what makes a family, aren't there?\""
    "\"I don't know that it's really amazing, but it's the truth,\" Mion said with a shrug. \"And even if he's not really our child, we do care for Kyon-kun -- so all of us are glad if you could help him come up here. I just hope his mother can get over it!\""
    "\"Well ... hiding things isn't that great...\" Tsuruya said, frowning."
    "\"Sometimes there are things that don't need to be said,\" Mion countered. \"In this instance, it helps you understand, and I think you'll know enough to not spread it around carelessly. Since he was so young, I'm certain that Kyon-kun himself doesn't even know this. Some day, I think his mother will admit it to him -- so don't tell him just yet. She should have that chance, shouldn't she?\""
    "\"That's true,\" Haruhi agreed, sighing. \"Wow, that was ... heavy. Thank you for telling us!\""
    "Tsuruya nodded her agreement."
    "\"Any other questions?\" Mion asked, offering a wry smile."
    "\"How old is Kyon-kun's fathers?\" the heiress wondered."
    "\"Hmm? He's thirty three, I think. Or is it thirty four? He's not that far off from her in age, in any case. Also a bit too young for when it happened, but ... I think he's done a fine job of proving himself a reliable husband.\""
    "\"Can't argue against that,\" Haruhi agreed. \"Ugh -- this mood! We need something more cheerful!\""
    "\"Okies,\" Tsuruya said, grinning. \"One last question, then -- Mion-san--\""
    "\"That's 'Auntie Mion' or 'Aunt Mion' to you outside of business,\" the Sonozaki family head scolded with a gentle smile."
    "\"Hehe-- Okies, Auntie. My questions is: Are you saying you were Kyon-kun's wet-nurse?\" Tsuruya pressed, narrowing her eyes."
    "Mion blushed, but nodded. \"Why do you ask?\""
    "\"That ... totally explains Kyon's type,\" Haruhi explained without thinking."
    "The older woman blinked at that. \"'Type'? What?\""
    "Haruhi coughed and looked away, feeling her own face redden. \"Er, he likes ... bonbons and ponytails,\" she mumbled, pointedly not looking at Mion's chest."
    "The older woman snorted, face splitting into a grin, while Tsuruya's own laugh began to warm up."
    "Well ... that was one way to change a mood!"
    "* * *"
    "Seeing as the others were all busy associating with Kyon's relatives, Yuki and Kuyou spent their time with Hanyuu. The not-quite-data-entity had gotten enough of a charge from Kuyou's 'cookie transmission' to manifest in real space, but had chosen not to."
    "Yuki had initially determined that Hanyuu would want to have a physical form, but realized that wasn't always true. Evidently she had the capability on her own, but chose to conserve her strength. As she explained it:"
    "\"My power is for emergencies! I can feel the world through Rika anyway, it is so!\""
    "But despite that, Hanyuu seemed to enjoy patting Ryouko, and nibbling on the sweets Kuyou provided."
    "If she was content, Yuki and Kuyou didn't see a reason to impose a change on her."
    "It was trivial to participate in games with the children while also communicating with Hanyuu on a wavelength they couldn't observe. From a year and more of observing Kyon, Yuki engaged in the strategy she'd seen him employ against his sister, and rarely against Koizumi Itsuki."
    "That being to lose intentionally, but not obviously."
    "It was more interesting than just accepting the normal 'win' conditions, at any rate."
    "In the meantime, Kanae had gone with Rika to investigate something -- Hanyuu suggested it was 'to lift a dark mark on her spirit'. That didn't have particularly strong meanings for Yuki, but she determined it was something that even enjoying personal time with Kyon couldn't quite help alleviate."
    "Though she hadn't invested any processes to observing Kanae's exchange with the older woman, when the slider returned, Yuki judged that she seemed to be positively effected. While her demeanor was almost always cheerful, her energy had increased, as though some internal tension had been relieved by the shrine maiden."
    "After that, Rika determined, \"Now, Kyon-kun will probably be returning to Mion-chan's soon -- why don't you go meet your friends at Rena-chan's, and lead them back?\""
    "So after waving goodbye to the children and making Rika wonder where the cookies Kuyou had given them came from, the four of them set out. Hanyuu gave directions, so Yuki didn't even have to spend any special effort to find the way."
    "Sasaki seemed happy to see them, while Mikuru and Rena were deep in conversation about cooking techniques. The older woman clapped her hands excitedly at seeing Kanae. In general, she seemed to have a fixation on 'cute' things, and insisted on taking numerous pictures."
    "Yuki didn't particularly mind, even though it did mean they spent longer with her instead of visiting with Kyon. She fully intended to make up for that later in the evening anyway, without violating the sanctity of the hall to meet up with him."
    "The conversation was mostly what Yuki would have labeled 'small-talk' -- non-critical, yet pleasant exchanges. Most of it centered around the series of books that Rena had written. Yuki had actually found them to be very interesting, and Sasaki was a fan as well. Though she had not anticipated it, Rena even had a picture of Yuki and Kyon from when she had dressed up as the titular character."
    "Then the topic wandered to costumes in general, and the flash-mob that Haruhi had arranged, and from there, Rena wondered, \"Kanae-chan, how did you meet Kyon-kun?\""
    "\"Oh, I'm curious about this story, as well,\" Sasaki added, nodding."
    "From there, Kanae stumbled a bit, then transmitted an ... interesting rendition of a fight that Kyon had gotten into protecting Kanae from an upperclassman long ago. Rena was fascinated and shocked, but seemed to undergo a transformation when Kanae mentioned the name of the boy that Kyon had gotten into a fight with, seemingly ready to enter combat herself -- though keeping it behind a well-constructed mask of restraint."
    "Though the slider was oblivious, Sasaki's flinch suggested she'd observed it as well."
    "Hanyuu's reaction was to emit an entirely unexpected string of words -- the kind of language that Yuki had read was typically related to European mariners -- and demanded, \"Don't let Rena get to her cleaver!\" before speeding toward Rika, ignoring all intervening obstacles."
    "How unique!"
    "* * *"
    "As surprised as he was that his uncle had clothes that fit him, Kyon wasn't sure it was really his style. Realistically, thanks to a certain greatcoat, it didn't really matter, but that could raise questions he didn't really want to deal with."
    "Anyway, it was supposed to be a vacation. Black tank-top, red vest, and denim shorts -- it would do. It had made Rika double-take at the sight of him before they drove off to handle the shopping, giggling at the look. It wasn't Kyon's fault if there was a family resemblance! And one that was not being helped by wearing one of his uncle's old outfits, too."
    "Still, shopping wasn't too bad, though by the time they finished, Keiichi's car was so packed with groceries that there wasn't room for more than just the two of them. Kyon liked his uncle, though, so it wasn't a tedious chore picking up everything on Mion's list -- in bulk. It didn't hurt that they were both saiko-komon for their respective ninkyo dantai family heads."
    "Of course, Kyon knew that his uncle and his aunt Mion were only good friends, as opposed to him actually being engaged to Tsuruya. As much as he enjoyed chatting, it wasn't as though he could tell his uncle, \"I'm kind of mixed up with this incredibly magical girlfriend who's set me up with a harem.\""
    "When they reached Mion's place, the woman was waiting at the gate anxiously, for some reason, and dashed over to the car. \"Kei-chan!\" she called, as soon as the door was opened. \"Rena-chan found out about ... that distant relative -- we really need to go help her out!\""
    "\"Eh?\" Keiichi reacted, before his eyes widened."
    "\"What's wrong?\" Kyon asked, climbing out of the car."
    "\"It's....\" Keiichi shook his head. \"Alright-- I'll head to Rena-chan's on foot; Kyon-kun, go ahead and stay here -- sorry about this, but I'll have to leave you to unload the groceries yourself. It's something we can handle, just ... your aunt Rena has some issues with her own extended family and ... well, we help each other out whenever we can.\""
    "\"So if I can ask you to hold down the fort and take care of things here, we'd be very grateful!\" Mion added, nodding."
    "\"Eh, okay,\" Kyon agreed, frowning. \"I can handle the groceries, I guess.\""
    "\"Great,\" Keiichi answered, grinning and tousling Kyon's hair. \"I'm in your debt, Kyon-kun!\""
    "Giving one last wave, he left the car unlocked and dashed down the dirt road leading to Rena's place, Mion in step with him."
    "Shrugging, Kyon tried his best not to worry about it and started unloading groceries, finding Haruhi and Tsuruya waiting for him at the door to the house. \"What was that all about, anyway?\" Haruhi asked, frowning."
    "\"Not sure,\" he admitted. \"Anyway, I've got a bunch of groceries to bring in -- if I drop them off here, can you carry them to the kitchen?\""
    "\"Ah!\" Tsuruya cheered, clapping her hands. \"Assembly line! Kyon-kun brings things here, I'll bring them from here to the kitchen, and Haru-nyan can put them away.\""
    "Haruhi gave Tsuruya a doubtful look. \"Sasaki's not around, right?\" she asked Kyon."
    "\"Uh -- not that I know of,\" he answered, frowning as Haruhi nodded decisively and slipped on her outdoor shoes from the large pile of things. Tsuruya looked at Haruhi curiously, but took the bags from Kyon's hands. \"Why?\""
    "\"We're on vacation,\" Haruhi said breezily as she marched out to the car, then looked around. Deciding the coast was clear, she waved a hand, and Kyon sighed, watching all of the assembled bags -- dozens of trips, at least -- just float free of the car effortlessly and proceed toward the house in an orderly line."
    "The car doors shut themselves as the last bag left the vehicle, and in only a single trip, Haruhi had levitated the entire load into the kitchen."
    "Kicking off his outdoor shoes, Kyon accused her, \"Cheater.\""
    "\"Efficient,\" she corrected him, grinning."
    "Tsuruya laughed, shaking her head. \"It's a time-saver,\" she admitted. The groceries then unpacked themselves and put themselves in the pantry, refrigerator, or freezer beneath Haruhi's watchful gaze, turning a thirty minute chore into an amusing minute of fast-paced automation."
    "\"There!\" Haruhi declared, as the last bag of rice was stacked in the pantry, and the grocery bags compressed into a ball that dropped into the recycle bin. \"Now, I've done my chores and I'm tired -- that gives us some solid cuddle time before everyone else shows up!\""
    "\"Don't I get a say in this?\" Kyon wondered, unable to keep from smirking. He probably was getting too used to casual uses of power ... but it wasn't like Haruhi was being really selfish or hurting anyone. Also, it didn't hurt that it had saved him effort...."
    "Taking his hand and tugging him toward the living room, the heiress asked, \"Do you really want to protest?\""
    "\"It's really difficult, but I think I'm supposed to,\" Kyon admitted, as he let himself fall back on the couch, the girls positioning themselves on either side of him."
    "Tsuruya pressed her lips to his cheek in a quick peck, and Haruhi eagerly leaned in—"
    "All of them froze at the sound of the house's doorbell chiming."
    "Tsuruya sighed and shrugged, not losing her smile."
    "Kyon gave Haruhi an apologetic shrug of his own, and moved to rise -- but Haruhi wasn't having any of that and just growled, grabbing his head in both hands and kissing him with all her might. When she was done, she released him and coughed, clearing her throat with a smug smile before dashing to the door, leaving him flustered with Tsuruya at his side."
    "\"W...wha...\" he managed."
    "By the time he cleared his head, the new arrivals had entered -- and he leaped to his feet. The Brigade members had come back, other than Koizumi and Kyouko. Kanae looked a bit dazed and anxious, Mikuru seemed to be shaken, and even Sasaki looked distressed. She was wearing an odd outfit -- it looked good on her, he thought -- but he was more worried about her expression than her costume."
    "\"What happened?\" he asked, simultaneous with Haruhi. They exchanged a glance, then turned to regard the unsettled girls."
    "Yuki and Kuyou looked unperturbed, but considering what it'd take to shake them...."
    "Sasaki shook her head, briefly massaging her temples before finding a seat in the living room. \"I'm ... not sure where to begin,\" she groaned."
    "\"I-- I'll make some tea!\" Mikuru declared, before marching into the kitchen."
    "\"I'll help!\" Kanae exclaimed, hurrying after her self-appointed 'big sister'."
    "\"Where are the cousins?\" Kyon wondered, frowning."
    "\"With your aunt Satoko,\" Sasaki answered. \"Um, Kyon-kun, do you remember ... getting into a fight with someone by the name of 'Ryuugu Ryo'?\""
    "\"Uh-oh,\" Tsuruya said quietly, as Kyon looked back over his shoulder to where Kanae had followed Mikuru, recalling a stern warning from Keiichi and Mion in the same house, weeks ago."
    "\"...oh, boy,\" Kyon sighed, rubbing at his own temples."
    "* * *"
    "As much as she'd been trying to hide from the world after everything had gone so horrifically wrong, Kyouko realized she needed to do more than just wait in a hospital except when pulled out by.... By her friends, she supposed. Somehow, despite everything she had done, they forgave her, and even moved to include her in their activities."
    "It wasn't just Koizumi, but the entire group. Of course, even despite that, it was slow going. A sedate stroll through the woods surrounding the village with Koizumi was something she could handle easily enough, though."
    "Somehow, Mion had managed to gather up enough from what remained in her kitchen to prepare a picnic lunch for the pair. Koizumi had happily accepted the basket, and then offered Kyouko a hand."
    "She blushed strongly enough that she thought her face might burst into flame, but had put her trembling hand in his firm grip -- and then he said something about Kyon suggesting a route they could walk down to enjoy the scenery."
    "He hadn't called it such, but by the time they reached the end of the trail, high up on the side of a hill with a breathtaking view of the surrounding valleys, she forced herself to admit it:"
    "They weren't just out for a walk. It was a date!"
    "And she was hard pressed to think of a more handsome and gentle person to be dating. Sure, Kyon was able to do some impressive things, and seemed like a nice person -- but Kyouko would never really know how much of that was her own feelings, and how much was just overflow from Sasaki. Added to that, she especially couldn't think of trying to date him when Sasaki's feelings for Kyon were so strong."
    "That, of course, was ignoring the fact that he seemed to have a substantial crowd of admirers already."
    "It was nothing short of a miracle that no one else had latched onto Koizumi! Or...."
    "Not long after Koizumi had set out the blanket and they had started unpacking their late breakfast, Kyouko managed the nerve to ask, \"Um ... Koizumi-kun, do you have a girlfriend?\""
    "\"Regrettably, no,\" he returned, shrugging with a gentle smile. \"I am unattached.\""
    "Well ... they were already on a date as far as she was concerned -- and she certainly hadn't had time for a boyfriend before. So.... Steeling herself, she turned to admire the view. What better opportunity to confess was there? They were alone, on a picnic, and he was single!"
    "Turning to him, she blurted out, \"The view is great!\""
    "What? That wasn't what she had wanted to say!"
    "Even though his attention was on her instead of the surroundings, he agreed, \"I concur.\""
    "\"I.... I want to say ... thank you for inviting me out for this,\" she stumbled, scowling. Why couldn't she get the words out?\""
    "\"And I'm glad for the opportunity, as well,\" he replied, settling back onto the blanket they were sitting on. \"I enjoy time in your company, and this should be a pleasant vacation, shouldn't it?\""
    "She nodded, feeling her face heat up. \"I'm ... glad we've come to really know one-another, and not just ... be opposed because of who we work for,\" she said quietly."
    "He smiled gently and poured some tea from a thermos for each of them, handing her a cup."
    "Instead of speaking, she sipped at her tea, annoyed with herself."
    "\"Kyon-kun suggested this location,\" Koizumi mentioned, turning to look at the view."
    "When he looked away, her heart skipped, and she felt a sudden release of tension. Somehow, without him looking at her...."
    "\"It is nice to get away from everyone else and enjoy some peace and quiet -- they are my precious friends, of course, but a break is truly wonderful,\" he continued."
    "She opened her mouth, but the words still didn't come."
    "\"Of course ... they are your friends, too. Certainly, Sasaki-san cares for you, and I believe Suzumiya-san and the others are concerned for your wellbeing, as well.\""
    "\"Th...that's,\" she started, before falling short. \"I'm ... glad for that,\" she tried instead, scowling at her hands, unable to keep looking him. \"I ... really am. I like them, too -- Kyon-kun cares for all of his friends and does his best to take care of them ... and everyone else does the same."
    "\"I still ... feel bad about the trouble I've caused in the past for everyone else. But ... I'm glad, and I like them, and....\" She hesitated, then managed to meet his gaze and finally choke out, \"I especially ... really like you.\""
    "He blinked a few times, then looked away, faint color coming to his own cheeks. \"I-- That....\" He sipped his tea and then coughed weakly before setting it down. \"Kyouko-chan ... do you have a boyfriend?\""
    "\"No,\" she answered quickly. \"But I'd like to-- I mean....\" This was it! Now or never! 'I like you' didn't cut it -- this was the real thing, wasn't it? \"I'd ... like to be your girlfriend, Koizumi-kun!\""
    "Finally! Even if it was tough, she'd finally spit it out! But ... did he really care about her that way? Or was he just a thoughtful friend?"
    "When he turned back to face her, his smile answered her questions well enough. \"I'd like that a lot, Kyouko-chan,\" he said quietly, reaching out and gently taking one of her hands in his own. She hesitated only a moment, and then set her half-finished lunch to one side and scooted closer to him. He shifted around, and she was shortly comfortably nestled against him."
    "\"I'm glad,\" she whispered."
    "He laughed softly, musing, \"I hope that everyone else is having a vacation as pleasant as ours!\""
    "She had to agree wholeheartedly ... if only for Sasaki's sake, she could somehow be Kyon's girlfriend! \"I guess it's not possible for things to be perfect ... so I think this is as close as things can really get.\""
    "He nodded, giving her a comforting squeeze."



