label IMRP:
    "Class had started innocently enough that day, but he'd long ago given up on expecting {i}that{/i} to mean anything. With each passing moment after lunch, he grew more and more anxious, stealing glances behind him to make certain that she was still there — still {i}safe{/i}. And every time their eyes met, she smirked knowingly and quickly looked outside, trying to pretend eye contact was never made."
    "He was absolutely certain that if his sense of anxiety weren't imagined, she was the one behind it — one way or another. When the fifth period bell rang, he was prepared. In a way, he'd always wanted to do this; exact that one tiny bit of revenge upon her for all the times she'd done it to {i}him{/i}. So when she rose, turned in one smooth motion, and made to bolt out of the room—"
    "—he was there first, seizing the decorative ties of her sailor uniform's neckerchief and making for the door at top speed. \"Bwa!\" she protested, arms waving frantically as she dashed to keep up, or risk the knot being pulled out. \"What the hell do you think you're doing!?\""
    "Naturally, he said nothing to her during the entire mad dash to the remote stairwell where she had first hauled {i}him{/i} by his own tie, so long ago. He released her at the top of the steps after looking around to ensure that no one else was nearby. Her momentum carried her forward, resulting in him pressing one hand flat against her chest, just below her neck. Her eyes quickly sharpened, her features fixed into a scowl. \"What the hell, Kyon!?\""
    "He held up one hand and said, \"Something's up.\""
    "Her irritation vanished instantly, replaced with wide-eyed excitement. She clapped her hands together and hopped from foot to foot. \"Yes!\" she cheered. \"It's been so {i}boring{/i} lately!\""
    "\"This better not be your fault!\" He shook his head in irritation, then patted his left coat pocket. Then right, then both pants pockets, then the back of each hand. After that, he traced the fingertips of his right hand above his ear, eyes distant, and pulled his cell phone from one pocket."
    "\"What is it?\" she asked, when he spent a long minute studying the screen."
    "\"Maybe a false alarm,\" he admitted, shifting his shoulders. \"Are you messing with me?\""
    "\"I should be asking {i}you{/i} that! But whatever! You hauled me all the way out here — by my shirt, I might add! — so tongues are going to wag! If you're going to do this, then you know what I want!\""
    "\"Haruhi....\""
    "\"Do it!\" she said, bouncing on the balls of her feet in excitement. \"I want to see it!\""
    "\"Is now really the time? Break's going to be over soon—\""
    "\"Get it out now! I want to see!\""
    "Heaving the sigh of the eternally doomed, he put his phone away and muttered underneath his breath."
    "\"Do that voice, too! You know the one? Like from a movie voice-over guy? I love that! Do it! Come on!\""
    "\"Fine,\" he grumbled. \"But {i}you{/i} come up with the excuse for class.\""
    "\"Student council president,\" she said without hesitation. \"Blame him.\""
    "\"{i}Ahem{/i},\" he coughed, shooting her a dark look. \"Take a step back, I don't want to catch you in the interdiction field again.\""
    "She nodded and stepped backwards, against the wall."
    "Standing perfectly straight, hands at his sides, he closed his eyes, and began speaking in his best faux movie announcer voice-over: \"Skinsuit active,\" as something that looked like nothing so much as black paint suddenly engulfed his entire body beneath his uniform. \"Gravimetric stabilizers and secondary gyrometrics online,\" as ridged metal studs appeared on the back of each knuckle, and beneath his uniform pants, metallic vertical rails were described in the skinsuit. \"Greatcoat thermoptic stealth disengaged,\" as a knee-length tan greatcoat coalesced, covering his shoulders with a thick mantle."
    "\"Doesn't that get hot?\" Her smile had only grown, her eyes shining with anticipation."
    "\"We had environmental conditioning added last night, since the weather's heating up,\" he said in a normal voice. Switching back, he said, \"Primary weapons check.\" He pulled a fifty centimeter long glittering metal cylinder from within the greatcoat, releasing it to spin on its axis in midair to one side, announcing, \"Long range precision and high yield weaponry is at full charge.\" A circle of light appeared on the floor around him, a simple white ring with glittering sparks chasing around in either direction, sending brilliant flashes to streak upwards."
    "Another cylinder, wider but shorter than the last was released to float next to the first. \"Mid- and short-range crowd-control weaponry is at ... ninety seven percent capacity and charging,\" he continued, squinting at the featureless gunmetal tube. Pulling a well-crafted sword hilt with no cross- guard or blade from one pocket, he released it horizontally, and it hung before him between the other weapons. \"Beam saber is at full capacity.\" After pulling his cell phone from one pocket, he brushed his fingertips over his ear, revealing three dull metal studs in the skinsuit. \"All systems nominal; no proximity alarms—\""
    "He broke off suddenly, scowling. \"Okay,\" he said in his normal voice. \"My mistake. We've got incoming.\""
    "\"God {i}damn{/i} it Kyon, you're so {i}cool{/i} when you do this,\" Haruhi gushed, clapping her hands together. \"What is it?\""
    "\"I'm not sure,\" he said, as a cold, familiar chuckle echoed. One eyebrow twitched and he stowed his weapons, banishing the ring of light and flinging his phone at Haruhi. \"Speed dial two,\" he snapped. \"Stay in the circle.\""
    "She pouted, but did as she was told, the ring of light reappearing on the floor around her this time."
    "\"Kyon-kun~!\" someone caroled up the stairwell, the echoing click of their shoes sounding as they climbed the stairs. \"It's been a while, hasn't it?\" The school bell chimed just as she rounded the landing, and he activated the beam saber. The blade made a crackling, whirring buzz and shed a soft, pale blue light. \"Y...you....\" she began, before she frowned, blinking, staring at the energy weapon."
    "\"Long time no see,\" he said, switching stance to the long-sword style, Ni-Ten Ichi Ryu."
    "\"Um.... Hm. This is different. You've certainly changed, Kyon-kun.\""
    "\"That's funny, Asakura-san, because you haven't.\""
    "* * *"
    "Author's Notes: I promised. And I wasn't kidding."
    "Now, count the tropes! Save, collect, trade for swell prizes!"
