label SB_4:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 042 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
   
    "Kyon had discovered an interesting side-effect to giving in and letting Haruhi have her way."
    "No matter how 'cute' Ryouko looked as a chibi, there was no way he could bring himself to sleep in the same room as her. In 'good child' mode, she said nothing unless spoken to, but what could he really do?"
    "There was no {i}chance{/i} he was going to let the tiny would-be-murderer near his sister, and who {i}knew{/i} what mischief she would get up to if he left her unattended?"
    "He thought about sticking her in an old shoe-box — possibly even weighting it down and trapping her inside. But then, he didn't believe cardboard would really slow her much if she genuinely attempted a hostile action...."
    "Thinking such things, he was still wide-awake when Yuki's nightly summons came. He arrived in her living room, feeling immediately better that the chibi wasn't around — except for the thought of her being alone with his sister. Mikuru and Kanae had adjusted to the teleportation, and for once, Mikuru hadn't seemed to be in the middle of anything. The slider, on the other hand, was sleeping again."
    "Yuki's gaze swept across him and then paused. \"Asakura Ryouko's presence is disruptive,\" she deduced."
    "\"Hard to sleep with her tiny form lurking in the darkness,\" he admitted. \"I can't say that Haruhi's failed anything she's put her will to, and I know you're backing it ... but it's still too hard for me to look the other way — especially that far. She can't hurt my family, can she?\""
    "\"No. I will provide you secure containment,\" Yuki determined. She rose smoothly to her feet and padded away to her room, while Mikuru knelt at Kanae's side and gently patted the smaller girl's face until she roused."
    "\"Mm.... Mikuru-onee?\" Kanae asked sleepily. She blinked and offered a tired smile at her upperclassmen, sitting upright and rubbing at her eyes, her luminescent blush igniting as she met Kyon's eyes."
    "Yuki returned a heartbeat later with a small cardboard box, the labels proclaiming it to have once held a pair of girl's indoor shoes, approved for use at Kitago. \"This has been modified to securely contain her,\" Yuki said quietly."
    "It wasn't as fancy looking as the sci-fi gun she had given him once, but he had a pair of those whenever he wanted them, so he gratefully accepted what appeared to his senses to be an unremarkable box — one that his mother and sister would both look at him slightly oddly if they ever found. So what if he had a seemingly empty girl's shoe box in his closet? It was a secure prison, where the tiny terror would be sealed away."
    "With this, he would be able to sleep comfortably."
    "\"Thank you, Yuki-chan,\" he said earnestly. He'd have to figure out some way to make it up to her, though.... Hmm, maybe he could take Yuki and Kanae somewhere?"
    "He wasn't entirely sure if that would work, but filed the idea away for later consideration."
    "Yuki nodded back stoically, unable to keep a tiny blush of her own from coming to her cheeks as their fingers touched when she passed the box over."
    "* * *"
    "While she seldom remembered her dreams, except for the very best (and frequently, also the strangest), Kanae knew for a fact that she was sleeping immensely better at her sempai's side — and since Tsuruya had given her a green-light to do that, she intended to {i}keep{/i} doing it, until someone told her to stop."
    "Certainly, her sempai hadn't seemed to mind, and even though Yuki was the one among the club that she knew the least, she felt a tiny bit closer to realize that the other slight figure seemed to feel similarly."
    "That thought in mind, even though she could simply {i}jump{/i} to the clubroom, or the somewhat more reliable concept of her sempai...."
    "It was strange, but she needed to know places better than people, to easily jump to a space with no one around. She wondered what that meant for sliding, and the fact that she tended to look for her sempai ... but there had been occasions when she hadn't found any instance of him."
    "Then again, perhaps her sliding had just landed her far away, and she hadn't learned how to jump closer without starting an entirely new slide? It was hard to say...."
    "Something else Yuki had shown her in those training sessions; really, once she started to think about it.... If she was growing closer to Yuki, and they were both sharing the brigade's vice commander anyway ... she should get the brigade's most silent person something to thank her for her help."
    "That thought in mind, when she went to the train platform, she ran into Haruhi, and a minute later than that, the small girl in question approached the pair."
    "\"He will not be attending classes today,\" Yuki announced, after Haruhi and Kanae had greeted her."
    "\"Aw...\" Kanae couldn't help but pout."
    "\"Yeah, he warned me about that,\" Haruhi admitted with a sigh. \"I was still hoping, though.... Oh! Say, Yuki-chan, does that mean that you know where he is?!\""
    "\"Today is a temporal transition; it covers a stable-time loop,\" Yuki replied after a quiet moment of thought, the trio turning to march up the hill — which Kanae had to fight the temptation to jump to the top of. She had to use her powers responsibly, though; what would her sempai think if she didn't? \"Further information is classified.\""
    "Haruhi allowed an irritated growl to escape. \"You {i}still{/i} won't tell me?\" she complained. \"I just want to time travel once! Or maybe a few dozen times— Come on, what's the worst thing that could happen?\""
    "A few steps away, approaching the group, arm linked with Tsuruya, Mikuru squeaked at that question."
    "\"And,\" Haruhi continued with a frown, glancing at the time traveler, \"if Kyon is time-traveling, why is Mikuru-chan still here?\""
    "\"I...I'll have to come back here?\" Mikuru wondered with a nervous glance around at the others — and more importantly, for any eavesdroppers. \"Um ... I was ordered to tell Tsuruya-chan that Kyon wouldn't need a ride to school today, but that's all I know....\""
    "\"Hmm, I like that,\" Haruhi mused. \"Kyon acts weird around you sometimes because he knows future instances of you, huh?\""
    "\"W...well,\" Mikuru began, before blinking, her eyes widening. \"Oh,\" she breathed very quietly, her expression paling."
    "\"Eh? You didn't think of that?\" Haruhi asked in surprise."
    "Tsuruya, still with one arm linked through the time traveler's, patted the stunned girl's hand. \"Mikuru-chan?\" she asked worriedly. \"Are you alright?\""
    "\"I'm fine,\" Mikuru answered suddenly, shaking her head, still looking mildly dazed, but managing a weak smile. \"I.... Um, there is a piece of information I will need to get from someone who ... scares me a bit....\""
    "Kanae cocked her head to one side. \"Is there any way I can help?\" she wondered."
    "\"I'm not sure.\" Shaking her head, some of Mikuru's color returned, though she still looked horribly nervous. \"I n...need to ask Sasaki-san a question.\""
    "\"How did this come up?\" Haruhi asked warily, narrowing her eyes as she turned her gaze to Mikuru. Kanae winced sympathetically for the older girl."
    "\"U...um ... I think she's seen my future self,\" Mikuru answered meekly, flinching back into Tsuruya, who held her steady."
    "The brigade president nodded thoughtfully, one hand smoothing the ponytail that hung to midway between her shoulder-blades. \"Hmm.... I suppose we'll have to talk to Kyon about that,\" she mused."
    "Pursing her lips, Mikuru hesitantly answered, \"I think that ... Kyon-kun may not be able to answer my questions.\""
    "\"That's silly,\" Haruhi scoffed. \"Kyon's supposed to be one of the best time travelers around, right?\""
    "Kanae nodded eager agreement; she'd heard the same thing on many occasions."
    "Mikuru smiled and gave a hesitant nod. \"But ... he probably isn't supposed to tell me,\" she said, shaking her head. \"And he doesn't have something to keep him from saying things he shouldn't on accident, like a classified information....\" She shrugged helplessly after she trailed off."
    "\"Man, all of this hidden time travel information is seriously getting on my nerves!\" Haruhi groused. \"Everything's gotta be so sneaky — really, you guys have {i}no{/i} idea how to make traveling through time fun!\""
    "* * *"
    "As confusing as everything was, Ryouko realized that the greatest bulk of her time would be taken up with boredom. Since she had nothing better to do but observe and follow her currently assigned tasks, she spent that time observing her surroundings. For a substantial period of time in the night, that had been the interior of a shoe box."
    "Significantly less interesting than the time she spent in her prey's greatcoat pocket. Still silenced, she had tried to test the limits of her current interface status, but her options were irritatingly brief, mostly left in a series of blue boxes with white text, nested in various menus and sub-menus."
    "They didn't let her do much at the moment, anyway."
    "Where had Nagato come up with such a strange idea?"
    "Some time after completing his morning rituals, Kyon finally plucked her from the shoe box with obvious reluctance, tucking her into his greatcoat pocket before heading out to school."
    "At least, Ryouko had guessed that was what he had planned given the data she could read from his PDA. Which she recognized as a once favored piece of her {i}own{/i} data, though Nagato had changed it quite a bit. Now it functioned as a sort of limiter and governor for her abilities ... if she wanted to do anything she wasn't directly ordered to, she had to do it through the auspices of that data."
    "She'd familiarized herself with the data at least, and the PDA automatically enforced his permissions — so she couldn't divulge any information that he didn't authorize. What actually happened, was that a figure that Ryouko did not recognize appeared. She checked with the database on Kyon's PDA and quickly identified the newcomer as matching the picture of Mikuru Asahina, though this was obviously a time-divergent version."
    "\"Er.... Hello, Asahina-san,\" Kyon greeted the woman, glancing around to see if anyone was nearby. \"I take it it's time for more time travel?\" he asked, managing a nervous, worried smile."
    "Mikuru nodded, gesturing him to follow her down the street a ways, then into a small alley. Ryouko reflexively bookmarked the spacial and temporal coordinates as the woman placed one hand on Kyon's shoulder and then invoked a function to destroy local space-time, catapulting them somewhere else."
    "She had weathered stranger transitions before, such as being turned into a smaller holographic version of herself, after all. Once they reached some form of stability, she conferred with the data structures of the PDA. They had moved a few kilometers in space, and back in time a single day."
    "Kyon surveyed the rooftop of the school building and gave a reluctant sigh. \"I should have figured,\" he groused. \"So ... I just need to wait until Asakura attacks, and then step in and save the day. Let's see ... I learned from Yuki what kinds of things would slow Asakura down. Hmm, the only part I'm worried about is arranging that exit from Asakura's data jurisdiction.... Oh— Asakura would know how to do that, wouldn't she?\" He turned to look at his pocket thoughtfully. \"It's a pre-determined event, so in order to prevent a paradox, you'll have to.\""
    "Ryouko grimaced. \"I have to be responsible for assisting with my own capture?\" she asked for clarification."
    "Kyon nodded in response, surveying the surroundings. \"Ah, after this, where should I meet with you, Asahina-san?\" he asked the woman."
    "\"Our usual bench will be fine,\" she said with a wink. \"Oh— And Kyon-kun, one thing before you go to wait for your mission?\""
    "\"Yeah?\" he asked, turning to look at her curiously."
    "With his defenses lowered, Ryouko recorded all of the openings he left, and how Mikuru exploited them. It was a minor inconvenience being squished between the woman and the young man, but she was certainly learning Kyon's weak spots."
    "Mikuru broke the kiss with a giggle and then stepped into the stairwell. Kyon seemed almost ready to follow before shaking his head, hopping atop the stairwell and settling in to wait, adjusting his weapon ahead of time. It didn't take long for him to become bored, though he at least seemed indifferent to his discomfort."
    "Ryouko couldn't {i}speak{/i} unless spoken to ... but when Kyon started up a round of chess, she was delighted for the chance to challenge him and try and learn his true measure, through her link to the PDA."
    "Some hours later, when her best was a single stalemate, she wondered once again what the entity had in mind when they assigned her on her mission. There was no doubt in her mind now that the entity had intended her to fail. Knowing that, she had resigned herself to disrupting her own past-self's environmental control when the time came, allowing Kyon and Haruhi's previous iterations to escape through the gap."
    "She {i}could{/i} have tried to warn her past self, but she doubted her ability to withstand paradox without the entity's help. So, she watched as Kyon stunned and captured her past self, then vanished, swiftly taking an interesting route down the hill — leaping from rooftop to rooftop while cloaked."
    "At one point, he even ran across the top of a power-line. An interesting mode of movement, but inferior to teleportation. Then again, if he was limited in that regard, it was efficient...."
    "He hopped down from his height and landed, undamaged and unnoticed, near a park bench. He studied some passers-by before targeting a nondescript man of average appearance, meandering out of sight and capturing the image with his PDA. Ryouko was irritated to be assigned the task, so imported the costume and disguise, which Kyon activated shortly after that, seeming to the people nearby to just step out from around a bend in the path before sinking to the bench."
    "His PDA was out shortly, though this time he was flipping through notes from his classes, not playing any games. After only a half hour or so, Mikuru's future self trotted along the sidewalk, looking faintly pleased, but very tired. She sat next to Kyon, nodding at him politely, then checking her wristwatch and frowning."
    "Kyon straightened up, then remarked, \"You know, you're very pretty to be here alone.\""
    "Mikuru blinked at that, then smiled slowly, realization setting in. \"I'm not so pretty,\" she demurred, shaking her head. \"But that's quite kind of you. Ah! I wish you good luck; a man as handsome as you should have a date with a younger girl than me, tonight!\""
    "Ryouko had remembered that date well enough. Mikuru and Kyon both chuckled, though Kyon was blushing fiercely beneath his disguise."
    "\"Okay,\" Kyon said, shaking his head once they had settled down a bit. \"This was probably one of the easier loops to close ... is there anything I've left undone too long?\""
    "\"Not {i}too{/i} long,\" Mikuru assured him. \"Um ... according to my superior, anyway....\""
    "He blinked, wondering — not for the first time — if there was some still older Mikuru watching over the woman at his side. \"If it's good enough for you, it should be good enough for me,\" he decided, nodding."
    "Mikuru smiled and reached a hand out. \"I'm glad,\" she said, smiling. \"Now, if you're ready...? Unfortunately, I need to move you forward a bit to reduce your temporal deviation.\""
    "He nodded thoughtfully at that, recalling the time he had taken 'the slow path' back half a day. But then ... if his deviation hadn't been a problem before.... He wondered if that suggested that at some point soon, the balance would shift the other way.... Could he be traveling into the future at some point?"
    "* * *"
    "Haruhi decided to wander to the clubroom to visit with Yuki during lunch, since Kyon was elsewhere at the moment. Or else{i}when{/i}, she supposed. Probably in the past; he was too much of a stick-in-the-mud to go to the future, she was sure. And if he {i}did{/i} he'd manage to clam up about it, somehow."
    "She sighed as she opened the clubroom door, giving Yuki a bright smile as the bookworm looked up at her entrance. Haruhi hadn't really been thinking about it, but the link that they had shared had calmed down recently ... probably because even if she didn't say anything all the time, Yuki was frustrated at Kyon not knowing the truth."
    "\"How are you doing today, Yuki-chan?\" she prompted."
    "\"I am well,\" Yuki answered, closing her book and rising from her seat. She moved it to the table and sat opposite Haruhi. \"How are you?\""
    "Haruhi couldn't help but smile at that. She was still a little awkward, but she was slowly coming out of her shell. No doubt about it, spending time with Kyon was good for her. \"Ah, bored,\" she sighed. Yuki blinked at that, staring at her without otherwise changing her expression."
    "Slumping, Haruhi acknowledged, \"Okay, I'm a little jealous of Kyon and it always bothers me when he's got to do something and none of us can be there. Except, I guess, a future Mikuru.... You know, recently, I've been starting to think that I should have more sympathy for her, considering how annoying and difficult this all must be for her. If even she, of all people, is willing to face Sasaki for answers....\""
    "Yuki nodded, offering, \"Asahina Mikuru's situation is difficult. I also am sympathetic to her.\" She paused for a moment and looked thoughtful. \"She may need a hug.\""
    "Haruhi blinked at that, stifling a snicker, though she still felt warmed by the sentiment. \"That's probably true.... So, what are you reading, anyway?\""
    "The bookworm wordlessly held up a worn but cared for hardcover book titled, 'Brave Detective Sasha and the Red Tape of Obfuscation' by Ryuguu Rena. Haruhi frowned, squinting. \"That's the same 'Ryuguu' kanji as the boy that Kyon got expelled for picking on Kanae-chan, isn't it? I wonder if they're related?\""
    "Yuki seemed uncertain, so before she could try and answer, Haruhi dismissed the obvious coincidence."
    "\"Well, anyway— What's it about?\" Haruhi pressed."
    "\"This is the sixth volume,\" Yuki explained. \"The premise is that a young orphaned girl named Sasha is sent to a seven-year boarding school for detectives by a mysterious benefactor, and must learn the art of deduction and investigation to solve her problems. Each book covers one year of her enrollment. Along the way, she wins several friends and makes some enemies. While some portions of the story are a clearly defined formula, the presentation is a deliberate softening of less palatable themes, carefully dressed to be presentable to children.\""
    "Haruhi raised an eyebrow. \"So, what's the target audience age, anyway?\" she wondered."
    "\"Ages twelve through twenty,\" Yuki answered."
    "\"Hmm.... So, give me an example of one of these 'softened themes',\" Haruhi pressed, intrigued. \"I'm curious, now!\""
    "Yuki gave a tiny nod of acknowledgement. \"In an early story, one of Sasha's closest friends comes under the auspices of an unkind guardian. Sasha and her remaining friends must prove the mistreatment of her friend. When this proves to be difficult, Sasha's love interest — Ichigo — devises a plot to make the guardian ill enough to be sent to a hospital, thus freeing their friend,\" she explained."
    "Haruhi narrowed her eyes. \"I can see how that would be readable to a kid while someone who could read more into it.... Huh. Interesting.\""
    "\"The stories have an emphasis on compromise and reliance on friends to overcome problems, with a special focus on communication. The series is unusual in the extremely downplayed role of violence in Brave Detective Sasha's world. While the threat of mortality is made clear, severe injury and death are exceedingly rare.\""
    "Nodding slowly, Haruhi managed to keep herself from smirking. \"You're becoming a total Sasha fan-girl, aren't you?\""
    "Yuki blinked twice, then turned her attention back to the book, unable to keep the mild flush from appearing on her cheeks."
    "Giving in to the forming smirk, Haruhi grabbed a laptop, quickly checking her favorite website, and finding a wealth of information on the series. She avoided the spoilers, deciding that she'd actually read it — it was written by Kyon's aunt, after all. From there, she found a character art gallery, including promos for a suggested anime adaptation of the series."
    "A handful of images of 'Brave Detective Sasha' were available online, and Haruhi liked the picture immediately. \"Okay! I think Kanae-chan's favorite will be Trope-tan, but for you, Yuki-chan, Mikuru's next project will be this!\""
    "She turned the laptop's screen to face Yuki, who looked up and blinked at the image. Despite Rena's Japanese roots, the setting for Sasha's universe was somewhat more Western, and set in the early nineteen hundreds. Sasha had brown hair cut exactly the same way as Yuki's, and wore a dark plaid-patterned newsboy hat, a neat vest, and a white blouse. Her skirt was patterned just like the hat, going past her knees, but not quite a full-length dress. Other than a pair of darker leggings and sturdy boots...."
    "Yuki nodded, not {i}quite{/i} smiling, but Haruhi was positive that she was pleased with the idea."
    "Her love interest would be trickier, but Kyon could just cheat, after all. Plus, Haruhi knew he looked good in anything, so putting him in the dapper outfit that Ichigo usually wore.... She took a picture of the character and then saved it to her phone; Kyon's PDA could scan it later if it came down to it. \"Hmm, I don't know if Mikuru-chan can have this ready in time to surprise Kyon's aunt tonight ... that would be especially nice....\""
    "Yuki hesitated before finally slowly saying, \"If Mikuru is interested in such a project, I will offer my assistance.\""
    "She smirked at that, giving Yuki a nod of approval. \"Outstanding!\""
    "* * *"
    "Koizumi had been wandering in a happy fog ever since he'd found out that he'd be given a chance to meet his childhood idol. His classes had passed in a pleasant blur, and it had been a real struggle to focus on his job. But the world of Brave Detective Sasha had always been one of his favorites, and he'd tried to model himself after her ideals of deduction and compromise."
    "He found it had actually helped serve him quite well in his assigned role in the SOS brigade in the first year."
    "Still, since today was the day, and he was Kyon's assistant, he tried to gather his wits. He needed to be at his best to meet Rena-sensei!"
    "He entered the clubroom after Haruhi had time to determine who had the responsibility of dressing up, and was mildly surprised to see Mikuru busily sewing away at something, while Yuki sat next to her, measuring and cutting cloth. Kanae watched the pair of them closely, while Haruhi and Tsuruya sat opposite the busy duo. Haruhi was reading the first of the Brave Detective Sasha books that he had loaned Yuki, and Tsuruya was slowly leafing through Kanae's drawings."
    "\"Where's Kyon-kun?\" he wondered aloud, taking one of the free seats after closing the door behind him."
    "\"I'm not sure yet,\" Haruhi said, glancing up from the book, then setting it aside. \"He had something to do today that—\""
    "The door opened at just that moment, and Kyon stepped in, looking unharmed. Ryouko was in his greatcoat pocket, her arms dangling free as she peered around, silent for the moment."
    "\"Successful mission?\" Haruhi asked, raising an eyebrow and looking at him appraisingly."
    "\"Yeah,\" he agreed, nodding, then stiffing a yawn, and taking his seat after setting Ryouko on the table. \"I have a lot more sympathy for snipers, now....\""
    "\"Exciting stuff?\" Haruhi asked eagerly, leaning forward."
    "\"Really boring, actually,\" he answered, shaking his head. \"Seriously — I had to wait three hours in stealth without moving very far.\""
    "Haruhi was taken aback, frowning. \"All of that, just for three shots?\""
    "Ryouko corrected, \"Four!\""
    "Kyon shrugged, adding, \"I don't think the capture field really qualified as a sniper shot, though.\""
    "Yuki had finished cutting cloth, so offered a quiet nod. Mikuru was still working on the last details, completely absorbed in her work."
    "\"Um ... I think it's really good that Sempai can handle situations like that, even if I wish ... um ... you didn't have to...\" Kanae offered hesitantly."
    "\"For what it's worth, with as many combat capable allies as we have, I suspect that relatively few situations should require our vice commander to unleash his full strength,\" Koizumi offered."
    "\"Well, was the team pet any use to you?\" Haruhi prompted."
    "\"What's the team pet?\" Ryouko asked, turning to look around the room curiously."
    "Kyon winced slightly, looking at the chibified schoolgirl standing on the table before him. After almost a minute, she blinked, scanning across the club members, all of which were regarding her, except for Mikuru."
    "\"Don't feel too bad about it,\" Koizumi encouraged her. \"There was a time when Kyon-kun was the lowest ranked in the brigade!\""
    "\"I had to pay a lot more penalties, back then,\" Kyon mused. \"Of course, now I have all these neat toys!\""
    "\"I'm not a pet!\" Ryouko whined."
    "Yuki blinked and quietly ordered, \"Sit.\""
    "Ryouko promptly sat down, pouting. \"If I don't you'll take away my speaking privileges,\" she complained."
    "\"Cheer up!\" Tsuruya encouraged, patting Ryouko's head. \"I think of you as a chibi, not a pet!\""
    "Kanae giggled at that, shaking her head. \"Though ... um, she does look a bit dusty, doesn't she?\""
    "\"We were laying on the top of the roof for a while, and it was very gritty,\" Kyon offered. \"But, anyway, she was helpful, actually. She disrupted her past- self's barrier.\""
    "\"It was pre-determined,\" Ryouko chirped, shrugging helplessly."
    "\"Done!\" Mikuru cheered, looking up from her work with a bright smile. She started slightly. \"Oh! Kyon-kun! I didn't even notice you coming in!\""
    "\"You didn't miss anything,\" he assured her, unable to meet her eyes."
    "Tsuruya smirked at that, then shook her head. \"It's costume change time, isn't it?\" she prompted."
    "\"Oh, right, let me get Kyon first,\" Haruhi agreed, turning to look at the boy in expectancy, holding one hand out."
    "With a roll of his eyes, he handed the PDA over, and Haruhi scanned an image from her phone before punching in the commands to activate his new disguise. He looked down at himself, and Haruhi opened her mouth to tell him what his costume was before he said, \"Ichigo, from Brave Detective Sasha, eh?\""
    "The brigade chief bit back her explanation with a pout, before grinning. \"Yeah, now get out,\" she ordered, pushing Kyon from the room, but giving him time to collect his tea."
    "Once he was waiting in the hall with the other male member of the brigade, the two both checked the hallway for eavesdroppers and began a whispered conversation as Koizumi ventured, \"All things considered, you're doing well?\""
    "\"I've been a lot worse,\" Kyon acknowledged. \"How about you?\""
    "Koizumi smiled and shrugged. \"Naturally, I'm doing quite fine; I'm truly looking forward to meeting Ryuguu Rena-sensei!\""
    "Kyon scratched the back of his head and frowned, gazing out the window opposite the clubroom doors. \"I feel a bit slow, but I hadn't realized how famous Auntie Rena was until just recently,\" he admitted."
    "The esper nodded sagely. \"Ryuguu Rena-sensei is incredibly secretive about her private life,\" he explained. \"So, beyond her name, very little is known about her beyond the fact that many of her books are dedicated to her daughter, and 'all of her cute little nephews and nieces'. She doesn't answer personal questions at signings or readings, either.\" He couldn't help but chuckle at Kyon's wince. \"Dedicated fans have searched, but had long ago concluded that it was actually an assumed name; the closest real person to that name anyone ever found was someone who was officially listed as 'Ryuguu Reina'.\""
    "Kyon shivered for some reason at that, frowning thoughtfully. \"Somehow ... that sounds familiar,\" he mused quietly."
    "Koizumi raised an eyebrow at that, then shrugged, dismissing it. 'Ryuguu Reina' probably didn't matter, considering that he had finally gotten the chance to meet the genuine article. He glanced around to ensure that the area was clear before proceeding to the next topic of discussion."
    "He'd practiced with Mori a little bit ... and was actually getting to the point where he could pick out some thoughts when he focused on someone and attempted to 'link' with them. Unnerving as it was practicing on a willing subject, it wasn't {i}half{/i} as alarming as the thoughts that went through that woman's head. Still, considering that Kyon had — once again — been on a mission where Koizumi had been entirely uninvolved...."
    "\"I would like to be able to stand at your side when you confront your foes at some point,\" Koizumi commented. \"When we faced Wataru the first time, I did not have the option to try and ... see what he might have known. If we confront him again, that may change. I suspect I could be able to offer more, even from the ostensibly passive role of observer,\" he continued, as Kyon turned to give him a speculative look. \"Once I practice using my skills a bit more, at least.\""
    "\"Have you tried Taniguchi?\" Kyon asked with a smirk. \"I'm sure his mind is filthy, but it's probably pretty simple.\""
    "Koizumi chuckled politely. \"I have not,\" he answered, shaking his head. \"The idea of using such a power vicariously.... It seems it would be a simple trap to fall into, and harder to escape. I have so far restrained myself to willing subjects.\""
    "Kyon nodded at that, not looking particularly surprised. \"That's commendable. Okay, I'll ask Yuki-chan if she can include you for a training session,\" he decided. \"Then you'd get a relative year to practice — maybe less if it's hard for her to figure out how your powers work.\""
    "The esper blinked, having forgotten that particular aspect and explanation for Kyon's skills. \"Is that so?\" he wondered."
    "The boy dressed in the western outfit from the 1920s nodded, draining the last of his tea. \"Tsuruya wanted to try it once, and Yuki-chan figured out how to give her a chance. If it's not too much trouble, she can probably do the same for you.\""
    "The esper nodded thoughtfully at that, offering a smile to his friend. \"I would greatly appreciate that,\" he admitted."
    "Before Kyon could answer, the door was unceremoniously wrenched open by Haruhi, cheering with a loud, \"Ta-da!\""
    "Both boys turned to look in simultaneously, both pausing when they spotted Yuki. Her costume as Brave Detective Sasha, looked almost perfectly spot on, except for the absence of Sasha's eternally luminescent spots of blushing color and smile, and Yuki's hair being a lighter color."
    "Koizumi thought it was cute, anyway. \"That's quite charming,\" he remarked."
    "In response, Kyon reached into his coat — though, thanks to the disguise, it appeared he reached into his vest — and pulled out what looked like a faithful reproduction of Ichigo's signature improbably over-sized wrench, propping it over one shoulder. \"Time to solve another mystery, Sasha-chan?\" he asked."
    "Yuki nodded, answering in her almost toneless way, \"Of course, Ichigo-kun.\" Kyon grinned, then reached up to tip back his illusionary hat, which obligingly moved with his hand."
    "Even though the vice-commander was a bit too tall for the role, compared to Yuki's Sasha, Koizumi couldn't help but clap his approval for the duo. \"Very nice!\""
    "Yuki looked down at her vest and skirt, then straightened and agreed, \"Mikuru's effort is worthy of praise.\""
    "The time traveler blinked at that, blushing. \"O...oh, well, it's nothing—\" she demurred, before Yuki surprised her into wide-eyed silence by suddenly giving her a hug."
    "\"Thank you,\" Yuki said again, though her voice was somewhat muffled by Mikuru's chest."
    "\"Ah, um,\" Mikuru temporized, reflexively hugging Yuki back as her face almost instantly flushed crimson, her eyes tracking across the others beseechingly."
    "\"Cute!\" Kanae and Tsuruya cheered together, as the heiress and Haruhi simultaneously reached for their cameras."
    "After that, Kyon and Yuki had to pose, and Koizumi wondered at the implied romance of the cosplaying pair. Sasha and Ichigo were somewhat of romantic interests, but the books were very subtle about that, limiting it (so far) to hand-holding. Rumor had it that the seventh and final volume might contain a {i}kiss{/i}, but...."
    "Well, Haruhi seemed to like it — if not actively demand more, so he supposed that made a certain degree of sense."
    "\"We should probably be heading out soon, if we don't want to be late,\" Kyon finally commented, glancing at the clock."
    "\"Right,\" Haruhi agreed happily, leaving her camera on the clubroom table. Ryouko was looking at Yuki with an expression that seemed to convey confusion. \"Hmm, you don't like the cosplay?\""
    "\"I've never seen Yuki-chama in other clothes,\" the chibi offered."
    "Haruhi nodded, remarking, \"It did take some doing....\""
    "* * *"
    "Ryuguu Rena was not terribly worried about the success of her new book. She did enjoy the time she got to spend with her fans, and she absolutely adored creating the worlds and stories that her characters went through. Nishinomiya wasn't the most notable place in the world for her to have a book signing, but Keiichi was headed there on business anyway, and Rika couldn't leave on account of the upcoming festival in Hinamizawa."
    "Satoko might have gone instead, but she tried bluffing on a pair of fives when Rena had a full house."
    "Her publisher had agreed to find a venue after Keiichi talked to them, and so she'd been looking forward to the chance to see Kyon and his girlfriend. Girlfriends, she supposed — but she really wanted to meet more than just Haruhi. Oh, Haruhi was likable enough — they were all agreed on that — but she was curious to meet the others."
    "Considering the fact that Keiichi was kept busy with his work, she'd been somewhat bored, having little to do. There were still ideas for other books that she hadn't quite jotted down, but so far nothing had really leapt out at her the way the premise for her first series had. Especially, she didn't want to start writing something while traveling, though. Something about that felt strangely like a bad idea...."
    "She'd tried calling Kyon's house and lucked out by getting Yuuto instead of Keiichi's sister, but there hadn't been a good chance to arrange for a visit."
    "Yuuto was being polite, she knew, but his wife...."
    "Gloomy thoughts like that haunted her until Keiichi came back to their hotel room and dismissed her worries with that patented Keiichi magic. And once she was confident she was ready for it, he commented that he'd briefly run into Kyon at work — though, the nephew in question had actually been on a date, to appearances. And while Rena {i}wanted{/i} to be happy for Kyon and wish him luck, well ... she hadn't gotten a chance to meet all of the girls he was involved with."
    "That Suzumiya girl was adorable, but Satoko and Rika had gotten to meet an Asahina Mikuru, as well — and everyone {i}but{/i} her had gotten a chance to meet with Tsuruya Haruka."
    "Really, Rena was confident that her winning hand was just the cosmic balance of the universe making up for that lack and letting her visit Kyon. She'd mentioned as much to Rika, who immediately adopted that amused, 'I know more than you', look she wore from time to time.... But then, after wearing that face, something pleasant almost always happened to one of them, so she wasn't {i}worried{/i} precisely...."
    "Just a bit anxious."
    "The bookstore for the venue was fairly sizable, and she waited in the back room with the store manager, who was babbling something about sales she didn't care about. Keiichi was nearby, speaking quietly on his cell-phone, his eyes distant as he nodded, and Rena's publicist — Kimiyoshi Natsuki — was flipping through some paperwork thoughtfully, occasionally glancing through the door to where a swelling throng of fans waited for Rena to come out for the signing."
    "\"Great!\" Keiichi said happily. \"I'll find you based on that— See you soon!\""
    "\"Good news?\" she asked anxiously, clasping her hands together."
    "\"Great news,\" he assured her with a grin. \"Just wait here one minute, alright?\""
    "Natsuki beamed a smile at him as Keiichi walked out into the crowded bookstore without hesitation. A few short minutes later, he came back, looking amused as he led Kyon through the doorway — Rena couldn't help herself and immediately seized him in a hug. \"Kyon~!\" she cried in delight. He was even dressed up as Ichigo!"
    "\"Now hold her,\" Keiichi ordered Kyon, who looked confused but did as instructed, hugging Rena back."
    "\"Eh?\" she managed to noise, before she spotted the incredibly cute girl dressed up as Sasha, right next to the girl she recognized as Haruhi. \"I'm taking you home!\""
    "* * *"
    "Koizumi's first meeting with the legendary figure of his beloved Ryuguu Rena- sensei was not at all what he'd anticipated. He thought from the way she'd written that she was a coolly collected person, not the excitable and ... energetic figure that by appearances, Kyon only {i}just{/i} managed to physically restrain from charging at Yuki to envelop her in a hug."
    "Of course, the second she got free from Kyon she managed to sweep Yuki up {i}anyway{/i}."
    "A few moments later, she'd calmed down enough to accept introductions, and Koizumi was pleased to finally get a chance to meet her. She raised an eyebrow at his name, and before he even got to reach for his membership card, she laughed softly and said, \"We've exchanged several letters, haven't we, Itsuki- kun?\""
    "\"Y...you remembered?\" he asked, surprised."
    "She nodded at him, and the woman that Koizumi gathered was an assistant or aide motioned Rena out to the floor proper."
    "\"Okay,\" Rena allowed, nodding at her assistant. \"Thank you, Natsuki-chan. My cute little Kyon and the even cuter little Yuki-chan can sit with me while I sign, though~! You're dressed too perfectly not to!\""
    "\"I agree!\" Haruhi encouraged, grinning."
    "Rena smiled and waved as she led Kyon and Yuki out to the main floor of the bookstore."
    "Koizumi managed to restrain himself, even though he felt an urge to join the crowd and wait in line.... Well, he'd get more of a chance to talk to her later, he was confident."
    "Sure enough, once the signing had finished, Rena returned to the back room, unwilling to release the Sasha cosplayer from her grasp. \"Too cute!\" she declared."
    "\"Hmm,\" Keiichi remarked, smirking. \"Alright— Natsuki-san, I'm going to take my nephew and his friends out to eat, would you care to join us?\""
    "\"Thats alright,\" the woman declined with a shake of her head. \"I've got some more paperwork to catch up on.\" Turning to Rena, she added, \"Thank you for your hard work, Rena-san.\""
    "Rena finally released Yuki to giggle in embarrassment before nodding back at Natsuki. The second the woman was gone, Haruhi remarked, \"I think that Kyon's aunt Rena is very pretty — and that Mikuru-chan will grow up to look just like her!\""
    "For whatever reason, Kyon choked at that, shaking his head quickly once before suddenly becoming utterly fascinated with a floor tile."
    "\"R...really?\" Mikuru squeaked out, eyes widening. \"I might be ... {i}that{/i} pretty?\""
    "Kyon continued his intense study of whatever it was that occupied his attention."
    "\"I don't think she'll look a thing like me,\" Rena demurred, taking Mikuru's hands in her own. \"She'll be much cuter! Ah! You must never wear anything with a low neckline; you'll steal my cute little Kyon away for sure like that!\""
    "Tsuruya's guffaw broke what might have otherwise been an uncomfortable silence, and Keiichi joined in, if not as heartily. \"Rena-chan,\" he chastised her, still smiling."
    "Rena pouted, then distracted herself by hugging Kanae-chan. \"But you!\" she exclaimed. \"This cute little kohai for my cute little Kyon!\""
    "Kanae giggled at that, her face suffused almost as crimson as Mikuru's."
    "Koizumi began to wonder if his idol were bi-polar, while Haruhi merely took dozens of pictures. Kyon looked up suddenly, as Keiichi was checking something on his cell phone, and asked, \"Ah ... Haruhi ... where did we get so many SD cards, anyway?\""
    "\"Spoils of war,\" she declared without hesitation."
    "He gave her a stern look. \"Did you steal the evidence from our investigation?\""
    "\"I appropriated resources for Brigade use,\" she corrected with a sniff. \"Aside from which, I gave everything {i}incriminating{/i} to the police."
    "After a pause, she added, \"Yuki-chan formatted these for me.\""
    "Kyon pursed his lips and nodded grudging acceptance, seeming to realize that he wouldn't win this argument."
    "\"Ah, I can't decide!\" Rena protested, still clinging to Kanae. \"You're all so perfect for my cute little Kyon!\""
    "\"Well,\" Keiichi said, \"why don't we move this discussion somewhere we can get something to eat? Personally, I'm famished.\""
    "\"I haven't eaten since breakfast,\" Kyon agreed."
    "\"My treat,\" Tsuruya insisted suddenly, grinning. \"We're a big party, so let me cover it!\""
    "\"Oh, I can't possibly allow that,\" Rena insisted, shaking her head quickly. \"It's so cute that you'd offer, though~! Ah, no — you came for my signing, let me treat you!\""
    "Tsuruya opened her mouth to protest, and Keiichi commented, \"Really, whichever of you accepts the responsibility is going to write it off as a business expense on taxes later, right?\""
    "Koizumi was mildly surprised to see both Rena and Tsuruya nod guiltily."
    "\"Well, the same goes for me,\" he said with a grin, shrugging. \"So, allow me, instead.\""
    "Rena pouted, but Tsuruya acquiesced. \"If you can get a free meal from your lawyer, it's a good day,\" she acknowledged, eyes sparkling."
    "\"Well,\" Kyon remarked, still in his 'Ichigo' costume, \"you're almost family, Tsuruya-kun, considering that we're engaged.\""
    "\"Eh,\" Rena managed, blinking once as her smile hardened, seeming suddenly more like a mask than the genuine article."
    "\"Y...you're engaged?\" Keiichi asked, his humor draining away, replaced with surprise before his face fell, and he slapped a hand to his forehead. \"Oh, damn.... Imouto.... She thought she was doing you a favor, huh?\""
    "Kyon nodded, his own smile fading. \"Mom didn't.... Didn't even tell you?\""
    "Rena very gently pushed Kanae towards Mikuru, giving her a soft pat on the head before drawing herself to her full height and giving Keiichi a sharp look. \"Kei-chan, we need to speak with—\""
    "\"Ah— No,\" he said, shaking his head and overriding her before she could finish. \"Rena-chan, I think that needs to wait until we're back in Hinamizawa.\""
    "Rena's right hand began to curl, perhaps into a fist, and she seemed to stop herself with an obvious display of will, grabbing the palm of her right hand in the fingers of her left and rubbing at it. \"Um ... writer's cramp,\" she said apologetically, offering a much weaker smile."
    "\"Ah, if that's something that's bothering you, it shouldn't,\" Haruhi said, shaking her head. \"We've already accounted for that interference.\""
    "\"Pardon?\" Koizumi couldn't help but wonder."
    "Kyon returned to studying his fascinating floor tile. Keiichi raised an eyebrow, fighting harder and harder to resist snickering as he scanned across the others in the room, who were all blushing, with the exception of Yuki and Haruhi."
    "\"Time for dinner, then,\" Keiichi determined, opening the rear exit and gesturing the group through. \"There's an udon place down the street that's supposed to be really good!\""
    "\"Right!\" Haruhi declared, grinning at Tsuruya. \"So let's have fun!\""
    "\"Everyone should just have fun!\" the heiress agreed."
    "* * *"
    "After everyone had eaten, a few hours had been lost to pleasant chatter. Once Rena had gotten over how 'cute' everyone was, she seemed to calm down a bit. She had engaged Koizumi in discussion over the course of the evening, and had proven surprisingly insightful, considering her initial, somewhat flighty behavior."
    "Kanae was still puzzling out what to make of the woman, beyond a general good impression for both facets of her behavior. Everyone had a good time, at least — just as the older girls had insisted."
    "In step with her, Mikuru held her free hand as they walked to her apartment."
    "\"You're sure you won't be in any trouble?\" the taller girl wondered. \"Um, that ... no one will see?\""
    "\"I picked out a really good spot to the side of the house that no one ever goes to,\" Kanae replied confidently. \"So I'll just jump back from your place.\""
    "Mikuru nodded, offering a smile to the smaller girl. \"I'm a bit envious,\" she admitted. \"I can't do that sort of thing without permission, but you can,\" she trailed off with a giggle, then continued, \"'jump' wherever you like. That must be nice!\""
    "Thinking of the only places she'd used her ability so far, she nodded eagerly. \"It's much better than the, erm, alternative. I really, really like this world! I'm so lucky to have Sempai, and Suzumiya-sempai is so brave, and Tsuruya-san and Mikuru-onee, too!\" she agreed. \"And especially Nagato-san.... She's kind of scary and amazing at the same time, you know?\" she asked, blushing in embarrassment."
    "\"I understand exactly,\" Mikuru replied, giving the slider a warm smile. \"Now, Kyon-kun knew this before anyone else ... but Yuki-chan is a very sweet girl. She just needs people to look a little beneath the surface!\""
    "Kanae's face reddened as she considered her recently growing ... nearness ... to Yuki in their sleeping arrangements. Hmm, she wondered what her sempai would think if she suggested that Yuki-chan swap the slider for the time traveler some night.... Though, it would be difficult to bring herself to actually give up a night of that on her own. She resolved herself to at least bring up the idea with the quiet but powerful girl; really, it did seem a {i}little{/i} unfair not to share her time with her sempai with the other girls...."
    "\"Well, I promise to try and make it so that everyone benefits from what I can do as much as possible,\" Kanae decided. Yes, she realized, this was a good plan; Suzumiya-sempai would surely approve, and so would Tsuruya!"
    "That thought in mind, Kanae saw the time traveler to her apartment, where she was insistently ushered inside. \"It's safer in here, with only myself to see you leave like this,\" her self-proclaimed older sister warned her, smiling."
    "Kanae agreed and waved goodbye, but before she could leave, Mikuru gave her a hug, and then a soft kiss on the forehead. \"Take care, imouto-chan!\" she chirped."
    "The slider dazedly managed to nod, forgetting her plan to return home and instead jumping straight to Yuki."
    "She felt the space between her and Yuki snap together — pinched and contorted a little, instead of tearing it open like she needed to in order to slide — and shifted herself to the other side of the field. The second she did, her control over the bridge collapsed, and instead of letting it fade neatly, it snapped shut, catapulting her at an odd angle across the space she'd just entered."
    "A cry of alarm began to escape her before she stopped as abruptly as she'd been flung, suspended over the floor of Yuki's washroom mid-sprawl, her hands a few centimeters from the tiles. The other girl, for her part, was sitting in the bathtub with a book in one hand, her legs dangling over the side to balance the heat of the water against the coolness of the air. From her angle, Kanae's face was {i}just{/i} high enough to make out the form of Ryouko's tiny self, wearing an absurdly cute swimming-ring and paddling around the side of the bath that Yuki wasn't using."
    "Most importantly, Yuki was directing a palm towards the slider, evidently responsible for preventing her collision with the floor."
    "\"Um,\" Kanae managed, blinking, stuck for the moment in mid-air. \"I-I— I really should have called in advance?\" she squeaked out apologetically."
    "Ryouko splashed suddenly, only just then seeming to notice the slider's presence. \"Ah!\" she gasped. \"An intruder! I'll protect Yuki-cha—\""
    "Yuki tossed her book to the floor near Kanae, and used her newly freed hand to grab Ryouko and plunge her beneath the water, whereupon a suffusion of bubbles began to well upwards. \"I felt it inadvisable to allow her to wash with him,\" the girl offered softly in explanation, not {i}quite{/i} meeting Kanae's eyes. \"Also, the space around this dwelling has several defensive modifications in place; while you are welcome here, you are correct that you should call first.\""
    "She paused, then Kanae's position righted itself and she found herself set gently on the floor, standing upright. She hurriedly removed her shoes, incidentally averting her eyes as Yuki rose from the water, simultaneously allowing Ryouko to gasp, greedily sucking air in from her extended immersion. \"Yuki-chama...\" Ryouko panted, her tiny eyes all swirly. \"So ... cruel....\""
    "By the time Kanae looked up, Yuki was already out of the tub, releasing the plug to drain and then totally ignoring the tiny figure, which wailed and paddled frantically to reach the tiny swimming ring as though it were a life- preserver."
    "\"Um....\""
    "\"It is fine,\" Yuki insisted."
    "A few minutes later, Yuki was redressed, sitting with Kanae in the front room. Distantly, the slider was confident that she could hear the sound of incredibly tiny hands scrabbling at the interior of the bathroom tub, trying desperately to escape, but Yuki was pointedly ignoring it."
    "\"Erm,\" Kanae managed, nervously playing with the cup of tea that Yuki had given her, not tasting it yet, \"I w...wanted to suggest that maybe we, er ... you and I, that is ... should take turns and let the others spend time with, um, Sempai, too?\""
    "Yuki nodded slowly, her eyes still largely unreadable to the slider. \"Understood.\" She paused. \"Asakura Ryouko does not have to be included in this rotation.\""
    "Kanae blinked, not really certain what to make of that. Well.... \"That's probably fine by Sempai, too!\""
    "\"Good,\" Yuki decided, allowing the tiniest of smiles."
    "* * *"
    "Even though everything seemed to have calmed down, Sasaki was still uneasy. The idea of seeing Kyon in a few days wasn't nearly as reassuring as it should be; she was almost confident her associates were planning some strange trap for her friend. She may not be able to understand all the nuances of Kyon's job as an organized criminal, and she was slightly embarrassed to realize that as willing as she was to accept his assistance ... she didn't really {i}want{/i} to know the details of what he did."
    "He seemed just and reliable, and she couldn't bear to imagine him being little more than a thug."
    "Then again, considering how the people who wanted to call themselves her {i}friends{/i} behaved...."
    "Kuyou had been around much less lately, strangely seeming to fade into and out of Sasaki's focus, though she had completely vanished for a few days on Monday, not making another appearance until Thursday. It wasn't until she was headed to her Saturday session of cram school that she appeared suddenly from the crowd to walk at Sasaki's side."
    "\"At the node of {i}{/i}{i}{/i}{i}{/i}{i}{/i}{i}{/i}{i}{/i}{i}, remain {/i}{i}{/i}{i}{/i}{i} his ambit,\" she announced abruptly, staring forward and matching the other girl step-for-step, the others on the street seeming oblivious to her presence and odd manner of speech, as always."
    "\"Ah.... Kuyou,\" Sasaki returned, frowning. \"By 'his' you mean Kyon?\" She didn't really understand what Kuyou meant by 'ambit', though. Did Kyon control a territory she should try and stay within? That would make a good deal of sense. Or was it simpler, and she was just saying that Sasaki should try and stay {/i}near{i} Kyon? That made sense, too...."
    "Kuyou nodded before she turned to look at someone emerging from the crowd, waving eagerly at the pair of them. \"Ah, Kunikida-kun,\" Sasaki recalled, nodding at the boy. Come to think of it, he was classmates with Kyon still, wasn't he?"
    "\"H...hey, Sasaki-chan,\" he panted, catching his breath from his jog."
    "She gave him a small, polite smile, not appreciating the diminutive honorific from him, but restraining herself from pointing it out. That much honesty could be a bit painful for some people if she spoke it too easily."
    "He shook his head to dismiss something, looking sidelong at her. \"Ah, we.... We have a practice test on Tuesday, and I've actually been trying to compete with you; last time our scores were very close! Wouldn't it be something if we were the two highest scores?\""
    "It would be a statistic, she didn't reply. Instead, she answered, \"I suppose it might. Hmm, Kunikida-kun, you're still classmates with Kyon, aren't you?\""
    "\"Yeah,\" Kunikida answered with a sigh, slumping a little. \"He's sure getting popular....\""
    "Sasaki giggled. \"Jealous?\" she teased, which actually made Kunikida flush guiltily. \"That's silly, though. Kyon's engaged, and while he might be on occasion weak-willed, I couldn't see him cheating on someone. He couldn't hurt someone he cared for like that.\""
    "Kunikida was so distracted by her comment that he actually walked face-first into a utility pole, rebounding and sitting dazedly on the sidewalk in a heap, grimacing. \"K...Kyon's {/i}engaged{i}? He and Suzumiya— When did this happen?\" he burst out suddenly, drawing attention from everyone passing by, and pressing one hand to his nose."
    "\"I would have expected that too, but he's engaged to that older girl — ah, Tsuruya-san, was it?\""
    "Kunikida's eyes widened even further, and Sasaki winced internally. If this was something Kyon had avoided letting around at school, she might have just ruined that."
    "\"Ah— Well, perhaps they were playing a prank when they told me,\" she quickly said, forcing a smile. Where had Kuyou run off to, anyway? She bit back a sigh. \"At any rate, on the chance that it {/i}was{i} a joke, it would probably be for the best not to mention it — especially if he hasn't said anything about it himself.\""
    "Kunikida nodded doubtfully and hesitated a moment, almost seemingly expectant of something before he sighed and climbed to his feet again. \"I can't really keep up with what he does these days,\" he said. \"But honestly ... he is becoming quite popular, even if he seems not to realize it. For certain, if the rumors are true, then he's got quite a following for saving the girls of our school from major embarrassment."
    "\"Well.... Even if it's an unorthodox method, his way of attracting weird girls to him seems to have worked out in the end; people like us, though, will need to pursue a real education to be successful.\""
    "She pursed her lips and offered a dubious nod. She wasn't really looking for it, but as obvious as Kunikida was at this point.... Well, at least he hadn't worked his way up to confessing, she supposed. In a sense, she realized that he might think he was being clever; being Kyon's friend, if Kyon had talked to {/i}anyone{i} after she'd accidentally hurt him, it probably would have been Kunikida."
    "And Kunikida, he was fairly clever. Did he think that by playing smarter, he could walk in Kyon's footsteps and figure out how to 'succeed' where Kyon hadn't? Of course ... Kunikida didn't know how wrong she realized she was in the first place."
    "No; she had to cut this off before it became problematic. Aside from which, Kunikida could easily become a victim of the web that she herself was snared in. Kyon, at least, was strong enough to be indifferent to it, but making things difficult for him by needing him to protect yet another person...."
    "\"The way you say that ... Kyon seems remarkable enough to succeed without education?\" she wondered. \"Somehow, I don't believe that his mother would agree.\" Not from what she remembered of the woman, anyway."
    "She'd thought Kyon's mother liked her, commenting that she was a positive influence on Kyon's study habits. Her own mother was convinced of that, at least. It didn't help that her mother had a habit of constantly wondering aloud what had happened to her old study partner."
    "\"Well, I meant more to say that he's got enough people worried about him that he should be fine,\" Kunikida mumbled, looking away."
    "\"I have to admit, I'm one of those people,\" she sighed. \"Ever since he was injured for that thing you mentioned earlier....\""
    "\"M...maybe we could discuss more pleasant topics?\" he suggested, managing a hopeful smile."
    "She nodded graciously, glancing down the street, at the entrance to the cram school building. \"I remember when Kyon and I used to come this same route for cram school,\" she sighed, pretending to be a little more wistful than she actually was. Strange how easily that came to her. \"I'd ride on the back of his bicycle....\" Only, now that she'd brought it up, she {/i}did{i} miss those memories...."
    "It was mostly scary at first, her hanging on, uncertain of her grip and terrified of bouncing off to fall into the street. After a week or so, she'd become adjusted to it, confident that she could hold on with one hand, and close her eyes, trusting in Kyon to pedal the pair of them safely through the dark. There was only one incident where something went wrong — and it wasn't so bad."
    "Either a rock or a curb — she wasn't certain — but something had caused the wheel to turn almost exactly ninety degrees instantly. The bicycle flipped over, throwing the pair of them into a pile on the lawn at the side of the path. Kyon was grumbling about skinning an elbow and bruising himself, but what Sasaki had noticed most was that while they were flung free, her trust had been rewarded; somehow, he'd managed to twist around, making sure he landed on his back, but cushioned the blow for her."
    "For a very brief moment, she'd thought he'd done it on purpose, some juvenile attempt at getting a hug, or maybe even trying to feel her up— Though, he didn't do that at all, actually. Almost immediately, she dismissed that. She and Kyon were {/i}friends{i}; that was all. He'd proven that by trying to take care of her...."
    "And again more recently."
    "\"Sasaki-chan?\" Kunikida asked, waving a hand before her worriedly."
    "\"Ah,\" she started, shaking her head, realizing she'd come to a stop before the bicycle rack in front of the cram school. \"S...sorry, my mind was elsewhere....\""
    "\"Are you alright?\" he asked, frowning even more deeply."
    "\"Just old regrets ... nothing important,\" she assured him, trying to force her smile again. Though.... It might be a little cruel — both to Kunikida, and in the long run, herself, but...."
    "\"Kunikida-kun ... could I ask you for a favor?\" she wondered."
    "\"Anything,\" he replied immediately, perking up slightly."
    "She pointedly pretended not to notice, asking, \"Since you see Kyon so much, could you ask him for a more recent picture? The only one I have of him is a bit older.\" From before they'd actually become closer in cram school, as it so happened. And while she probably {/i}could_ ask Kyon directly, she didn't want to give him the wrong idea; the whole thing was naturally just for Kunikida's benefit, to save him a more painful rejection later."
    "That was all."
    "Risking a sidelong glance, she caught the shorter boy's pained flinch. \"Ah.... Y...yeah. I can ask him for a more recent picture,\" he agreed with a sigh. \"Um ... I'll see you after class, maybe?\""
    "She nodded, warning him, \"I'll be skipping cram school on Monday — I'm meeting with some friends.\" Admittedly, she wasn't sure which of her associates were actually friends at the moment. Kuyou was probably on that list, and Kyon absolutely was. Fujiwara she was still less certain about, though at least he was genuinely trying."
    "There wasn't any question about Kyouko, who Sasaki had successfully avoided for almost a week, now."
    "\"Tuesday, then,\" he said, offering a wan smile."
    "\"Tuesday,\" she agreed."
