label OB_4:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 047 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
   
    "Morning found Kyon with a surprising, soft pressure against his lips, and his eyes slowly drifted open as he reflexively kissed whoever woke him back. He glimpsed Tsuruya's eyes briefly before she closed them, and then he closed his own, enjoying the dream for what it was. His right arm was pinned, but he got his left free to press against her back and run his fingers up and down her spine, prompting her to shiver and break the kiss with a quiet gasp."
    "Eyes opening, he looked up at her face, surrounded by a curtain of her loose hair, shadowing both of them. Her lips formed a smile at him as she blushed, rising on hands and knees to push herself off him and move to his left side. On her knees, she gathered up the hair that had gotten loose, giving him a gentle nudge with one knee and whispering, \"Wake Haru-nyan the same way!\""
    "Or, perhaps, he realized, it wasn't a dream at all? But ... Haruhi and Tsuruya instead of Kanae and Yuki? Not that he was going to complain for any reason; it was a different, but still winning combination."
    "He couldn't really find a reason to deny Tsuruya's command, though ... it wasn't like he hadn't kissed Haruhi in front of Tsuruya before. As pleasant a wakeup as his own was, he hoped he could do the same for her. When he turned to look, the girl had snuggled up to his right arm and clasped it tightly to her chest, her sleeping head resting on his pillow, her cheek pressed against his shoulder as she softly breathed."
    "She looked undeniably cute that way."
    "With some care and wriggling, he managed to pull his arm free enough to kiss her properly. She made a quiet hum and kissed him back, her eyes fluttering open. After a single moment of surprised confusion, he found himself pulled down tightly against her as she returned the kiss with increased enthusiasm."
    "\"Hehe,\" Tsuruya chuckled softly. \"Good morning, Haru-nyan~!\" before Haruhi finally released him to gasp for breath."
    "\"Good morning!\" the brigade chief echoed with a proud grin, her gaze flicking across the bed to Tsuruya. \"Now {i}that's{/i} how to wake up! Can't help but be pleased that Kyon's an early ri—\""
    "Whatever else she was about to say was cut off as both girls vanished abruptly, simultaneous to his door opening. His mother stepped halfway in, though she was still looking worriedly over her shoulder, down the hall. \"Kyon,\" she called, \"if you're done with your phone call — your sister's really not well, I could use your help for a bit before you go to school.\""
    "He climbed out of bed with a frown, taking a moment to switch mental gears. Of course ... Nonoko had been sick, and he'd forgotten with the time travel. It wasn't that bad before, though ... had she taken a turn for the worse?"
    "\"Mo~om,\" Nonoko moaned quietly from her room, before a wheezy, rasping cough escaped. \"I'm thirsty!\""
    "\"I need some clean washcloths and a fresh bag of ice,\" the woman in the doorway ordered, finally turning to look at him, revealing her worried, weary expression."
    "\"Got it,\" he agreed without hesitation, not even changing out of his pajamas before he moved towards the stairs."
    "* * *"
    "Annoyed at the interruption that sent her home — but glad that Kyon hadn't been caught with the pair of them in his bed — Haruhi rushed to school as quickly as she could after rising. For all her hurrying, at least she had her telekinesis to help with the process of making breakfast and lunch for herself and Kyon."
    "For all of that, though ... Kyon didn't make his normal train to the station. Troubled, she considered calling him, but instead decided to head to the school. He occasionally did catch rides with Tsuruya, and she might have intended to say something to him before they'd been interrupted, too.... Maybe that was it?"
    "He wasn't in class when she got there, arriving earlier than anyone else except for Saeki and Takato."
    "Her irritation growing, she watched more and more students trickle in — none of them Kyon. She hated when that happened!"
    "Finally, just as the final chime was sounding, he dashed through the door, looking as upset as she felt, barely getting to his seat before the last of the tone ended. Okabe gave the boy a cool, calculating look, as Goto led the class in the morning ritual."
    "She restrained herself through all of homeroom, pouncing on him the second it ended to demand, \"What happened?\""
    "\"My sister's sick,\" he grumbled. \"It bothers me to see her ill.... She's really not that bad; she certainly deserves much better than this. If that weren't enough, I was so distracted trying to help take care of her, I left my coat in her room — with my phone and ... everything in it.\""
    "She blinked, taken aback. It was dangerous for him leave his house without the tools he needed to keep up and stay safe — but she didn't snap at him for that. Instead she sighed and said, \"That cheerful little sister of yours? Well ... since we have the same opinion, why don't we let Yuki-sensei and her lovely nurse Mikuru-chan take a look at her this evening?"
    "\"And naturally, I'll help, too; I may not be a match for Mikuru normally, but I can make a soup that her stomach can handle while the others are busy! Between the three of us we'll have her on her feet in no time; you'll be back to being secretly jealous of her innocent enthusiasm right away!\""
    "He looked surprised at that, then faintly relieved. \"Thanks, Haruhi,\" he allowed, most of the gloom about him dispelled. \"I didn't even think of that.... I must be a terrible brother.\""
    "\"We'll let it slide this one time because you're distracted, but next time, you'll absolutely have to do better than that,\" she agreed, glad that she could finally improve matters for Kyon. And Nonoko would surely love to see Mikuru and Yuki anyway. \"It's your job to protect her, after all!\""
    "He smiled weakly. \"That's true,\" he replied. \"I guess ... it's probably not such a big deal to leave my things behind just once. If it's really a problem, I can ask Kanae-chan or Yuki-chan for help, right?\""
    "That was more like it! \"Right!\""
    "* * *"
    "Left in good-child mode, and unable to warn Kyon that he had forgotten her — and his tools — Ryouko sighed from her position in the pocket of his greatcoat. At the moment, she was trapped in the article of clothing, which had been haphazardly tossed over the chair in his sister's room. Not that Ryouko needed to breathe, or that the sigh was audible, but she didn't want to get out of the practice of proper emulation, as that was a good deal of her initial focus!"
    "She received an unexpected memetic packet from Kuyou, decoding it as a warning of some sort of disruption in the fabric of space-time from what the other entity had identified as some incredibly alien force — more so to her than Ryouko herself."
    "Calculating, she realized it was a warning of incoming slider activity."
    "The coordinates of anticipated arrival were near Kitago, but she had no ability to transport herself there, and in good-child mode, she couldn't address anyone who didn't address her first!"
    "If she wasn't there, she couldn't record any data! None at all!"
    "But she had to move the PDA there, somehow ... and Kyon's equipment wouldn't be cooperative outside of his hands! Or a near ... genetic match...."
    "Her attention went to the small form on the bed as she shivered. The girl's health wasn't in optimal condition, but given what Ryouko knew of her interests, and the database that Haruhi had directed her to...."
    "* * *"
    "It had been a while since she'd talked to Haruhi about her relationship with Kyon, Yanagimoto decided. She'd last prodded Kyon to try and figure out his feelings — with Taniguchi's help. That hadn't seemed to motivate Kyon towards any kind of commitment, though. Haruhi certainly {i}seemed{/i} close with Kyon, but...."
    "Well, Yanagimoto hadn't missed the way that almost every day without fail, Haruhi would slip Kyon some food. Sometimes a whole bento, sometimes just a smaller container of leftovers. That really seemed beyond 'friends' to her. Then again, that thing between Kyon and Tsuruya...."
    "He really did have to make a choice — idling as he was, he'd caught an awful lot of positive attention from the girls of the school. Enough time had passed from the initial shock of the ring that Kyon had exposed and defeated that rumors were going around about quite a few girls — first years included — thinking of trying to confess to him. That was a complication he didn't need, when he'd established relationships with other girls, and some of them seemed strong already."
    "Resolved to try and speak to Haruhi about it at lunch, which the clock told her would be in twenty minutes, she was startled along with the other students when the entire school building shook in a low rumble, the windows rattling alarmingly in their frames. She was embarrassed to cry out, but glad to see she wasn't the only one when the lights flickered twice."
    "There was a single heartbeat of further surprise before her memories of earthquake safety drills took over and she — along with every other student — dove beneath their desks head first, hanging onto the desk legs."
    "Not long after that, the shaking stopped, and she peeked cautiously out."
    "Surprisingly enough, she realized Kyon had {i}not{/i} dived beneath his desk, instead leaping to Haruhi's side and holding one arm over her protectively, while she stared at him with a look of irritation that failed to conceal her blush."
    "She was about to laugh at the scene when a thunderously loud voice rattled the windows anew, screaming, \"Kyon! Face me!\""
    "Everyone was stunned into complete silence as Kyon's expression hardened, and he shot through the door more quickly than Yanagimoto thought he could run."
    "\"H...hey!\" Tanabe called from behind the teacher's lectern, only just rising from his cower. \"We need to maintain order—\""
    "\"Student council business,\" Haruhi snapped, running after Kyon, pausing only to add, \"that wasn't an earthquake!\" before vanishing through the same doorway as Kyon."
    "In the confused silence, Taniguchi was the first to ask, \"Did ... someone just come here to publicly pick a fight with Kyon?\""
    "\"I ... think so,\" class representative Goto agreed in befuddlement, already pulling his phone from his pocket and edging towards Kyon's vacated seat to peer out the window."
    "\"And he just ran out of class? Amazing! That guy's hot-blooded for sure! He is one bad mother—\""
    "\"Shut your mouth!\" Yanagimoto snapped in irritation, before Taniguchi got himself in trouble."
    "\"Aw, I was just talking 'bout Kyon!\" Taniguchi protested, ignoring the teacher's glower and the slow snickering of the surrounding classmates."
    "Shooting him a very stern look, one that she'd taught him meant 'we need to talk after this, and not about what I'm saying', she warned him, \"Don't make it dirty!\""
    "He adopted a hang-dog expression and gave a tiny nod in response, mumbling, \"Aww....\""
    "* * *"
    "Nonoko was not feeling well at all. Her stomach hurt terribly, and she was thirsty all the time ... but had trouble keeping even water down. When she wasn't burning up, she was freezing, and even Kyon's soothing presence earlier hadn't abated all of her discomfort."
    "Her mother murmured, checking her temperature again before sighing. \"Hmm ... if your temperature goes up a single degree further, we're taking you to the hospital,\" she decided. \"I'll be back in a few minutes, and we'll see if you can handle just a tiny bit of chicken broth, alright?\""
    "\"Okay,\" the girl replied weakly."
    "Her mother rose from the side of her bed, patting her on the head once and then briskly striding away."
    "She sighed, her gaze going to the ceiling. A flash of light caught her attention, and she turned her head to stare blearily at her brother's coat, slung over her chair. Oh ... he'd forgotten it? Or was he back, already? She couldn't remember clearly anymore."
    "If he was back, why didn't he say 'hello'? She really wanted a hug, as miserable as she felt!"
    "The light winked again, brightening slightly, and she squinted. It wasn't something in his coat ... it was something ... in the air over it?"
    "A third flash came, much brighter, and she started, gasping in surprise as she saw a tiny blue-haired figure in a frilly blue dress, with six fainter, translucent blue wings, evidently sculpted from some form of crystal. Nonoko's eyes widened in amazement at the sight, and she blurted out, \"Who are you?\""
    "\"I am an augmented reality projection of a human contact purposed interface!\" the tiny creature chirped."
    "\"Does that mean that you're a fairy?\" Nonoko asked in surprise."
    "\"I'm being rendered as a sprite at the moment!\""
    "\"Wow! Are you here to make me a magical girl?\""
    "\"Yes! Just put on this coat, and take the harmonic energy device from the front pocket!\""
    "Unsteady on her feet and shivering at the cold, she climbed out of bed, pausing to cough. \"Okay! What's the magical pass-phrase?\""
    "\"I'll tell you more after you say, 'Disable good-child mode!'\""
    "* * *"
    "Haruhi pressed herself at full speed to catch up to Kyon, barely keeping in sight, and only reaching him when he skidded to a halt at the top of the interior stairwell. He had enough time to twist around and catch her when she tackled him — that'd teach him to try and run off into a fight without her again!"
    "To her surprise, he grabbed onto her and then vaulted the pair of them over the edge of the railing."
    "She spent a moment to wonder what he was thinking in stunned amazement before she realized they were already alighting on the bottom floor. He set her down and they both burst into motion together, running past their shoe-lockers to the school's main entrance."
    "Standing in the center of the walkway were a pair of figures, one of which Haruhi hadn't seen before — but guessed to be Wataru. He had black hair down to his shoulder blades and an angry glower on his face; his outfit was a blue pair of slacks and shirt with militaristic lines. One of his hands held a weapon of some sort — looking like a sleek, futuristic pistol."
    "The other figure was Kuyou, still in the same outfit she always wore, her back to Kyon and Haruhi at the moment."
    "The pair of Kitago students drew up cautiously behind Kuyou, Kyon on the left, and Haruhi on the right. Kuyou watched the boy intently, while Wataru glared at her — shifting to shoot an even darker look at Kyon as he drew near."
    "\"What is it this time?\" Kyon asked dourly. \"You called me out.\""
    "Haruhi shifted her shoulders and watched the boy closely, occasionally allowing her gaze to flick to the impassive Kuyou. Sneering, Wataru jerked his head in a single nod. \"Today is your last day,\" he warned. \"Once the resonance cascade begins, your civilization will fall — like the others. The greatest resistance we have ever seen with an active portal storm was seven hours, and I strongly doubt you'll do better.\""
    "\"Just you try it!\" Haruhi snapped impatiently. \"Our world won't give up so easily— Kuyou-chan! Use your spellcard - Spooky Action 'Wide Area Transmigration'!\""
    "Obediently, the dark-haired girl abruptly raised one hand. The sound of the world about them shifted, giving Haruhi the briefest impression of a storm of strangely twisted shadows and haunting voices — almost like a chorus — before everything settled to being more-or-less the same. It felt emptier, even though the same people were standing in the same places."
    "But then, there were no sounds of traffic or distant yelling. \"So, this is Kuyou's closed space?\" she wondered."
    "\"Haruhi,\" Kyon warned, his attention on the enemy — reminding her that they didn't have time to play around."
    "The black-haired boy looked indifferent, the weapon in his hand unwavering. \"Shadow-song,\" Kuyou said, blinking once."
    "\"Alright — you think this is going to be the end,\" Kyon said in annoyance, nodding at Wataru. \"Before we get into a pointless fight for anything, can we talk this out?\""
    "\"Yeah,\" Wataru snapped, shaking his head and — surprisingly — lowering his weapon."
    "Haruhi wanted to complain that Kyon wasn't being {i}any{/i} fun at all ... but it wasn't like she could pick the fight she expected would relieve her of the stress of recent events — especially with the entire world potentially on the line. Come to think of it, where were Yuki and the others? Well, she could worry about that if Kyon couldn't talk him down. For the moment, she'd focus on the enemy."
    "As angry as the boy looked, he gave a single terse nod. \"I'm glad you're at least somewhat reasonable this time, 'Kyon',\" he snarled."
    "\"Hey!\" she protested, scowling. Why wasn't she worth his notice?"
    "Still ignoring her, Wataru continued, \"If you wish to survive and perhaps spare some things of value to you ... well you in {i}particular{/i} may become part of the Overwatch. Just hand over my sister's body, that doll,\" he paused to point at Kuyou, who merely blinked in response, \"and the rest of this planet.\""
    "Haruhi's eyebrows rose. Was he {i}serious{/i}?"
    "\"Oh, is that all?\" Kyon asked dryly, neatly echoing her sentiment, though with much more sarcastically unimpressed reserve than she could muster."
    "\"Yeah, well, we both know you're too proud to make the deal,\" Wataru derided. \"But now I can say I've offered.\""
    "\"Well, you've figured right that I'm not handing Kanae-chan over,\" Kyon agreed. \"She's one of us — just like Suou-san. So, if you're going to demand to take people from us ... well, even from another world, you already know our answer.\""
    "\"Then it's on you,\" Wataru declared, shaking his head as space ripped open behind him."
    "Haruhi winced; the edges of that dark gap made her eyes hurt, and it crackled with a strangely alien energy, showing nothing of whatever lay behind the jagged, irregular edges of the rift."
    "Instead of backing up, he held his position as another figure emerged from the portal behind him. Dressed identically, her hair the exact same way, not a single strand out of place.... Another copy of Suou Kuyou stepped from the nothing behind Wataru, walking to stand at his side, her gaze locked on her alternate."
    "\"Well?\" Haruhi asked, annoyed. Was there going to be a fight? Should she try and help Kuyou get rid of her copy?"
    "Either way ... she pulled a spare ribbon from her pocket without hesitation, a thought sending it to wend through the hair of the Kuyou at her side. No sense letting the two of them get mixed up, after all. Kuyou seemed unperturbed by the addition of a golden ribbon on her head, done up precisely as Haruhi's was."
    "\"Begin,\" Wataru ordered tersely, his eyes fixed on Kyon."
    "The other Kuyou shifted her stance very slightly, her voice sounding strangely discordant. Her dark eyes fixing on her counterpart, she intoned, \"Beginning synchronization.\""
    "Kyon and Haruhi both stiffened, turning to look at their Kuyou worriedly — but only for a moment before their attention was brought to another of the painful-to-look-at rifts in space. This one was much larger, forming in the air directly overhead. Haruhi stumbled backwards in alarm, unable to grasp the scale of the thing."
    "The boy at her side looked like he was saying something urgently, but she couldn't hear it over the sudden, shaking rumble of some huge airborne craft emerging from the portal. It streaked overhead, slamming into part of the school building before she could more than glimpse it, unleashing a billowing cloud of dust and smoke — though the portal remained open."
    "Kyon reached for Haruhi's wrist, and Kuyou's as well. The dark-haired girl let herself be snared, her eyes fixed on her counterpart."
    "Pulling her hand free from Kyon's grip, Haruhi immediately filled it with a glowing orb of power, dazzling in its intensity. Tiny beads of light streamed in from all directions, until the single pulsating sphere of energy was abruptly attended by three smaller bluish orbs, which rotated around on separate axis."
    "Wataru's dark, clouded eyes jerked away from Kyon and to the pulsating energy in Haruhi's hand before he raised his sidearm warily."
    "\"Not this time,\" she declared. The orb floated before her as her hand fell away, hovering in place. \"Kyon, take care of Kuyou-chan — this time, {i}I{/i} get to fight!\""
    "\"Haruhi!\" he protested, too late, as Wataru fired — a beam of light shooting from the tip of his weapon towards Haruhi — to suddenly be intercepted by the glowing energy that Haruhi had summoned. The blinding crimson beam vanished into the tiny orb of light, which grew larger and flickered violently, its smaller spinning attendants whirling wildly before settling back down, as the flickering slowly faded. The spinning energy zipped back before her, resuming its defensive position, and Kyon took a step backwards, Kuyou drifting along with him."
    "Summoning another pair of attendant orbs, Haruhi set her feet, watching Wataru expectantly — prepared to intercept an attack towards either of her friends, should he try it."
    "Kyon looked unhappy about the situation, but allowed a grudging nod, taking a firmer grasp of Kuyou's wrist and dashing back inside the school building."
    "* * *"
    "The Chorus itself was straining under the strange strings that projected from the Other. Kuyou did not know what to call the Other, except to think that it was {i}like{/i} her."
    "Only that core of 'memory' allowed her to deny the layers of false observation that she found herself assaulted with. Even then, the effort cost so much spin that she was struggling to keep herself oriented, her awareness compressed, nearly removed from the Chorus entirely. She was no longer merely projecting her awareness into her interface; she was limited to it — {i}trapped{/i} there."
    "Unprepared for such a situation, she offered no resistance when Kyon grabbed her wrist and pulled her away into the school building. Physical distance and intervening materials, unfortunately, did not seem to help. The assault on her observations continued, forcing her to rely on Kyon's guidance to climb up the shaking stairs."
    "The section of small cubical containers filled with shoes was disrupted by a release of intense heat and light. The boy pulled her form to the floor at the top of the first flight of stairs, covering her protectively as sharp pieces of metal and burning footwear shot overhead."
    "The second the explosion died down, he scrambled to his feet, effortlessly sweeping her unresisting form into his arms. Meanwhile, trusting him to care for her body, she sent her focus against the false observations, the imposition against the Chorus that the Other was trying to force onto her."
    "She had precious little spin, finding herself in a situation where only Kyon's occultation could protect her."
    "Just as she had predicted."
    "Even so, it was against her nature merely to wait, so she pitted every spare bit of spin into creating her own false observations, projecting them against the Other. Even though she had never done such a thing before, 'memory' made separating genuine observations from false simple; she could rely on 'memory' and know that anything else wasn't reliable. The interference was consuming to maintain, but shifted the brunt of the assault on the Chorus directly into those false observations, relieving the pressure and freeing a small bit of spin."
    "She returned her awareness to her surroundings again. Kyon had carried her across the building a short distance, muttering a series of well-rehearsed memetics to indicate frustration. They were pursued by a pair of somewhat spherical beings with a trio of thick mechanical limbs, clomping after them as the nearest one began emitting a piercing high-pitched yelp."
    "Kyon dashed abruptly to one side, kicking open a door as a burst of glowing projectiles spat out of the chasing forms. The brightly lit flechettes quivered in the doorway and wall behind the fleeing pair briefly before abruptly exploding, unleashing a smaller burst of energy."
    "\"Great!\" Kyon yelled, which Kuyou somehow suspected he said without sincerity. She would need to ask Ryouko about that later."
    "He set her in a corner and whirled, grabbing the nearest of the desks in one hand— She watched the way he manipulated the effects of gravity on it, appreciating that resonation. First he made it almost weightless, and then he threw it at the doorway with all the force he could muster."
    "She could spare a single rotation of spin for that, adding additional pull in the direction he was throwing it. The first of the pursuing forms charged through the doorway and was smashed into a glittering spray of bright fluid and sparking metal parts; the second rapidly backpedaled, chirping loudly."
    "\"Alright,\" Kyon sighed, backing to Kuyou's side, hefting another desk as he watched the entrances warily. \"I think we can hole up in this classroom for a bit.\""
    "The pressure against Kuyou to conform to the Other's false observations abruptly increased, simultaneous to the arrival of another quartet of the things that had been chasing them — through the flimsy crystalline barriers between the classroom and the hallway."
    "* * *"
    "Once Kyon had vanished from sight, hauling Kuyou along, Haruhi used her telekinesis on the dust before it could expand out — throwing it straight to the ground to prevent it from obscuring the entire battlefield. Once that was dealt with, she turned her attention to the boy before her, who held his weapon leveled at her expectantly, as though waiting for her to do something else."
    "And maybe he was, she realized."
    "She was attended by a trio of glowing orbs, after all. She set two of them to orbit her defensively, raising the third high overhead in one hand. \"So,\" she challenged, suddenly not feeling as confident as she wanted to pretend, \"you've never fought me before, have you?\""
    "Wataru grunted at her, his expression sour. \"You always talk too much,\" he said flatly. Before Haruhi could find a retort, he continued, \"If you've come this far, I don't expect to have to. Not that it matters ... you're not invulnerable, and this doll,\" he paused to indicate Kuyou, \"has taken you out before.\""
    "Haruhi tried to stand her ground, but one foot slid backwards reflexively as she set herself, and the other Kuyou suddenly turned her dark eyes towards her. \"Insufficient synchronization progress,\" she announced in a clipped voice, still strangely discordant, blinking slowly."
    "A smirk coming to her lips, but not quite willing to open fire on Wataru, Haruhi asked, \"Are you just going to stand around all day?\""
    "\"Hmph,\" he sneered, lowering his firearm. \"You're really still not my problem. They'll take care of you,\" he finished, waving vaguely behind her."
    "She dropped her hand and spun, releasing the suspended sphere to join her defensive pair. The crushed wing of the school stood strangely still, only faint wisps of dust floating about. There was, admittedly, a void where several classrooms would have been, from the top floor and extending down a story and a half."
    "Belatedly, she realized that in the disarray of broken walls and scattered desks and assorted other rubble was a distinctly alien mass — the craft from before. As she looked more closely, something like a hatch opened, disgorging a quartet of spherical entities that ran on a trio of legs, releasing shrill yelps."
    "She'd need to deal with them at some point, she realized with a scowl. Already in motion away from the boy, she summoned another pair of projectiles, sending one from the array that orbited her to the ground between Wataru and the other Kuyou. A backwards glance revealed Wataru flinching back from the explosive spray the impact left behind, but most of the blast was deflected by a green barrier of some kind of energy, which disappeared even as she watched."
    "Kuyou didn't seem fazed or affected in the slightest."
    "Then her attention was on the distance between her and the strange figures, whatever they were, as she dashed forward, releasing and summoning a small cloud of attendant spheres."
    "Two of the weird ... things hesitantly hopped their way down through the broken-open wing of the school, descending a single floor at a time. She wondered what their offensive capabilities might be, checking the two that seemed stationary. One of them seemed to be peering intently at her, while another furtively rooted around, as though searching for something."
    "Even though she expected it, and tried to dodge, the 'watching' figure spat a sudden spray of projectiles at her — brilliantly glowing things that left dazzling trails of light in their wake. It seemed to anticipate her sudden change of direction, heading to dive behind a planter with one of the school's hedges, hoping for slight cover."
    "Her defensive orbs intercepted the things, catching and holding them in place before her. Sprawling behind the hedge, wincing as she skinned her knee lightly on the cement, she let herself loose a shaky laugh as she heard more of the things shooting out, blocked by the short cement planter. Her relief was short-lived, however, as the brightly glowing things in the orbs exploded."
    "The blasts rattled her, and she reflexively covered her face with her hands, dazed and more than a bit shaken. Okay, she thought belatedly, just before the rounds in the other side of her defensive barrier exploded."
    "Distantly, she thought she heard Wataru laughing over the ringing in her ears as she scrambled away from her treacherous cover, her defensive energy catching more of the— No! She couldn't keep those things around!"
    "Seizing them from the spheres with her telekinesis, she threw them back at the nearest of the approaching attackers with desperation, she was momentarily staggered when they struck — and the construct exploded into a small pile of debris with an oddly hollow shell. Her ears were still ringing from the first explosion, and after that seemed to detect some annoying whine that kept rising in pitch."
    "She was snapped out of her surprise by the arrival of more incoming rounds, intercepted by the orbs she'd freed up by— Hey! This was going to be ridiculously easy! She didn't have anything to worry about, now that she had it down!"
    "Recovering her confidence, she threw the incoming rounds back at the next attacker, not too worried to see what looked like more emerging from the downed craft. She had this down. She had the small things — she supposed she'd call them 'hunters', because that seemed to describe their behavior — under control. If only that piercing noise wasn't still getting louder!"
    "Though ... when she stopped to think about it, were there other portals?"
    "She glanced to one side, realizing with surprise that the sound she'd been hearing wasn't coming from her ears — but from another strange construct. This one actually seemed oddly reminiscent of the one at the beach, though it was taller, and had only three legs. It seemed to be directing some sort of weapon at—"
    "She had a moment of dismay to realize that her defensive orbs weren't quite enough to stop it before the blast struck."
    "* * *"
    "While he wished for a lot of things, Kyon realized he would settle for just one of his weapons ... or even the coat. Not that he wanted to dismiss the skinsuit, but it just didn't feel adequate. With a quartet of incoming enemies and no reliable cover, he opted to frantically kick through a window, using his body to shield Kuyou as they dove out."
    "On the opposite side of the school from Haruhi and Wataru, he realized with dismay. He brought himself and Kuyou down gently, looking around the courtyard between the school building and the clubroom."
    "He started, shifting backwards after his landing at the sight of Wataru standing there, somehow, the other Kuyou at his side, staring fixedly at the one at this side. He almost started to ask, \"How?\" before realizing it was pointless."
    "Slider technology, Kyon had spent longer dodging robots than he'd thought ... it didn't matter. Wataru had a way to get there, and now Kyon had to deal with him. And possibly the other Kuyou."
    "\"What {i}this{/i} time?\" he asked in annoyance."
    "\"I just plan on watching, this time,\" Wataru answered with a shrug."
    "Kyon narrowed his eyes, then leaped away, as a trail of glowing flechettes spat out from a classroom window, drawing a line that almost reached him before he landed. He kept moving, loping across the quad and quickly hopping over a planter to use as cover, setting Kuyou down before peeking out to survey the area."
    "Without Ryouko's perception to mark things in augmented reality, this could be really dangerous."
    "Had he become that reliant on her already?"
    "He grimaced, ducking back before seeing any of the robots. They might see him, even if he couldn't spot them. Kuyou remained where he set her, leaning against the planter like a doll, except for the dark eyes following him. Well ... now what was he supposed to do?"
    "The planter itself shook faintly as he heard the whistling impacts of more flechettes. Realizing what it meant, he scooped Kuyou back into his arms and quickly dashed for the next planter before his cover exploded. He dashed madly, sliding to a halt on his knees, narrowly avoiding yet another storm of explosive darts before finding new cover. As he came to a halt, glancing at his torn and stained pants, the first of the darts began to explode, reminding him of just how little time he had."
    "Okay, he decided, open areas were not the best terrain given his current options."
    "As the trail of explosions worked its way over to the planter he was hiding behind, he stared fixedly at the roof of the nearby wing of the school. There would be a full quad and another part of the school building between him and Haruhi — but he could work his way back down the interior hallway. That thought in mind, he threw himself up towards the rooftop, hoping that Kuyou could — as she had before — give him the extra mileage he needed to reach that height."
    "She did, throwing his balance off and leaving him landing unsteadily, jogging forward as another spray of flechettes traced up the wall below him. He shakily staggered forward to the center of the rooftop, turning around. He needed to get his bearings, he thought, gently setting Kuyou down before he straightened, looking up at a sudden shadow — and freezing still."
    "Overhead, looming like a giant red-rimmed eye, a massive portal whirled. Its outer edges were surrounded by bits of cloud, lit an eerie crimson, lending it the ominous appearance of a rotating galaxy, while dozens — hundreds, even — of shining stars tumbled free, twinkling dully as they descended. At different points in their erratic, winding falls, they suddenly shone brighter, shooting away and leaving glowing white trails behind them as they zoomed rapidly away."
    "Dozens had already passed above, stretching glowing streams behind them towards the horizon — what ... ships? Crafts of some sort, maybe like the first one that had slammed into the building?"
    "But more impressively, casting a shadow that blotted out much of the sky, some enormous metallic structure descended, the base narrow and pointed, tipped like a drill."
    "\"W...what,\" he managed, just staring at the thing in amazement."
    "While he was distracted, an unexpected force slammed into his back, sending him tumbling heavily across the rooftop. He clawed his way to a flat position, relying on his skinsuit to protect him from abrasion and almost climbing to his feet before he even slid to a halt— But not fast enough to keep the next robot from repeating the tactic, crashing into him and knocking him tumbling again."
    "His joints protested as he tried to right himself — this time stopped by a third robot crushing a single heavy foot into his spine, causing the rooftop beneath him to snap, cracks shooting out from under him in a spiderweb as he tried to catch his breath. They must work in squads, some calm part of his mind notified him. The three had perfectly exploited his distraction, and he was unarmed as it was anyway...."
    "While he was pinned, one of the robots marched near Kuyou inspecting her curiously, as the other moved to Kyon's side, unlimbering another pair of limbs — these tipped with wicked blades. Ignoring the robot nearest her, and staring at him with a combined look of confusion and ... hope?"
    "The dark-haired girl extended a hand towards him almost expectantly, even a dozen meters away."
    "* * *"
    "By the time Tsuruya reached the front of the school, hopping out of her indoor shoes and landing on tiptoes to jog to the door, several other brave students had bolted from their classrooms to try and investigate. No teachers yet, at a glance, though she did see Koizumi looking around anxiously, along with the other students."
    "Nodding decisively, and pulling a page from Haruhi's book, she whistled shrilly, bringing all eyes to her, as a few slower students jogged into the shoe lockers behind her. \"Back to classes,\" she ordered primly. \"Koizumi-kun! Student council business.\""
    "\"Ah, right,\" the esper said belatedly, as the other students fled, even though she hadn't offered a direct threat."
    "Koizumi shook his head, quickly regathering his wits and glancing around. Drawing close enough to speak in a murmur, he offered, \"Suzumiya-san and Kyon- kun don't seem to be in a closed space that I can reach; for the moment my powers are limited to this realm.\""
    "\"That's fine,\" she replied, leading the way towards the student council office. \"Can you calls the president? We can work on the cover stories while they're handling things.\""
    "\"He should already be in place for situations like this,\" Koizumi answered. \"Ah, we're accounted for, I believe Kyon-kun and Suzumiya-san are together ... wherever they are. Do you know—\""
    "\"I sent Mikuru-chan to take Kanae-chan to the clubroom,\" she replied, before he could finish, nodding. \"What about Yuki-chan?\""
    "The esper winced, admitting, \"I did not think to check on her.\""
    "Tsuruya nodded and gestured for him to lead the way, pulling her phone from her pocket and pulling the other girl's number up. The phone rang a single time before clicking. \"Yuki-chan?\" Tsuruya asked, rounding the corner to the council room door. \"Hiyas! Are you okay?\""
    "\"I am fine,\" Yuki answered. \"Asahina Mikuru and Michikyuu Kanae are with me. I have sealed the clubroom.\""
    "\"Eh?\" she wondered. Koizumi opened the door and peeked in cautiously. \"Why?\""
    "\"I have engaged Kimidori Emiri in a trap,\" Yuki explained softly. \"It will prevent her from gathering data on current events, but also requires my presence in this room.\""
    "\"Can she hear this call?\" Tsuruya asked, pushing the door open completely and gesturing Koizumi in."
    "\"Yes.\""
    "Tsuruya nodded slowly, following the esper in. That was good to know. At a glance, the room was empty, except for the pair of them and the student council president, sitting behind his desk and looking at them curiously."
    "\"My secretary isn't here at the moment,\" he warned the pair."
    "\"Oh, she's going to be tied up for quite a while,\" Tsuruya answered, hanging up the phone. \"But that's fine; that gives us time to talk without her interfering!\""
    "Behind her, Koizumi closed the door."
    "The student council president raised an eyebrow. \"Well, you're the benefactors, so what's the official story?\" he prompted. \"Keeping in mind that, officially, nothing has been handed down to the student council yet ... so none of this is our business.\""
    "\"Well, how do we get it handed down to us?\" Tsuruya prompted."
    "\"I believe I can make some calls to see about that, but if Kimidori-san interferes....\""
    "\"Yuki-chan's keeping her busy.\""
    "\"Ah.\" Koizumi pulled his phone from his pocket, saying, \"I'll see to it, then.\""
    "\"Excellent,\" Tsuruya decided. Hopefully things were coming together just as nicely for Haruhi and Kyon."
    "* * *"
    "The defensive energy Haruhi had summoned was not quite able to stop the bright lance of destructive energy that blasted out of the taller robot. The little lights burned away, orbs scattering into white dots that flickered out one- after-another as she tried to brace herself, being shoved backwards by the backlash. Wait—"
    "Those other robots were still there, and she was about to—"
    "Her defenses were overcome, and she was sent tumbling back. She put her hands up before her and managed to keep herself from being knocked out, but her nose burned at the sudden impact against the wall of the school, and she was too disoriented to properly defend herself. Those orbs.... They were automatic, but they'd all burned out trying to stop the...."
    "What the hell was that? Hadn't Kyon been hit by that once?"
    "She moved a hand before her, fumbling for her surroundings and blinking to try and clear her eyes of the bright blur that was left behind. Was that ... on her hand.... Was that ... blood?"
    "Even though she knew it wasn't the time for that, one hand rose to her face in surprise, coming away red. Her nose was bleeding? Her vision slowly cleared and she looked down at herself in dismay; her legs were scraped, and her school outfit was singed, and she was sprawled half in a hedge against the wall of the school building."
    "She heard a fierce yipping noise nearby, and distantly, a familiar whining hum, like the one she had heard before— She tried to stagger to her feet, but slipped down to a sitting position, wincing at the pain that shot through her. Casting around, she spotted the taller robot, already preparing to fire at her again."
    "As if the hunters hadn't already pinned her down — what could she do? This wasn't fun! This wasn't fun at all!"
    "Where was Kyon when she needed him?"
    "But just as she thought that, in a blur of motion and bright pink, Haruhi heard a familiar voice cheerfully cry, \"Radiant Buster!\""
    "She stared, shocked into complete confusion when a trio of red beams shot out from some point behind her, braiding together into a single, brighter beam that shifted color just as it connected with the glowing point where the taller robot's weapon charged. There was a brief crackle, and then the robot exploded, sending pieces flying in all directions."
    "One of them shot towards her — and she caught it with her telekinesis, summoning a full quartet of defensive attendants before she even tried to climb to her feet again. They hovered around her as she shakily made her way upright, reaffirming her resolve as she did, absently tossing the shrapnel aside to find out who had saved her."
    "Her eyes widened in confusion anew as she saw the form of Kyon's younger sister, standing proudly upright — thought wobbling slightly — with a goofy grin on her face. Ryouko hovered at her shoulder in a slightly more two dimensional form than usual, with six crystalline wings."
    "What mostly got Haruhi's attention was the fact that Nonoko was wearing what looked like a magical girl outfit. It was a blue and white dress — more white than blue, with a feathered hem, and a wide skirt for mobility. She appeared to holding a— It clicked into place suddenly; she had to be wearing Kyon's coat!"
    "Did that mean the gem-tipped magic wand she was carrying in her right hand was one of Kyon's weapons?"
    "Haruhi didn't even realize she'd done it when she flew across the distance separating her from the little girl, snatching the slight form in her arms and then leaping away, her defensive orbs catching darts that easily could have tagged the pair of them."
    "\"Nonoko!\" Haruhi yelped, already tearing away as a larger group of the hunter robots swarmed out from— Where the hell were they all coming from, anyway?"
    "\"Haru-nee!\" Nonoko cried out happily, her voice rough, before she coughed. \"You can {i}fly{/i}!?\""
    "\"Yeah!\" Haruhi answered in annoyance, realizing that she had — {i}had{/i} to, in order to get to Nonoko fast enough. This was no place for Nonoko to be playing around! Gritting her teeth, holding Nonoko tight to her with one arm, Haruhi summoned more spheres of light to surround the pair of them as she suddenly shot upward, tracing along the side of the school building and looking straight upwards as—"
    "She nearly turned around and threw herself and Nonoko flat to the earth at the scale of the vortex overhead — and after a second of thought, did change course, picking up speed as the pair of them shot away from the school building, parallel to the ground."
    "And providing a clear shot for the now {i}dozens{/i} of robots below them."
    "\"Damn!\" she swore, throwing darts back with telekinesis whenever possible, but mostly just dropping them."
    "\"Ah!\" Nonoko started, before sneezing. The little girl then sniffled, worming one hand free of Haruhi's grip, as Haruhi was already keeping her in place with telekinesis anyway. \"It's okay!\" she cheered, her voice sounding congested. \"Magical Radiant Nonoko is here to help!\""
    "\"This isn't a game!\" Haruhi protested, wishing she hadn't thought this was something to look forward to only a moment ago. Hell, her nose had only just stopped bleeding— Damn! Had she gotten her blood on Kyon's little sister!? He'd never forgive her if the little girl got hurt!"
    "With that thought in mind: \"Ryouko! What do you have to say for yourself?!\""
    "\"She shut me up and won't listen when I tell her this is dangerous!\" Ryouko exploded immediately in response, her hands flailing wildly. \"She's going to hurt herself!\""
    "Haruhi's heart nearly stopped at that. \"{i}What{/i}!?\" she screamed, actually dropping out of flight for a few meters — incidentally dodging another hail of flechettes — before catching herself and Nonoko."
    "\"Whee!\" the girl cried, pointing her wand at the nearest of the hunters. \"Radiant Buster!\""
    "\"I told her it's for emergencies only!\" Ryouko wailed. \"I just wanted her to go to Kyon to warn him about the sliders!\""
    "\"You're a bit {i}late{/i}!\""
    "Reaching the end of the school building, finding herself hovering over the track, Haruhi aimed towards a PE storage shed. Not the best holdout in the world, but she needed to buy a few minutes to think! \"Awww!\" Nonoko protested with a shiver, as the hunters fell out of her range. \"Hey! Ha...Haru-nee! I rescued you, right?\""
    "\"Yeah,\" Haruhi growled, slowing down and setting the pair of them down near the shed door. She frowned at what remained of her defensive cloud, eight whirling lights. One of them was spent to blast the lock off, and she quickly stepped inside, lowering Nonoko to the ground and then gasping for breath, letting the lights surround the pair protectively."
    "Nonoko looked inordinately pleased with herself, and Haruhi turned her attention to Ryouko, guessing her anger was easily readable to the tiny schoolgirl. \"Well?\" she fumed. \"No cute Cirno cosplay is getting you out of this, Ryouko!\""
    "\"I can only answer questions when spoken to!\" Ryouko cried, tiny virtual tears streaming from her eyes."
    "One eyebrow twitching, Haruhi ordered, \"Disable good child mode,\" which prompted Nonoko to pout."
    "\"But, Haru-nee, she wants me to let Kyon do everything! How are we supposed to show him he needs to rely on us and we can be trusted?\" the little girl whined, still wobbling, sweat standing out on her forehead."
    "Haruhi felt an eyebrow twitch; if Nonoko had somehow arrived before she'd gotten hit by that beam.... Well, then she might have agreed; having survived one blast, she didn't look forward to another. And letting {i}Kyon's little sister{/i} get involved in a fight like this?"
    "\"Nonoko,\" she said, forcing her voice to be gentle, and giving the girl the best smile she could manage — probably hideous with the blood on her face. \"Why not rest a minute, okay?\""
    "Yawning, then shivering fiercely, Nonoko agreed, curling into a ball on one of the exercise mats that was laying about, almost instantly dropping to sleep. In better circumstances, Haruhi might have thought it was cute, but she couldn't just leave Kyon's little sister there...."
    "She'd seen him angry before ... but she didn't know that she wanted to see his reaction to this. She shook her head, turning to one side; there was a first aid kit in the shed, though it wasn't great. She could tend her scrapes and clean the blood from her face. \"Explain how this happened, Ryouko,\" she ordered."
    "* * *"
    "After Nonoko had released her permissions to speak, Ryouko had happily explained, \"I'm assigned to Kyon! I'm a personal assistant; you're holding one of the tools I help him use!\""
    "\"And it's going to turn me into a magical girl?\" Nonoko asked between coughs, her eyes fixed on Ryouko's."
    "\"For values of 'turning you into a magical girl' equal to 'you having a costume that protects you and operates on principles most people won't understand, and wielding equipment that few on Earth have ever seen, let alone held,' yes, this will turn you into a magical girl!\" Ryouko agreed."
    "\"Finally!\" the little girl cheered. Giddy with excitement, Nonoko grabbed the coat from the back of the chair before stumbling back to sit heavily on the floor, looking at the garment in surprise as Ryouko drifted slightly closer."
    "\"It weighs less once you wear it!\" she assured the small girl."
    "Nodding, Nonoko climbed to her feet, as her mother called up from downstairs, \"Nono-chan? Are you alright?\""
    "\"I'm fine, Mom!\" Nonoko yelled back, her voice raspy before she set off another round of coughing."
    "\"I'm coming up,\" the woman replied, unconvinced. \"It's time to check your temperature again anyway!\""
    "Ryouko didn't see her helping the plan much, so she pre-emptively toggled the coat to stealth as Nonoko managed to get her arms through it, rolling the sleeves up. She vanished from normal human perceptions behind a shield of warped light, though to Nonoko's eyes, she would be wearing the magical girl outfit. The weapon in her hand had likewise shifted to match her expectations, forming into a long staff capped with a red jewel nestled in a golden crescent."
    "\"Oooh!\" Nonoko enthused, eyes widening. \"Now what?\""
    "\"Now you're invisible!\" Ryouko encouraged her. \"Sneak downstairs, and we'll find Kyon!\""
    "Giggling, the girl did as she was told, holding her breath and sneaking past the woman who came in the room and began looking around with increasing alarm. \"Nono-chan? Where did you go?\" she called, walking right past her daughter and peering into the closet worriedly. \"Nono-chan!\""
    "Still on unsteady legs, but stifling her laughter, the girl tottered down the hall, reaching the staircase and grabbing the rail to slowly work her way down. Ryouko hovered behind her shoulder, calculating. At this rate, she would take far too long to reach Kyon!"
    "She wouldn't be able to move as quickly as Kyon, and while invisible, there would be issues with public transportation — aside from the fact that it was slow."
    "There had to be {i}something{/i} she could use...."
    "Another data entity, though one in a mostly dormant state, entered her perceptions."
    "She studied it in fascination as she hovered over Nonoko's shoulder. In return, the other data entity's host turned to regard her warily, then blinked once."
    "Well, maybe she could get that data entity to help her out. It was subordinate to Kyon in some way, too, right?"
    "The host was a bit small, but she could devise a program to apply to one of the slider weapons that Nonoko hadn't used yet that would take care of {i}that{/i}."
    "* * *"
    "The reverberations between the Chorus and the Other grew more intense, even through the sheltering protection of the shadow-song that she had constructed."
    "Helpless beneath the assault of the overwhelming Noise, confined to her physical form, Kuyou watched helplessly as Kyon — the one she needed for occultation — was pinned beneath an aggressive synthetic construct. There were many in the area, small primitive entities, connected to a larger entity anchored somewhere in the immense construct of steel that was inevitably plummeting from the portal overhead."
    "The construct unlimbered a sharp cutting edge of some sort as she reached helplessly towards him, unable to spare the energy to move closer — limited to observations only. The edge drew back, and then over the span of only a few hundred rotations, snapped forward, driving towards Kyon's chest."
    "Faster than it descended, however, a massive blur of orange, black, and white surged into view, swatting the thing away errantly."
    "An unfamiliar life form, similar to ones she had observed, but stretched in scale stood protectively over Kyon. It looked at her as Kyon stared up in amazed fascination."
    "\"Did ... I really just get rescued by a giant Shamisen?\" Kyon asked, staring up at the creature."
    "It ignored him, leaping away towards another of the aggressive synthetics as Kyon hurriedly scrambled to his feet and dashed to her side. He scooped her back into his arms as the Shamisen-entity returned — suddenly shrinking in scale to the one Kuyou expected."
    "A friendly resonation, strengthening her connection to her memories. That was it."
    "She recognized the entity that had possessed the creature, and then the creature itself as separate beings. A resonant note of the Chorus? Some memetic construct that a past instance of herself had nudged into this place so she would have an ally in the shadow-song?"
    "That was it, she realized, gaining strength and leading the Chorus to counter the Noise. The memetic construct had been pushed into the past, using the influence of the one known as Kyon. Now it guided her, resonating with the memories she had formed — and would make."
    "Words that Kyon would teach her; meanings that he would present for her observation came to her."
    "Those observations were processed and saved into her precious memory. Then she said: \"It is pre-determined that I do not synchronize with the Other.\""
    "Kyon responded instantly, running as quickly as he could away from the center of the mass of concrete, wood-pulp, and conductive cables they stood atop. She kept careful hold of the body that housed the other reinforcing note of the Chorus, cradling it just as protectively as Kyon held her; in response, the small furred form began to rumble in synchronization with the Chorus itself."
    "The surface beneath them buckled, just as Kyon reached the edge and leaped free. Behind them, the concrete shattered beneath the stresses it was being subjected to. Most of the central mass of the building was simply smashed out of the way in a gargantuan, billowing cloud of dust; much of the remaining structure began to collapse because of the reverberations through the ground and underlying support."
    "The pair of them flew free of both the debris from the impact, and the expanding cloud of dust, dropping to a large flat area, filled with short grasses over a carpet of dirt."
    "Kuyou's strengthening progress against the Other faltered when the three of them briefly came to rest, surrounded on all sides by a crowd of at least thirty of the tripedal synthetics."
    "\"Ugh,\" Kyon groaned, freezing, eying the things warily. \"{i}More{/i} robots....\""
    "As if prompted by his complaint, the nearest emitted a high-pitched yelp, preparing to fire the highly energized projectiles it used for its primary assault."
    "* * *"
    "After applying a resonation field that amplified the physical weight and other properties of the other data-entity — cloaked in a field of the same 'stealth' as Nonoko herself was — the girl laboriously climbed onto the back of the now-enlarged host creature."
    "Ryouko belatedly identified it as a house cat, though according to the database she was pulling most of her resources from, the creature would more accurately be classified within the 'mega' order of the 'neko' subcategory. Strange that for a site in mostly English they used Japanese terms, but perhaps that was the human method of slowly increasing memetic transfer rates?"
    "Whatever the reason, Nonoko finished climbing into place on the creature's shoulders, then leaned forward and grabbed tightly onto the collar that had grown with it. It sniffed once, sending her a memetic query and confirming that it would work with her. The data entity within the being evidently had some interest in Kyon through the host — Ryouko noted a connection between highly desirable (to the host) pellets of dried proteins that the boy frequently provided it."
    "The data entity portion of the composite being gave her an unclear memetic transmission, suggesting it was one of those more primitive data entities that existed naturally within the universe. Except ... this one seemed slightly unusual, and if she hadn't spent time learning how to communicate with Kuyou, she would not have been properly equipped to realize that the transmission had a secondary memetic channel attached, communicating on the same wavelength as Kuyou herself!"
    "\"Nonoko!\" the girl's mother yelled, her voice worried as she dashed to the front door, looking around worriedly and staring right through her daughter. \"Nonoko! Where are you?! This isn't time for games! Nono-chan!\""
    "Giggling quietly, Nonoko leaned forward, sitting across the massive cat's shoulders, and then kicked with her heels."
    "\"Nono-chan!\" the woman behind them cried anxiously. Ryouko registered the panic and concern there, caught by functions she had been given to understand social interactions more clearly. After all, she spent a great deal of her time understanding their significance!"
    "Except ... with her connection to Kuyou open, there was a strange echo of that data. More than just the data of the values that Ryouko recorded, there was some other, strange sensation that went through the data of her being."
    "She was confident she wasn't {i}contaminated{/i}, precisely, but what was she experiencing? A reverberation of some memetic carrier sent by Nonoko's mother? Strengthened by Kuyou?"
    "Ryouko couldn't understand what she was feeling, except to determine that it was something to be avoided."
    "Trying to sort that out, she focused primarily on unraveling that tangle and determining what it meant, only some of her processing power devoted to actually directing the creature that Nonoko was calling 'Shamisen' through the city. The over-sized feline had no trouble navigating invisibly between cars, bounding effortlessly through and over traffic, while Ryouko tried to sort out that sensation."
    "She made sense of things only as the slider arrived, Kuyou sending out a wave of her exotic energies, Ryouko just managing to synchronize the pair of them through the transition before she understood:"
    "Nonoko's mother loved her, and was worried about her daughter. Somehow, either through the data entity that resided within the body of the cat, or through Kuyou, {i}Ryouko felt it too{/i}. Whatever it was ... she didn't like it!"
    "Something affecting her judgment, making logical choices harder? She didn't want negative emotions! They would slow her down and keep her from performing at an optimal rate! But since being captured and abandoned by the IDSE, she'd experienced {i}several{/i}. Anger at being abandoned ... fear at the threat of Kuyou ... and now, what, {i}guilt{/i} over trying to help Kyon?"
    "Turning to Nonoko, still in sprite form, Ryouko said, \"Nonoko! It's very dangerous from here!\""
    "The girl's eyes weren't on Ryouko, though, but the portals forming in the air over the school ahead of them in the space they had entered. She blinked, her forehead shining with sweat, and shook her head, reaching for Kyon's weapon and forming it into a staff in one hand. \"Kyon-kun's in there?\" she asked Ryouko eagerly."
    "\"That's right!\" Ryouko agreed. \"And once you reach him and give him his tools, your mission will be complete!\""
    "The little girl nodded at that, then declared, \"Well, I'm just going to rescue him myself, then! Since you're the well-meaning mentor who tries to talk me out of winning my first, climactic battle, I have to stop listening to you and go forward to prove myself! So don't try and talk me out of it!\""
    "Ryouko observed in silence, unable to respond due to Nonoko's last order. What was this new sensation she was feeling? One that wasn't copied from someone nearby, but had originated within herself?"
    "* * *"
    "\"Okay, that's enough,\" was what snapped Nonoko back out of the doze she'd been in. She blinked and sat up, happily smoothing her magical girl garb back into place, pleased she hadn't lost her magic wand, either."
    "Well, she supposed it was technically her brother's magic wand, but he was a {i}boy{/i}, anyway, so she'd make better use of it."
    "The speaker in question, when she looked, was Haruhi, who was glaring at the advisor sprite that had shown Nonoko how to use her brother's tools. For whatever reason, the minature blue-haired figure was crying continuously, tiny animated waterfalls flowing down her normally cheerful face."
    "\"Kyon is going to be very upset about this, and I can't blame him,\" Haruhi growled. \"Ugh — but enough of that.\" She turned to Nonoko, her gaze suddenly stern, not the smile she had told Nonoko to rest with. \"Nonoko, you understand that we need to give those tools to Kyon, so he can help us win this fight, right?\""
    "\"No!\" she protested, her own smile slipping. \"Kyon-kun still doesn't trust me enough! This is the way to prove it once and for all! Let me help rescue him!\""
    "\"Ryouko!\" Haruhi snapped, turning to the floating figure once more."
    "\"There's nothing I can do!\" the sprite sobbed, sounding genuinely distraught — and oddly like she wasn't used to it. \"Only Kyon-kun or Yuki-chama can override her!\""
    "Nonoko perked up slightly at that. Of {i}course{/i} magical girl gear bonded to the user! \"So, let's go rescue Kyon!\" she demanded. \"Isn't that what we want to do?\""
    "\"Somehow, hearing that from you....\" Haruhi trailed off, rubbing at her face. Nonoko blinked, slightly taken aback. Haruhi's nose looked red, for some reason.... Ah, if Nonoko's head didn't feel so fuzzy, she was {i}sure{/i} she would have remembered something important about that."
    "Well, if she didn't remember, what did her mother always say? If she couldn't remember, it must not have been important!"
    "\"I've got the Radiant Buster, so I can help, Haru-nee!\" she cheered, trying to encourage her."
    "Another of the inexplicable changes in temperature hit her then, and it went from being far too cold, to too warm. She wiped the sweat from her forehead and stared at Haruhi pleadingly. She was a magical girl now! Like Haruhi and Yuki!"
    "Shouldn't they get to have magical adventures?"
    "\"So, let's go rescue Kyon!\""
    "\"I can't be happy about this!\" Haruhi growled, stamping one foot, then shaking her head. \"We've wasted enough time here — Kyon could be in trouble. Okay, Imouto-chan, you're with me; if you get hurt, Kyon will never forgive me. Do you understand?\""
    "Nonoko was taken aback to find herself picked up by no visible source at all, her legs kicking in alarm as she was borne straight before Haruhi, arms outstretched expectantly. The taller girl grabbed her, seizing her in a tight hug before Nonoko remembered — of course! Haruhi could fly and move things with her mind!"
    "\"Nono-chan ... we're going to have a long talk about this afterwards, alright? But for now, in case Kyon and Kuyou-chan need us ... stick with me.\""
    "\"I'll be good!\" Nonoko promised, grinning, hugging the older girl back."
    "Haruhi and the sprite exchanged a look that was strangely identical on both of their faces — the kind of expression she had seen when her parents were letting her get her way, but weren't happy about it. Hey! What was that all about?"
    "Before she could ask, though, Haruhi had kicked the door open, unleashing a positive {i}storm{/i} of the defensive orbs she kept revolving around them before snatching Nonoko into her arms and leaping back out into the field — just in time to see the distant, desperate form of Kyon, leaping away from the school building."
    "The field he was leaping towards was almost completely filled with the fast- moving robots that had pinned down Haruhi when Nonoko first arrived! Even as she watched — and Haruhi zoomed forward, lobbing easily a dozen of her spheres towards Kyon, as her grip on Nonoko tightened — the building behind Kyon seemed to explode, crushed by the immense weight of a massive blue construct of some sort."
    "Already most of the school building was obscured beneath the rising pillars of dust. The ground beneath them seemed to shake, even as Kyon landed — like an anime character. A ring of dust shot outwards from where he landed, blasting across the ground beneath the robots' feet without disrupting them in the slightest."
    "\"There's so many!\" Nonoko exclaimed in sudden worry, seeing how far they still had to go before reaching Kyon. She steeled her resolve, even though it was a bit strange being carried by Haruhi's invisible powers. With that...."
    "Remembering what the sprite had taught her, and ready to fight, Nonoko called out, \"Radiant Magical Nonoko — Set-Up!\""
    "The sprite made a worried noise instead of a happy one, answering, \"Augmented reality targeting system enabled.\""
    "As the first of Haruhi's glowing orbs shot within range of Kyon, moving too slowly to help him. The nearest of the robots suddenly spat a stream of brilliantly glowing ... things ... at him, even as Haruhi cried out, \"No! Kyon!\""
