label Re_2:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 058 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear

    "After the unexpected distraction of Taniguchi's outburst, class settled down for what felt like a very normal day for Kyon. The semester-end testing was coming up very soon, which he wasn't looking forward to, but thanks to Haruhi's help studying, he wasn't actually worried about it."
    "He had bigger concerns. Well, he'd had the concern of the IDSE for quite a while, but angry sliders were a new wrinkle, to say nothing to his part-time job as a criminal. Which, once he paused to think about it, he realized was probably actually going to be his career path as well."
    "Those thoughts circled through his head through lunch and all the way until the end of class, where they headed toward the club room as always. \"Oh,\" Haruhi remarked, walking at his side instead of dashing ahead. \"Koizumi won't be at the meeting, since he wanted to visit his girlfriend.\""
    "\"They're dating already?\" Kyon asked, scratching the back of his head. That seemed fast.... Well, he certainly wasn't in a position to actually judge, was he?"
    "Haruhi nodded, glancing at him sidelong. \"I think it'll work out once she calms down and gets over that hero-worship thing she's got going on for him. I guess that's probably to be expected after ... what he's done,\" she said, glancing around and choosing her words carefully."
    "He shrugged, thinking of Koizumi's interest in Haruhi herself. Even if they were friends, it had kind of bothered him -- the idea of Koizumi being interested in someone else, though, that suited him just fine. In fact, thinking about things, he was actually glad for the esper. It was probably not the most comfortable thing trying to be friends with a guy who had a whole host of supernatural girlfriends anyway."
    "Kicking the door open with her usual enthusiasm, Haruhi planted her hands on her hips and surveyed the room-- The only person present was Yuki, tapping slowly away at something on her laptop. She did pause to look up and give her tiny nod of acknowledgement, but that was the extent of it."
    "\"The others will be here soon enough,\" Haruhi declared confidently, nodding back at Yuki with a wide smile."
    "Kyon nodded absently, pulling Ryouko from his greatcoat pocket and setting her on the table. Her tiny form scampered to the side of Yuki's laptop to read the screen, but Yuki preemptively lowered it, giving her a cool gaze. \"Wah!\" Ryouko yelped, jumping back a step, eyes wide."
    "He snorted at the interaction and took the seat opposite Yuki."
    "One of Haruhi's eyebrows rose as she caught that, setting down her bag and claiming one of the seats next to Kyon. \"What are you working on, Yuki-chan?\" she asked."
    "Yuki's gaze was surprisingly evasive, orienting toward the door."
    "Kyon wondered himself, but before Haruhi could try to investigate with force, he offered, \"I think it's private.\""
    "Haruhi's other eyebrow rose, and Kyon cursed inwardly; that was the perfectly wrong choice of words!"
    "\"I mean,\" he added quickly, \"I think she's trying to keep it secret from me.\""
    "Surprisingly, Yuki gave a nod at that -- slightly more than her normal minimalistic response!"
    "\"Oh!\" Haruhi exclaimed. \"Well -- you'll have to let me know what it is later, then,\" she declared, nodding."
    "Not quite what he'd intended ... and now he was really curious! Hopefully he'd find out some day. Yuki's incredibly faint blush and the way she avoided meeting his gaze after that.... Hey, what was that about?!"
    "The door creaked open just then, Tsuruya leading Kanae in, with Mikuru just behind them."
    "\"Hmm, I just realized, I should take over Tsu-chan's job of escorting Kanae-chan to our meetings,\" Haruhi mused, smiling at the newcomers. \"Well-- Except for Koizumi, who will meet up with us later, we're all here! Any important news?\""
    "\"There is one thing,\" Tsuruya said cautiously, taking the seat next to Yuki and opposite Haruhi."
    "Haruhi surmised, \"Something ninkyo dantai related?\" Kanae quickly claimed the other seat near Kyon, and Mikuru settled for the seat opposite her, not changing into her maid outfit for that day."
    "Tsuruya nodded, explaining, \"Um, with the help of Yuki-nyan, I was able to makes inroads toward peace with the Sumiyoshi-rengo!\""
    "\"That's great!\" Haruhi exclaimed, grinning. \"They're no fun to fight, and we have plenty of other enemies-- That means no more kidnapping Sasaki-chan, right?\""
    "\"Hopefully,\" Tsuruya agreed. \"We haven't finalized it, and the persons I talked to said there could still be active agents in the field.\""
    "\"Better than nothing,\" Haruhi allowed. \"Anything else?\""
    "\"Um ... nope!\" Tsuruya said brightly."
    "Kyon frowned slightly. She wasn't going to bring up that she was in danger? But maybe that was alright. Haruhi couldn't have helped, either.... Well, she could have, but it would probably have been overkill."
    "Maybe he should bring it up himself. \"Well, I found out about it from Suou-san last night,\" he explained, blinking when she suddenly appeared, her tiny form standing next to Ryouko's on the table. He was momentarily disconcerted by that, studying the small figure."
    "\"And?\" Haruhi prompted, though her gaze was drawn to Kuyou as well."
    "\"Then Kyon and Chuou kissed!\" Ryouko exclaimed happily. \"What an interesting experience!\""
    "Yuki looked up from her typing and nodded. Kanae, Mikuru, and Tsuruya blinked and turned to look at Kuyou as well, who beamed a tiny, happy smile all around."
    "\"She-- She wasn't that size at the time,\" Kyon said, mildly defensive when Haruhi's expression turned incredulous. Wait, that was completely the wrong thing to say! \"I mean--\""
    "\"It is fine,\" Yuki said quietly, her attention going to Haruhi."
    "\"It's 'fine'?\" Haruhi asked. \"It-- Well, hmm....\" She settled back into her seat, crossing her arms over her chest as she contemplated. \"We can't let this grow out of hand, you know, since we're all struggling with figuring out how to get enough Kyon-time as it is. But then again ... she's been trying to find you for almost four years at this point, right?\""
    "\"I-- What?\" Kyon managed, thoroughly bewildered."
    "\"The symbol I made you draw that Tanabata, four years ago,\" Haruhi explained, shrugging. \"It was supposed to be a declaration of, 'I am here,' to the universe. She heard it and came looking ... for you. So her attraction to you is my fault-- Ah, think about it! I could have a cute alien with a chibi form chasing me and making you jealous instead of the other way around!\""
    "\"S...sorry,\" he stuttered, wincing. 'Special hell' indeed...."
    "\"Well, Yuki-chan evidently already approved. I guess we have to make something of a special case for her, anyway,\" Haruhi continued. \"Kanae-chan, what do you think?\""
    "\"Eh-- Me?\" the slider squeaked."
    "\"Of course!\""
    "\"U...um....\" Kanae hesitated. \"Um ... Suou-san looks a lot like one of the sliders that ... chased me a lot. But this one's ... nice. She's sometimes a little silly, but she makes nice cookies. I think ... she's really friendly -- and she's done a lot to help both of my favorite sempai out!\" She blinked, smiling brightly. \"Yeah, um, I don't mind! Suou-san is really cute when she's small like that, too!\""
    "\"Mikuru-chan?\" Haruhi pressed, grinning."
    "\"I ... don't mind Suou-san,\" Mikuru said cautiously, offering the dark doll-sized form a tentative smile. \"She's fun to teach cooking, and she's worked very hard to help us all.\""
    "\"I agree!\" Tsuruya said brightly. \"I'm fine with her!\""
    "\"Alright!\" Haruhi declared, slapping one palm on the table authoritatively. \"Then you're in, Kuyou-chan! Welcome to the group!\""
    "\"I don't-- I don't get a say in this?\" Kyon asked belatedly."
    "\"You kissed her already,\" Haruhi reminded him. \"So your vote has been cast. I'm not even going to consider that you're saying you'd give someone a kiss you didn't mean!\""
    "Kyon bit his tongue, thinking very far back, to the first kiss he had shared with Haruhi. \"I wouldn't,\" he said quietly, guessing she was thinking of it, too."
    "Coughing, she gave a firm nod, her cheeks reddening. \"A...anyway, anything else will have to wait. We're supposed to be going to Hinamizawa for this weekend!\""
    "Kyon felt a frigid shock in his spine. Oh, right. He was supposed to somehow take care of that ... and he'd been so distracted by everything else he'd screwed up and forgotten!"
    "\"Ah, H...Haruhi,\" he started hesitantly."
    "\"Too late to back out now,\" she warned him, frowning. Sweeping Kuyou's form up from the table, holding her gently in both hands toward him, she added, \"You accepted her, and she's in! Could you say no to a face like that?\""
    "Kuyou's small face offered a happy smile, and her arms reached out, as though to grab him in a hug. \"That's.... No, Haruhi,\" he sighed, looking away. \"It's--\""
    "\"No more lip; this is supposed to be a vacation,\" she insisted, spinning Kuyou around and hugging her tightly. \"So we're going to meet up at Tsu-chan's place. Don't be late, and since I know you're chronically lazy -- Ryouko, make sure he packs, and don't let him try and leave his sister out of it! She doesn't really need to be part of things, but she's helped us out and done other activities with the Brigade anyway.\""
    "\"Magical Radiant Nonoko!\" Ryouko cheered, as Haruhi gently returned Kuyou to the table."
    "\"Hopefully she won't need that this time,\" Haruhi said, shaking her head. Clapping her hands together, she surveyed the other girls in the room. \"Okay -- we've got a big weekend, so nobody be late-- I'm going to help Kanae-chan pack-- Tsu-chan, you help Mikuru-chan, okay?\""
    "The slider and the time traveler exchanged a glance before shrugging."
    "\"And you, Kyon,\" Haruhi added, before he could protest, \"had better hurry!\""
    "He bit his tongue, wincing as Haruhi grabbed her bag and vanished through the doorway. Tsuruya bounced to her feet and pulled Mikuru after her the same way. But ... he hadn't come up with any kind of plan to actually get them to Hinamizawa! He could show up -- everyone could -- but unless he could somehow figure things out before he got to Tsuruya's place.... Actually, he didn't see any alternatives!"
    "Well, he could beg Haruhi and Yuki for help? Resigned to his fate, he sighed. Maybe he could think of something."
    "Somehow."
    "Closing the laptop up, Yuki's footsteps navigated silently around the table, where she gently patted him on the head twice before taking Kuyou's form from the table and slowly walked after the others."
    "\"Oh, boy,\" he sighed, as Ryouko's small form turned to face him expectantly."
    "* * *"
    "As busy as things had been, Mikuru was glad they seemed to be calming down. Well, there was the addition of Kuyou to their already complex arrangement, but despite her earlier reservations, Mikuru had learned that the strange entity was a lot more like Yuki than the time traveler had given her credit. Admittedly, she could turn into that tiny, cuddly form-- So cute!"
    "So easy to make costumes for, too!"
    "And of course, more importantly, she was an ally, someone who wanted to help Kyon, Kanae, and the rest of the Brigade. It also didn't hurt that Mikuru enjoyed teaching her how to bake cookies. With any luck, once the group of them went to Hinamizawa for the weekend, Mikuru could teach her how to make a cake, as well! Oh, that would be nice!"
    "That thought in mind, she was still humming to herself when she reached Tsuruya's home, hefting a heavy bag of clothing for the trip. Well, it would be a shorter trip than some the Brigade had taken, but a few changes wouldn't hurt...."
    "The chief maid quietly greeted her at the gate. She wasn't tired from the walk, but wondered how the others might have fared. \"I...is anyone else here?\" she asked the woman cautiously."
    "\"Right this way,\" the woman said, nodding. Mikuru fell into step behind her, touching a thoughtful fingertip to her lip. Her costume was a traditional kimono, but she was a maid too, wasn't she? They already had kimono to dress up in for the club, though...."
    "When she got to the living room, Mikuru was unsurprised to see Haruhi already there, her bag set to one side. Tsuruya was sitting on the couch next to her as the pair discussed something quietly. Mikuru wasn't sure what it was, but Haruhi's expression was both eager, and pink -- Tsuruya's face was a bit red, too!"
    "\"Um, hello?\" Mikuru called cautiously."
    "Tsuruya cut off instantly, hopping to her feet and bounding to Mikuru's side. \"Ah, Mikuru-chan!\" she caroled. \"Soon we'll all be here!\""
    "Mikuru nodded thoughtfully at that as there was a muted rush of displaced air -- Kanae and Yuki appearing in the middle of the room, holding hands. Each of them had their own travel bags in their free hands. \"Oh!\" Haruhi exclaimed, hopping to her feet while Tsuruya's chief maid blinked once before quietly dismissing herself. \"Kanae-chan, you thought to bring Yuki-chan with you?\""
    "\"Eh?\" the slider managed, before Haruhi grabbed her in a hug. \"Wah!\""
    "\"I asked for her assistance,\" Yuki answered softly."
    "\"You needed help?\" Tsuruya wondered."
    "\"More efficient.\""
    "Haruhi snorted, shaking her head. \"I'm starting to think you're just lazy, Yuki-chan,\" she jibed gently, still smiling. \"Of course, just like Kyon, you come through when it's needed, so it's cute for both of you.\""
    "\"Speaking of Kyon, though,\" Haruhi mused, frowning, \"where is that guy?\""
    "Before anyone could answer, Tsuruya's maid returned, this time leading Koizumi and a shyly, hesitant Kyouko into the room."
    "Haruhi blinked at the female esper, raising an eyebrow, and Kyouko ducked her head. \"U...um,\" she started haltingly, not able to meet anyone's gaze. \"T...thank you for inviting me along,\" she mumbled."
    "Tsuruya tapped her chin, her smile fading. \"Hmm, is this ... the first time you've left the hospital since we took you in?\" she wondered."
    "Kyouko's face reddened slightly more, and she suddenly found her indoor slippers fascinating."
    "\"Wait, really?\" Haruhi wondered."
    "Mikuru blinked in astonishment -- Kyouko was still hiding away from the world except for Koizumi? Maybe bringing her along on this trip would be very good for her, then!"
    "\"I...it's scary when people try and capture you,\" Kanae said supportively, once Haruhi released her. \"Um, if it weren't for Sempai, and Suzumiya-sempai, I wouldn't ... have the courage, either.\""
    "Mikuru bit her lip. No one had ever tried to kidnap her except for ... well ... Kyouko herself! Still, she did understand Kanae's point about it being easier to deal with thanks to Kyon being around."
    "Haruhi had gotten caught up in that craziness more recently, though, and nodded thoughtfully, her eyes distant. \"Alright-- Kyouko-chan, you're working for us, now, right?\" she asked, placing her hands on her hips and raising her eyebrows."
    "\"Y...yes!\" Kyouko yelped, shivering and trying to stand up straight."
    "\"Ah, Suzumiya-san,\" Koizumi began uncertainly."
    "The Brigade chief silenced him with a waggled fingertip. \"Okay, Kyouko, you can't afford to miss this much school -- but since you have already, your next assignment is to transfer to Kitago,\" she declared, grinning. \"Understand?\""
    "\"I-- But ... I should ... stay by Sasaki-san,\" Kyouko protested weakly."
    "\"Oh, but ... she's transferring to Kitago, too!\" Mikuru supplied thoughtfully. \"So won't that be fine?\""
    "\"I.... Um ... okay?\" Kyouko answered, looking dazed and unsteady. Koizumi linked one of his arms with hers to steady her, patting her wrist gently with his other hand. Aww.... Well, Koizumi wasn't Kyon, but he wasn't bad looking -- and with Kyouko like that ... they really were a cute couple. Oh! Matching costumes!"
    "As if to underscore that thought, Tsuruya and Haruhi both snapped pictures of the blushing Kyouko hesitantly turning to look up to the taller esper. \"Would that be okay?\" she asked softly."
    "\"Certainly, I would have no complaints,\" he agreed beaming a smile that looked ... different from the smiles he used to wear. This one seemed more genuine, more heartfelt. No doubt about it in Mikuru's mind -- that girl was good for him, too!"
    "\"Um, then okay!\" Kyouko agreed happily."
    "\"Girl doesn't have a tsun-tsun bone in her,\" Haruhi remarked, clicking her tongue. \"I think she's made of one hundred percent pure dere-dere-tonium.\""
    "\"Like Mikuru-chan and Kanae-chan?\" Tsuruya snickered."
    "Mikuru felt her face redden in time with the slider's. \"H...hey,\" she protested weakly, at the same time as Kanae. Both the time traveler and the slider were caught in a hug from Tsuruya, while Yuki looked on expectantly."
    "\"But that's what we like about you!\" the heiress explained. \"Two cute and endearing girls!\""
    "\"Also the power to warp space and time -- I'm starting to wonder if that's not part of the moe factor, too,\" Haruhi supplied. Looking at the wall clock, she frowned. \"Late as always,\" she sighed, shaking her head. \"Alright, we should call Kyon and find out what's holding him up. Though ... it could be his parents....\""
    "\"I-- I'll try calling him!\" Mikuru offered quickly. She wanted to help too, after all. Come to think of it, she was still a bit amazed that her superiors somehow agreed to let her do this! Haruhi nodded expectantly as Mikuru pulled her phone from her pocket and dialed Kyon's number."
    "\"Hello?\" he answered almost immediately. \"Mikuru?\""
    "\"That's right!\" she agreed brightly. \"Um, Kyon-kun, we're all gathered at Tsu-chan's; are you on your way?\""
    "\"I'm ... still at home,\" he answered, sounding anxious about things. \"There's.... I mean, I haven't figured out how to pull this off, yet.... Wait, you say everyone else is there?\""
    "\"Um, yes,\" she replied, before biting her lower lip."
    "What was the problem? Haruhi put her hands on her hips again, her smile fading. \"What's the hold up?\" the Brigade chief asked in irritation."
    "\"I ... still haven't figured out how to run this past my parents,\" he admitted. She could envision his pained wince just from his tone of voice! Poor Kyon-kun!"
    "She knew he'd been stressed lately, but perked up at a sudden realization. \"Um, Kyon-kun,\" she said, a smile coming to her lips. \"Are you-- Are you alone right now?\""
    "\"Huh? Yeah, just me and the chibi,\" he agreed. \"I mean, Ryouko, not my sister.\""
    "\"Okay!\" Mikuru said brightly. \"Just wait right there!\" She hung up quickly-- It would be okay, after all."
    "\"Well?\" Haruhi pressed, eyebrows rising expectantly."
    "\"Um, he needs to get past his mother,\" Mikuru explained. \"For that, um ... Kanae-chan, could you bring Kyon-kun and his sister here?\""
    "\"Yes!\" the slider exclaimed eagerly, before popping out of sight with another whoosh of displaced air."
    "\"Good thinking!\" Haruhi approved, before Kanae popped back just as abruptly, beaming a pleased smile at having Kyon in tow. She was holding one of his hands, and he ran the other through his hair, looking nervous. Why did he look worried? Well, he didn't have to worry about a thing, here."
    "On Kanae's other hand, though, was a wide-eyed Nonoko, clutching a bag stuffed with supplies in the other. \"Just like Trope-tan's archive-teleport!\" she gushed."
    "\"Aw, your mom didn't give you an opportunity to pack a bag?\" Tsuruya wondered."
    "\"N...no,\" Kyon began, looking off-balance. \"It's--\""
    "\"Okay, we're all here, except for Kuyou-chan. Is she coming with us?\" Haruhi asked, looking around."
    "\"She'll meet us there!\" Ryouko chirped from Kyon's greatcoat pocket."
    "\"Alright-- Let's do it!\""
    "Kyon sighed and hung his head for some reason. All the more reason to start their vacation, Mikuru decided! \"Um, let's all form a circle,\" she said, smiling softly. \"Put your bags on the floor in front of you, and we'll hold hands. Um, Yuki-chan, if you could help me out, and Kanae-chan, too....\""
    "While the vice commander looked confused, he followed instructions along with the others, until they were standing in a circle, hands linked. Except for Kyon, everyone had a bag in front of them. Ryouko wasn't holding anyone's hand, but she would be secure in Kyon's pocket anyway. It was also unlikely that Kanae would really be able to help, but Mikuru wanted to give the girl a chance to be recognized -- really, without her, Kyon might have been stuck at home!"
    "\"Now, keep your eyes closed to avoid getting time-sick,\" she warned, just before activating her TPDD."
    "* * *"
    "Probably she should have followed Mikuru's instructions, but the thought that they might actually not just be traveling through space, but time had excited Haruhi too much. So she kept her eyes opened and...."
    "Well, she wasn't entirely certain what was supposed to happen, but the bright lights and fantastic shapes had overwhelmed her. She had to blink several times to regain her bearings, staring up at the early afternoon sky. Shaking her head, she realized she was held in Kyon's arms, protected from crashing to the ground. Well, she had been holding his hand ... and Tsuruya's as well."
    "\"W...what happened?\" Mikuru asked anxiously. \"Are you okay, Haruhi-chan?\""
    "\"I'm betting she kept her eyes opened,\" Kyon offered, shaking his head and giving her a knowing smile."
    "She felt her face heat up. \"S...shut up!\" she grumbled. \"I'd like to see you try it!\""
    "\"Well, it's not really fair,\" he said with a shrug, helping her up to her feet, though she still wobbled a bit. \"I've been through that a few times -- through probably not as much as Asahina-san.\""
    "\"...you were able to keep your eyes opened,\" she surmised, scowling."
    "He looked around, scratching the back of his head. \"If.... If it makes you feel any better,\" he offered, \"I totally screwed up arranging this trip. I completely forgot about setting things up.\""
    "\"What?\" Haruhi snapped, at the same time Mikuru voiced a confused, \"Huh?\""
    "He shook his head, looking apologetic. \"It slipped my mind!\" he said, wincing. \"Luckily, somehow, Mikuru was able to set this up anyway!\""
    "Haruhi stared at him, while Mikuru's eyes widened. \"I-- I forgot to tell Kyon-kun, didn't I?\" she realized aloud, her face reddening."
    "While she wanted to snap at someone for the embarrassment, she really couldn't hold on to her temper. That was too cute -- and anyway, Kyon had enough to deal with. So she laughed, shaking her head and looking around. She hadn't spent much time exploring Hinamizawa thanks to the rain, and then spending what time she had with Kyon on her last visit."
    "At a glance, Mikuru had transported all of them to a clearing on a hillside not far from the shrine that Kyon's aunt Rika maintained. Their bags were neatly on the ground in front of them, and...."
    "\"Uh,\" Haruhi realized belatedly, frowning at her feet. \"We forgot that part, didn't we?\""
    "Since they were standing in deep wild grasses between the trees, their indoor slippers were probably already ruined."
    "\"Oops!\" Tsuruya exclaimed, chuckling."
    "Of to one side, Koizumi and Kyouko held hands, both marveling at their changed surroundings. \"I wish Sasaki-san could have joined us, somehow,\" the shorter esper wished aloud."
    "Shaking her head, Haruhi turned to Yuki, who was watching her with a look of very faint amusement. \"Yuki-chan,\" Haruhi declared, pointing at her feet. \"Proper shoes for everyone?\""
    "\"Executing program,\" Yuki answered, not even glancing to Kyon as everyone's indoor slippers morphed and shifted over the span of a few seconds, becoming more appropriate shoes for the situation."
    "\"Alright! Now we're ready!\" Haruhi declared. \"Let's meet Kyon's awesome family!\""
    "\"You've met my family before,\" Kyon pointed out."
    "Waggling a fingertip and grinning, Haruhi clarified, \"Not the awesome half, though!\""
    "He snorted, running a hand through his hair. \"That's.... Well, think about this, Haruhi. If I didn't manage to arrange anything, we're going to have to crash on my aunts unexpectedly.\""
    "\"Minor setback,\" Haruhi allowed. \"Okay, worst-case, we rent rooms in Okinomiya.\""
    "\"I didn't bring money with me,\" Kanae fretted, suddenly looking anxious."
    "\"I.... I didn't either,\" Mikuru allowed."
    "Koizumi and Kyouko shook their heads in a synchronized gesture of apology, while Kyon frowned. \"I do have some of that,\" he allowed. \"Today was payday, after all.\""
    "\"No need!\" Tsuruya declared confidently. \"Kyon-kun, we can just ask one of our allies in the area to help us out as an allied syndicate! I can always pays it back later!\""
    "\"So, you mean crash in on my aunt unexpectedly,\" he clarified, raising an eyebrow."
    "\"...yes,\" Tsuruya agreed, chuckling in embarrassment. \"But, Sonozaki Mion-san is an ally!\""
    "\"And my aunt,\" Kyon sighed, rubbing the bridge of his nose. \"Okay. Well, it won't hurt to ask, but if it's trouble, we can probably still figure something out with a hotel in Okinomiya.\""
    "\"W...we have to reimburse you for that and make it a group expense if that happens,\" Haruhi added quickly. Giving Kyon penalties was all well and good when he wasn't stressed out. When he was, it was no fun at all."
    "\"In the meantime, um, for those of you who have not been here before ... that's Kanae-chan, Koizumi, and Tachibana, I guess, welcome to Hinamizawa! Now, be warned, my cousins are unholy terrors, so there's likely to be pit traps everywhere.\""
    "Kanae burst into laughter at that. \"Pit traps?\" she chuckled, prodding the ground before her with an experimental toe. \"That's-- Waaah!\""
    "Haruhi and Kyon both burst into motion toward the girl, but thanks to the fact that Haruhi could, well, cheat, she beat Kyon there. The slider windmilled her arms comically as her foot plunged through a screen of grass over -- just as Kyon had warned! -- a pit in the grass. Kyon himself hopped over another en route, but Haruhi managed to capture the slider in her arms, floating just over ground level."
    "The boy came to a halt, shaking his head ruefully. \"Yeah, so ... be extra careful to watch your step,\" he sighed."
    "\"Are you okay, Kanae-chan?\" Haruhi asked, still holding the slider tightly."
    "\"Y...yes,\" the girl squeaked, still wide-eyed. \"Um, why are there traps like this?\""
    "\"Because it's fun to surprise people!\" Nonoko declared, giggling."
    "\"The Houjou twins,\" he said with a shrug. \"Cousins of mine-- Anyway, they know better than to make traps on the road, so let's get to the shrine.\""
    "\"I helped make a few -- we even caught Nii-san a few times!\""
    "\"I wish I could have seen that!\" Haruhi remarked, snickering. Shaking her head, she said, \"Still -- Everyone be extra careful!\""
    "Kyon nodded, making his way to Mikuru's side and hefting her bag with a wink, motioning for her to follow him. She did so cautiously, watching her step anxiously. Kanae's bag, and Haruhi's as well, simply floated along when she thought about it. No sense worrying about that extra weight with those things around...."
    "In short order, they had crossed the field, no one else falling prey to a pit trap, but managing to find two more on the way. Really, except for the fact that Sasaki wasn't ready to join them, the trip was actually starting off pretty well. Not as nice as the trip to Tsuruya's snowy villa, or the island mansion that Koizumi's Organization had set up, long ago."
    "But this one was all them, with no outside help -- and more importantly, none of those lurking secrets preventing them from being honest with one-another! That had to count for something!"
    "A screen of trees obscured the field they arrived in from the road, and there Haruhi stopped levitating, setting Kanae and their luggage down. Kyon wordlessly hefted the slider's bag, and at a glance they looked like ordinary traveling youths."
    "Nodding decisively, Haruhi pushed through the underbrush between the trees to the path leading up to the shrine, freezing as she made it through. Kyon was a step behind her, but he froze, too. He found his voice before she did, asking, \"Uh ... Fujiwara, what ... is going on here?\""
    "Haruhi didn't know him well, but had encountered him a few times-- His scowl made Kyouko yelp and grab onto Koizumi reflexively, but the time traveler looked away from both espers, coughing. \"T...this is my apology,\" he grumbled. \"Uh ... Kyon ... still owes me one favor, and ... this is part of it,\" he mumbled, gesturing behind him."
    "Of course, whatever the time traveler's motive, that was what had really gotten Haruhi's attention, and she suspected Kyon's as well. Kuyou being there wasn't a huge surprise, not really -- Yuki had said she'd meet them there. But standing there in her own clean and neat -- new looking -- Kitago uniform...."
    "\"I still don't understand this game,\" Sasaki said with a sigh. \"Can I remove the blindfold yet?\""
    "\"Y...yeah, I think that's fine, Sasaki,\" Kyon said scratching the back of his head. \"So, Fujiwara ... what's that favor, exactly?\""
    "\"You have to explain where we are, and bring her back home afterward,\" Fujiwara said, crossing his arms over his chest and looking away. \"After ... that there may be something else, but it's just as much a favor to you as me.\""
    "Meanwhile, Sasaki reached up and tugged off the plain scarf covering her eyes, blinking at her surroundings. \"Oh, my,\" she remarked. \"Are we in the mountains north of Nishinomiya?\""
    "\"Really far north,\" Kyon mumbled, as Fujiwara waved, turning to march down the stairs. \"Uh, what day is today, anyway?\""
    "\"Monday, of course,\" Sasaki answered looking a bit puzzled. \"Oh! Are we skipping class this morning for, um, 'work'?\" she asked anxiously, eyes widening. \"Missing my first day! But this is exciting, too, isn't it?\""
    "\"Hey,\" Kyon called to the other time traveler, while Mikuru blinked in stunned confusion, and Yuki watched everything impassively. \"Fujiwara -- did future me put you up to this?\""
    "\"Yeah,\" Fujiwara called back, nodding. \"And by the way, he is almost as big a jerk as future me.\""
    "\"You can say that again,\" Kyon grumbled."
    "\"Almost,\" Fujiwara reiterated, looking back and shooting Kyon a pained smile."
    "Pressing her hands together, Sasaki asked, \"Does this have something to do with what happened on Saturday? I should thank you again for getting me this uniform!\""
    "\"Oh, boy,\" Kyon sighed, setting down the bags he was carrying to massage his temples."
    "* * *"
    "When she was younger, the Hinamizawa festival had seemed to just happen. Even when she was in the time loop, Rika had nothing to worry about beyond her role in the ceremony. As she'd grown older and taken on more of the responsibilities of actually managing the shrine, that had changed."
    "Now she was more than just an 'honorary' member of the council. It seemed every year more and more responsibilities were handed to her. Which stalls to approve, which vendors to place where.... Aside from that, Matsuri had taken over the ceremonial role of shredding the cotton anyway."
    "It seemed that the festival she was currently working on planning had no real relationship to the festivals she had participated in the past. So she found herself in one last tedious meeting discussing permits and allowing outsiders to set up stalls. For the last few years they'd let more and more in.... Hinamizawa was no longer the 'controlled' and 'closed' village it once had been."
    "That much was fine, but annoyingly enough, the outsiders, traveling vendors that just moved from festival to festival across the country, were trying to muscle out the locals. Festival traditions that were years old were being pressured to make room for 'professional' outfits."
    "The villagers didn't like it, and Rika didn't, either. It was starting to get to the point where instead of meeting and being polite about it, she was just about ready to ask Mion if she could 'discreetly encourage' those vendors to calm down and respect the local traditions. Wasn't it fine if the outsiders set up stalls and served tourists?"
    "Well, it was less than ideal that the locals only visited local stalls, but being pressured to go to the 'professional' outfits grated on everyone's nerves, and undermined the value of tradition."
    "As it was, she and Mion were representing the village and dealing with a quintet of the outsider vendors. The vendor's chosen representative complained, \"All we want is the option to pay for a better location to place our stall -- something adjacent to the lot where the stage is, so we can serve customers during the ceremony.\""
    "Mion was unmoved, answering, \"There's no point to that anyway. Our custom is to close down all of the stalls during the ceremony itself.\""
    "Rika nodded, glancing to one side as Hanyuu sped through the walls of the meeting room, wide-eyed and waving her arms. \"Rika, Rika!\" she whined. \"You're not going to believe this!\""
    "\"Well, if we have to shut down for the ceremony, that's fine,\" the man continued. \"The point is, holding all of that space only for locals is an unfair monopoly! Isn't it only reasonable to let fresh blood in?\" For whatever reason, he punctuated the last remark with an unsubtle tug at his collar, where he wore a pin that Rika didn't recognize."
    "Mion seemed to, but her reaction was to look very unimpressed. \"Really?\" she asked, raising an eyebrow. \"Big men, flaunting your organization's brand and trying to threaten a pair of women you outnumber.\""
    "\"Hey,\" the representative growled, even as he bowed his head. \"We're trying to be nice and--\""
    "\"Kyon's here?\" Rika said aloud, too startled by Hanyuu's news to keep herself in check."
    "\"--huh?\""
    "\"What, really?\" Mion asked, turning to look at Rika in surprise. \"That sixth sense of yours?\""
    "Rika allowed a smile, shrugging. Being a shrine maiden did have its perks.... \"Mm,\" she noised, noncommittally."
    "\"Well-- Sorry if we're treading on family time or something,\" the man continued, \"but the point here is, we're willing to work with you on this. It would be great if we could work together, and we didn't--\""
    "\"Excuse me,\" one of the other men said, frowning. \"Did you say, 'Kyon'?\""
    "\"Yeah,\" Mion agreed, nodding. \"Our cute little nephew from Nishinomiya!\""
    "\"Ni...shi....\" The leader of the men looked suddenly far less certain, and actually took a step back. \"Uh....\""
    "\"He gave me this darling little pin the last time he visited!\" Mion added, her eyes glinting as she reached into one sleeve of her kimono and produced one of her own. \"Now that I think about it, he mentioned he'd been doing some ... business with your group lately.\" Turning to Rika, she asked, \"What's he doing here, though?\""
    "Starting to catch what was going on, Rika remarked, \"Oh, I think he just wants a chance to relax and unwind in peace. A traditional festival surrounded by family and friends, visiting the vendors and stalls he remembers from his childhood ... that sort of thing!\""
    "Rika bit her tongue to keep from laughing aloud at the sudden sheen of sweat on the lead man's forehead, or the way the other men looked exceptionally nervous. \"You know,\" he said hurriedly, \"we're quite happy with our lots for the festival, come to think of it!\""
    "\"Really impressed at the reasonable rates,\" one of his followers echoed."
    "\"On reflection--\" He paused as there was a knock on the door, and surreptitiously pulled his pin off, sticking it in his pocket -- the others did the same, with varying degrees of subtlety. \"Well, thanks for your time, and we look forward to working together at the festival!\" he spat out in a rush. \"Your shrine can expect a donation to show our gratitude!\""
    "The door slid open, revealing Kyon, as Hanyuu had promised, and behind him.... Well, Rika recognized Haruhi, of course, and Mikuru and Tsuruya as well. There was Yuki, too, which made some of the other girls mysteries to her, though she had a guess.... There was another boy\girl pair in that group as well."
    "\"Uh ... hey, Auntie Rika, Auntie Mion,\" Kyon called, scratching the back of his head and offering an uncertain smile. \"I hope I'm not interrupting anything?\""
    "\"We were done!\" the representative for the group said, waving a hand quickly. \"We were just on our way out -- so thanks for your time!\""
    "Kyon looked mildly confused as the five men sped outside, barely pausing to put on their shoes before leaving. Shrugging, he spread his arms apologetically. \"Sorry about all of us just dropping in like this....\""
    "\"It's not a problem at all!\" Mion and Rika said together."
    "Grinning, Mion put her pin away and climbed to her feet. \"I admit, I'm pretty amazed your mother agreed to it, though!\" she remarked."
    "Rika, already knowing what was to come, smirked, one hand covering her mouth."
    "\"Uh.... Yeah, um, about that,\" Kyon mumbled, scratching the back of his head again."
    "Mion burst into laughter, Tsuruya chiming in with her. \"You snuck up to Hinamizawa behind her back?\" she exclaimed. \"Oh, that's perfect!\""
    "\"S...something like that,\" Kyon agreed, chuckling nervously. \"A...anyway, I know it's, uh, short notice and all, but--\""
    "\"Ah, that's too rich!\" Mion laughed again. \"Of course you and your friends can stay at my place. Now, introductions!\""
    "Coughing once and nodding, Kyon said, \"Ah, so, you've met Tsuruya-hime, but since we last talked, uh, our parents decided to arrange an engagement between us....\""
    "* * *"
    "While she was initially thrown off balance, and afraid of what might happen if she trusted Fujiwara.... Well, Kyon trusted his friends, and had mentioned that he was working with Fujiwara in the past. Despite the risk, when he'd met her on the way to her first day at her new school, Sasaki decided to trust him anyway."
    "It seemed silly, but she'd played along, even going so far as to put on the blindfold when he'd asked. He hadn't explained much, but the fact that Kuyou was there and appeared to approve assured her enough to keep going along."
    "Well, maybe that wasn't the most perfect trust, if she also needed it reinforced."
    "But other than a mild sense of disorientation and her ears popping, he hadn't led her very far while blindfolded. She suspected it was an elevator, but couldn't recall if any buildings in the city were actually tall enough to cause that much of a difference in air pressure."
    "Once she was able to take the blindfold off, Fujiwara had strangely left.... On the other hand, it was with the rest of Haruhi and Kyon's group -- including his younger sister -- so it should have been fine. Mostly, she was just trying to figure out where they were."
    "She'd been blindfolded for a handful of minutes at best. How had she been moved so far that she couldn't see any sign of Nishinomiya's familiar surrounding mountains? She tried to puzzle that out while Kyon led everyone up a hill and into a shrine."
    "Once there, he met a pair of his -- evidently -- aunts. Kyon made introductions for everyone, and Sasaki felt strangely unnerved under Rika's scrutinizing gaze. The woman had a demeanor as though she could look right through her.... What a strange thought!"
    "Something Kyon and his aunt Mion had mentioned struck her, though, and she asked, \"Are-- Are we staying here for a while, then? I'm worried about missing school, after all!\""
    "\"Other than what you must have missed getting here before midnight?\" Mion teased. \"Or do you have Saturday classes?\""
    "\"Well....\" Sasaki was fairly certain there was something about alternate Saturdays, but she wasn't sure if that were a standard thing, or just making up for other days earlier in the year the school might have shut down -- for snow or other issues. \"In any case, tomorrow is Tuesday, and we'll certainly have class then.\""
    "\"Ah ... so....\" Kyon hesitated for a minute, then shrugged, as though realizing that he was trying to postpone the inevitable, and said, \"We time traveled to get here. Well, Sasaki did -- the rest of us only traveled through space, really. And ... maybe Kuyou?\" The last he said uncertainly, looking to Kuyou curiously."
    "She smiled slightly, giving no other answer."
    "Sasaki sighed slightly. Why was Kyon being silly? Or were those code phrases?"
    "Mion blinked slowly. \"School must be really stressful for you lately,\" she remarked. \"Well, walk with me to my place, and I'll get you all situated. Hmm ... a few of you will have to share rooms, I think. It's a big house, but only so big!\""
    "\"We're time travelers now?\" Nonoko asked excitedly. \"I don't remember a Trope-tan episode where that happened! I'm going to be an even better magical girl!\""
    "\"The 'Trope-tan and the Age Before Radio' OVA?\" Kanae asked. \"She went back to the past in that, didn't she?\""
    "\"Oh, right,\" Nonoko realized, deflating."
    "\"That was a good special!\" Tsuruya exclaimed. \"Trope-tan discovering the ancient trope-stones from the masters was really neat! But she also goes to the future in the NeoTropeo III arc.\""
    "Rika and Mion closed up the room they were in and stepped outside. Sasaki frowned as she looked at the sky ... the sun was somehow lower. It couldn't be afternoon, though!"
    "The group of them, led by Kyon and Mion, marched out of the shrine, down the hill, and across a very scenic village. There was no place near Nishinomiya like that!"
    "\"How are you feeling?\" Haruhi asked, pulling away from the others and giving her a cautious smile."
    "\"I think I'm alright,\" Sasaki allowed. \"It's ... disconcerting. It couldn't be hypnosis, because that doesn't work unless the target is willing. So I'm trying to understand why I missed half of the day ... time we must have spent traveling here, though it somehow didn't feel like it!\""
    "\"What do you mean?\""
    "\"Logically speaking, if the time has somehow changed to afternoon, and we're somewhere that must be a hundred kilometers or more away from Nishinomiya, at a guess, it's because we spent that time traveling!\" Sasaki declared."
    "Haruhi nodded warily. \"A lot farther than that -- we're not that far from the Tsugaru Strait! But -- today is actually Friday, not Monday,\" she explained."
    "Sasaki frowned. \"My mother can't possibly be handling me vanishing for five days very well!\" she said. \"I can't help but be concerned about her reaction!\""
    "\"What time does your phone say it is?\" Haruhi posed."
    "That was a fair question, actually. Sasaki pulled her phone from her skirt pocket and checked the display. \"And my phone has evidently been hacked,\" she sighed. It did say the date was the same Friday that Sasaki had submitted her withdrawal forms from her old school, though it also kept regaining and losing signal."
    "\"The signal here is really intermittent,\" Haruhi agreed."
    "\"Hmm, this is a very elaborate prank,\" Sasaki mused, putting her phone away. \"But I can form several logical explanations. It could be next week, and I've somehow lost almost five days.\""
    "Haruhi nodded as the group reached the base of another hill and started climbing. \"How would you just forget those memories?\" she asked."
    "\"I don't like that explanation because all that really comes to mind is ... some form of subliminal control, or chemical influence,\" Sasaki admitted, shivering."
    "Starting slightly, the other girl shook her head quickly. \"Kuyou-chan -- would you allow that to happen to Sasaki?\""
    "The girl with long dark hair blinked once, very slowly, turning to look and pausing her walk. Sasaki and Haruhi stopped as well, though the rest of the procession went on. \"I would occult unwelcome influence,\" she replied after a thoughtful pause."
    "Sasaki felt her cheeks burn faintly; why was she so important that so many people were looking out for her?"
    "\"I certainly wouldn't let it happen,\" Kyon remarked, causing Sasaki to jump faintly in alarm. She realized he must have broken off from the rest of the group and come back to check on her, Haruhi, and Kuyou. \"I can't swear that Fujiwara wouldn't ... but somehow, that doesn't seem his style.\""
    "\"R...right,\" Sasaki said with a cough. \"I feel similarly. So ... the next logical possibility is that this is a very complex prank, for some reason.\""
    "Kyon stared blankly for a moment, and then his eyes widened as understanding dawned on him. \"Oh, I see,\" he said quietly. \"Trying to figure out when and where we are?\""
    "\"Yes ... but that theory still doesn't explain how it suddenly shifted from morning to evening,\" Sasaki explained. \"It's a bit troubling! I ... would like to ask that if this is a prank, someone explain it to me.\""
    "\"Well, do you have other logical explanations?\" Haruhi wondered, seemingly more confident once Kyon was nearby."
    "\"I might be dreaming?\" Sasaki posed."
    "Haruhi reached out a hand and pinched Sasaki's wrist hard enough to sting mildly, smirking as she did so."
    "\"Delusional, then! It's a scary thought -- I've fallen and hit my head, or been drugged after all. Or worse, maybe something terrible has happened to me, and I've created this fantasy realm to escape it!\" She shivered, not liking that thought."
    "Kyon's eyes widened again -- this time in alarm."
    "\"You can chase that rabbit all the way to the Descartes rabbit-hole,\" Haruhi countered. \"At some level, you have to trust that your senses aren't lying to you. I think we can discount the 'escapism' fantasy. Surely if it was purely a fantasy....\" She trailed off with a sidelong glance at Kyon, her face reddening very faintly. \"Well, there would be ... less people,\" she concluded."
    "Kyon looked momentarily puzzled, then shook his head. \"Well, I don't know what to say about this being a delusion, except that it feels real to me. Though, I guess you'd expect me to say that....\""
    "\"I just ... don't know what to make of this all,\" she said, shrugging. \"You did say on Saturday that I should be prepared for something, and to trust you ... and I don't believe I was delusional then.\""
    "Kyon rolled his eyes and looked irritated, setting down a bag to pull his phone from his pocket and muttering, \"Well thanks, future self.\" After poking at the device a bit, he stowed it and picked up the bag again. \"Anyway ... I don't want you to worry too much. You're in good company, right?\""
    "\"Well, I believe so,\" Sasaki agreed."
    "\"Then, don't sweat the details so much, and just trust your friends,\" Kyon encouraged her, giving a warm smile to go along with it."
    "\"That's ... rather difficult, though.\""
    "\"Hmm.... For the sake of argument, if time travel did exist, wouldn't it explain things?\" Kyon wondered."
    "\"If it existed, then certainly,\" Sasaki agreed after a moment of thought. \"But I thought that 'time travel' was a code-phrase for 'organized crime'!\""
    "Kyon blinked slowly, while Haruhi snorted and covered her mouth to try and quash her snickering."
    "Wincing, Sasaki said, \"...but now I'm guessing that was incorrect.\" Rallying, she shook her head and protested, \"It's too strange to think that we've somehow traveled through time!\""
    "\"Why?\" Kuyou wondered, cocking her head slightly to one side."
    "\"I.... Because time doesn't work like that?\""
    "\"Ah-- But how do you know that?\" Haruhi posed."
    "Sasaki shrugged, answering, \"Simple -- if time travelers did exist, then surely our present and past would have been flooded with visiting time travelers wanting to understand history better!\""
    "Haruhi's eyebrows rose. \"Are you so sure?\" she asked."
    "Kyon shook his head. \"Well, wouldn't that be a paradox, though?\" he countered. \"The past can't be altered, so time travelers would just be observers by nature.\""
    "\"So since we are here and able to change things, we can't be time travelers,\" Sasaki replied. She winced, realizing she was sliding back into that role where she deconstructed Kyon's arguments. \"We ... did discuss this back in middle school.\""
    "He shrugged, not seeming to mind. \"It's like this,\" he explained. \"You can make changes as long as they don't contradict your knowledge. So you can't do anything that contradicts your observations up through next Monday.\""
    "\"What's to prevent me from calling myself and warning me about the kidnapping attempt you prevented on Saturday?\" she countered."
    "\"What did happen last Saturday?\" Haruhi wondered."
    "Sasaki couldn't help but frown at her. \"You couldn't have forgotten Kyon driving after those thugs already -- you were there!\" she protested."
    "Haruhi's eyes widened. \"I-- I was?\" she wondered. \"Wait--\" Turning to Kyon, she demanded, \"When did you learn to drive, anyway!?\""
    "\"At a guess, Friday night,\" he said dryly, grumbling as he once again set the bags down to jab at his phone. \"Okay-- Let's say that hypothetically, we did time travel. It's fine as a thought exercise, right?\""
    "\"Certainly,\" Sasaki agreed. Hypotheticals were fine!"
    "\"So from that perspective, we can say ... our group teleported directly here on Friday, and you were sent back in time from next Monday,\" Kyon explained."
    "\"Ah, so ... in this scenario, you would not yet have saved me. Allowing for both time travel and teleportation ... which I suppose you'd need teleportation of some sort to avoid moving to some other point in Earth's orbit, wouldn't you?\""
    "Haruhi nodded thoughtfully, as well as Kyon. Kuyou had -- somewhere -- come up with a bag of cookies, and offered them around."
    "Well, that was considerate, and a welcome break. \"Thank you, Kuyou-chan,\" Sasaki allowed, smiling before trying a bite. They weren't bad at all! Sasaki suspected that she could really use the chocolate chips just then, too. \"Alright ... so in that scenario, you will have to teleport back to rescue me last Saturday.\""
    "\"Well, with free time travel, we can just go back to a moment after we left initially, and take care of it later,\" Kyon reasoned."
    "Sasaki couldn't help but chuckle. \"You would be so lazy,\" she accused, smiling."
    "Haruhi nodded again, snorting. \"You can say that again,\" she muttered."
    "\"Everyone's a critic,\" Kyon sighed. \"Alright -- in that case, if you don't trust me, what would make the point to you?\""
    "She was surprised at how much that stung -- her eyes growing moist. She wanted to protest that she did trust him ... except she realized that he was right. She was being terribly inflexible, wasn't she? It was true that Kyon had done enough amazing things.... Was it really totally beyond reason that he'd been able to do it with the aid of ... well ... time travel?"
    "Such a thing, even if it was scary, and upset her confidence that she understood the universe.... Well, it would be a tremendous advantage. Moreover, Kyon was arguing for -- and explaining -- a set of internally consistent rules. As inflexible as she'd been, she didn't really have any way to prove he was wrong yet!"
    "\"I'm sorry,\" she said contritely, trying to mask rubbing her eyes as massaging her forehead. \"Um-- I need to give you the benefit of the doubt, don't I? Very well....\""
    "She took a deep breath before opening her eyes, forcing a smile."
    "\"You can't pretend to believe something you don't, though, and it's a lot to ask for without any evidence,\" Kyon said with a shrug. \"Don't ... be too hard on yourself.\""
    "\"E...even so, I'll try to accept the hypothesis,\" she insisted. \"I can't ... make myself believe something, but I will try to look for evidence either way. It ... is closed-minded to simply refuse to give something credence when it hasn't actually been disproven.\""
    "Kuyou smiled. \"Harmony,\" she said in an almost musical tone."
    "\"Are you sure?\" Haruhi asked uncertainly."
    "\"Don't force yourself and overdo it, though,\" Kyon said, stooping to lift the bags again."
    "\"Well, it would be much nicer to think we have traveled in time, so I don't need to worry about explaining a long disappearance or missing classes to my mother,\" Sasaki joked bleakly."
    "If only that weren't so true!"
    "\"Alright!\" Haruhi declared, surprising her by taking her hand and giving a reassuring squeeze. \"That's the spirit, Sasaki-chan!\""
    "Somehow.... Somehow, as she felt her face warm up a little bit at the gesture, that really was a comforting thought."
    "\"Right-- Let's get up to Aunt Mion's place,\" Kyon said confidently, grinning. \"For now, we should treat this as a vacation! ...even if a somewhat odd and unexpected one.\""
    "\"Yes!\" Sasaki agreed in tandem with Haruhi, the pair of them exchanging a glance before they chuckled."
    "* * *"
    "The country air was a pleasant change from the city, even if it was thinner. Koizumi thought he could understand why Kyon's family might like to visit such remote relatives occasionally. The countryside was scenic, too-- The ancient style houses certainly had a soothing aesthetic."
    "While the rest of the group seemed to cluster together, Kyon was walking between Mion and Rika, with Tsuruya on the green-haired woman's other side. Kyouko walked at Koizumi's side, still holding his hand from when the group was in a circle -- something he was quite enjoying. While she'd been mislead by her former superiors, she really was a charming girl!"
    "Her quiet start and mild tug alerted him that something had changed, and he roused himself from his thoughts to see Kyon nodding at the woman in the blue sun-dress, breaking away from the group to fall back. Glancing back, he saw that Haruhi, Sasaki, and Kuyou were engaged in a quiet, tense-looking discussion, and the vice-commander was headed to join them."
    "He wondered if he should join them, but Kyouko gave a short shake of her head. \"Um-- I think Sasaki-san would be happier if we left them alone for now,\" she said quietly."
    "\"Alright,\" he agreed easily enough. He wasn't really certain what he could do there, anyway. Making sure he couldn't be overheard by the others, he asked, \"Is she ... handling this alright?\""
    "\"She's troubled,\" she admitted. \"Um, but ... it's hard to sort out. I don't know if I could explain it to her, but my connection to her works with the one here and the one in Nishinomiya ... and it's hard to tell which is which.\""
    "Koizumi frowned. There was a thought. If he still had his connection with Haruhi, would that likewise have been an issue? \"Are you alright?\""
    "\"Ah, I'm fine,\" she said, ducking her head as she smiled, and her face reddened. \"If we ... spend the weekend here and time travel back, does that mean that I'll end up feeling my connection with both instances of her twice?\""
    "\"I would guess so,\" he agreed, nodding. It did make logical sense."
    "\"I wish I could just tell her and she'd believe it,\" Kyouko sighed. \"And ... it's great that Kyon-san somehow can reassure her like he does, but .... it makes me a bit sad, too.\""
    "\"Sad?\" Koizumi wondered, looking at her curiously. \"Why?\""
    "\"She--\" Kyouko coughed, double-checking for anyone who might be listening in, and then dropping her voice anyway. \"She's hopelessly in love with him, you know ... but he's already engaged, and if he weren't, I don't doubt for a second that Suzumiya-san wouldn't grab him up.\""
    "Koizumi blinked slowly. Kyouko had mentioned Sasaki's attraction to Kyon before, and he'd noticed hints himself. Even so.... Kyon's 'arrangement' with the others -- would Haruhi be able to set aside her jealousy so easily? He did not envy Kyon trying to handle that situation!"
    "\"I think that Kyon will be able to convince her, if anyone can,\" Koizumi said, shrugging. \"I've learned that people are more capable of growth than we often give them credit for. Consider our own stances once being adversarial! Since you are linked to her, though, let me know if there's anything I can do to help.\""
    "\"Ah, um,\" Kyouko managed, blushing darkly. \"T...thanks, Itsuki-kun....\""
    "\"Any time, Kyouko-chan!\" he returned brightly."
    "\"And we're here!\" Mion declared loudly, turning around as the group finished their long march atop the hill. They had walked into what looked like quite an estate-- The esper had to admit, he was surprised at how extensive the home appeared. Large, too!"
    "\"Hehe,\" Rika giggled. \"Well, we appear to have lost Kyon-kun.... Mion-chan, should I round up all of his cousins? I'm sure they'd love to say hello~!\""
    "\"Mm, sure,\" Mion agreed. \"In the meantime, let's see about getting everyone rooms -- though I'm afraid everyone will need to share. Nono-chan, you'll be with Makoto-chan.\""
    "\"Ah-- I'll share a room with Sasaki-san,\" Kyouko volunteered quickly."
    "\"Hehe-- Haru-nyan and I can share a room,\" Tsuruya supplied."
    "Mikuru hesitantly chimed in, \"Um, if Kanae-chan doesn't mind....\""
    "\"Of course not, Mikuru-nee!\" the slider agreed happily."
    "\"Suou Kuyou,\" Nagato quietly contributed."
    "\"And ... I suppose that means I will be sharing a room with Kyon-kun?\" Koizumi hazarded."
    "\"Alright -- let me show you where you'll be staying, then -- this way!\""


