label Re_1:
    if music_need:
        $ renpy.music.set_volume(0.2, .5, channel="music")
    stop music fadeout 3
    scene black
    show title 057 at card_pos
    with slowfadein
    pause
    play sound "SE/Pageflip3.mp3"
    nvl clear
    
    "The Sumiyoshi-rengo, as a coalition of many smaller groups that had banded together, was many things. It was smaller than the oppressive Yamaguchi-gumi. It was more agile."
    "It was also suffering quite a bit in the region of Osaka, thanks to both the NPA and the Yamaguchi-gumi being more aggressive. This would have been enough of a problem if they hadn't lost face -- and manpower, equipment, weapons, territory, and so on -- so badly recently."
    "Backing down would make them look bad, and how could they expect to intimidate anyone if the rumors were true, and their operations were easily shut down by a high school student? Something was needed to recover from that loss, before they ended up hurting themselves worse -- or causing members in the lower and more distant ranks to wonder if they should defect to the Yamaguchi-gumi!"
    "Nakamura Ichiro knew that these were issues, but as it seemed a problem that couldn't be solved easily, it had been dumped on his head to sort out. So he had unenthusiastically taken all of the gathered reports, all the information the Sumiyoshi-rengo had on the supposed 'Kowa-Keigo Kyon.' Things should have been formally resolved with the Tsuruya-tachi when Fujiya Masao had formally apologized."
    "He'd even explained to his superiors that was the case!"
    "And somehow after that, one of his men had borrowed a weapon from another branch and assaulted the Kowa-Keigo. After that, the NPA had gotten involved, and the Sumiyoshi-rengo had lost billions of yen in potential profits."
    "Not for the first time, in the cramped office in the back of the pachinko parlor that served as his headquarters until he finished his assignment, he wondered why he had been set up. Certainly, they couldn't have expected him to succeed! If even the esteemed Hiko had failed -- been captured, set up by the Yamaguchi-gumi and then handed over to the police -- how was Nakamura Ichiro to accomplish anything?"
    "He didn't have a reputation nearly as solid as that man, after all. He was a careful, methodical thinker ... and probably one who was being punished for a lack of initiative by being given an impossible task. Sighing, he leaned back in his creaking chair, swirling a glass of water in one hand and wondering how he was going to get out of this one. Or if he would, really."
    "Someone had to be blamed for the Sumiyoshi-rengo's recent failings, and why wouldn't it be him, if everyone else were out of reach in the hands of the police? Well, blaming Kowa-Keigo Kyon was a possibility, but he was beyond the Sumiyoshi-rengo's ability to punish, it seemed."
    "Certainly, they couldn't afford to maintain aggression with the Yamaguchi-gumi much longer, could they?"
    "He looked up as he heard a chuckle, and one of the street guards opened the door without knocking, looking especially smug. \"Boss,\" the man said, nodding to the figures behind him. \"We got a guest who wants to talk to you.\""
    "Ichiro blinked slowly, taking in the smaller forms standing behind the guards. A pair of schoolgirls? One of them looked particularly average, except for her flat expression; the other was taller, grinning with only the faintest hint of nervousness in her expression. Something about her height and demeanor seemed familiar, somehow...."
    "\"...and?\" he prompted, looking back to the first guard."
    "\"Says she's Kowa-Keigo Kyon's fiancee,\" the second said. \"So -- do we want to have some 'fun' with them? We already promised to show them a good time!\""
    "Ichiro blinked slowly again. \"Certainly,\" he drawled. \"Drinks on the house -- a few hundred yen of free pachinko balls-- Whatever our guests would like!\" He very much doubted two random schoolgirls would show up, one of them making that claim. And if they did, if he failed laughably, letting himself be taken in by ordinary high-school students ... well, it was a bit of a long shot, but if he was so pathetic that it wasn't worth keeping in the current position long enough to punish him...."
    "On the other hand, if she was who she claimed, and that small girl was the one he'd heard of fighting at the Kowa-Keigo's side-- If that were the case, trying something as stupid as the guards were suggesting would end nightmarishly badly. That in mind, he eyed the guards, who looked at him with mild surprise. \"Er,\" the first one started. \"Boss--\""
    "\"Would you like something to drink, young ladies?\" Ichiro asked, cutting the guard off. \"Where are my manners? These times strain civility, don't they?\""
    "The heiress belted out a laugh-- Oh, right. He'd heard of that. She was probably the real thing!"
    "\"A real gentleman after all, eh?\" she chortled. \"Just water or tea is fine-- So nice to deal with someone polite!\""
    "\"We are a reasonable organization,\" he returned. \"Please, go ahead and have a seat -- make yourselves comfortable, if you're not interested in playing any games.\""
    "\"Uh,\" the second guard said slowly, looking befuddled. \"B...boss, if this is her, we're at war, aren't we? Shouldn't we--\""
    "\"Be reasonable when they come to parley, like the civilized ninkyo dantai that we are?\" Ichiro interrupted the not-very-bright guard, furrowing his brow. \"Now, now-- We're far too respectable to do something so foolish it would cause the Yamaguchi-gumi to need to come into Osaka, the heart of our territory, for revenge ... aren't we?\""
    "\"Uh-- Tea,\" the guard said quickly, nodding as he backed away. His companion looked puzzled, but likewise nodded and backed away, the pair of them letting the door shut."
    "Ichiro raised a hand to his face and sighed. \"My apologies for their behavior,\" he said, bowing his head. \"Good help is hard to keep from being thrown away in a pointless attack on your ... fiance.\" What a strange thing to say!"
    "The heiress chuckled again, seeming to relax as she surveyed the office. \"I'm glad you're being reasonable about this,\" she remarked."
    "\"Well,\" Ichiro said slowly, \"we seem to have a poor record when it comes to encounters between our forces.\""
    "The heiress shrugged, her grin widening the tiniest bit. \"Kyon-kun's pretty good,\" she agreed, before dropping comfortably into one of the two seats opposite Ichiro's desk. The other girl blinked, then quietly followed suit."
    "The guard returned hesitantly, bearing a tea service and still looking confused. After squeezing around the smaller girl's chair, he set it on the desk and retreated the way he came."
    "Ichiro poured tea into the waiting cups and then took one. \"Now -- since you came all this way ... what can I do for you?\""
    "\"I like you!\" the heiress cheered, grabbing a cup and hefting it, then pausing and glancing at her companion."
    "The shorter girl examined the cup, not reaching up to touch it, then gave a tiny nod."
    "\"You're being very helpful, so far!\" she continued, sipping at her cup politely before setting it back down. \"However.... As bad as things are, while Kyon-kun is pretty amazing, we really have other things to worry about. So -- I want to ask if it's possible to make this whole thing stop."
    "\"Quietly, of course! Hmm, so, it's difficult, but our kumichou is content to let things continue as they are. I don't want to go against him, but it's troublesome for Kyon-kun if things continue like this.\""
    "\"...troublesome?\" Ichiro wondered aloud. They were sending hit squads after the boy, and his fiancee was treating it like a nuisance?"
    "\"Mmm, yeah! They interfere with study time and dating!\" the heiress said, her expression becoming very solemn. \"He has to worry about his friends, too! Well ... I've probably given a lot away about how much we're not enjoying this little 'war', but it would be very good if we could solve things, somehow!\""
    "Ichiro nodded. Okay, sure. This whole thing was surreal. He was probably actually still dreaming. Or maybe the stress had gotten to him, and he'd snapped. \"I'm mostly here as a scapegoat, myself,\" he said, returning the girl's candor. \"You know, make someone take responsibility for all the failures we've had against you recently.\""
    "\"Well, you have ceremonial powers, undoubtedly,\" Tsuruya said, shaking her head. \"Something to justify your position. Right?\""
    "\"That, I do,\" he agreed. \"But I can't imagine I can do much to help here. If I were to try and make a public apology, or otherwise say, 'We need to dismiss this animosity,' then my superiors would undoubtedly denounce me-- Well, I expect they're planning that anyway.\" He sighed morosely, raising his tea and sipping at it -- and quickly putting it back down."
    "They really needed fresher tea!"
    "\"What if a third party were implicated as responsible for starting the animosity?\" the quiet girl posed."
    "Ichiro blinked, furrowing his brow. \"You mean ... something like the NPA trying to trick us into fighting one another?\" he asked."
    "She gave a tiny nod, while the heiress raised her eyebrows."
    "\"Well, that's a thought,\" he allowed, settling back into his chair. \"It might help a little, but there's still the question of us losing as much as we have so far. And the NPA may be a common enemy, but this isn't particularly their style.\""
    "\"So ... what do you know about 'Saki-nyan?\" Tsuruya wondered."
    "Ichiro took a moment to decipher the nickname, recalling, \"Ah-- Yes, let's see ... a girl who was supposed to be important to the Kowa-Keigo in some way? A lot of recent operations -- er, they were Hiko's, not mine -- were centered around trying to kidnap her and use her for leverage. I'm not really sure why she's so important, myself.\""
    "\"Hmm.... But where did the idea of going after her come from?\""
    "That was a good question. \"I'm trying to remember,\" Ichiro said slowly. \"Let's see ... we worked with an independent group -- a shady bunch which, well ... for us, is saying a bit. Anyway, the original deal was that they wanted our assistance capturing her. In exchange, they would help us use her as leverage against the Kowa-Keigo.\""
    "\"Well, she's my friend, and I'd like that to stop,\" the heiress remarked, mildly cross."
    "\"I'd like us to stop wasting men trying to capture her,\" he agreed quickly. \"But ... what's your plan, then? Blame those people who wanted her captured for causing this mess between us? Have a public meeting where I approach someone from your group and we trade information, implicating them?\""
    "\"Yes,\" the quiet girl agreed. \"You have been manipulated.\""
    "Rubbing his head, Ichiro pondered it. Some way or another, the Sumiyoshi-rengo had to pass the blame on. Since the idea of him being a scapegoat didn't particularly seem like his idea of a good time, blaming someone else.... Well, that had a certain appeal to it."
    "\"I don't have much information on those people from my own side of things,\" he said slowly. \"But if I approach you -- publicly -- for an information exchange, I suppose you could fill in those gaps?\""
    "\"I'll check with Mori-san, but I believe so!\""
    "Ichiro had no idea who that was. \"Well, that's all fine by me ... but is this really what happened?\" he wondered. \"I mean -- you're saying this is only a problem because of this other group we worked with?\""
    "\"Partially,\" the smaller girl said quietly. \"Another outside force acted to cause further problems to your group and promote aggression between you and our organization.\""
    "This was fascinating stuff! \"Who? And ... what did they want?\""
    "\"To cause him stress and see how he would react,\" the girl replied, blinking. \"And cause further interactions for the purposes of observation.\""
    "\"...you're telling me that all of these problems have the root cause of someone wanting to see how one high school aged boy reacts to stress?\" Ichiro asked, squinting. That somehow seemed a very far-fetched story."
    "\"Not just him, but his other girlfriends, too,\" the heiress clarified."
    "\"...right,\" Ichiro said slowly. 'Other' girlfriends? \"Thinking about things, as confusing as it is, I don't need to understand if I can point to someone else and let my superiors handle things. And if I can broker peace between us with no further animosity, that's great, too. So, how would you like to handle this, then?\""
    "\"Hmm, so, Saturday,\" the heiress said slowly."
    "The shorter girl shook her head a tiny distance."
    "\"Oh-- Right!\" the heiress exclaimed, miming a blow to her head. \"I forgots! Okay, then on Monday! On Monday, come to meet with my father at Tsuruya Towers, and say you want to resolve things peacefully, and you think that you've been tricked into fighting us. If you do that, even the kumichou would hear you out -- and with Kyon-kun and Mori-san there to fill in the blanks, that should suffice.\" She clapped her hands together, smiling. \"So! If that works, can you not try and kidnap Saki-nyan again? It's terribly upsetting when these things happen, you know!\""
    "\"I ... can only imagine,\" Ichiro agreed. \"I'll promise not to authorize any further actions against you personally, but ... well, being largely a figurehead, I can't guarantee there won't be other hot-headed upstarts who might try something before we make an official deal. I sincerely apologize for my lack of ability in that regard.\" Hell, he'd bow and scrape, if she asked! From where he sat, fighting was pointless-- The most that he could possibly accomplish by letting his men attack the pair was really upsetting the Kowa-Keigo."
    "Even if the boy didn't have superhuman abilities, Ichiro didn't have the stomach to take hostages -- not when it would bring the wrath of the entire Yamaguchi-gumi down on their heads. If they were at 'war', and the other group was largely indifferent, content to let Ichiro's allies throw themselves away on futile attacks...."
    "Shaking his head, he swore, \"The sooner we can get this resolved, the better. I'll do everything within my power to achieve peace between our groups.\""
    "\"Good!\" the heiress exclaimed, bouncing to her feet. \"Very good! I will see you on Monday!\""
    "Ichiro rose, nodding. \"Understood,\" he replied. \"And let me add, I'm very happy that the heiress of the Tsuruya-gumi prefers such tolerant and forgiving methods. I hope that our organizations can work together peaceably in years to come.\""
    "She chuckled, face reddening slightly. \"Aha, well, hopefully it will be a long times before my father retires,\" she replied. \"But yes, I would be happy for peace, too!\""
    "\"Let me walk you to the door, just in case any of my men get stupid ideas,\" Ichiro said belatedly, stepping around the desk and opening the office door. If this was a crazy dream ... it was worlds better than his reality!"
    "* * *"
    "Spending some time relaxing and chatting about inconsequential things with Haruhi and Kyon.... Sasaki felt a bit guilty about taking time away from Tsuruya, when she undoubtedly wanted to be with her fiance, too-- But ... even if it was a bit selfish, and she couldn't have more than she had -- just being friends...."
    "And of course, afterwards, everyone but Mikuru had left her place together, so Sasaki didn't even feel that out of place for being escorted home. After all, they were going as a group!"
    "\"Thank you for inviting me to spend time with you and the others, Suzumiya-san,\" she remembered to say belatedly. \"Dinner was amazing! Asahina-san must have spent considerable effort learning how to cook so well! I'm impressed with your contributions as well, Michikyuu-chan!\""
    "\"Aw, ah, heh,\" the younger girl managed from Haruhi's side, blushing faintly. \"T-thanks, Sasaki-san! Um, but you can call me Kanae-chan!\""
    "\"And while we're on that subject, Sasaki-chan, just 'Haruhi' is fine -- we're friends, after all, right?\" Haruhi added."
    "Sasaki giggled, slightly nervous. \"T...that's true. We'd have to be after that ... adventure we had together!\" she mused, rubbing the wrist that she'd had cuffed to Haruhi's. Now, that had been a strange experience! \"I think, other than Kyon, it's been a long time since I had a friend I could consider myself so close to.\""
    "\"Friends,\" Haruhi corrected, smirking. \"Now say it -- it's not that hard. 'Ha-ru-hi'. Kyon says it all the time! And I never gave him permission!\""
    "\"Didn't know I needed it,\" Kyon returned dryly, smirking."
    "Haruhi's confidence flashed to a brief look of surprise before she scowled. \"I'll let you get away with it,\" she agreed. \"But, come on, Sasaki-chan.\""
    "\"Alright, Haruhi-chan,\" Sasaki laughed."
    "\"Hey!\" Kanae cried, pouting. \"What about me?\""
    "\"And you, too, Kanae-chan!\" she agreed, nodding at the smaller girl, unable to resist grinning."
    "\"That's more like it,\" Haruhi said smugly, shooting Kyon a mild glare, not able to conceal her amusement completely. He casually laced his fingers behind his head and stared up at the sky, pretending not to notice."
    "Sasaki had to chuckle at the interplay, and Kanae giggled as well."
    "\"Ah, but more seriously,\" Haruhi said, her expression sobering. \"Hmm, it may not be simple, but I had a thought -- something that might make things a bit easier for us all.\""
    "\"What's that?\" Sasaki returned, curious. \"Considering what you all have done for me so far, I can't imagine it would be too much to ask for!\""
    "\"I'm glad you say that, because ... what do you think about changing schools and coming to Kitago with us?\" Haruhi posed, looking completely serious."
    "\"I--\" Sasaki cut herself off before she could protest. What were her arguments? She'd invested time and effort in her current school? Her mother would be confused and irritated? It could hurt her grades to transfer so close to the end of the quarter?"
    "All of that weighed against:"
    "She'd be taking classes with Haruhi? (And Kyon, of course!) And she'd asked to work with them, hadn't she? If that was her first 'task,' given what they'd been through for her...."
    "\"I'll get to work on that straight away,\" she declared, when Kyon and Kanae turned to join Haruhi's curious stare."
    "\"Really?\" Kyon wondered, surprised as he scratched his head. \"That's-- I mean ... just like that?\""
    "\"It certainly seems the most reasonable route!\" she returned, shaking her head. \"Certainly, it would be less trouble for you and Haruhi-chan! Well ... I hope it's not too much trouble, but once I'm transferred, can I ask for help studying?\""
    "\"Naturally,\" Haruhi answered, before Kyon could even respond. \"I study with Kyon regularly! No way am I going to let his grades slip to the point his mom makes him drop out of the club!\""
    "Then naturally, Sasaki vowed to herself, she would be part of that effort, too! That 'club' was very important to her already! As scary and upsetting as things had been lately, the promise of that instilled her with too much confidence and happiness to let herself feel down!"
    "They had reached the gate to her home at that point. Though she was eager to rush inside and share her news, she also wanted to give her sincere farewells to those who had gone through the trouble to walk here there!"
    "After waving goodbye to the trio, she opened the gate, feeling light on her feet. As soon as she had opened the door and kicked her shoes off, she immediately announced to her mother, \"I'm dropping out of my school tomorrow to transfer to Kitago!\""
    "\"But ... Sasaki-chan ... why?\" her mother asked, looking bewildered. \"Your current school is rated better!\""
    "\"Well, Kyon is there, and ... it came up that we should study together,\" she said pragmatically. \"Things at the current school haven't particularly been working out as well.\""
    "Her mother put her hands on her hips, brow furrowing in concern. \"This seems a bit sudden, Sasaki-chan -- don't you at least want to finish the quarter?\" she objected, shaking her head slowly. \"I do approve of that young man, but this is a bit much!\""
    "\"Well....\" She faltered, realizing that on the face of things, it was a bit sudden. And telling her mother something like, 'it's part of my initiation into Kyon's organized crime syndicate!' wasn't likely to make things go smoother. \"I've decided to aim for the same college as Kyon in any case.\""
    "\"But I think you might be able to do better than that! It's nice that you're willing to put that effort into staying at his side, but shouldn't he be working hard and transferring to join you?\""
    "She bit her tongue, her smile vanishing. \"My current school used to be an all-boys school until very recently,\" she reminded her mother. \"While it has a good reputation and I can generally fend for myself, I can also expect far less harassment at the new school.\""
    "Her mother's protest died in her throat. \"W...well.... I don't ... like that you're being bullied out of the school you worked so hard to get into, but ... I suppose I can't really stop you from making your own choices on high school....\""
    "Not, Sasaki thought, that it would slow her down much! Unfortunately, even if it wasn't really her classmates, there were legitimate issues of 'harassment'."
    "\"But, Sasaki-chan, why didn't you ever mention that other students were bothering you?\""
    "\"I just ... didn't want to say anything until I had something else arranged,\" Sasaki managed, sighing. \"But ... thanks to Kyon and his friends promising to help me study....\""
    "\"Already with a study group arranged?\" Sasaki's mother mused, raising one eyebrow, then sighing and shaking her head. \"Well, I suppose that's fine, then....\" Her expression suggested she wasn't convinced -- but wasn't going to put up more of a fight."
    "Sasaki unleashed a tiny breath she hadn't realized she was holding -- success!"
    "* * *"
    "Tsuruya was almost astounded at how successful she'd been; she had been afraid it would break down into a fight! Using Yuki like that, well ... it didn't sit well with her. She could only imagine how upset Kyon would be if she'd gone to handle it alone, especially if she made a mistake."
    "Or her father and the kumichou -- she doubted they'd be pleased with her, either. That whole affair had the chance of going wrong badly enough that if she escaped, it'd be grounds for another distinction!"
    "\"Yuki-nyan,\" she said, relaxing in the back seat of the taxi headed back to her mansion, \"I don't know that I can ever pay you back! I hope dinner will suffice for a start, but I am honestly in your debt!\""
    "\"It is nothing,\" the smaller girl replied almost without hesitation. Tsuruya snorted and grabbed Yuki in a hug -- she was so cute! Like a doll! \"I am his subordinate, and he is your subordinate. Therefore, I am your subordinate, too.\""
    "\"Well, technically,\" Tsuruya allowed. \"But in realities, I still owe you! So -- what would it take to pay you back?\""
    "\"I am ... glad to help,\" Yuki replied slowly, leaning into the hug. \"There is no need.\""
    "\"If that changes, you must lets me know!\" Tsuruya insisted, grinning. Releasing her from the embrace, she held Yuki at arm's length, looking her in the eye. \"Promise, okay?\""
    "After a moment, Yuki haltingly raised her right hand, pinky finger extended. \"Promise.\""
    "Tsuruya nodded firmly, and linked pinkies with Yuki. \"Where did you learn that?\" she giggled, as they shook on it, sealing the promise."
    "\"Asakura,\" Yuki answered quietly."
    "\"Hmm?\" Tsuruya mused, tilting her head to one side. \"So you talk with her a lot?\""
    "\"We communicate,\" Yuki agreed, as they let their hands drop. \"Her insight is ... different. Likewise, on some occasions she requires my input to understand things.\""
    "\"So you two work together and share what's going on? That's great! I bet Nono-chan would be happy to hear that! She adores the chibi, so if you're friends....\""
    "She trailed off, distracted by a thought as the taxi pulled to a stop before the driveway of Tsuruya's home. The driver turned around, but before he could even announce the fare, someone knocked on his window. Tsuruya started as he rolled his window down, and the voice of her fiance softly announced, \"I'll cover the charge.\""
    "\"...oops,\" she allowed, wincing."
    "* * *"
    "When she wasn't busy enjoying the benefits of persistent observation and improved communication, Kuyou was experimenting with the grand alchemy of cookie creation. Even if she retained records of the entire process from start to finish at the sub-atomic level, doing it again and watching the resultant interactions remained fascinating."
    "And when it was done, she could observe the effects of eating it on her biological form -- a new novelty, thanks to Mikuru and Kyon explaining how to chew things. It was a bit of a shift from what she was used to, just letting the mass fall in ... but at her current form's projected scale, that didn't work very well. So the 'chewing' and 'swallowing' thing made sense!"
    "The thing that puzzled her was the fact that she'd offered Kyon cookies, but hadn't gotten to participate in the entanglement she'd observed him engaging with others. Ryouko hadn't offered much insight into that, other than agreeing that Kuyou's logic for causing the effect seemed sound."
    "Then again, Kuyou's counterpart went off on a grumbling tangent about not really understanding why Kuyou wanted it to happen, until she explained that neither of them could determine if it was positive or negative without participating in it. Then the data entity grudgingly agreed that Kuyou had a point, and based on Nagato Yuki's reactions, they should try and observe more directly as well."
    "However, Ryouko's current physical size (and status as a projection) made her a poor candidate."
    "From within a shadow song where she had assembled the components required for 'baking' (that amazing transformative process!), Kuyou pondered. The shadow song was very small; it would take light only a half-dozen million rotations to cross."
    "Some day, she would have to show it to Mikuru, and ask her for guidance. The time-entangled being had explained that the important thing was the proportions. That worked well for Kuyou. Measure could be tricky; everything was at such a fine scale compared to what she was used to that it was very difficult to judge. If she only compared it to itself, then it was much simpler!"
    "Despite that, when she tried to merge simple masses of sugar, brown sugar, flour, and everything else she needed -- spheroids only as far across as light could travel in a mere thousand rotations -- it didn't work the way she'd hoped. That was a sufficient quantity, wasn't it? Except that strange effects that were much less pronounced when Mikuru did it became evident."
    "After mixing in the other components at the correct ratio, then arraying it in a layer the correct distance from the sun for the right amount of time, she ended up consistently getting something very cookie-like, but it somehow wasn't quite right, either."
    "She'd tried to ask Ryouko if she had any insight, but the entity had only returned, \"Sorry, we need to work on that communication gap; it looks like you're trying to work with a ball of sugar that's twenty times as far across as the Earth is wide.\""
    "Well, Mikuru had said that proportion was the key, so Kuyou still didn't understand why that would be problematic."
    "So she surveyed the masses as they collided and mixed at her direction -- and sure enough, at that scale it didn't work."
    "Scale was so hard without reference!"
    "Annoyed that it still wasn't working the way she wanted, she decided to meet with Ryouko to consult with her again. Being physically present often helped when communication wasn't working well. Thanks to Sasaki's observation, she needed to wait until a time when she wasn't present around Kyon; she was confident that an opportunity would arise soon enough."
    "In fact, from what Kuyou could observe via Ryouko, Kyon had just finished a session of the entanglement that Kuyou wanted to try with Suzumiya Haruhi and the Other that tried to harmonize -- Michikyuu Kanae."
    "She felt the all-too-familiar surge of clarity that accompanied the Chorus synchronizing her to the location in space at Kyon's side. He froze, preparing to leap from the rooftop he was standing on, looking at her curiously."
    "\"Chuou-san?\" He shook his head, one hand rubbing at the side of his face. \"Suou-san, I mean -- sorry about that. My sister's.... Well, I guess you know.\""
    "Kuyou tilted her head very slightly to one side, thinking. Kyon's sister -- 'Imouto-chan', or 'Magical Radiant Nonoko', according to Ryouko -- was interesting to observe and interact with. \"I like Imouto-chan,\" she said, feeling the words out."
    "Yes, that was accurate."
    "...it didn't hurt that she enjoyed Kuyou's cookies, even when Kuyou was doubtful they were as good as Mikuru's."
    "Kyon raised his eyebrows, then smiled. \"I can't really be surprised that my sister gets along with beings like you and Ryouko can I? I said at one point she reminded me of Haruhi enough I shouldn't worry about her so much ... and I guess that's true!\""
    "Kuyou nodded firmly in agreement."
    "\"Anyway,\" Kyon said, shaking his head abruptly. \"What can I do for you, Suou-san?\""
    "Hmmm.... She hadn't observed a plan to achieve her desired effect. She turned to Ryouko, perched on his shoulder. The blue-haired data entity blinked, then returned a data packet that she had marked as potentially interesting, but not enough to raise alarms."
    "After decoding it, Kuyou explained, \"Nagato Yuki and Tsuruya Haruka have engaged with potentially hostile forces.\""
    "Kyon twitched slightly, his gaze hardening. \"Really?\" he growled. \"Alright-- I'm confident in Yuki-chan, but if they're in danger--\""
    "\"No danger,\" Ryouko chirped. \"Yuki-chama decided to go with Churuya's plan to try and appeal to the Sumiyoshi-rengo's sense of reason! They're on their way back from Osaka right now!\""
    "Kyon froze, blinking repeatedly. \"I ... see,\" he said, frowning. Straightening up, he ran a hand through his hair and sighed. \"I trust both of them, but why didn't they tell me anything? And I don't really want to interfere ... but damn it, I can't not worry!\""
    "Kuyou nodded. \"Worry about important entities,\" she agreed."
    "\"Alright -- thanks for the warning, Suou-san. I should probably go meet with Tsuruya-hime once she gets back to her place so I can try and talk things over with her -- at least make sure she's okay.... Well, no, I'm sure she'll be fine thanks to Yuki-chan, but that's not the point.\""
    "Kuyou could help with that! She held a hand out, offering, \"Travel?\""
    "He hesitated a moment, then gave her a warm smile -- now that was an effect more interesting than even making cookies! What an amazing sensation! She wanted to feel it again, so when he took her hand and she warped space, she was extra mindful of the precautions that Yuki and Ryouko had explained human bodies needed against some of the subatomic particles that evidently weren't helpful to most physical forms at that scale."
    "It was worth it, though!"
    "* * *"
    "After Kuyou transitioned the pair of them to the roof of Tsuruya's house, he gave her another smile. He wasn't even feeling the teleports at all, anymore! \"Thanks, Suou-san -- and ... since Ryouko didn't say anything herself, thanks for letting me know about Tsuruya-hime and Yuki-chan doing this.\""
    "Though, teleporting to a rooftop might normally be a bit odd, if they were on another rooftop to begin with, it wasn't that strange."
    "He hopped to the ground, not surprised when Kuyou followed him. He was also not surprised when Shinobu appeared -- that woman was absolutely a ninja -- and gave him a polite greeting. \"Kyon-dono, I'm afraid that Haruka-chan isn't in at the moment. Is there something I can help you with?\""
    "\"Er, I know that Tsuruya-hime is out,\" Kyon sighed, scratching the back of his head anxiously. \"Ah ... I was hoping to wait until she got back from Osaka to talk to her.\""
    "\"Ah,\" Shinobu said quietly, looking mildly anxious. \"Haruka-chan does mean well,\" she said softly."
    "\"I know ... and this isn't about giving her grief,\" Kyon agreed, wondering -- not for the first time -- what exactly her relationship with Tsuruya was. \"I'm just worried, you know? We rely on one another, and while it's great she relies on Yuki-chan, too, I wish she'd let me know."
    "\"Or ... maybe I'm overstepping my bounds. I'm only a saiko-komon, aren't I?\" he realized with dismay. \"I suppose if my oyabun makes a decision and doesn't feel the need to tell me, I don't have a right to question it?\""
    "Shinobu hesitated, then raised a hand to her lower lip. \"As.... That is, as a saiko-komon, your subservience to her should be absolute,\" the maid agreed quietly. \"But does family not come first? As her fiance, you are correct, and it is I who have overstepped my bounds by suggesting otherwise.\" The woman gave a small sound -- an awkward half laugh. \"I must apologize, Kyon-dono -- you are handling this rightly.\""
    "\"E...er, thanks,\" he said, taken aback."
    "\"Is there anything that I can offer to help you, in the meantime?\" the woman asked, one hand dabbing at her eyes. Looking to Kuyou, she pursed her lips. \"Or perhaps you, young lady? You must have been in a kitchen recently -- you've gotten sugar and flour all over yourself.\""
    "Kyon realized he hadn't even noticed in the evening light ... that girl did seem to love her cookies. Now that she was standing beneath a light on the Tsuruya estate, the powder across her outfit, face, and hair was very obvious."
    "Kuyou's head tilted slightly to one side, a fine dusting of her baking ingredients sifting down from her hair."
    "Well, he supposed she'd needed to learn how to eat. Probably, forgetting to bathe frequently could be an issue, too. \"Do you want to take a bath, Suou-san?\" he asked. \"There's probably time for that, really.\""
    "She gave an abrupt nod and reached out, taking Ryouko from his shoulders and cradling her gently. The small data entity flailed her arms, then said, \"We'll be back!\""
    "If Shinobu thought it was strange that Kuyou appeared to be holding an invisible entity, she didn't say anything -- though Kyon was relatively certain she was just trying to keep Kuyou occupied and distracted for when he met Tsuruya."
    "Well, that was reasonable enough, all things considered, wasn't it? Though, it wasn't like he was going to yell at Tsuruya.... He wasn't angry, just ... worried. And it wasn't like she and the others didn't worry about him, after all, was it?"
    "He settled in to think about things and wait. He could see Shinobu really worried about Tsuruya ... well, she wasn't the only one!"
    "Still.... Feeling a bit restless, he bounded up to the rooftop of the archway leading into the compound, watching for her return. Only a few minutes passed before a taxi pulled up to the driveway, and he hopped to the ground, knocking on the driver-side window. He couldn't see them through the windows, but considering Shinobu's care at being discreet about things, quickly paid the driver anyway."
    "It was strange to have as much money as he did, considering how rarely he spent it, but he was getting paid regularly, after all! In short order, the driver was headed away, leaving him alone on the street with Tsuruya and Yuki."
    "The shorter girl looked up at him without flinching, while Tsuruya blushed and giggled nervously. \"Shall we go in?\" he asked, gesturing to the gate."
    "\"Ah, y...yeah,\" Tsuruya chuckled. \"Um, so.... What brings you by, Kyon-kun?\" she asked as they walked to the gate and it opened for her."
    "\"Well, I was worried about you,\" he said with a shrug. \"I mean ... that's really all there is to it.\""
    "\"I...it was nothing, though,\" Tsuruya said, shaking her head. \"No reason to worry about me!\""
    "\"Well, worrying doesn't have to be reasonable to happen,\" he countered. Looking around to see that no one was eavesdropping, he added, \"And anyway, Suou-san and Ryouko already told me what you were up to.\""
    "\"A...ah,\" Tsuruya sighed. \"Um....\""
    "\"I'm not ... here to give you a hard time or make you feel bad,\" he said quietly. \"I just ... care about you a lot. Both of you. Even though I know you're really good at what you do, and that Yuki-chan can keep you safe, I still worry. It doesn't matter that it's safe or not, and....\" He trailed off. \"Actually, how did it go?\""
    "\"Really well!\" Tsuruya said quickly, closing the gate behind them. \"Um -- so we should have a meeting on Monday and have everything put behind us!\""
    "\"That is great,\" he agreed. \"I ... wish I'd known it was that easy!\""
    "\"...you're really not mad?\" Tsuruya asked softly, looking anxious."
    "Now that was a surprise."
    "\"I ... just learned today that seeing Tsuruya-hime's face when she's not smiling makes me sad,\" Kyon mused, offering her a weak smile of his own. \"But, no. How could I be mad? Didn't I try and do the same thing? Well -- something really close, anywa--\" He was cut off as the taller girl suddenly crashed into him, her arms wrapping around him."
    "\"Sorry,\" she said again, her face pressed into his chest, fingers gripping his greatcoat. \"I just ... I had to do something about them upsetting my precious people! They were stressing you, and so....\""
    "\"I...it's fine,\" he said, still a bit surprised. \"I mean ... you did it because you cared, right? I guess-- I guess I'm just glad it came to light, though.... And next time, let us know -- we can have everyone ready to help out!\""
    "\"Sorries,\" Tsuruya sighed, still not moving to let go."
    "\"Really, Tsuruya-hime,\" he said gently, looking up beseechingly at Yuki, who was watching the pair of them -- did she look amused? \"...Yuki-chan ... did you know it was going to work out like this?\""
    "She shook her head gently. \"Investigating IDSE tampering,\" she said quietly."
    "That was unexpected! \"And you didn't tell us?\" he asked, frowning gently."
    "Unexpectedly, Yuki looked away, silently stepping forward and joining the hug with Tsuruya. \"...sorry,\" she said quietly."
    "Kyon sighed, shaking his head as Tsuruya giggled, shifting to one side and making room. \"Oopsie?\" she posed."
    "\"Well, let's just be careful and none of us do something like this again,\" he chuckled. \"And I suppose we should thank Suou-san for pointing this out, huh?\""
    "\"Yes,\" Yuki agreed, while Tsuruya nodded wordlessly, the pair finally releasing him from the hug."
    "\"Really ... that was the only thing I wanted to talk to you about,\" Kyon said, shrugging. \"But, I guess it is a lesson I have to be sure to apply to myself as well.\""
    "\"Will you join us for dinner?\" Tsuruya asked. \"I have to repays Yuki-nyan for her help, after all ... and maybe Suou-san, too?\""
    "\"I already ate, but I would be glad to keep you company,\" he offered. Shaking his head, he muttered, \"Shinobu-san decided Suou-san needed a bath after her last baking experiment. But she might want something to eat, too, right?\""
    "\"A bath?\" Tsuruya wondered. \"Hmm.... Except for the cosplay, I've never seen her in anything but a school outfit and a swimsuit. Does she have extra clothes?\""
    "Somehow, Kyon doubted it. \"Good question....\""
    "* * *"
    "Yuki didn't mind whatever Tsuruya's cook brought them. Mikuru was a better cook by far, but the food was still 'good' in any case. It was also with Kyon and Tsuruya, even if he only had tea. Kuyou's presence wasn't unwelcome either; Yuki had already told the other entity she regarded her as a friend, and that much was still true."
    "After all, even if Kuyou's interaction in this instance was slight compared to what had been done in the past, she'd helped the others out substantially."
    "The four of them were seated comfortably at the table, both Kyon and Tsuruya rather distracted by Kuyou. The other entity had washed -- incidentally washing Ryouko with her -- and then Tsuruya's maid had determined that her clothes needed to be washed."
    "Yuki or Kuyou herself could have handled that without troubling the woman, but Yuki found the results interesting -- if not quite as fascinating as Tsuruya and Kyon seemed to. After she'd come out of the bath, Shinobu had helped Kuyou dress in one of Tsuruya's many spare kimono, and spent some time putting a flower in her hair."
    "\"Kuyou-nyan, you look like a princess!\" Tsuruya finally judged, snapping a half-dozen pictures with her phone."
    "Yuki's references suggested that wasn't far off, and likely Ryouko (perched on Kuyou's shoulder) had suggested Kuyou sit the way she had, kneeling instead of crossing her legs beneath her."
    "\"It ... isn't a bad look,\" Kyon agreed hesitantly, offering a smile. \"Reminds me of her costume for Haruhi's flash-mob, actually.\""
    "Kuyou perked up slightly at that."
    "After enjoying the meal -- technically, the company, more than the food, but Yuki had read that both components made the meal -- Kyon checked his PDA and grimaced. \"Alright,\" he sighed. \"I should probably get home. As much as we talk about worrying people, I imagine my parents must be getting worried about me, too.\""
    "\"Help?\" Kuyou offered, drifting to her feet with a hopeful expression."
    "Tsuruya giggled again. \"I'm glad she's our friend -- even when she's not a chibi, she's adorable, isn't she?\" she remarked."
    "\"Er, I guess,\" Kyon allowed, nodding. \"Thanks for the offer, Suou-san -- that'd save me a bit of trouble.\""
    "\"I will go as well,\" Yuki decided. Friends did help friends after all, didn't they?"
    "\"Alright--\" Kyon broke off as he rose, and Tsuruya lunged at him -- not knocking him over, but occupying his attention before she kissed him. Kuyou watched with wide eyes, obviously keenly interested."
    "\"Um,\" he coughed, once Tsuruya finally broke the kiss. \"Uh-- Thanks....\""
    "\"No problems,\" she returned with a wink. \"Hmm, we need to tell Haru-nyan what really happened today, but.... Well! Tomorrow I will give you a rides to school, as we always do on Fridays!\" she determined, nodding."
    "\"Okay,\" Kyon said, a little unsteady as Yuki took one of his hands and nodded to Kuyou."
    "She took his other hand without hesitation, and Yuki observed that Kuyou took painstaking care to avoid lethal levels of radiation for the transition -- straight to the porch of Kyon's home."
    "He shook his head and gave Yuki a grateful smile. \"Thanks, Yuki-chan,\" he said earnestly, tugging gently to try and get her to release his hand."
    "Instead of letting go, she shifted closer and rose on her toes. He balked at first, then gave a resigned half-shrug and leaned down into the kiss. As always, she felt like her body might float away while she enjoyed the contact with him—"
    "Her internal chronometer momentarily desynchronized for the duration, and she finally released his hand. She wasn't good at expressing herself, but could tell he could read her attempt at a smile anyway. \"That ... was a little awkward with Suou-san still holding my other hand,\" he mumbled sheepishly."
    "She couldn't really understand why he'd think that-- Still, Kuyou had waited long enough, so moved to take Yuki's place. \"W-wait!\" he protested, eyes going wide. \"That-- Uh, I mean--\""
    "\"It is fine,\" Yuki said, mildly puzzled by his resistance. Hadn't Kuyou done enough to help them already?"
    "\"W...well,\" he hedged, still held by Kuyou's grip as he tugged at his collar with his free hand, trying not to look down at her upturned face. \"That.... Oh ... fine,\" he sighed, shaking his head and giving a weak smile."
    "He mumbled a familiar phrase before gazing down-- Yuki had some sympathy for the other entity when their lips contacted and her eyes become unfocused, drifting shut. The boy ended up putting an arm around her before she could collapse, struggling to process the sensation. From her revised perch on the dark-haired entity's head, next to the decorative flower Shinobu had picked out, Ryouko exclaimed in surprise, hopping toward Yuki."
    "Instead of letting her fall, Yuki caught the tiny form -- impervious or not. Haruhi had mentioned positive reinforcement anyway, and hadn't Ryouko been well-behaved lately?"
    "Kyon finally broke the kiss, holding Kuyou in his arms until she found the strength to stand, smiling widely. Well, that was an easy enough reaction to read. Not that she had to, given Ryouko's reaction to it across the link she shared with Kuyou."
    "\"There,\" Kyon declared, stepping away. \"That ... will probably need to be brought up with Haruhi, too,\" he said, his face slightly red. \"Oh ... boy.\" Then he muttered that phrase again and shook his head before saying, \"Good night, to both of you -- and ... thanks again, Suou-san, er.... I guess Kuyou-san, and Yuki-chan.\""
    "How interesting. The designation that wasn't her, shifted into that slightly different alignment, provoked a reaction not entirely unlike the mild physical entanglement from earlier! He took Ryouko from Yuki and stepped into the house, waving to the pair before he vanished."
    "Kuyou abruptly snapped to attention once he was out of sight, blinking once before turning an inquisitive gaze to Yuki and asking, \"Where is, 'the special hell'?\""
    "\"Unknown,\" Yuki admitted."
    "\"I must find it so that when he goes there, I can go with him.\""
    "Yuki nodded in agreement. \"We will search together,\" she promised."
    "* * *"
    "As much as Kyon was getting used to waking up with other people in his bed -- something strange to wake up to, after all -- he continued to be impressed at how often he could still be surprised."
    "Mikuru and Yuki? No complaints -- that was actually a really fun pair to wake up with!"
    "The time traveler cuddling Kuyou's 'chibi' form to her chest, and Yuki holding Ryouko the same way?"
    "That was not expected -- but he had to admit, even the once-murderous data-entity managed to look cute and harmless, just dozing in Yuki's arms."
    "Was it possible to overdose on cuteness? If it was, he'd probably already died of it."
    "Mikuru's eyes fluttered open slowly and she squirmed, pulling the small black-haired figure tight against her chest. Kuyou blinked silently, and Kyon had to suppress a moment of jealousy. \"Good morning, Kyon-kun,\" Mikuru said quietly, offering a shy smile."
    "\"Good morning, Mikuru,\" he replied. Looking over, he saw Yuki's eyes open as well, only Ryouko evidently asleep. \"Good morning to you, too, Yuki-chan, and, um, Kuyou-san.\""
    "\"Yes,\" Yuki agreed, as she usually did."
    "Kuyou nodded silently, and he heard the warning step of his sister's footsteps before they vanished -- Ryouko dropping a short distance to sprawl on the bed at his side as he sat up."
    "\"Waah,\" the small data entity noised, climbing upright."
    "Did she even need to sleep?"
    "\"Morning!\" his sister cheered, bursting into the room, looking around quickly."
    "Realizing she was trying to catch the other girls in his bed -- something she wasn't going to pull off -- he rolled his eyes. Well, she was causing the mornings to be a little less fun than they could be, but maybe that was actually for the best."
    "\"Morning, Imouto,\" he said, picking up Ryouko with one hand around her midsection. He was really getting too used to this.... \"Don't forget to give her back before I leave,\" he warned, handing her over."
    "\"Yay!\" Ryouko and his sister cheered in tandem."
    "\"Thank you, nii-san!\" the girl echoed, winking as she picked up the small form and dashed to her room."
    "At least his mother was busy with something downstairs this time. Sighing, he shook his head and tried to think of what he still had to do later that day."
    "* * *"
    "Considering the previous evening, being joined by Kyon and Tsuruya at the train station was a positive follow-up, in Haruhi's mind. Tsuruya was the one left out while they were spending time with Sasaki, after all."
    "\"Morning!\" she greeted brightly, waving at the engaged couple."
    "\"Good morning, Haruhi, Kanae-chan,\" Kyon answered, nodding."
    "Tsuruya echoed him, waving to the slider at Haruhi's side and grinning. \"You decided to walk from the station instead of taking the limo?\" Haruhi asked, once the group of them started the long march up the hill."
    "\"It's fun once in a while, but spending time with friends is better,\" the heiress answered, smiling. \"Did you want to ride in it?\""
    "Well, Haruhi didn't mind, but she'd done it enough with Tsuruya that she could understand the novelty wearing off."
    "\"Not a big deal,\" Haruhi shrugged, taking Kanae's hand in her own. \"I think you're right!\""
    "\"Hey-- Hey,\" a voice wheezed quietly, Taniguchi jogging up from behind the pair and clapping a hand on Kyon's shoulder."
    "Haruhi glanced at the boy. \"Not with Yanagimoto today?\" she wondered."
    "Taniguchi grimaced, falling into step at Kyon's side as he dropped his hand to his side and shook his head. \"Nah,\" he sighed. \"It's kinda complicated, but.... So, did you know that Sakanaka has a crush on....\" He trailed off. \"Actually, I probably shouldn't say. Girls don't like that to be spread around, do they?\""
    "Scowling, Haruhi nodded. \"I know who,\" she said warning. \"I just can't imagine how someone like you could figure it out!\""
    "\"Aw, come on, Suzumiya!\" he protested. \"I'm already in trouble with Yanagimoto-hime -- I don't need you giving me a hard time, too!\""
    "\"'Hime'? No, nevermind that-- Why are you telling me about this?\" Kyon wondered. \"I mean, good for Kunikida and all, but what makes you think I can help?\""
    "\"And how'd you piss Yanagimoto off?\" Haruhi demanded, irritated. Sakanaka and the gymnast were her friends, after all!"
    "\"We can help, Kyon,\" Taniguchi corrected, raising his arm and putting it across Kyon's shoulders, pulling the other boy close."
    "\"Really.\""
    "\"Absolutely,\" Taniguchi agreed, nodding vigorously. \"Now, the problem is, Kunikida's fallen for someone else, okay? Now, help me out, but who do you think it could be? What girls have you seen Kunikida around?\""
    "Haruhi blinked -- Taniguchi had figured that all out? She couldn't see Yanagimoto telling him, but from him, that was amazing!"
    "\"I don't even know what you're talking about,\" Kyon said in irritation, plucking the cloth of Taniguchi's sleeve and pulling the other boy's arm off him. \"Seriously -- this is your area of expertise, not mine. The only girl I've seen him pay attention to outside of, er, Asahina-san and Tsuruya-hime is a classmate from middle school.\""
    "Taniguchi made a sharp 'tsk' noise, snapping the fingers of the hand Kyon had just brushed off and scowling. \"Any chance he would run into her outside of school?\" he pressed."
    "Haruhi shook her head, interrupting him before Kyon could answer. \"Hey, what good does knowing this even do?\" she pressed."
    "\"Well, then I know how hot this girl is and which attributes to point out to Kunikida, of course,\" Taniguchi said, as though it were the most obvious thing in the world."
    "Kyon sighed, one hand rising to press into his face over his eyes. \"You are really something else, you know that, Taniguchi?\" he groaned."
    "Puffing with pride, the other boy grinned. \"You're right-- You're right! Okay, then-- I'll handle this, Kyon, you obviously need to focus on other stuff!\""
    "Haruhi shook her head in time with Kyon, the pair of them releasing a synchronized sigh as the boy with the slicked-back hair charged up the hill like a man possessed."
    "\"I don't even know where to begin,\" Kyon grumbled."
    "\"Hehe, you two are so alike,\" Kanae giggled, squeezing Haruhi's hand."
    "\"Too cute!\" Tsuruya agreed, laughing aloud."
    "\"It's probably best not to worry too much about him,\" Haruhi said doubtfully. \"Don't let it worry you, anyway, Kyon.\""
    "\"I'll try not to,\" Kyon agreed. \"Though, I guess it's nice to sometimes see craziness that doesn't have to involve us, you know?\""
    "Haruhi gave Kanae a sidelong glance as she giggled, undoubtedly recalling Haruhi meeting with Yanagimoto and Sakanaka. \"It does make for a change in perspective,\" she agreed, nodding reluctantly. \"Anyway, we should get to class sooner than later.\""
    "Shrugging, he added, \"It's not like any of our problems are going to solve themselves, after all.\""
    "* * *"
    "As steamed as Taniguchi had gotten her by being so insensitive, Yanagimoto had pointedly not even read his texts. Instead, she'd spent most of the afternoon on damage control with Sakanaka. She'd thought the singer was interested in Kunikida, but the entire affair, with Sakanaka barely even touching her parfait...."
    "She wasn't just a little sad -- she had it bad for Kunikida."
    "It was starting to get to the point where Yanagimoto wanted to hit the guy! What was so great about Sasaki anyway? Yanagimoto wasn't certain why, but had a grim certainty that she was way more trouble than she was worth -- that girl would cause whatever guy she ended up with worlds of difficulty, she just knew it!"
    "When she got to class, still ignoring Taniguchi, Sakanaka's desk was still empty. That was worrisome; was Sakanaka so broken up she was taking a day off from school? She was almost always one of the first to arrive!"
    "Yanagimoto wasn't sure she could blame her if she was skipping, though. She knew she could blame Taniguchi.... Well, maybe that wasn't entirely fair."
    "For his part, her boyfriend sat at his desk, mumbling to himself. What, practicing an apology?"
    "She wasn't sure how to feel about that yet. Maybe after she heard it...."
    "At least they were early enough that most of the other students hadn't arrived yet. Sakanaka could just be late."
    "Kyon and Haruhi were at their desks, chatting quietly about something. While she was a little curious, Sakanaka (and thus, Taniguchi) were her focus for the moment."
    "Kunikida, naturally, was the next student to walk in through the door. Taniguchi glanced over, then slapped both palms onto the surface of his desk, springing to his feet. \"You!\" he called out, pointing at the smaller boy menacingly."
    "Yanagimoto nearly fell out of her own seat, so couldn't particularly blame the shorter boy for flinching in alarm. \"W...what?\" he returned in confusion. \"Do you need to borrow my assignments that badly?\""
    "\"Well,\" Taniguchi said in a more reasonable tone, \"I actually didn't have a study partner last night-- But that isn't the point!\" His voice rose dramatically, and Yanagimoto found herself grudgingly realizing that he probably would be good at voice acting. \"Kunikida, are you a man, or aren't you?\""
    "Everyone in the class was staring at the pair by that point. Great voice or not -- what the hell did Taniguchi think he was doing?"
    "\"I-- What is this about?\" Kunikida asked, mildly indignant. Usually he was the peacemaker, so Yanagimoto could understand why he wasn't sure how to respond to ire directed at him."
    "\"You know, you're a smart guy,\" Taniguchi said, heaving an exaggerated sigh and shaking his head. \"I'm glad you let me copy your homework and all, but you're still a man, and that means it's your responsibility to be a good guy! If you make a nice girl cry because you're ignoring her and mooning over some girl you met in middle school -- well, if Kyon's too busy to give you a much-needed bright slap and wake you up, I'll do it myself!\""
    "Yanagimoto groaned, slapping the heel of one hand to her forehead. Kyon wore his normal unimpressed look -- though it somehow also managed to say, \"leave me out of this,\" without him uttering a word."
    "What the hell! This was grounds for a break-up-- Yanagimoto didn't mind Taniguchi being dramatic and boisterous, but this was just plain stupid!"
    "\"I-- What?\" Kunikida managed, now completely off balance."
    "\"Recover your pride! Stand up for honor, justice, and making cute girls smile!\" Taniguchi barked. \"And since you need a wingman and some practice -- let your aniki Taniguchi help you out! So -- forget about that girl, and if not for you, then for her....\" Taniguchi rose to his full height and pointed a finger directly at Kunikida's face, intoning, \"Try and get to know some other nice girl better! Like, maybe someone who can sing, and went to a party with you!\""
    "\"You-- What, you mean, Sakanaka-san?\" the smaller boy blurted out, eyes nearly crossing as he stared at Taniguchi's fingertip."
    "\"Yes!\" the taller boy declared, pulling his hand back and pumping one fist before moving instantly to the shorter boy's side, leaning close and stage-whispering, \"Also, listen, I'm in trouble with my girlfriend, so help me out, huh? I hope to get back on her good side with a double-date, alright?\""
    "Kunikida blinked several times."
    "\"Sakanaka-san?\" he repeated, seemingly stunned."
    "Yanagimoto felt her face warm up as nearly everyone else in the class gave slow nods of understanding. She wasn't sure if she wanted to kill Taniguchi for the embarrassment, or forgive him on account of covering for Sakanaka-- With that production, he had really made it seem like the entire ploy was to get back on her good side, not just to get Kunikida to pay attention to Sakanaka. Hadn't he made displays that were almost as embarrassing throughout the year already?"
    "\"...wish I'd recorded that,\" Haruhi muttered, shaking her head. \"How come you couldn't act that well when we were filming the movie, anyway?\""
    "\"My apologies to the idol star of that film, but she didn't motivate me the same way,\" Taniguchi said with a shrug, trying his best smile at Yanagimoto."
    "That nearly made Yanagimoto roll her eyes -- no way did she compare to Mikuru! Still...."
    "Flattery and problem solving?"
    "Smirking as though he were some kind of hero, Taniguchi sauntered over to his desk and dropped into his seat."
    "Realizing what her own role in the whole mess logically implied, she flatly said, \"In order for me to be seen with you in public, it would take at least two other people, right now!\""
    "Sakanaka stepped into the room just then, still looking downcast. Her mood must have improved slightly, because she seemed concerned at hearing that, offering Yanagimoto a sympathetic look, though her attention quickly went to Kunikida, still standing paralyzed halfway to his desk."
    "\"Uh--\" the smaller boy managed, faking a cough and shaking his head. \"Um, Sakanaka-san, i...it seems that our respective friends are having some ... difficulty.\""
    "\"Er.\" Sakanaka's answer was timid, using none of the range of her singer's voice. \"I-- Um, yes,\" she agreed belatedly, nervously glancing at the rest of the class. \"I...it's unfortunate.\" She hesitated on the verge of saying more, but bit her tongue, glancing across the other students again."
    "Even if it was less than half of the class, it was still a bit of an audience! Haruhi had even taken Kyon's phone and surreptitiously started to record!"
    "Almost flooring Yanagimoto, the shorter boy stepped closer to Sakanaka -- he was only slightly taller than the singer -- and said, somewhat haltingly. \"W...well, maybe we could help them? They ... are our friends, and I have to look out for, um, poor Taniguchi, after all!\""
    "\"Huh?\" she responded, bewildered. \"Er-- W...we should, I suppose, but, um, how?\""
    "Yanagimoto was tempted to break in, but Kunikida -- once Tanugichi had prodded him enough -- managed to maintain some momentum. \"T...that is, we could, um, go out ... with them, so they could make up-- Er, if you'd, uh, go out with me--\""
    "\"Yes!\" Sakanaka yelped, standing straight, eyes wide as she stared into Kunikida's face. \"That's-- Naturally! That would be wonderful, wouldn't it? Er, to help our friends?\""
    "\"R...right,\" Kunikida agreed awkwardly."
    "Yanagimoto heaved a sigh, glancing over to where Taniguchi appeared to be winding himself up again-- Okay, enough was enough! \"Right,\" she declared quickly, \"well, sorry we're so clumsy at this, and thanks for being our friends; let's meet up after class and go to the cafe together. Um, if Taniguchi-baka behaves, maybe we can form a study group!\""
    "\"Okay!\" Sakanaka agreed unhesitatingly."
    "\"I-- A study group ... could be nice,\" Kunikida agreed, still slightly off balance."
    "Yanagimoto couldn't blame him!"
    "Seemingly satisfied, Taniguchi settled back into his seat, even smirking despite the 'honorific'."
    "Kyon shook his head in disbelief before turning his attention to his homework; Haruhi just grinned, giving Yanagimoto a wink when no one else was looking."
    "Well ... maybe she'd underestimated Taniguchi, and the fastest way to Kunikida was just being blunt? She'd have to give him points for that!"


