label SB_2:
    "After spending almost the entire meeting establishing how the new regime concerning outside threats would work, Haruhi glanced at the clock and said, \"Well, there's only five minutes left, so I think we can call today's meeting to a close — we'll pick up and decide more activities tomorrow.\""
    "Kanae looked up from where she had been sketching a rough design of another outfit. Across from her, Mikuru was going over one of the earlier drafts, determining how much material it would take to complete the design, though she looked up, too. \"That's it for the day?\" she asked, stretching her arms over her head, giving an uncertain smile."
    "\"Well, you do have one last assignment,\" Haruhi reminded her, raising an eyebrow."
    "\"R...right, but I should change,\" Mikuru fretted, plucking at the hem of her maid outfit uncertainly."
    "\"Ah, well, that's our cue to wait outside,\" Kyon noted, glancing to Koizumi."
    "\"Of course,\" Koizumi agreed, rising with Kyon. He hesitated before moving towards the door, then added, \"Ah, Suzumiya-san — I forgot to mention this before, so for that I apologize. You are aware of Kimidori Emiri's status?\""
    "Haruhi crossed her arms over her chest and nodded. \"Yeah ... hmm, no one's assigned to take care of the student council, are they?\""
    "\"Considering the severity of circumstances, when Kyon-kun suggested that I look into it, I did,\" the esper explained. \"The student council president is as corruptible as you suspected, so with some help from Mori-san and her contacts, we've bribed him onto our side.\""
    "Mikuru blinked at that, unsure what to make of it, and turned to look at Tsuruya, wondering at her insight. The heiress looked thoughtful, but her attention was on Kyon, not Koizumi. Haruhi looked briefly astonished, then mildly annoyed. \"I had wanted to do something about that ... but then, if it was so trivial to deal with in the end, I suppose it's just as well that's taken care of.... So, he works for us, now?\""
    "\"Ah ... to present a convincing front, outwardly nothing will have changed. You've defeated him in all past altercations, after all. We don't know how aware Kimidori Emiri is of his situation, but in front of her, we would maintain that illusion.\""
    "\"As expected of Kyon's personal assistant,\" Haruhi judged, giving a slow nod. \"So, this means that we can skip class any time we want, and say it was student council business, couldn't we?\""
    "\"Er,\" Koizumi managed, his smile looking slightly worried. \"I ... suppose so.\""
    "\"Let's save that for emergencies, Haruhi,\" Kyon warned. \"But, yeah, excellent work on that, Koizumi.\""
    "Mikuru was able to see that the happiness is Koizumi's smile after that was very real. \"Well, we shouldn't delay Asahina-san any longer, should we?\" he asked."
    "Kyon agreed, and the two excused themselves. Kanae began tidying up her sketchbooks. Mikuru had been amused to realize that she and the slider had picked the exact same brand and size of book, so the shorter girl kept having to double-check the books to make sure they didn't get mixed up with.... With...."
    "As she removed her apron, she realized she had absolutely no idea of what Kanae drew, still. There was probably a better time to ask about that. She hurriedly changed while the others cleaned up after themselves. It was hard not to feel a little self-conscious ... even if Kyon and Koizumi were in the hall, out of sight, there were still four other people to watch her change."
    "At least she got to change herself, though — for whatever reason, Haruhi had stopped trying to force her into costumes, instead turning that attention to Kanae. Mikuru didn't like the idea of hiding behind the smaller girl for protection from Haruhi, but ... Kanae really didn't seem to mind. She had finished putting on her blouse, needing only to retie her ribbon when she wondered why she felt a little bad about that."
    "Was she somehow feeling jealous of the slider? That didn't make sense...."
    "\"Mikuru-chan~!\" Tsuruya caroled, plucking the ribbon from her fingers while she was distracted."
    "The taller girl executed a flawless pirouette, the ribbon held directly over her head — and twirling just out of Mikuru's reach — before stopping, bringing her arms down and looping the chord into place. Humming, and with her eternally present smile, Tsuruya expertly re-knotted the ribbon, then placed her hands on her hips, beaming an even brighter grin at her. \"Where's your head?\" she teased."
    "\"Ah, um,\" Mikuru managed, her face coloring as she remembered earlier that same morning — when Haruhi had done almost the exact same thing for Kyon. Then again ... Haruhi {i}had{/i} commanded her to order Kyon on a date. She tried to explain herself, but her nervousness turned the statement into a question as she squeaked out, \"I n...need to talk to Kyon-kun?\""
    "\"Right,\" Haruhi agreed, nodding. \"I'll send him in, then.\" She strode to the door and opened it, heading out into the hallway. Tsuruya gave the time traveler a wink, then led Kanae out of the room. Koizumi and Kyon were discussing an upcoming project before the door clicked closed, and Mikuru felt a surprising, gentle tug on the sleeve of her uniform."
    "\"Eh?\" She turned and blinked in surprise, seeing Yuki standing beside her, fingertips just grasping the fabric of her uniform blouse. \"Um ... is something wrong, Yuki-chan?\""
    "Yuki shook her head very slightly, then held up her phone, displaying a video on the screen."
    "Mikuru felt a tiny gasp escape her at the amazing scene on the device. The upper horizon was a fleecy white mass, lit from behind by the brilliant blaze of the sun, and from it a billion sparkling prisms descended in an endless curtain. The light through them was refracted and scattered in all directions. From that vantage, the view turned away from the sun, revealing the dark sea below, and most spectacularly, almost the entire circle of a rainbow."
    "\"That's very pretty!\" Mikuru said. Then she hesitated and thought about it, looking back as it looped around and replayed. \"U...um.... Am I missing something?\""
    "The door clicked open again as Kyon stepped in, looking over his shoulder at Haruhi as he walked through the door. He glanced at the phone and blinked at the video Yuki was playing. \"Oh,\" he said in recognition, nodding."
    "\"W...what is this?\" Mikuru asked, anxious that she might not have realized something important. When she looked back to Yuki, though, she was just watching the images repeat, though she seemed to be smiling very softly."
    "\"That's from when we were falling earlier,\" Kyon explained. After a moment, he added, \"I didn't really enjoy the view as much as I probably could have, at the time.\""
    "\"I think this is ... pretty, too,\" Yuki said after a moment."
    "Mikuru glanced to Kyon, but realized she didn't need to — he understood the significance of that from Yuki, and offered the small girl a warm, friendly smile. \"Well, I think I'll agree with you,\" he said."
    "\"Um! Now that I know it's from when you were falling, it's a bit scary — but still very pretty, Yuki-chan!\" Mikuru chimed in, somewhat belatedly."
    "Yuki seemed strangely content with that and nodded before picking up her bag and walking to wait outside with the others."
    "\"What is it I can do for you, Asahina-san?\" Kyon asked, some of his smile fading, but still trying to keep a cheerful demeanor."
    "\"Ah ... Suzumiya-san wanted me to relay an order to you for some reason,\" she said uncertainly. \"Um.... I know she's been a bit upset lately, but it's not worse than that ... so I think she wanted to spend time with you tomorrow. Er — I'm supposed to tell you, that is ... that you're supposed to get tickets for three for the movie you took Kanae-chan to?\""
    "\"Oh, okay,\" he agreed uncertainly. \"If that's what I'm supposed to do. Um ... for you, Yuki-chan, and Haruhi?\" he guessed."
    "\"Ah, no, yourself, Suzumiya-san, and, um ... me.\""
    "Kyon looked, if anything, more perplexed. \"Well, okay. Huh.\" He looked away for a moment, then turned back, asking, \"Um ... is there anything I should know from the future?\""
    "She really didn't like the idea of questioning her superiors; answers were seldom forthcoming. What else could she do, though?"
    "\"Um,\" she murmured, checking her references. Unsurprisingly, her superiors had nothing to offer at the moment. \"I d...don't think so,\" she said. After a heartbeat of hesitation, she quickly added, \"But, um, personally, Kyon-kun? I think that whatever happens, you'll be okay! I have faith that Kyon-kun will solve this difficulty, just like the others....\""
    "She gave him what she hoped was a comforting smile. If it weren't for the fact that it was the clubroom, or maybe if she were braver, she might try and give him a hug right there. Maybe even.... She felt her face turn uncomfortably warm at just the thought of trying to steal a kiss."
    "He gave her a confused but happy seeming smile in return. \"T...thanks, Asahina-san,\" he said, just before the door exploded open, and Haruhi stomped one foot into the room impatiently."
    "\"Come on!\" the brigade chief called, hands balled into fists and placed at her hips. \"What's taking so long? I still have to lock up, you know.\""
    "Recovering her breath from what should really have been an expected entrance into the room, Mikuru offered a nervous giggle. \"N...nothing,\" she assured Haruhi, shaking her head. \"I had just finished telling Kyon-kun your orders.\""
    "Haruhi nodded, not meeting Kyon's gaze as he and Mikuru picked up their bags and joined Haruhi and Tsuruya in the hall."
    "\"Okay!\" Tsuruya cheered, grabbing Haruhi by one arm the second she finished locking the door. \"I got us reservations at a really nice places for dinner, Haru-nyan~!\""
    "\"Ah!\" Haruhi yelped, pulled off balance and needing to hurry to keep up with Tsuruya. Her bag flipped up into the air overhead, and Kyon snagged it before it could fall to the ground. \"T...Tsu-chan!\""
    "\"We've got to hurry and changes — I got new clothes for all of us!\""
    "\"B...but—\""
    "Giggling, Mikuru watched the trio walk down the hall. She was a bit envious that she wasn't getting to spend time with Kyon, like they were — and she really wondered what they were going to talk about.... All she had to look forward to was an uncomfortable period of time to think about the fact that she felt like ... something was missing. Something about her, Haruhi, and Kanae...."
    "...and for some reason she couldn't quite understand, the idea of going on a date with Kyon tomorrow was even more exciting than usual. Maybe because—"
    "She started and shook her head quickly. She needed a distraction, she resolved. Yuki was going to be alone, and Kanae could always use study help — especially with history. She quickly trotted towards the school exit. Now, if she could just catch the pair of them quickly enough...."
    "* * *"
    "Haruhi fought down a combination of annoyance and gratitude at the fact that Tsuruya seemed to have gone on ahead and made plans concerning their discussion with Kyon. It really bothered her that she'd been letting her inner tsundere take control, though, so she let Tsuruya keep charge for the moment."
    "After going to her place, Tsuruya hauled Haruhi into her bedroom and then the brigade chief thought she was starting to get a strange idea of what it might have been like for Mikuru, when she had been forcibly redressed. But then, after Tsuruya had redressed the pair of them to her satisfaction, Haruhi realized that the robes she was wearing weren't just another of the heiress's innumerable collection."
    "The new kimono was actually elaborate enough that she realized she probably couldn't have gotten it on nearly as quickly without Tsuruya's help anyway, considering the extra layers. \"This is really traditional, isn't it?\" Hers was a cool blue color, and had a series of painstakingly rendered crashing waves, which appeared to swirl and foam, crashing about her waist and spilling down her sleeves. Tsuruya's own coloring scheme was more of a greenish blue, suggesting a pool. Reeds ran up to her sash, and across her back, a trio of cranes winged away."
    "\"Yep!\" Tsuruya beamed. \"I didn't think a junihitoe would be as much fun to wear — but these are nice!\""
    "\"They're the nicest I've ever seen,\" Haruhi returned honestly. She suspected that it would be a challenge for even Mikuru to make ... or at least, it would take the older girl quite some time."
    "The heiress's grin widened, showing her fang. \"Then I think you'll like where we're going tonight!\" she said cheerfully, leading Haruhi to the hall, where Kyon had either already changed into a man's formal kimono from the same era — or just scanned it and activated his disguise."
    "She couldn't resist, and prodded him a few times to verify that he was actually wearing the outfit, not his disguise."
    "\"What?\" he asked, looking down at where she was poking him."
    "\"Just checking,\" she returned, trying to keep the defensiveness from her voice. Tsundere tendencies with Tsuruya being an eternally cheerful yamato nadeshiko — no, no, that wouldn't do. With some effort, she made herself say, \"Looks good on you.\""
    "He seemed surprised at that, looking down at himself. His outfit was much simpler — straighter lines, shorter sleeves, and a single blueish green color, midway between the hues of their own robes. Probably by Tsuruya's design, she realized in retrospect. The outfit {i}was{/i} very nice, though — Kyon needed only an elaborate folding fan and a malicious grin to appear dressed for ancient court intrigue."
    "\"W...what a choice of words,\" he said with a chuckle, his cheeks reddening very slightly as he looked up at the ceiling to avoid meeting her eyes. \"U...um, so this is what you like, then?\""
    "\"Huh? Sure, I guess,\" Haruhi answered, wondering what he was thinking of. Before she could come to a conclusion, Tsuruya burst into the small space between them, taking each by an arm. \"Onward!\" she insisted, hauling the pair forward without much resistance."
    "Shortly, they were piled into the back of Tsuruya's limo, with Kyon between them. Haruhi glanced over, seeing Tsuruya leaning against Kyon as she explained, \"Kyon-kun has been to this place before!\""
    "\"Ah,\" Kyon remarked sagely, nodding. \"That place.\""
    "\"Yeah!\" she agreed. Leaning even closer, pressing into Kyon — though he was very unobtrusively trying to edge away — towards Haruhi — she added, \"This is where we had our omiai!\""
    "The combination of factors — Tsuruya pressing close to Kyon, the reminder of their engagement, and the way Kyon seemed nervous — as though afraid of Haruhi's temper.... \"Tsu-chan!\" Haruhi protested, before biting her tongue."
    "Okay. Tsuruya wasn't just playing around, but the girl was demonstrating a very important point. She took a breath, trying to steady herself, and looked out the window, leaning towards Kyon, just like Tsuruya. Yeah ... this was starting to get a bit {i}too{/i} much like a romantic comedy anime. It might be amusing, but it wasn't helping her move towards the eventual goal she was looking for. And judging by Kyon's demeanor, since he didn't know all of the details — he didn't think it was as pleasant as it should be."
    "\"Eh?\" Tsuruya noised, turning a curious gaze to Haruhi. \"What is it, Haru- nyan?\""
    "Naturally, the green-haired girl seemed to be well aware of all these things.... \"Um, n...nothing, just....\" After a small sigh, she asked, \"What's the rest of the plan for the evening, anyway?\""
    "\"We'll have dinners, and then I'm going to show you and Kyon a movies — it's called 'Five Centimeters Per Second'!\" Tsuruya cheered. \"It's got a mega thought-provoking storyline!\""
    "Haruhi fought back the urge to choke. \"I've seen that years ago,\" she grumbled bleakly. \"Why do you want to make us watch one of the most depressing anime ever?\""
    "\"What's it about?\" Kyon asked, finally seeming able to contribute to the conversation."
    "\"Two people who were meant to be together, but didn't get together, because they were bad about communicating,\" she began, before the power of speech left her completely, as she considered what Tsuruya was implying. Evidently 'subtlety' was out the window at this point."
    "\"Aw, you spoiled it for Kyon-kun!\" Tsuruya complained, though Haruhi could hear her satisfied smile without looking. \"Well, anyway, it's not all {i}that{/i} bad.... I thought the ending was somewhat uplifting....\""
    "\"They moved on,\" Haruhi agreed, \"but they had the same dream— They were {i}meant{/i} to be together!\""
    "\"Yeah,\" Tsuruya sighed. \"It's too bad they weren't, huh?\""
    "Haruhi resisted the impulse to growl, but her inner urges demanded representation. She grabbed Kyon's nearer arm, hugging it to herself tightly. \"That's just a movie, anyway,\" she mumbled."
    "\"E...er,\" Kyon choked out. Tsuruya merely made a pleased noise and when Haruhi finally turned to try and see why — she found herself momentarily blinded by the flash of the other girl's camera."
    "\"Gah,\" she and Kyon managed simultaneously, before Tsuruya laughed."
    "\"I was just teasings,\" the heiress added, as the vehicle pulled to a halt. \"We're really going to watch 'Kashimashi Girl Meets Girl'.\""
    "Haruhi was vaguely familiar with that series, thanks to her favorite website, and frowned. \"That has something to do with aliens?\" Haruhi asked."
    "\"And more! But let's just worry about dinner for now, hmm?\""
    "Haruhi nodded her agreement, then blinked, actually taking in her surroundings. She knew that Tsuruya's family had money, but she was surprised to see Tsuruya gesturing her and Kyon to follow her along the carpet from the parking lot, and through the gardens surrounding the restaurant. \"This is the most exclusive restaurant in Nishinomiya!\" Haruhi hissed to Kyon quietly. \"You know that, right?\""
    "Kyon nodded absently. \"Tsuruya-kun's father owns it, probably,\" he remarked."
    "\"That's right!\" the heiress agreed. \"Come on!\""
    "This was annoying, Haruhi thought, trying to resist being overwhelmed. Tsuruya was doing nothing but leaving her bewildered and confused, while the heiress and Kyon seemed to know what was really going on. She made herself admit that she was fairly sure that things were going to turn out alright, confusion or not...."
    "Was her point maybe, that she and the other girls had put Kyon into such a situation?"
    "If so, Haruhi was absolutely feeling sympathetic to him, now!"
    "Soon enough, they'd gotten into the restaurant — which seemed empty, outside of themselves and the staff — and were seated at a traditional table. Kyon was sitting nearest the large open window, his back to the candle-filled pond. Haruhi tried not to stare at the image of a dimly illuminated Kyon in classic attire, framed by floating points of light on the water behind him."
    "Tsuruya kept stealing glances at him too, and seemed especially pleased when a very familiar looking woman in a simple but elegant kimono drew near the table to bring them water and tea, then take a picture of each of them. Once she withdrew out of earshot, Tsuruya grinned, waving a hand as though to downplay the severity of their surroundings. \"Relax!\" she cheered. \"Enjoy! This is meant to be fun, right?\""
    "\"Last time I was so nervous I didn't even taste anything,\" Kyon admitted, shaking his head."
    "Looking somewhat surprised, Tsuruya chuckled and shook her head as the first course approached. \"The same for me!\" she agreed."
    "\"Ah! So that's why you're really here again!\" Haruhi realized aloud."
    "Tsuruya's cheeks reddened and she giggled in embarrassment, scratching the back of her head. \"Caught!\" she admitted."
    "* * *"
    "After returning from the delicious meal — Tsuruya enjoyed it almost as much as Mikuru's cooking — she contentedly collapsed onto the sofa before the television. Once she'd made sure Kyon was next to her, at any rate. She admitted to herself that she might have gone a {i}tad{/i} overboard teasing Haruhi. Still, it had mostly put her and Kyon on equal footing."
    "Surely this would let the energetic brigade chief direct some of her unwarranted annoyance away from Kyon.... And Haruhi was smart enough to realize that the redirection was intended more as a reminder than anything else."
    "Haruhi sat next to Kyon, not quite touching him, but looking like she was strongly thinking about it. Kyon was staring steadily at the screen, which hadn't even been turned on yet. \"Alright,\" she said, abruptly turning to face Kyon directly. \"Um, so ... I.... Well, {i}we{/i}, actually.... We were doing something behind your back without properly explaining things to you, and we really shouldn't have.\""
    "He turned to look at her warily. \"What's that?\" he asked. \"I've kind of given up on trying to figure things out on my own, at this point.\""
    "\"This is supposed to actually be somethings really good,\" Tsuruya assured him, raising one hand to rest on his shoulder, pulling her knees up onto the sofa and shifting to face Kyon. \"But ... we didn't really communicates this very well, did we?\""
    "\"Communicate what?\" Kyon asked anxiously. \"I just.... I don't want to hurt anyone — or to be hurt, especially among my friends. I kind of ... get the idea I've been doing a really bad job of that lately.\" He shook his head, staring at his hands in consternation. \"I.... I know that Tsuruya-kun said it was okay, but—\" He cut off with that and sighed, raising the arm at Haruhi's side and rubbing at his forehead. \"I just really don't want to mess things up.\""
    "\"You haven't done anything wrong,\" Haruhi said, her voice quavering a tiny bit as she pushed his arm down and assumed a pose identical to Tsuruya's. \"So, t...the plan is kind of strange, but if you haven't figured it out, w...we kind of want to, um ... share you.\""
    "Kyon turned to look at her, and his mouth fell open a short distance."
    "\"So, you can't do anything wrong on that counts,\" Tsuruya elaborated. \"Some details aren't figured out yet ... like how everything will eventually settle down, but hopefully, somedays ... everyone can be happy, together!\""
    "\"Uh....\""
    "\"Does that make any sense?\" Haruhi ventured uncertainly."
    "\"Actually, no.\""
    "Haruhi blinked, taken aback. \"I...it's really straightforward,\" she said, irritation overcoming her nervousness. \"You, us, Mikuru-chan, Yuki-chan, and Kanae-chan all ... together.\""
    "\"Right — so that's why it's okay to be more than friends with us,\" Tsuruya elaborated. \"We just didn't explains it to you like we should have, so things got confusing!\""
    "\"Even if I sometimes do act a bit jealous,\" Haruhi added quietly."
    "\"So,\" Kyon said very slowly, looking between the two girls, \"you're saying that ... you want all five of you to date me, at the same time, and that's okay?\""
    "Her face turning red, Haruhi noted, \"Even if you haven't noticed, somehow, you've {i}been{/i} dating the five of us!\""
    "\"I ... have been dating five girls,\" Kyon repeated, looking flabbergasted, as though unwilling to confront what he'd just said."
    "\"Yep!\" Tsuruya agreed. \"Um ... our engagement wasn't somethings we planned, though — that just kinds of ended up happening.\""
    "\"I.... Why— How— What?\""
    "\"I...is it so hard to understand?\" Haruhi grumbled prodding him gently in the ribs. \"I mean ... I've been trying to build a foundation for this relationship for a while, so....\""
    "\"No, wait,\" Kyon said suddenly, blinking. \"Okay — I get it. I get it.\" He shook his head and broke away from both of the girls, hopping off the sofa and turning to face them. \"Um ... now I get why you told me that, at that time, Haruhi....\""
    "\"What time?\" Haruhi asked, anxious that Kyon had moved away from her. Tsuruya was worried about that, too — were they not managing to calm him down?"
    "Turning to face Haruhi, Kyon took a deep breath and said, \"Haruhi ... I'm really sorry that things got like this — but there's something you need to know.\""
    "\"W...what is it?\" she demanded. \"Spit it out already!\""
    "\"Haruhi,\" Kyon began, standing up straight and staring at the girl solemnly, \"I am—\" And then {i}something{/i} Tsuruya couldn't quite make out happened, and there was no more sign of the pair."
    "\"K...Kyon-kun?\" she asked, blinking at the suddenly empty room. \"Haru-nyan?\""
    "* * *"
    "Though she had no idea why Tsuruya had decided to give her the strange instruction she had gotten, Kanae couldn't help but spend all of the time she wasn't around her sempai daydreaming about the upcoming evening. Well, after training, once he was in bed, and she could join him...."
    "She shook her head, trying to dismiss the thought. For whatever reason, while her sempai, Haruhi, and Tsuruya were busy, Mikuru had thought to organize a small get-together for the other girls at Yuki's apartment. The reliable older girls had helped her with her homework, and then the three watched an anime — something Mikuru had picked out, called 'Voices of a Distant Star' — while enjoying dinner."
    "There was the idea that Yuki could get more furniture, though.... Her apartment had very solid floors, and there were only two cushions at her low table. Since it was Yuki's place, and Kanae was the youngest, the only padding she had to sit on was the thick rug beneath the kotatsu. It wasn't too bad, but it wasn't helping her excitement."
    "\"Kanae-chan seems very happy this evening,\" Mikuru noted, giggling quietly once the short film had finished. \"Did something good happen?\""
    "\"Ah, um ... n...not yet,\" she managed, feeling her face turn red. \"I was thinking um, about when I ended up in Sempai's bed.\""
    "Yuki and Mikuru both blinked and turned to regard her with interest, though Mikuru couldn't {i}quite{/i} meet her eyes. \"O...oh?\" Mikuru noised quietly. She fanned her face, which was heating up. \"T...that must have been nice.\""
    "Kanae managed a wordless nod in response. Yuki gave a single nod of agreement before blinking, her gaze dropping to the table in consternation."
    "Mikuru noticed, too, turning to look at the other short girl. \"Yuki-chan?\" the time traveler asked worriedly. \"Is something wrong?\""
    "\"He and Suzumiya Haruhi have left this reality,\" Yuki answered after a moment."
    "\"Eh!\" Mikuru started. \"T...there's an attack? W...what happened?!\""
    "\"Uncertain,\" Yuki replied."
    "\"C...can we do anything to help?\" Kanae asked worriedly. \"M...maybe I can slide us there?\""
    "After a pause, Yuki said, \"I do not know how to transmit the coordinates of their current location to you in language.\""
    "\"Maybe I can help!\" Mikuru offered. \"Um, can you tell me?\""
    "Shifting her shoulders, Yuki explained, \"Our current spacial reality is located at the intersection of two parallel membranes in the Calabi Yau manifold,\" and then there was a slew of information that Kanae {i}really{/i} couldn't follow. There were numbers in there, but that didn't seem helpful."
    "\"Their current location,\" Yuki continued, once the several-minute long stream of technical words stopped, \"is relative to these coordinates at—\" She cut off and turned to look at her phone as it rang."
    "\"S...so, that's something that I don't think human science of today can handle well,\" Mikuru said with dismay, as Yuki answered her phone."
    "\"Do I have to understand that to slide better?\" Kanae asked, daunted."
    "\"I hope not,\" Mikuru said shakily. \"Yuki-chan, who's calling?\""
    "\"Tsuruya Haruka,\" Yuki answered, handing the phone to Mikuru."
    "* * *"
    "Even though it was familiar, Kyon was not reassured by the place he abruptly found himself. At least, he consoled himself as the clubroom appeared around him through the wave of disorientation that teleportation and time travel seemed to cause, he was really adjusting to that jarring sensation. It was gray outside, no sign of sun or stars — just gray."
    "Honestly, having Haruhi and Tsuruya both cuddling up to him had been ... somewhat amazing. He just hadn't expected trying to make things right to {i}physically{/i} transport him to the special hell."
    "For the first time, he found himself next to Haruhi in her in that place dressed in the clothes he'd been in before vanishing. \"Somehow,\" he said shakily, \"I was expecting the school uniform again.\""
    "Haruhi's response was a growl of pain— He looked up in alarm, seeing the girl standing before him, her expression a grimace of frustration as she clapped both hands to her head. \"Ow,\" she whimpered. \"Ow, ow, {i}ow{/i}!\""
    "\"W...what's wrong?\" he asked nervously. \"What— Did I do something else wrong?\""
    "\"This really hurts!\" Haruhi snapped, standing upright in her kimono and glaring at him, her eyes glittering with unshed tears. \"I just got almost two months of memories all at once — why the {i}hell{/i} did you take so long!\""
    "\"I was supposed to do this?\" Kyon managed, his voice shaking. \"You never {i}told{/i} me!\""
    "\"I—\" Haruhi cut herself off and grabbed a chair, collapsing into it and rubbing at her temples. \"I want some tea,\" she mumbled."
    "\"Right,\" he agreed, turning around to take care of it, but surprised to find the kettle ready. With nothing else to do, he poured the waiting hot tea for both of them, then set Haruhi's on the table near her before finding a seat of his own — carefully leaving a seat between him and Haruhi. \"Um ... tea's ready....\""
    "\"Okay, so this whole thing started off because of not explaining things well,\" Haruhi grumped, throwing back her tea without hesitation, then slamming the empty cup onto the table. \"Amazing.... You went {i}this{/i} far and never used the emergency codeword....\""
    "\"The only thing I can say in my defense is — again — that I didn't know what to do!\" Kyon protested, feeling like a broken record."
    "\"No, no,\" she sighed, hanging her head. \"Ugh ... we need to make this quick, too, because Tsuruya just got left behind and is probably {i}really{/i} confused about what happened. There's also the fact that Yuki-chan's probably going to try and figure out how to get here with Kanae-chan's help.\""
    "\"At first, I was slightly clueless,\" Kyon offered."
    "She raised her head to give him an inquisitive look, and he gave her his best reassuring smile — usually reserved for his sister or cousins."
    "\"And then ... I was {i}completely{/i} clueless!\" He covered his face with both hands. \"Please be reasonable, Haruhi. I can't ever do the right thing if I don't even {i}know what it is{/i}!\""
    "Haruhi winced, looking away. \"Okay, okay,\" she sighed. \"Um ... so, this is 'safe-mode'. Basically, the idea was, when you got overwhelmed, you'd tell me, then I'd remember all the stuff I sealed away for emergencies, and we could talk it out and plan from here.\""
    "Even though he felt one eyebrow twitch, Kyon managed to say nothing, just staring at her fixedly."
    "\"S...so,\" she said, her face turning red, \"I ... kind of expected you to use the panic button sooner.... I didn't realize how ... um ... good you really were at dealing with things.\" She turned away and gave a very obvious fake cough. \"That means that if I'm responsible for my own actions, I can't blame you.\""
    "Hearing some of the best news he'd gotten all day, Kyon perked up slightly. Maybe, somehow, he could still survive this?"
    "\"I'm really, {i}really{/i} stressed about this, though,\" Haruhi warned."
    "\"I can get that,\" Kyon agreed. \"I'm {i}really{/i} sorry I let, uh ... the you that doesn't fully understand her powers try and start a whole....\" He made a vague gesture, uncertain how to encapsulate the relationships he was in, still. Giving a nervous laugh, he scratched the back of his head and stared at the ceiling."
    "\"Urg,\" Haruhi noised, very quietly."
    "\"B...but why would she do that? Something that you wouldn't want?\" he asked, shaking his head."
    "Haruhi was staring at him with a certain morbid fascination. \"Y...you think that I'm different from when I remember that I have powers?\" she asked."
    "He shrugged, shifting his shoulders. \"Y...you said you were making yourself 'more tolerant' and that I'd thank you for it — but isn't this too far? I don't think the Haruhi I know would be happy about, um ... sharing ... something that important.\""
    "\"You idiot,\" she sighed, rubbing at her temples."
    "\"W...well.... I think you just said it wasn't my fault, but never mind that, now.\" Kyon sighed, hanging his head. \"How do we resolve this, Haruhi? How can we sort things out so no one gets hurt?\""
    "\"You're a bigger idiot than I thought!\" Haruhi yelled, slamming one fist against the table hard enough to shake the teacups resting on it. \"Of course you're right — that I wouldn't be instantly happy about it! But that's not why this is going on! The plan was to make myself learn to like it slowly, bit by bit!\""
    "His mouth dropped open as he stared at her. That Haruhi's plan had gone horrifically wrong — or, maybe horrifically right — well, he'd pretty much expected that to happen to one of her plans at {i}some{/i} point. But the idea that she'd {i}always{/i} intended such a thing, even before she decided to tamper with her own memories...."
    "\"Okay,\" Haruhi sighed, raising a hand to forestall any complaints he might have made. \"On the surface, it seems almost impossible — and thanks to outside information, my plan got a {i}lot{/i} of unexpected refinement. The point of this is that I know for a {i}fact{/i} it can be done, and we can all end up happy. I didn't know that when I started, but the proof is out there. And, come to think of it ... you're a {i}guy{/i}! What is wrong with you that you're trying to get {i}out{/i} of a relationship with five attractive women?\""
    "\"I.... It might make you unhappy?\" he ventured, uncertain. No ... that wasn't really it. \"More and more, it's that it's just something too amazing to believe could happen to someone like me!\""
    "\"...setting aside all of the other things that should be difficult to believe?\""
    "Kyon blinked, staring at her for a moment."
    "Haruhi quirked one eyebrow up in challenge, leaning slightly closer to him. \"Well?\" she pressed."
    "He waved a hand and said, \"While you make a salient point, this situation is somehow on a whole new level!\""
    "\"Are you trying and say that not {i}one{/i} of us is your type?!\""
    "\"What? No! I just can't see why ... well ... {i}me{/i}!\""
    "\"Your idiocy is actually kind of cutely charming,\" Haruhi determined, covering her face with both hands. \"I {i}was{/i} starting to feel bad that we weren't including you in the romantic plans for your own future — doing the same thing as your parents! Now I'm starting to think that might have been the best choice all along! You really {i}don't{/i} get it?\""
    "\"I really don't get it!\" Kyon complained, too shaken to try more of the tea. \"I just....\" Unbidden, a series of pleasant kisses replayed themselves in his memory. More than that, how many warm embraces had they shared? \"Y...you {i}really{/i} think it can be done?\""
    "\"Kyon, if you can just behave remotely reasonable — like any other healthy young man in your position would — then give us a chance. When your birthday comes around, I {i}will{/i} prove it to you,\" Haruhi swore."
    "\"Within the year?\" he asked."
    "\"Within the {i}month{/i},\" Haruhi clarified. \"So, you're going to give this a fair chance, aren't you?\""
    "Being honest ... it wasn't like he'd really nailed the 'just friends' speech with Yuki. But ... going the other route — descending towards what he'd been calling his 'special hell' for more than a month — {i}intentionally{/i}? On the one hand, breaking things off after letting things go as far as they had would result in a lot of hurt feelings. On the other hand, continuing as things were, there were innumerable obstacles and issues ahead."
    "On the gripping hand, some of those hurt feelings would be {i}his{/i}, and that was because he {i}did{/i} care...."
    "He'd have to thank Yuki for suggesting that book."
    "\"Earth to Kyon!\" Haruhi snapped, bringing him back to the waking world."
    "Or was it Haruhi's dream? Okay — enough distracting himself."
    "\"I still can't say I get it, but fine,\" he agreed. \"I want to argue against it, but I get the sense that I wouldn't be doing myself any favors — especially since it's against you.\""
    "\"Excellent!\" Haruhi said, sighing in relief as she nodded. \"Thank goodness that's over!\""
    "\"Well.... While we're here, is there anything else I should know?\" Kyon asked. \"Last time — you didn't give me any warnings on what you did, and I'm not positive, but I {i}think{/i} something happened in there to make me a light sleeper ... more than just Yuki's training, anyway.\""
    "\"Y...yeah, I did that,\" Haruhi admitted guiltily. Well ... he couldn't really blame her — that had turned out rather handy. \"Um ... for you, Mikuru-chan, and Kanae-chan, too. Yuki's training sessions seemed to really be taking a toll on you guys, so.... I mean, Kanae-chan was falling asleep in the club room during meetings! And probably classes, too!\""
    "He found the confidence to climb to his feet and place his hands on the girl's shoulders. She shifted nervously, looking up, but not moving away. \"Haruhi ... that's while I'll give you that chance ... even if I wish you had told me.\" He shrugged, dropping his hands to his side and adding, \"So I guess, in the end ... both of us were pretty bad about that — meaning well, and hiding things we shouldn't have been.\""
    "\"Yeah,\" Haruhi agreed quietly, looking away."
    "\"S...so ... should I, um ... remind you who I am once in a while for regular checkups?\" he asked. \"I ... don't know if I really like the idea that the Haruhi I know here is the real one, though — especially if we're supposed to be, er ... dating....\""
    "\"We're not {i}that{/i} far apart,\" Haruhi warned. \"If you don't get it, still, the me that you know {i}here{/i} is the true me — but the one you've been spending all your time with is the one I'd rather be. The person I want to grow into. It's not like I'm not still there.... I just keep the memories that would prevent me from having fun locked away. The real me {i}can't{/i} be happy with everything the way it is, so.... There have to be some simplifications."
    "\"If it makes you feel better, then yeah, we can do this from time-to-time. Hmm ... I should change the connection between Yuki-chan and myself so she understands what's going on a bit better, now that I'm thinking of it.\" She abruptly rose and went to the computer, wiggling the mouse to wake it from screen-saver — a bouncing trope-tan logo — and tapping at some keys."
    "\"You use the computer for your powers?\" Kyon asked with mild surprise."
    "\"'Safe-mode',\" Haruhi replied absently, opening up a command prompt when the screen appeared, and suddenly typing much more quickly. \"Do you have any idea how volatile this power can be? I know what you're thinking — first of all, no one else should be able to get here. Even if they {i}do{/i}, the computer is only a {i}symbol{/i}. A way of using my powers without a lot of Yuki-chan's help. For someone else, it's just a normal computer. And no, I'm not reading your mind — for reasons I'm not entirely clear on, I actually can't.\" She turned to flash him a bright grin before turning back to the screen."
    "Clearing her throat, she continued, \"Anyway, I think this is a much better solution than, 'You know, I'm kind of miffed that Kyon's looking at Mikuru, and ignoring my increasingly skimpy outfits today — better remake the world on a whim!', don't you think?\""
    "He stared at her, events from a year ago suddenly clicking into place as Haruhi's face reddened. She'd been ... interested in him ... since then?"
    "\"Yeah,\" she sighed, shaking her head, \"with keen romantic observational skills like that, it's a wonder you were still single when we met.\""
    "\"Do you think you could tone down the jibes, just a bit?\" he asked, despite the fact that he was starting to realize that she was right."
    "\"Kyon, you have five girls trying to share you,\" she replied, finishing the last few commands with a flourish and looking up from the screen at him. \"And you don't think that confession was difficult for me?\""
    "\"You, uh ... were pretty attractive in those outfits,\" he offered, suddenly finding the rim of Haruhi's abandoned teacup fascinating. \"Just ... um ... not as much as when you had your hair up in a ponytail....\""
    "Haruhi slowly began to grin. \"I knew it,\" she declared triumphantly, tossing her hair playfully. \"Okay, I think we've done well so far, but this has taken a lot of time, and the others are probably worried about us. So! Because things got to this point, you're going to have to solve something I couldn't!\""
    "After a moment of staring, Kyon sighed, shrugging. \"You know what? Sure — orders, I can handle. What do I need to do?\""
    "\"I'll allow that attitude for {i}now{/i}, but I think you'll see things my way after your birthday,\" she decided. \"So, planning how we get there is up to you — but the entire SOS Brigade is going to be in Hinamizawa that day!"
    "\"Good, okay,\" he agreed. That was a significantly more reasonable impossible task. Never mind the fact that they would have only a single day, and needed over half a day of travel to get there. \"I'll look into that— And in the meantime—\""
    "\"—you {i}are{/i} dating the five of us!\" Haruhi concluded, not quite smiling."
    "\"Will you remember this?\" he asked, scratching the back of his head. \"Once we get back?\""
    "\"Just that you're in charge of figuring out Hinamizawa,\" she said, shaking her head. \"T...that code phrase I gave you will still work, if you really do get overwhelmed.\""
    "\"Um ... and Tsuruya-kun — if we just vanished...?\" Kyon asked."
    "Haruhi looked thoughtful, then nodded. \"Yuki-chan will get what's going on,\" she said. \"As for Tsu-chan, well, even if you talk about it in front of me — for tonight, at least — I won't really remember that. I'll just think I got caught in that new field Yuki-chan put in your phone. Just tell Tsuruya I had to drag you to a pocket dimension and beat some sense into you!\""
    "\"Well, if that's not the truth, it's close enough for government work,\" Kyon agreed, managing a nervous smile. \"If it's all the same, even though I've agreed to this, I believe I'm justified in having a minor mental breakdown.\""
    "\"Hold it together a minute or two longer!\" Haruhi protested anxiously, reaching one hand towards him before drawing it back. \"Ah ... s...so, listen. There's one other thing you need to know. Because of how you've been acting lately, and the fact that the powers the 'waking' me has are meant for fun, well.... As I'm sure your little sister would approve, I'm going to increase that power some — to keep us closer together. You don't {i}seriously{/i} see me letting myself become your damsel in distress all the time, even if you are a hero, right?\""
    "\"I guess not,\" he admitted, envisioning any number of video game villains regretting the idea of locking Haruhi up in their fortresses."
    "\"Plus, we've got plenty of other girls for you to rescue when the situation arises, right? Maybe enough that we can rescue a few together!\""
    "That sounded enough like Haruhi's old self that he couldn't help but laugh. After a moment, she laughed softly along with him, shaking her head and smiling. \"O...okay, it's time to go back, but, um....\""
    "\"Same as last time?\" he asked."
    "She nodded, her cheeks turning red."
    "\"Alright,\" he agreed, reaching forward and tracing the curve of her cheek with his fingertips. She shivered nervously, her eyes narrowing as her lips pursed, and her face tilted upwards. Their lips met, and Kyon didn't care about reality exploding away around him. He'd long since adjusted to {i}that{/i}, and, anyway, she was there, and they were going back to Tsuruya...."
    "* * *"
    "Other than an annoying dizzy spell, thanks to the fact that she had asked Kyon to try his new defensive power, and then gotten caught in the disorienting 'interdiction field', Haruhi thought the evening went very well. Tsuruya had convinced Kyon to join their plan for the moment, and aside from getting caught in Kyon's new defense, Haruhi was quite pleased with the evening so far. After Kyon finished elaborating to Tsuruya that Haruhi had finally managed to beat some sense into his head, the three returned to the couch to start watching their anime."
    "Tsuruya allowed herself to be reassured, but at the same time, decided to grab onto Kyon and not let go — citing concerns that he might abruptly vanish. Haruhi didn't think that was likely, but an excuse to grab onto Kyon was an excuse to grab onto Kyon, so before he could really protest, he found himself pinned between two of his girlfriends. After a moment of the pair cuddling up to him, he relented, hesitantly putting an arm about either, as though expecting some kind of explosion."
    "\"W...well, Haru-nyan does things differently, but as long as they work out,\" Tsuruya decided, in response to something Kyon had said — something not {i}terribly{/i} important, Haruhi was fairly certain."
    "\"Y...yeah,\" Kyon agreed uncertainly. \"Would now be a good time for me to have a delayed mental breakdown?\""
    "\"Sure!\" Tsuruya chirped, wriggling in his grasp a bit, flashing him a mischievous grin. \"I'll help!\""
    "Haruhi felt an annoyed squeak escape her as Tsuruya — with no further warning — pressed her lips against Kyon, engaging him in an entirely unexpected kiss. Her eyes widened as Kyon first started, then hesitantly kissed her back. \"H...hey!\" she protested."
    "Tsuruya broke the kiss before Kyon or Haruhi could try and fumble her away. \"Better?\" she asked. Kyon's only response was to look terribly confused — but not really upset, and make a bewildered sound. \"Hmm.... Haru-nyan, you should try, too!\""
    "Haruhi hesitated ... she had seen Kyon kiss other girls — Mikuru and Kanae, specifically. Even so, they had previously always at least managed to try and do so out of {i}direct{/i} line of sight.... Then again, she knew for a {i}fact{/i} that Yuki had made a recording of her kissing Kyon — and acting tsundere towards a boy who was already making out with his fiancee wasn't going to be helping any kind of cause."
    "\"Y...yeah, but ... you can't just kiss Kyon like that!\" Haruhi protested. \"You have to warn him first!\""
    "He blinked, turning to look at her in alarm."
    "\"That was your warning,\" she added. Tangled in Tsuruya's embrace, Kyon couldn't escape as she closed the distance and almost knocked the three of them into a comfortably tangled pile, her lips pressing against his. Her eyes closed as he returned the kiss, one hand tangling in his hair as she trailed the fingertips of her other hand across his cheek."
    "When the kiss was broken, she found to her embarrassment that she'd been smoothing Tsuruya's hair — Kyon's, naturally, wasn't that long. The heiress didn't seem to mind at all, just giving her an encouraging wink, half pinned beneath the other couple, so not able to move in for another kiss of her own at the moment. Even better, Kyon wasn't putting up any kind of fight, so that meant...."
    "One hand was still in Tsuruya's hair, the fingertips brushing across the other girl's head.... With Kyon between them, seeming comfortable (if justifiably dazed), Haruhi thought that things were pretty much perfect. As though to underscore that point, there were a series of surprisingly loud footsteps down the hall, and she hurriedly pulled herself off of the others, straightening her robes out and then hauling Kyon upright when he continued being dazed."
    "Tsuruya sat upright as well, giggling when her chief maid (on mysteriously silent feet, once more) crept into the room, moving to Tsuruya's side unobtrusively. \"Your father has arrived with a guest, Tsuruya-san,\" she breathed quietly."
    "\"Ah!\" Tsuruya exclaimed, her smile widening. \"Well, that's good timing!\""
    "\"Hello!\" Tsuruya's father called, stepping into the room and grinning, Kyon's uncle beside him."
    "\"Heya, Kyon!\" Keiichi added, grinning just as mischievously, his eyes scanning across the trio before understanding of some sort seemed to set in. Then his smile widened even further. \"Aha.... Well, I happened to be in town on business; I'd hoped to see you doing well!\""
    "\"Awesome,\" Kyon agreed somewhat shakily, his eyes not quite focusing."
    "Haruhi wanted to smack Kyon — why hadn't he {i}said{/i} his uncle was going to be in town? She also really wanted to ask Keiichi if Rika were there, but since this was Tsuruya's place, she bit her tongue."
    "\"Oh!\" Tsuruya exclaimed cheerfully, hopping to her feet and giving the older men a polite bow. \"You're in town on businesses?\""
    "Keiichi raised an eyebrow and glanced across Haruhi and Shinobu before Tsuruya's father assured, \"This is trusted company.\""
    "Nodding, Keiichi explained, \"I'm coordinating a legal team for an upcoming trial involving some men who recently left the employ of the Sumiyoshi-rengo.\""
    "\"You're a lawyer?\" Haruhi blurted out in surprise, unable to keep quiet. She had thought Kyon said he was just a motivational speaker!"
    "\"Yep!\" Keiichi agreed, nodding. \"When I was younger, I had a strong disagreement with the way the law handled some things — and learning more about the law seemed like a good way to make sure if it happened again, I'd be better able to deal with it!\""
    "\"But ... Dad said you never finished college,\" Kyon said, frowning in confusion."
    "\"Well, that's because when I was working on my law degree, Imouto was ... very busy,\" Keiichi said, shrugging. \"That was just around the time you were born, so ... communication was not at its best. Ah ... a story for another time, though. Are you busy on Friday, Kyon?\""
    "\"I don't think so,\" he answered cautiously."
    "\"Well, great! Rena-chan's new book is being released then! She'd love it if you could stop by to see her,\" Keiichi said, before checking his watch. \"Ah.... Well, at any rate, Kyon-kun, Suzumiya-chan, Tsuruya-san — enjoy your evening.\" He gave Haruhi and Tsuruya a wink that helped explain why Rika had agreed to the relationship she had."
    "\"Yes,\" Tsuruya Kenshiro agreed, nodding, seemingly oblivious. \"Sorries about the unexpectedness! But family is importants, so I thought this would be a good surprise!\""
    "\"Today has been strangely full of those,\" Kyon said, managing a genuinely happy, if somewhat nervous smile."
    "\"It has!\" Tsuruya agreed aloud. Haruhi agreed, too, but didn't say anything, just offering a nod and a happy smile of her own."
    "* * *"
    "After getting home somewhat late — excused by his parents, since it was with Tsuruya — Kyon settled into a contented rest, drifting off and only peripherally aware of the now-regular nightly training. When morning came around, he became aware of the somewhat familiar sensation of someone else in his bed, warm breath tickling his neck. The evenings and early mornings were cool enough still that the extra warmth was amazingly pleasant, though."
    "He cautiously turned, not that surprised to see Kanae curled up and pressed into his side, her sleeping face cutely angelic as she sighed at something in her sleep and shifted, giving a tiny smile. Okay ... he supposed if this was part of what Haruhi said he should expect...."
    "Well, normal girls would probably want normal relationships, but he realized with a full training session and the following night to sleep on it, it was probably pretty obvious that extraordinary girls might want an extraordinary relationship. He hoped he could keep up with them, though.... He started to pull one arm over, thinking of tracing his fingertips across the slider's cheek — but an unexpected weight pinned that arm down."
    "Turning, he blinked, surprised to see Yuki there, too, the two girls managing to just squeeze into his small bed with him. At a glance, Yuki's eyes were slowly drifting open, as though she were just waking up. \"Um,\" he began cautiously, trying to keep his voice very quiet. \"Good morning?\""
    "\"Yes,\" Yuki agreed."
    "\"Mmm,\" Kanae mumbled, pressing her face into his shoulder. \"Sempai....\""
    "The slider blearily sat up, then blinked at her surroundings, face reddening slightly at the sight of Kyon, and then intensely at the sight of Yuki. \"U...um.... G...good morning, Sempai!\" she agreed, her voice timidly quiet."
    "Part of him wanted to complain that the girls had just slid into his bed without asking. The greater part of him, now that he realized Haruhi's jealousy shouldn't be the greatest factor in daring to return affection, really didn't mind {i}that{/i} much, except to maybe append a complaint that Mikuru could probably have squeezed into his bed, too."
    "He felt his own face heating up — these weren't the kinds of thoughts he should be having. Instead, he tried to focus on the fact that waking up in his own bed with two cute girls was something he could probably get used to. \"Did you rest well?\" he offered."
    "Kanae looked slightly embarrassed, shifting her gaze away. \"Y...yes,\" she agreed. \"I had ... very nice dreams.\""
    "Yuki blinked then turned to look at Kyon's alarm clock. After studying it for a moment, she decided, \"I will return to my apartment to prepare for school.\""
    "Kanae startled slightly, then shook her head. \"I ... should be going back too,\" she said quietly, as Kyon sat up. \"U...um....\" She hesitated, wringing her hands, and Kyon replayed the time he had spent with the other girls. Kanae had {i}said{/i} she liked him, at the beach. If he were supposed to be dating five girls, she'd probably been left behind a bit, in terms of kissing and dating."
    "\"I'm going to a book signing on Friday, after the club meeting,\" he said quietly. \"It's written by one of my aunts, and my uncle will be there, too. Would you like to come with me?\""
    "She smiled eagerly, nodding, then after a moment of hesitation, grabbed him in a tight hug. \"I'll see you at school, Sempai,\" she assured him, before she too vanished, almost the exact same way Yuki had."
    "A heartbeat later, while he was still sitting up, thinking about the minute or so before his alarm went off, his bedroom door opened, his sister peeking in with a mischievous grin. \"Aw,\" she pouted, when the only other being she could spot in Kyon's bed was Shamisen. The cat, already roused, hopped to the floor and slipped between Nonoko's feet."
    "She gave him a cheerful, \"Good morning!\" before chasing after the departing feline, already singing one of her little tunes. \"Sha~mi!\""
    "He turned off his alarm and climbed out of bed, thinking that things were going better — until his phone chirped a notification that he had a new text message. Somehow, from that ... he just knew his day was going to go downhill."
    "* * *"
    "Kanae felt surprisingly well rested, all things considered. Even better, if sliding into her sempai's bed.... Well, it wasn't {i}really{/i} sliding. She supposed it was more skimming, or jumping than really {i}sliding{/i}."
    "But what an amazing skill that was! With that, she could be less of a burden for her sempai — she could always escape, just jumping to places or people she knew."
    "The best part of the day had been the way that once she had woken up, her sempai hadn't seemed worried or alarmed to see her, this time. In fact, even though he hadn't called it a date, he'd asked her out!"
    "In that happy fog, she went through her classes, for once feeling confident before her history test."
    "When class ended, she happily followed Tsuruya's lead to Haruhi's impromptu lunch meeting to celebrate Mikuru completing the latest costume. In the clubroom, the moment she arrived, Haruhi stood up from her seat behind the computer with an eager grin. Koizumi and her sempai recognized it, trading a glance and retreating into the hall with their teacups."
    "Shortly enough, she was redressed in her new outfit, complete with a blue cap, and the boys were let back in. Her sempai and Haruhi both agreed that she looked very cute in the costume, and she tried to blushingly defer their admiration to Mikuru, who had actually made it. For her part, Mikuru watched with a happy, glowing smile, just like Kanae always imagined a big sister would. Tsuruya took several dozen pictures before settling down enough to sit at the table again, and then Yuki closed her book and set it down as Haruhi called the meeting to order."
    "\"Okay!\" Haruhi called, surveying the group. \"First order of business — since we're here anyway, are there any new issues to report?\" She turned an inquisitive gaze to Tsuruya."
    "\"No critical new developments!\" Tsuruya reported happily. \"Mori-san did say she might want to request a meeting with myself, Kyon-kun, and Koizumi-kun about the police investigation against the Sumiyoshi-rengo in the future, though.\""
    "Haruhi nodded and turned her attention to Mikuru, who quickly shook her head. \"Nothing from me,\" she said."
    "\"No enemy slider activity has been observed,\" Yuki reported, once Haruhi's gaze swung to her. \"Suou Kuyou's presence has not been detected since the previous encounter.\" She paused briefly, then continued, \"The probability of the IDSE initiating a hostile action has increased due to Kimidori Emiri's actions being detected.\""
    "Frowning at that, Haruhi crossed her arms over her chest and cocked her head to one side. \"I suppose we haven't seen much sign that they've done much to us, really, have we?\" she mused."
    "\"Actually, I'm not sure, but I think Kimidori's been behind the issues we've been having with the Sumiyoshi-rengo,\" Kanae's sempai noted, crossing his arms over his chest. \"Yamane Jun and his photography ring are what got that whole thing started, but he was kind of tricked into it by one of the entity's traps — that piece that's now my PDA.\" He fished the device from his pocket to show it briefly."
    "Haruhi made a slight gesture and it shot from his hand and into hers, almost absently."
    "\"That incident was likely not originally intended by the entity as a whole,\" Yuki added. \"However, once set into motion, Kimidori or another agent of the entity would be able to influence the organization.\""
    "\"I have a difficult time understanding why an existence as powerful as the IDSE would bother using such crude methods, given their capabilities,\" Koizumi remarked, frowning. \"I suppose we should be grateful, but when you look at the enemy sliders, they don't seem to hesitate to bring all the force to bear that they can. Why does the IDSE have such restraint? Is it {i}just{/i} because of Kyon- kun's 'open time loops'?\""
    "\"Such things are more critical than you may realize,\" Mikuru said, shaking her head. \"The backlash for causing a temporal paradox could be catastrophic — on the scale of a classified information....\" She trailed off and heaved a brief sigh."
    "\"The goal of the entity is presumably the neutralization of myself as a potentially hostile agent,\" Yuki added. \"Beyond that, our activities slowly generate new data that the entity wishes to acquire. Therefore it has so far been extremely cautious of us. As time grows on and we grow more capable, the entity will become more willing to arrange — or dispatch — more hazardous threats.\""
    "\"Aha ... so ... we're really just an experiment to them?\" Koizumi asked, frowning."
    "\"Well, {i}that{/i} pisses me off,\" Haruhi noted. \"Still ... they're logical, right? There must be {i}some{/i} way to reach them — maybe try and talk sense into them? I really, really hate those typical science fiction movies where humans meet aliens for the first time and they have to fight!\""
    "\"Violent conflict would be undesirable,\" Yuki agreed. \"I do not predict high chances of success in combat against another interface with the backing of the entity.\""
    "\"So, we'd need to give you some sort of upgrade to be able to handle that?\" Haruhi mused."
    "Yuki seemed somehow uncertain, and said nothing."
    "\"If we really want to talk to the entity, we can just track down Kimidori Emiri,\" Kanae's sempai noted. \"She told me at one point she wanted to try and remain non-violent so we could communicate if things somehow changed. It seemed a bit unlikely given our last run-in, but she's still supposed to be a student at this school.\""
    "Haruhi crossed her arms over her chest. \"I don't know ... it {i}has{/i} been pretty boring lately, at least in terms of being able to really {i}solve{/i} any of our problems.... Alright. Well, we can form a plan of attack against her, and—\""
    "\"Hold up there,\" Kanae's sempai protested, holding one hand out. \"I'm not sure where this fits into things, but if she's harmless for the moment, we should let well enough alone. If we take her out, I'd expect retaliation.\""
    "\"They may not be human, but they are an organization of some kind,\" Tsuruya agreed, nodding. \"I think Kyon-kun's probably right....\""
    "\"I...it would be nice if we could avoid fighting,\" Kanae supplied. Mikuru agreed with that, putting one hand on the slider's shoulder and nodding vigorously."
    "\"That's the best lead-in I can imagine for this next bit of news,\" Kanae's sempai said cautiously. \"Ah ... Haruhi, you know that I've been getting text messages from a certain person regularly, right?\""
    "Haruhi's expression shifted from annoyed to wary. \"Yeah,\" she said slowly, nodding. \"Why.... What's {i}Sasaki{/i} got to say?\""
    "Kanae's sempai shifted slightly in his seat and glanced across the table. \"She says that her friends want to have a meeting with me to try and talk things out next Monday,\" he explained."
    "\"And that you should come alone?\" Haruhi asked skeptically."
    "\"That's what they wanted,\" he agreed. \"Ah ... but then, she also said that since she doesn't really trust Tachibana right now, she doesn't think I should either.\""
    "Haruhi considered that, seeming uncomfortable with the idea."
    "\"This might be good,\" Tsuruya put in thoughtfully. \"Even if we can't reach a peaceful compromise, we can at least understands their motivations better, right?\""
    "\"I guess,\" Haruhi allowed, grimacing. \"If we do this, I want a {i}lot{/i} of contingencies to get Kyon out of there for once they double-cross us! And {i}more{/i} contingencies to handle their counters, since it's so obvious this is a trap!\""
    "\"Yes, that does seem somewhat obvious,\" Koizumi agreed."
    "\"Okay, anything else to drop on us, Kyon?\" Haruhi asked, raising an eyebrow at the boy."
    "\"Um ... I'm going to that book signing for my aunt on Friday?\" he asked, scratching his head thoughtfully."
    "\"That's a bit of a change in subject,\" Koizumi remarked, smiling thoughtfully as he sipped at his tea. \"Your aunt ... Fuurude Rika, yes? What has she written?\""
    "\"Another aunt — actually, a close family friend. Her name is Ryuguu Rena,\" Kanae's sempai clarified. \"She wrote—\""
    "He cut off as Koizumi sputtered into his teacup and began choking. Since Yuki was at his side, she raised an arm without hesitation, smacking his back with an open palm firmly. A few moments of ragged breathing later, everyone was staring at the esper in consternation. Kanae couldn't really think of an occasion where she'd seen the normally eternally-cool Koizumi so flustered."
    "\"Ryuguu Rena-sensei is your {i}aunt{/i}?\" he gasped, once he could speak, his eyes wide."
    "\"Er ... yeah,\" Kanae's sempai agreed, mildly taken aback by Koizumi's demeanor. \"You've heard of her, then?\""
    "Koizumi pulled his wallet from his pocket and produced a worn but cared for card, presenting it to Kyon proudly. \"'Brave Detective Sasha Fan-club',\" Tsuruya read aloud, sharp-eyed enough to make it out from where she sat. \"'Member number 24601, Koizumi Itsuki'.\""
    "\"Kyon,\" Koizumi said with unexpected heat in his voice, \"I don't know that I've ever asked for much as a personal favor — but {i}please{/i} let me meet your aunt!\""
    "\"Huh,\" Haruhi mused, raising an eyebrow. \"That's a pretty good idea, actually — I think we should all go!\""
    "Kanae's smile faded at that.... Well, even if it wasn't really going to be a date anymore, at least he'd {i}tried{/i} to ask her first."
    "\"What's that face about?\" Haruhi asked. \"Don't you want to introduce your friends to your aunt?\""
    "\"Er, yeah, I do,\" he agreed. \"I'd just.... Well, don't worry, Kanae-chan, I'll come up with something else, huh?\""
    "\"T...thank you, Sempai,\" the slider managed."
    "\"What, did we just crash a date between you and Kanae-chan?\" Haruhi asked, blinking. Mikuru gasped quietly, and Kanae felt her face warming up as she blushed beet red. Koizumi seemed too distracted to notice, just offering a dazed smile and looking at his card happily."
    "\"Aww,\" Tsuruya murmured. \"Sorry, Kanae-chan.... I'll help Kyon-kun make it up to you, though!\""
    "\"Yeah ... sorry about delaying that for you, Kanae-chan,\" Haruhi said, nodding at the heiress. \"Once Koizumi comes back to earth we can get back to planning how that meeting on Monday is going to work out, right?\""
    "\"I...is there any way I can help?\" Kanae asked anxiously. It was nice to be able to dress up, but she'd like to be able to do just a {i}little{/i} more to help out...."
    "\"Yes,\" Yuki agreed, turning to regard Kanae."
    "She brightened at that immediately. Things were looking up, after all!"
    "As though to underscore that thought, the bell warning that class resumed in a few minutes rang, making Kanae wonder if she'd be able to change back in time to get back to class...."
